'''
FUNC:A_1tz3_3_6_1_26
PDB:1tz3
EC:3.6.1.26
RESI:gly,ala,gly,asp
LOCI:a-249,250,251,252;
'''
cmd.select('gly1', 'n. O&r. gly w. %s of n. CB&r. ala'%(d*8.25))
cmd.select('gly2', 'n. O&r. gly w. %s of n. O&r. ala'%(d*5.39))
cmd.select('gly3', 'n. O&r. gly w. %s of n. C&r. ala'%(d*5.86))
cmd.select('gly4', 'n. O&r. gly w. %s of n. CA&r. ala'%(d*7.35))
cmd.select('gly5', 'n. O&r. gly w. %s of n. N&r. ala'%(d*7.87))
cmd.select('gly6', 'n. C&r. gly w. %s of n. CB&r. ala'%(d*7.38))
cmd.select('gly7', 'n. C&r. gly w. %s of n. O&r. ala'%(d*4.93))
cmd.select('gly8', 'n. C&r. gly w. %s of n. C&r. ala'%(d*5.04))
cmd.select('gly9', 'n. C&r. gly w. %s of n. CA&r. ala'%(d*6.47))
cmd.select('gly10', 'n. C&r. gly w. %s of n. N&r. ala'%(d*6.81))
cmd.select('gly11', 'n. CA&r. gly w. %s of n. CB&r. ala'%(d*6.35))
cmd.select('gly12', 'n. CA&r. gly w. %s of n. O&r. ala'%(d*4.75))
cmd.select('gly13', 'n. CA&r. gly w. %s of n. C&r. ala'%(d*4.42))
cmd.select('gly14', 'n. CA&r. gly w. %s of n. CA&r. ala'%(d*5.80))
cmd.select('gly15', 'n. CA&r. gly w. %s of n. N&r. ala'%(d*6.28))
cmd.select('gly16', 'n. N&r. gly w. %s of n. CB&r. ala'%(d*5.02))
cmd.select('gly17', 'n. N&r. gly w. %s of n. O&r. ala'%(d*4.25))
cmd.select('gly18', 'n. N&r. gly w. %s of n. C&r. ala'%(d*3.33))
cmd.select('gly19', 'n. N&r. gly w. %s of n. CA&r. ala'%(d*4.43))
cmd.select('gly20', 'n. N&r. gly w. %s of n. N&r. ala'%(d*4.89))
cmd.select('gly21', 'n. O&r. gly w. %s of n. O&r. gly'%(d*7.02))
cmd.select('gly22', 'n. O&r. gly w. %s of n. C&r. gly'%(d*7.69))
cmd.select('gly23', 'n. O&r. gly w. %s of n. CA&r. gly'%(d*8.75))
cmd.select('gly24', 'n. O&r. gly w. %s of n. N&r. gly'%(d*9.59))
cmd.select('gly25', 'n. C&r. gly w. %s of n. O&r. gly'%(d*6.14))
cmd.select('gly26', 'n. C&r. gly w. %s of n. C&r. gly'%(d*6.64))
cmd.select('gly27', 'n. C&r. gly w. %s of n. CA&r. gly'%(d*7.65))
cmd.select('gly28', 'n. C&r. gly w. %s of n. N&r. gly'%(d*8.41))
cmd.select('gly29', 'n. CA&r. gly w. %s of n. O&r. gly'%(d*6.36))
cmd.select('gly30', 'n. CA&r. gly w. %s of n. C&r. gly'%(d*6.52))
cmd.select('gly31', 'n. CA&r. gly w. %s of n. CA&r. gly'%(d*7.57))
cmd.select('gly32', 'n. CA&r. gly w. %s of n. N&r. gly'%(d*8.03))
cmd.select('gly33', 'n. N&r. gly w. %s of n. O&r. gly'%(d*5.46))
cmd.select('gly34', 'n. N&r. gly w. %s of n. C&r. gly'%(d*5.36))
cmd.select('gly35', 'n. N&r. gly w. %s of n. CA&r. gly'%(d*6.50))
cmd.select('gly36', 'n. N&r. gly w. %s of n. N&r. gly'%(d*6.87))
cmd.select('gly37', 'n. O&r. gly w. %s of n. CB&r. asp'%(d*6.23))
cmd.select('gly38', 'n. O&r. gly w. %s of n. CG&r. asp'%(d*6.81))
cmd.select('gly39', 'n. O&r. gly w. %s of n. OD1&r. asp'%(d*6.36))
cmd.select('gly40', 'n. O&r. gly w. %s of n. OD2&r. asp'%(d*8.04))
cmd.select('gly41', 'n. O&r. gly w. %s of n. O&r. asp'%(d*5.55))
cmd.select('gly42', 'n. O&r. gly w. %s of n. C&r. asp'%(d*4.96))
cmd.select('gly43', 'n. O&r. gly w. %s of n. CA&r. asp'%(d*4.75))
cmd.select('gly44', 'n. O&r. gly w. %s of n. N&r. asp'%(d*4.24))
cmd.select('gly45', 'n. C&r. gly w. %s of n. CB&r. asp'%(d*5.69))
cmd.select('gly46', 'n. C&r. gly w. %s of n. CG&r. asp'%(d*6.11))
cmd.select('gly47', 'n. C&r. gly w. %s of n. OD1&r. asp'%(d*5.70))
cmd.select('gly48', 'n. C&r. gly w. %s of n. OD2&r. asp'%(d*7.27))
cmd.select('gly49', 'n. C&r. gly w. %s of n. O&r. asp'%(d*5.91))
cmd.select('gly50', 'n. C&r. gly w. %s of n. C&r. asp'%(d*4.99))
cmd.select('gly50',' br. gly1&br. gly2&br. gly3&br. gly4&br. gly5&br. gly6&br. gly7&br. gly8&br. gly9&br. gly10&br. gly11&br. gly12&br. gly13&br. gly14&br. gly15&br. gly16&br. gly17&br. gly18&br. gly19&br. gly20&br. gly21&br. gly22&br. gly23&br. gly24&br. gly25&br. gly26&br. gly27&br. gly28&br. gly29&br. gly30&br. gly31&br. gly32&br. gly33&br. gly34&br. gly35&br. gly36&br. gly37&br. gly38&br. gly39&br. gly40&br. gly41&br. gly42&br. gly43&br. gly44&br. gly45&br. gly46&br. gly47&br. gly48&br. gly49&br. gly50')
cmd.delete('gly1')
cmd.delete('gly2')
cmd.delete('gly3')
cmd.delete('gly4')
cmd.delete('gly5')
cmd.delete('gly6')
cmd.delete('gly7')
cmd.delete('gly8')
cmd.delete('gly9')
cmd.delete('gly10')
cmd.delete('gly11')
cmd.delete('gly12')
cmd.delete('gly13')
cmd.delete('gly14')
cmd.delete('gly15')
cmd.delete('gly16')
cmd.delete('gly17')
cmd.delete('gly18')
cmd.delete('gly19')
cmd.delete('gly20')
cmd.delete('gly21')
cmd.delete('gly22')
cmd.delete('gly23')
cmd.delete('gly24')
cmd.delete('gly25')
cmd.delete('gly26')
cmd.delete('gly27')
cmd.delete('gly28')
cmd.delete('gly29')
cmd.delete('gly30')
cmd.delete('gly31')
cmd.delete('gly32')
cmd.delete('gly33')
cmd.delete('gly34')
cmd.delete('gly35')
cmd.delete('gly36')
cmd.delete('gly37')
cmd.delete('gly38')
cmd.delete('gly39')
cmd.delete('gly40')
cmd.delete('gly41')
cmd.delete('gly42')
cmd.delete('gly43')
cmd.delete('gly44')
cmd.delete('gly45')
cmd.delete('gly46')
cmd.delete('gly47')
cmd.delete('gly48')
cmd.delete('gly49')
cmd.select('gly51', 'n. C&r. gly w. %s of n. CA&r. asp'%(d*4.42))
cmd.select('gly52', 'n. C&r. gly w. %s of n. N&r. asp'%(d*3.32))
cmd.select('gly53', 'n. CA&r. gly w. %s of n. CB&r. asp'%(d*6.81))
cmd.select('gly54', 'n. CA&r. gly w. %s of n. CG&r. asp'%(d*6.97))
cmd.select('gly55', 'n. CA&r. gly w. %s of n. OD1&r. asp'%(d*6.44))
cmd.select('gly56', 'n. CA&r. gly w. %s of n. OD2&r. asp'%(d*8.00))
cmd.select('gly57', 'n. CA&r. gly w. %s of n. O&r. asp'%(d*7.35))
cmd.select('gly58', 'n. CA&r. gly w. %s of n. C&r. asp'%(d*6.36))
cmd.select('gly59', 'n. CA&r. gly w. %s of n. CA&r. asp'%(d*5.77))
cmd.select('gly60', 'n. CA&r. gly w. %s of n. N&r. asp'%(d*4.41))
cmd.select('gly61', 'n. N&r. gly w. %s of n. CB&r. asp'%(d*7.04))
cmd.select('gly62', 'n. N&r. gly w. %s of n. CG&r. asp'%(d*7.26))
cmd.select('gly63', 'n. N&r. gly w. %s of n. OD1&r. asp'%(d*6.99))
cmd.select('gly64', 'n. N&r. gly w. %s of n. OD2&r. asp'%(d*8.09))
cmd.select('gly65', 'n. N&r. gly w. %s of n. O&r. asp'%(d*7.86))
cmd.select('gly66', 'n. N&r. gly w. %s of n. C&r. asp'%(d*6.73))
cmd.select('gly67', 'n. N&r. gly w. %s of n. CA&r. asp'%(d*6.28))
cmd.select('gly68', 'n. N&r. gly w. %s of n. N&r. asp'%(d*4.88))
cmd.select('gly',' gly50&br. gly51&br. gly52&br. gly53&br. gly54&br. gly55&br. gly56&br. gly57&br. gly58&br. gly59&br. gly60&br. gly61&br. gly62&br. gly63&br. gly64&br. gly65&br. gly66&br. gly67&br. gly68')
cmd.delete('gly50')
cmd.delete('gly51')
cmd.delete('gly52')
cmd.delete('gly53')
cmd.delete('gly54')
cmd.delete('gly55')
cmd.delete('gly56')
cmd.delete('gly57')
cmd.delete('gly58')
cmd.delete('gly59')
cmd.delete('gly60')
cmd.delete('gly61')
cmd.delete('gly62')
cmd.delete('gly63')
cmd.delete('gly64')
cmd.delete('gly65')
cmd.delete('gly66')
cmd.delete('gly67')
cmd.delete('gly68')
cmd.select('ala1', 'n. CB&r. ala w. %s of n. O&gly'%(d*8.25))
cmd.select('ala2', 'n. CB&r. ala w. %s of n. C&gly'%(d*7.38))
cmd.select('ala3', 'n. CB&r. ala w. %s of n. CA&gly'%(d*6.35))
cmd.select('ala4', 'n. CB&r. ala w. %s of n. N&gly'%(d*5.02))
cmd.select('ala5', 'n. O&r. ala w. %s of n. O&gly'%(d*5.39))
cmd.select('ala6', 'n. O&r. ala w. %s of n. C&gly'%(d*4.93))
cmd.select('ala7', 'n. O&r. ala w. %s of n. CA&gly'%(d*4.75))
cmd.select('ala8', 'n. O&r. ala w. %s of n. N&gly'%(d*4.25))
cmd.select('ala9', 'n. C&r. ala w. %s of n. O&gly'%(d*5.86))
cmd.select('ala10', 'n. C&r. ala w. %s of n. C&gly'%(d*5.04))
cmd.select('ala11', 'n. C&r. ala w. %s of n. CA&gly'%(d*4.42))
cmd.select('ala12', 'n. C&r. ala w. %s of n. N&gly'%(d*3.33))
cmd.select('ala13', 'n. CA&r. ala w. %s of n. O&gly'%(d*7.35))
cmd.select('ala14', 'n. CA&r. ala w. %s of n. C&gly'%(d*6.47))
cmd.select('ala15', 'n. CA&r. ala w. %s of n. CA&gly'%(d*5.80))
cmd.select('ala16', 'n. CA&r. ala w. %s of n. N&gly'%(d*4.43))
cmd.select('ala17', 'n. N&r. ala w. %s of n. O&gly'%(d*7.87))
cmd.select('ala18', 'n. N&r. ala w. %s of n. C&gly'%(d*6.81))
cmd.select('ala19', 'n. N&r. ala w. %s of n. CA&gly'%(d*6.28))
cmd.select('ala20', 'n. N&r. ala w. %s of n. N&gly'%(d*4.89))
cmd.select('ala21', 'n. CB&r. ala w. %s of n. O&r. gly'%(d*6.23))
cmd.select('ala22', 'n. CB&r. ala w. %s of n. C&r. gly'%(d*5.67))
cmd.select('ala23', 'n. CB&r. ala w. %s of n. CA&r. gly'%(d*6.79))
cmd.select('ala24', 'n. CB&r. ala w. %s of n. N&r. gly'%(d*6.76))
cmd.select('ala25', 'n. O&r. ala w. %s of n. O&r. gly'%(d*5.18))
cmd.select('ala26', 'n. O&r. ala w. %s of n. C&r. gly'%(d*5.68))
cmd.select('ala27', 'n. O&r. ala w. %s of n. CA&r. gly'%(d*7.15))
cmd.select('ala28', 'n. O&r. ala w. %s of n. N&r. gly'%(d*7.93))
cmd.select('ala29', 'n. C&r. ala w. %s of n. O&r. gly'%(d*4.87))
cmd.select('ala30', 'n. C&r. ala w. %s of n. C&r. gly'%(d*4.97))
cmd.select('ala31', 'n. C&r. ala w. %s of n. CA&r. gly'%(d*6.37))
cmd.select('ala32', 'n. C&r. ala w. %s of n. N&r. gly'%(d*6.94))
cmd.select('ala33', 'n. CA&r. ala w. %s of n. O&r. gly'%(d*4.76))
cmd.select('ala34', 'n. CA&r. ala w. %s of n. C&r. gly'%(d*4.42))
cmd.select('ala35', 'n. CA&r. ala w. %s of n. CA&r. gly'%(d*5.78))
cmd.select('ala36', 'n. CA&r. ala w. %s of n. N&r. gly'%(d*6.16))
cmd.select('ala37', 'n. N&r. ala w. %s of n. O&r. gly'%(d*4.25))
cmd.select('ala38', 'n. N&r. ala w. %s of n. C&r. gly'%(d*3.33))
cmd.select('ala39', 'n. N&r. ala w. %s of n. CA&r. gly'%(d*4.41))
cmd.select('ala40', 'n. N&r. ala w. %s of n. N&r. gly'%(d*4.72))
cmd.select('ala41', 'n. CB&r. ala w. %s of n. CB&r. asp'%(d*9.41))
cmd.select('ala42', 'n. CB&r. ala w. %s of n. CG&r. asp'%(d*9.74))
cmd.select('ala43', 'n. CB&r. ala w. %s of n. OD1&r. asp'%(d*9.71))
cmd.select('ala44', 'n. CB&r. ala w. %s of n. OD2&r. asp'%(d*10.32))
cmd.select('ala45', 'n. CB&r. ala w. %s of n. O&r. asp'%(d*10.08))
cmd.select('ala46', 'n. CB&r. ala w. %s of n. C&r. asp'%(d*8.96))
cmd.select('ala47', 'n. CB&r. ala w. %s of n. CA&r. asp'%(d*8.88))
cmd.select('ala48', 'n. CB&r. ala w. %s of n. N&r. asp'%(d*7.64))
cmd.select('ala49', 'n. O&r. ala w. %s of n. CB&r. asp'%(d*7.34))
cmd.select('ala50', 'n. O&r. ala w. %s of n. CG&r. asp'%(d*8.13))
cmd.select('ala50',' br. ala1&br. ala2&br. ala3&br. ala4&br. ala5&br. ala6&br. ala7&br. ala8&br. ala9&br. ala10&br. ala11&br. ala12&br. ala13&br. ala14&br. ala15&br. ala16&br. ala17&br. ala18&br. ala19&br. ala20&br. ala21&br. ala22&br. ala23&br. ala24&br. ala25&br. ala26&br. ala27&br. ala28&br. ala29&br. ala30&br. ala31&br. ala32&br. ala33&br. ala34&br. ala35&br. ala36&br. ala37&br. ala38&br. ala39&br. ala40&br. ala41&br. ala42&br. ala43&br. ala44&br. ala45&br. ala46&br. ala47&br. ala48&br. ala49&br. ala50')
cmd.delete('ala1')
cmd.delete('ala2')
cmd.delete('ala3')
cmd.delete('ala4')
cmd.delete('ala5')
cmd.delete('ala6')
cmd.delete('ala7')
cmd.delete('ala8')
cmd.delete('ala9')
cmd.delete('ala10')
cmd.delete('ala11')
cmd.delete('ala12')
cmd.delete('ala13')
cmd.delete('ala14')
cmd.delete('ala15')
cmd.delete('ala16')
cmd.delete('ala17')
cmd.delete('ala18')
cmd.delete('ala19')
cmd.delete('ala20')
cmd.delete('ala21')
cmd.delete('ala22')
cmd.delete('ala23')
cmd.delete('ala24')
cmd.delete('ala25')
cmd.delete('ala26')
cmd.delete('ala27')
cmd.delete('ala28')
cmd.delete('ala29')
cmd.delete('ala30')
cmd.delete('ala31')
cmd.delete('ala32')
cmd.delete('ala33')
cmd.delete('ala34')
cmd.delete('ala35')
cmd.delete('ala36')
cmd.delete('ala37')
cmd.delete('ala38')
cmd.delete('ala39')
cmd.delete('ala40')
cmd.delete('ala41')
cmd.delete('ala42')
cmd.delete('ala43')
cmd.delete('ala44')
cmd.delete('ala45')
cmd.delete('ala46')
cmd.delete('ala47')
cmd.delete('ala48')
cmd.delete('ala49')
cmd.select('ala51', 'n. O&r. ala w. %s of n. OD1&r. asp'%(d*8.12))
cmd.select('ala52', 'n. O&r. ala w. %s of n. OD2&r. asp'%(d*9.06))
cmd.select('ala53', 'n. O&r. ala w. %s of n. O&r. asp'%(d*6.97))
cmd.select('ala54', 'n. O&r. ala w. %s of n. C&r. asp'%(d*6.01))
cmd.select('ala55', 'n. O&r. ala w. %s of n. CA&r. asp'%(d*6.34))
cmd.select('ala56', 'n. O&r. ala w. %s of n. N&r. asp'%(d*5.41))
cmd.select('ala57', 'n. C&r. ala w. %s of n. CB&r. asp'%(d*7.31))
cmd.select('ala58', 'n. C&r. ala w. %s of n. CG&r. asp'%(d*7.85))
cmd.select('ala59', 'n. C&r. ala w. %s of n. OD1&r. asp'%(d*7.80))
cmd.select('ala60', 'n. C&r. ala w. %s of n. OD2&r. asp'%(d*8.66))
cmd.select('ala61', 'n. C&r. ala w. %s of n. O&r. asp'%(d*7.66))
cmd.select('ala62', 'n. C&r. ala w. %s of n. C&r. asp'%(d*6.56))
cmd.select('ala63', 'n. C&r. ala w. %s of n. CA&r. asp'%(d*6.53))
cmd.select('ala64', 'n. C&r. ala w. %s of n. N&r. asp'%(d*5.35))
cmd.select('ala65', 'n. CA&r. ala w. %s of n. CB&r. asp'%(d*8.10))
cmd.select('ala66', 'n. CA&r. ala w. %s of n. CG&r. asp'%(d*8.60))
cmd.select('ala67', 'n. CA&r. ala w. %s of n. OD1&r. asp'%(d*8.72))
cmd.select('ala68', 'n. CA&r. ala w. %s of n. OD2&r. asp'%(d*9.20))
cmd.select('ala69', 'n. CA&r. ala w. %s of n. O&r. asp'%(d*8.73))
cmd.select('ala70', 'n. CA&r. ala w. %s of n. C&r. asp'%(d*7.60))
cmd.select('ala71', 'n. CA&r. ala w. %s of n. CA&r. asp'%(d*7.62))
cmd.select('ala72', 'n. CA&r. ala w. %s of n. N&r. asp'%(d*6.52))
cmd.select('ala73', 'n. N&r. ala w. %s of n. CB&r. asp'%(d*7.61))
cmd.select('ala74', 'n. N&r. ala w. %s of n. CG&r. asp'%(d*7.95))
cmd.select('ala75', 'n. N&r. ala w. %s of n. OD1&r. asp'%(d*8.22))
cmd.select('ala76', 'n. N&r. ala w. %s of n. OD2&r. asp'%(d*8.34))
cmd.select('ala77', 'n. N&r. ala w. %s of n. O&r. asp'%(d*8.87))
cmd.select('ala78', 'n. N&r. ala w. %s of n. C&r. asp'%(d*7.69))
cmd.select('ala79', 'n. N&r. ala w. %s of n. CA&r. asp'%(d*7.50))
cmd.select('ala80', 'n. N&r. ala w. %s of n. N&r. asp'%(d*6.48))
cmd.select('ala',' ala50&br. ala51&br. ala52&br. ala53&br. ala54&br. ala55&br. ala56&br. ala57&br. ala58&br. ala59&br. ala60&br. ala61&br. ala62&br. ala63&br. ala64&br. ala65&br. ala66&br. ala67&br. ala68&br. ala69&br. ala70&br. ala71&br. ala72&br. ala73&br. ala74&br. ala75&br. ala76&br. ala77&br. ala78&br. ala79&br. ala80')
cmd.delete('ala50')
cmd.delete('ala51')
cmd.delete('ala52')
cmd.delete('ala53')
cmd.delete('ala54')
cmd.delete('ala55')
cmd.delete('ala56')
cmd.delete('ala57')
cmd.delete('ala58')
cmd.delete('ala59')
cmd.delete('ala60')
cmd.delete('ala61')
cmd.delete('ala62')
cmd.delete('ala63')
cmd.delete('ala64')
cmd.delete('ala65')
cmd.delete('ala66')
cmd.delete('ala67')
cmd.delete('ala68')
cmd.delete('ala69')
cmd.delete('ala70')
cmd.delete('ala71')
cmd.delete('ala72')
cmd.delete('ala73')
cmd.delete('ala74')
cmd.delete('ala75')
cmd.delete('ala76')
cmd.delete('ala77')
cmd.delete('ala78')
cmd.delete('ala79')
cmd.delete('ala80')
cmd.select('glyi1', 'n. O&r. gly w. %s of n. O&gly'%(d*7.02))
cmd.select('glyi2', 'n. O&r. gly w. %s of n. C&gly'%(d*6.14))
cmd.select('glyi3', 'n. O&r. gly w. %s of n. CA&gly'%(d*6.36))
cmd.select('glyi4', 'n. O&r. gly w. %s of n. N&gly'%(d*5.46))
cmd.select('glyi5', 'n. C&r. gly w. %s of n. O&gly'%(d*7.69))
cmd.select('glyi6', 'n. C&r. gly w. %s of n. C&gly'%(d*6.64))
cmd.select('glyi7', 'n. C&r. gly w. %s of n. CA&gly'%(d*6.52))
cmd.select('glyi8', 'n. C&r. gly w. %s of n. N&gly'%(d*5.36))
cmd.select('glyi9', 'n. CA&r. gly w. %s of n. O&gly'%(d*8.75))
cmd.select('glyi10', 'n. CA&r. gly w. %s of n. C&gly'%(d*7.65))
cmd.select('glyi11', 'n. CA&r. gly w. %s of n. CA&gly'%(d*7.57))
cmd.select('glyi12', 'n. CA&r. gly w. %s of n. N&gly'%(d*6.50))
cmd.select('glyi13', 'n. N&r. gly w. %s of n. O&gly'%(d*9.59))
cmd.select('glyi14', 'n. N&r. gly w. %s of n. C&gly'%(d*8.41))
cmd.select('glyi15', 'n. N&r. gly w. %s of n. CA&gly'%(d*8.03))
cmd.select('glyi16', 'n. N&r. gly w. %s of n. N&gly'%(d*6.87))
cmd.select('glyi17', 'n. O&r. gly w. %s of n. CB&ala'%(d*6.23))
cmd.select('glyi18', 'n. O&r. gly w. %s of n. O&ala'%(d*5.18))
cmd.select('glyi19', 'n. O&r. gly w. %s of n. C&ala'%(d*4.87))
cmd.select('glyi20', 'n. O&r. gly w. %s of n. CA&ala'%(d*4.76))
cmd.select('glyi21', 'n. O&r. gly w. %s of n. N&ala'%(d*4.25))
cmd.select('glyi22', 'n. C&r. gly w. %s of n. CB&ala'%(d*5.67))
cmd.select('glyi23', 'n. C&r. gly w. %s of n. O&ala'%(d*5.68))
cmd.select('glyi24', 'n. C&r. gly w. %s of n. C&ala'%(d*4.97))
cmd.select('glyi25', 'n. C&r. gly w. %s of n. CA&ala'%(d*4.42))
cmd.select('glyi26', 'n. C&r. gly w. %s of n. N&ala'%(d*3.33))
cmd.select('glyi27', 'n. CA&r. gly w. %s of n. CB&ala'%(d*6.79))
cmd.select('glyi28', 'n. CA&r. gly w. %s of n. O&ala'%(d*7.15))
cmd.select('glyi29', 'n. CA&r. gly w. %s of n. C&ala'%(d*6.37))
cmd.select('glyi30', 'n. CA&r. gly w. %s of n. CA&ala'%(d*5.78))
cmd.select('glyi31', 'n. CA&r. gly w. %s of n. N&ala'%(d*4.41))
cmd.select('glyi32', 'n. N&r. gly w. %s of n. CB&ala'%(d*6.76))
cmd.select('glyi33', 'n. N&r. gly w. %s of n. O&ala'%(d*7.93))
cmd.select('glyi34', 'n. N&r. gly w. %s of n. C&ala'%(d*6.94))
cmd.select('glyi35', 'n. N&r. gly w. %s of n. CA&ala'%(d*6.16))
cmd.select('glyi36', 'n. N&r. gly w. %s of n. N&ala'%(d*4.72))
cmd.select('glyi37', 'n. O&r. gly w. %s of n. CB&r. asp'%(d*5.96))
cmd.select('glyi38', 'n. O&r. gly w. %s of n. CG&r. asp'%(d*6.76))
cmd.select('glyi39', 'n. O&r. gly w. %s of n. OD1&r. asp'%(d*7.33))
cmd.select('glyi40', 'n. O&r. gly w. %s of n. OD2&r. asp'%(d*7.22))
cmd.select('glyi41', 'n. O&r. gly w. %s of n. O&r. asp'%(d*6.96))
cmd.select('glyi42', 'n. O&r. gly w. %s of n. C&r. asp'%(d*5.85))
cmd.select('glyi43', 'n. O&r. gly w. %s of n. CA&r. asp'%(d*5.95))
cmd.select('glyi44', 'n. O&r. gly w. %s of n. N&r. asp'%(d*5.44))
cmd.select('glyi45', 'n. C&r. gly w. %s of n. CB&r. asp'%(d*6.61))
cmd.select('glyi46', 'n. C&r. gly w. %s of n. CG&r. asp'%(d*7.07))
cmd.select('glyi47', 'n. C&r. gly w. %s of n. OD1&r. asp'%(d*7.56))
cmd.select('glyi48', 'n. C&r. gly w. %s of n. OD2&r. asp'%(d*7.37))
cmd.select('glyi49', 'n. C&r. gly w. %s of n. O&r. asp'%(d*8.07))
cmd.select('glyi50', 'n. C&r. gly w. %s of n. C&r. asp'%(d*6.90))
cmd.select('glyi50',' br. glyi1&br. glyi2&br. glyi3&br. glyi4&br. glyi5&br. glyi6&br. glyi7&br. glyi8&br. glyi9&br. glyi10&br. glyi11&br. glyi12&br. glyi13&br. glyi14&br. glyi15&br. glyi16&br. glyi17&br. glyi18&br. glyi19&br. glyi20&br. glyi21&br. glyi22&br. glyi23&br. glyi24&br. glyi25&br. glyi26&br. glyi27&br. glyi28&br. glyi29&br. glyi30&br. glyi31&br. glyi32&br. glyi33&br. glyi34&br. glyi35&br. glyi36&br. glyi37&br. glyi38&br. glyi39&br. glyi40&br. glyi41&br. glyi42&br. glyi43&br. glyi44&br. glyi45&br. glyi46&br. glyi47&br. glyi48&br. glyi49&br. glyi50')
cmd.delete('glyi1')
cmd.delete('glyi2')
cmd.delete('glyi3')
cmd.delete('glyi4')
cmd.delete('glyi5')
cmd.delete('glyi6')
cmd.delete('glyi7')
cmd.delete('glyi8')
cmd.delete('glyi9')
cmd.delete('glyi10')
cmd.delete('glyi11')
cmd.delete('glyi12')
cmd.delete('glyi13')
cmd.delete('glyi14')
cmd.delete('glyi15')
cmd.delete('glyi16')
cmd.delete('glyi17')
cmd.delete('glyi18')
cmd.delete('glyi19')
cmd.delete('glyi20')
cmd.delete('glyi21')
cmd.delete('glyi22')
cmd.delete('glyi23')
cmd.delete('glyi24')
cmd.delete('glyi25')
cmd.delete('glyi26')
cmd.delete('glyi27')
cmd.delete('glyi28')
cmd.delete('glyi29')
cmd.delete('glyi30')
cmd.delete('glyi31')
cmd.delete('glyi32')
cmd.delete('glyi33')
cmd.delete('glyi34')
cmd.delete('glyi35')
cmd.delete('glyi36')
cmd.delete('glyi37')
cmd.delete('glyi38')
cmd.delete('glyi39')
cmd.delete('glyi40')
cmd.delete('glyi41')
cmd.delete('glyi42')
cmd.delete('glyi43')
cmd.delete('glyi44')
cmd.delete('glyi45')
cmd.delete('glyi46')
cmd.delete('glyi47')
cmd.delete('glyi48')
cmd.delete('glyi49')
cmd.select('glyi51', 'n. C&r. gly w. %s of n. CA&r. asp'%(d*6.73))
cmd.select('glyi52', 'n. C&r. gly w. %s of n. N&r. asp'%(d*5.99))
cmd.select('glyi53', 'n. CA&r. gly w. %s of n. CB&r. asp'%(d*6.79))
cmd.select('glyi54', 'n. CA&r. gly w. %s of n. CG&r. asp'%(d*6.96))
cmd.select('glyi55', 'n. CA&r. gly w. %s of n. OD1&r. asp'%(d*7.60))
cmd.select('glyi56', 'n. CA&r. gly w. %s of n. OD2&r. asp'%(d*6.91))
cmd.select('glyi57', 'n. CA&r. gly w. %s of n. O&r. asp'%(d*8.85))
cmd.select('glyi58', 'n. CA&r. gly w. %s of n. C&r. asp'%(d*7.73))
cmd.select('glyi59', 'n. CA&r. gly w. %s of n. CA&r. asp'%(d*7.34))
cmd.select('glyi60', 'n. CA&r. gly w. %s of n. N&r. asp'%(d*6.76))
cmd.select('glyi61', 'n. N&r. gly w. %s of n. CB&r. asp'%(d*7.88))
cmd.select('glyi62', 'n. N&r. gly w. %s of n. CG&r. asp'%(d*7.75))
cmd.select('glyi63', 'n. N&r. gly w. %s of n. OD1&r. asp'%(d*8.22))
cmd.select('glyi64', 'n. N&r. gly w. %s of n. OD2&r. asp'%(d*7.59))
cmd.select('glyi65', 'n. N&r. gly w. %s of n. O&r. asp'%(d*10.13))
cmd.select('glyi66', 'n. N&r. gly w. %s of n. C&r. asp'%(d*8.97))
cmd.select('glyi67', 'n. N&r. gly w. %s of n. CA&r. asp'%(d*8.41))
cmd.select('glyi68', 'n. N&r. gly w. %s of n. N&r. asp'%(d*7.64))
cmd.select('glyi',' glyi50&br. glyi51&br. glyi52&br. glyi53&br. glyi54&br. glyi55&br. glyi56&br. glyi57&br. glyi58&br. glyi59&br. glyi60&br. glyi61&br. glyi62&br. glyi63&br. glyi64&br. glyi65&br. glyi66&br. glyi67&br. glyi68')
cmd.delete('glyi50')
cmd.delete('glyi51')
cmd.delete('glyi52')
cmd.delete('glyi53')
cmd.delete('glyi54')
cmd.delete('glyi55')
cmd.delete('glyi56')
cmd.delete('glyi57')
cmd.delete('glyi58')
cmd.delete('glyi59')
cmd.delete('glyi60')
cmd.delete('glyi61')
cmd.delete('glyi62')
cmd.delete('glyi63')
cmd.delete('glyi64')
cmd.delete('glyi65')
cmd.delete('glyi66')
cmd.delete('glyi67')
cmd.delete('glyi68')
cmd.select('asp1', 'n. CB&r. asp w. %s of n. O&gly'%(d*6.23))
cmd.select('asp2', 'n. CB&r. asp w. %s of n. C&gly'%(d*5.69))
cmd.select('asp3', 'n. CB&r. asp w. %s of n. CA&gly'%(d*6.81))
cmd.select('asp4', 'n. CB&r. asp w. %s of n. N&gly'%(d*7.04))
cmd.select('asp5', 'n. CG&r. asp w. %s of n. O&gly'%(d*6.81))
cmd.select('asp6', 'n. CG&r. asp w. %s of n. C&gly'%(d*6.11))
cmd.select('asp7', 'n. CG&r. asp w. %s of n. CA&gly'%(d*6.97))
cmd.select('asp8', 'n. CG&r. asp w. %s of n. N&gly'%(d*7.26))
cmd.select('asp9', 'n. OD1&r. asp w. %s of n. O&gly'%(d*6.36))
cmd.select('asp10', 'n. OD1&r. asp w. %s of n. C&gly'%(d*5.70))
cmd.select('asp11', 'n. OD1&r. asp w. %s of n. CA&gly'%(d*6.44))
cmd.select('asp12', 'n. OD1&r. asp w. %s of n. N&gly'%(d*6.99))
cmd.select('asp13', 'n. OD2&r. asp w. %s of n. O&gly'%(d*8.04))
cmd.select('asp14', 'n. OD2&r. asp w. %s of n. C&gly'%(d*7.27))
cmd.select('asp15', 'n. OD2&r. asp w. %s of n. CA&gly'%(d*8.00))
cmd.select('asp16', 'n. OD2&r. asp w. %s of n. N&gly'%(d*8.09))
cmd.select('asp17', 'n. O&r. asp w. %s of n. O&gly'%(d*5.55))
cmd.select('asp18', 'n. O&r. asp w. %s of n. C&gly'%(d*5.91))
cmd.select('asp19', 'n. O&r. asp w. %s of n. CA&gly'%(d*7.35))
cmd.select('asp20', 'n. O&r. asp w. %s of n. N&gly'%(d*7.86))
cmd.select('asp21', 'n. C&r. asp w. %s of n. O&gly'%(d*4.96))
cmd.select('asp22', 'n. C&r. asp w. %s of n. C&gly'%(d*4.99))
cmd.select('asp23', 'n. C&r. asp w. %s of n. CA&gly'%(d*6.36))
cmd.select('asp24', 'n. C&r. asp w. %s of n. N&gly'%(d*6.73))
cmd.select('asp25', 'n. CA&r. asp w. %s of n. O&gly'%(d*4.75))
cmd.select('asp26', 'n. CA&r. asp w. %s of n. C&gly'%(d*4.42))
cmd.select('asp27', 'n. CA&r. asp w. %s of n. CA&gly'%(d*5.77))
cmd.select('asp28', 'n. CA&r. asp w. %s of n. N&gly'%(d*6.28))
cmd.select('asp29', 'n. N&r. asp w. %s of n. O&gly'%(d*4.24))
cmd.select('asp30', 'n. N&r. asp w. %s of n. C&gly'%(d*3.32))
cmd.select('asp31', 'n. N&r. asp w. %s of n. CA&gly'%(d*4.41))
cmd.select('asp32', 'n. N&r. asp w. %s of n. N&gly'%(d*4.88))
cmd.select('asp33', 'n. CB&r. asp w. %s of n. CB&ala'%(d*9.41))
cmd.select('asp34', 'n. CB&r. asp w. %s of n. O&ala'%(d*7.34))
cmd.select('asp35', 'n. CB&r. asp w. %s of n. C&ala'%(d*7.31))
cmd.select('asp36', 'n. CB&r. asp w. %s of n. CA&ala'%(d*8.10))
cmd.select('asp37', 'n. CB&r. asp w. %s of n. N&ala'%(d*7.61))
cmd.select('asp38', 'n. CG&r. asp w. %s of n. CB&ala'%(d*9.74))
cmd.select('asp39', 'n. CG&r. asp w. %s of n. O&ala'%(d*8.13))
cmd.select('asp40', 'n. CG&r. asp w. %s of n. C&ala'%(d*7.85))
cmd.select('asp41', 'n. CG&r. asp w. %s of n. CA&ala'%(d*8.60))
cmd.select('asp42', 'n. CG&r. asp w. %s of n. N&ala'%(d*7.95))
cmd.select('asp43', 'n. OD1&r. asp w. %s of n. CB&ala'%(d*9.71))
cmd.select('asp44', 'n. OD1&r. asp w. %s of n. O&ala'%(d*8.12))
cmd.select('asp45', 'n. OD1&r. asp w. %s of n. C&ala'%(d*7.80))
cmd.select('asp46', 'n. OD1&r. asp w. %s of n. CA&ala'%(d*8.72))
cmd.select('asp47', 'n. OD1&r. asp w. %s of n. N&ala'%(d*8.22))
cmd.select('asp48', 'n. OD2&r. asp w. %s of n. CB&ala'%(d*10.32))
cmd.select('asp49', 'n. OD2&r. asp w. %s of n. O&ala'%(d*9.06))
cmd.select('asp50', 'n. OD2&r. asp w. %s of n. C&ala'%(d*8.66))
cmd.select('asp50',' br. asp1&br. asp2&br. asp3&br. asp4&br. asp5&br. asp6&br. asp7&br. asp8&br. asp9&br. asp10&br. asp11&br. asp12&br. asp13&br. asp14&br. asp15&br. asp16&br. asp17&br. asp18&br. asp19&br. asp20&br. asp21&br. asp22&br. asp23&br. asp24&br. asp25&br. asp26&br. asp27&br. asp28&br. asp29&br. asp30&br. asp31&br. asp32&br. asp33&br. asp34&br. asp35&br. asp36&br. asp37&br. asp38&br. asp39&br. asp40&br. asp41&br. asp42&br. asp43&br. asp44&br. asp45&br. asp46&br. asp47&br. asp48&br. asp49&br. asp50')
cmd.delete('asp1')
cmd.delete('asp2')
cmd.delete('asp3')
cmd.delete('asp4')
cmd.delete('asp5')
cmd.delete('asp6')
cmd.delete('asp7')
cmd.delete('asp8')
cmd.delete('asp9')
cmd.delete('asp10')
cmd.delete('asp11')
cmd.delete('asp12')
cmd.delete('asp13')
cmd.delete('asp14')
cmd.delete('asp15')
cmd.delete('asp16')
cmd.delete('asp17')
cmd.delete('asp18')
cmd.delete('asp19')
cmd.delete('asp20')
cmd.delete('asp21')
cmd.delete('asp22')
cmd.delete('asp23')
cmd.delete('asp24')
cmd.delete('asp25')
cmd.delete('asp26')
cmd.delete('asp27')
cmd.delete('asp28')
cmd.delete('asp29')
cmd.delete('asp30')
cmd.delete('asp31')
cmd.delete('asp32')
cmd.delete('asp33')
cmd.delete('asp34')
cmd.delete('asp35')
cmd.delete('asp36')
cmd.delete('asp37')
cmd.delete('asp38')
cmd.delete('asp39')
cmd.delete('asp40')
cmd.delete('asp41')
cmd.delete('asp42')
cmd.delete('asp43')
cmd.delete('asp44')
cmd.delete('asp45')
cmd.delete('asp46')
cmd.delete('asp47')
cmd.delete('asp48')
cmd.delete('asp49')
cmd.select('asp51', 'n. OD2&r. asp w. %s of n. CA&ala'%(d*9.20))
cmd.select('asp52', 'n. OD2&r. asp w. %s of n. N&ala'%(d*8.34))
cmd.select('asp53', 'n. O&r. asp w. %s of n. CB&ala'%(d*10.08))
cmd.select('asp54', 'n. O&r. asp w. %s of n. O&ala'%(d*6.97))
cmd.select('asp55', 'n. O&r. asp w. %s of n. C&ala'%(d*7.66))
cmd.select('asp56', 'n. O&r. asp w. %s of n. CA&ala'%(d*8.73))
cmd.select('asp57', 'n. O&r. asp w. %s of n. N&ala'%(d*8.87))
cmd.select('asp58', 'n. C&r. asp w. %s of n. CB&ala'%(d*8.96))
cmd.select('asp59', 'n. C&r. asp w. %s of n. O&ala'%(d*6.01))
cmd.select('asp60', 'n. C&r. asp w. %s of n. C&ala'%(d*6.56))
cmd.select('asp61', 'n. C&r. asp w. %s of n. CA&ala'%(d*7.60))
cmd.select('asp62', 'n. C&r. asp w. %s of n. N&ala'%(d*7.69))
cmd.select('asp63', 'n. CA&r. asp w. %s of n. CB&ala'%(d*8.88))
cmd.select('asp64', 'n. CA&r. asp w. %s of n. O&ala'%(d*6.34))
cmd.select('asp65', 'n. CA&r. asp w. %s of n. C&ala'%(d*6.53))
cmd.select('asp66', 'n. CA&r. asp w. %s of n. CA&ala'%(d*7.62))
cmd.select('asp67', 'n. CA&r. asp w. %s of n. N&ala'%(d*7.50))
cmd.select('asp68', 'n. N&r. asp w. %s of n. CB&ala'%(d*7.64))
cmd.select('asp69', 'n. N&r. asp w. %s of n. O&ala'%(d*5.41))
cmd.select('asp70', 'n. N&r. asp w. %s of n. C&ala'%(d*5.35))
cmd.select('asp71', 'n. N&r. asp w. %s of n. CA&ala'%(d*6.52))
cmd.select('asp72', 'n. N&r. asp w. %s of n. N&ala'%(d*6.48))
cmd.select('asp73', 'n. CB&r. asp w. %s of n. O&glyi'%(d*5.96))
cmd.select('asp74', 'n. CB&r. asp w. %s of n. C&glyi'%(d*6.61))
cmd.select('asp75', 'n. CB&r. asp w. %s of n. CA&glyi'%(d*6.79))
cmd.select('asp76', 'n. CB&r. asp w. %s of n. N&glyi'%(d*7.88))
cmd.select('asp77', 'n. CG&r. asp w. %s of n. O&glyi'%(d*6.76))
cmd.select('asp78', 'n. CG&r. asp w. %s of n. C&glyi'%(d*7.07))
cmd.select('asp79', 'n. CG&r. asp w. %s of n. CA&glyi'%(d*6.96))
cmd.select('asp80', 'n. CG&r. asp w. %s of n. N&glyi'%(d*7.75))
cmd.select('asp81', 'n. OD1&r. asp w. %s of n. O&glyi'%(d*7.33))
cmd.select('asp82', 'n. OD1&r. asp w. %s of n. C&glyi'%(d*7.56))
cmd.select('asp83', 'n. OD1&r. asp w. %s of n. CA&glyi'%(d*7.60))
cmd.select('asp84', 'n. OD1&r. asp w. %s of n. N&glyi'%(d*8.22))
cmd.select('asp85', 'n. OD2&r. asp w. %s of n. O&glyi'%(d*7.22))
cmd.select('asp86', 'n. OD2&r. asp w. %s of n. C&glyi'%(d*7.37))
cmd.select('asp87', 'n. OD2&r. asp w. %s of n. CA&glyi'%(d*6.91))
cmd.select('asp88', 'n. OD2&r. asp w. %s of n. N&glyi'%(d*7.59))
cmd.select('asp89', 'n. O&r. asp w. %s of n. O&glyi'%(d*6.96))
cmd.select('asp90', 'n. O&r. asp w. %s of n. C&glyi'%(d*8.07))
cmd.select('asp91', 'n. O&r. asp w. %s of n. CA&glyi'%(d*8.85))
cmd.select('asp92', 'n. O&r. asp w. %s of n. N&glyi'%(d*10.13))
cmd.select('asp93', 'n. C&r. asp w. %s of n. O&glyi'%(d*5.85))
cmd.select('asp94', 'n. C&r. asp w. %s of n. C&glyi'%(d*6.90))
cmd.select('asp95', 'n. C&r. asp w. %s of n. CA&glyi'%(d*7.73))
cmd.select('asp96', 'n. C&r. asp w. %s of n. N&glyi'%(d*8.97))
cmd.select('asp97', 'n. CA&r. asp w. %s of n. O&glyi'%(d*5.95))
cmd.select('asp98', 'n. CA&r. asp w. %s of n. C&glyi'%(d*6.73))
cmd.select('asp99', 'n. CA&r. asp w. %s of n. CA&glyi'%(d*7.34))
cmd.select('asp100', 'n. CA&r. asp w. %s of n. N&glyi'%(d*8.41))
cmd.select('asp100',' br. asp51&br. asp52&br. asp53&br. asp54&br. asp55&br. asp56&br. asp57&br. asp58&br. asp59&br. asp60&br. asp61&br. asp62&br. asp63&br. asp64&br. asp65&br. asp66&br. asp67&br. asp68&br. asp69&br. asp70&br. asp71&br. asp72&br. asp73&br. asp74&br. asp75&br. asp76&br. asp77&br. asp78&br. asp79&br. asp80&br. asp81&br. asp82&br. asp83&br. asp84&br. asp85&br. asp86&br. asp87&br. asp88&br. asp89&br. asp90&br. asp91&br. asp92&br. asp93&br. asp94&br. asp95&br. asp96&br. asp97&br. asp98&br. asp99&br. asp100')
cmd.delete('asp51')
cmd.delete('asp52')
cmd.delete('asp53')
cmd.delete('asp54')
cmd.delete('asp55')
cmd.delete('asp56')
cmd.delete('asp57')
cmd.delete('asp58')
cmd.delete('asp59')
cmd.delete('asp60')
cmd.delete('asp61')
cmd.delete('asp62')
cmd.delete('asp63')
cmd.delete('asp64')
cmd.delete('asp65')
cmd.delete('asp66')
cmd.delete('asp67')
cmd.delete('asp68')
cmd.delete('asp69')
cmd.delete('asp70')
cmd.delete('asp71')
cmd.delete('asp72')
cmd.delete('asp73')
cmd.delete('asp74')
cmd.delete('asp75')
cmd.delete('asp76')
cmd.delete('asp77')
cmd.delete('asp78')
cmd.delete('asp79')
cmd.delete('asp80')
cmd.delete('asp81')
cmd.delete('asp82')
cmd.delete('asp83')
cmd.delete('asp84')
cmd.delete('asp85')
cmd.delete('asp86')
cmd.delete('asp87')
cmd.delete('asp88')
cmd.delete('asp89')
cmd.delete('asp90')
cmd.delete('asp91')
cmd.delete('asp92')
cmd.delete('asp93')
cmd.delete('asp94')
cmd.delete('asp95')
cmd.delete('asp96')
cmd.delete('asp97')
cmd.delete('asp98')
cmd.delete('asp99')
cmd.select('asp101', 'n. N&r. asp w. %s of n. O&glyi'%(d*5.44))
cmd.select('asp102', 'n. N&r. asp w. %s of n. C&glyi'%(d*5.99))
cmd.select('asp103', 'n. N&r. asp w. %s of n. CA&glyi'%(d*6.76))
cmd.select('asp104', 'n. N&r. asp w. %s of n. N&glyi'%(d*7.64))
cmd.select('asp',' asp50&asp100&br. asp101&br. asp102&br. asp103&br. asp104')
cmd.delete('asp50')
cmd.delete('asp100')
cmd.delete('asp101')
cmd.delete('asp102')
cmd.delete('asp103')
cmd.delete('asp104')
cmd.select('A_1tz3_3_6_1_26', 'gly|ala|glyi|asp')
cmd.delete('gly')
cmd.delete('ala')
cmd.delete('glyi')
cmd.delete('asp')
