'''
FUNC:P_1ecg-C1A-N101A-G102A
PDB:1ecg
EC:2.4.2.14
PFAM:PF00310,PF13230,PF13522,PF00156,PF13537
RESI:cys,asn,gly
LOCI:a-1,101,102;
'''
cmd.select('cys1', 'n. CB&r. cys w. %s of n. CB&r. asn'%(d*5.31))
cmd.select('cys2', 'n. CB&r. cys w. %s of n. CG&r. asn'%(d*5.49))
cmd.select('cys3', 'n. CB&r. cys w. %s of n. OD1&r. asn'%(d*6.44))
cmd.select('cys4', 'n. CB&r. cys w. %s of n. ND2&r. asn'%(d*5.03))
cmd.select('cys5', 'n. SG&r. cys w. %s of n. CB&r. asn'%(d*6.68))
cmd.select('cys6', 'n. SG&r. cys w. %s of n. CG&r. asn'%(d*6.77))
cmd.select('cys7', 'n. SG&r. cys w. %s of n. OD1&r. asn'%(d*7.81))
cmd.select('cys8', 'n. SG&r. cys w. %s of n. ND2&r. asn'%(d*5.99))
cmd.select('cys9', 'n. O&r. cys w. %s of n. CB&r. asn'%(d*4.60))
cmd.select('cys10', 'n. O&r. cys w. %s of n. CG&r. asn'%(d*4.16))
cmd.select('cys11', 'n. O&r. cys w. %s of n. OD1&r. asn'%(d*4.37))
cmd.select('cys12', 'n. O&r. cys w. %s of n. ND2&r. asn'%(d*4.37))
cmd.select('cys13', 'n. C&r. cys w. %s of n. CB&r. asn'%(d*5.12))
cmd.select('cys14', 'n. C&r. cys w. %s of n. CG&r. asn'%(d*5.00))
cmd.select('cys15', 'n. C&r. cys w. %s of n. OD1&r. asn'%(d*5.45))
cmd.select('cys16', 'n. C&r. cys w. %s of n. ND2&r. asn'%(d*5.04))
cmd.select('cys17', 'n. CA&r. cys w. %s of n. CB&r. asn'%(d*5.71))
cmd.select('cys18', 'n. CA&r. cys w. %s of n. CG&r. asn'%(d*5.52))
cmd.select('cys19', 'n. CA&r. cys w. %s of n. OD1&r. asn'%(d*6.20))
cmd.select('cys20', 'n. CA&r. cys w. %s of n. ND2&r. asn'%(d*5.11))
cmd.select('cys21', 'n. N&r. cys w. %s of n. CB&r. asn'%(d*5.94))
cmd.select('cys22', 'n. N&r. cys w. %s of n. CG&r. asn'%(d*5.28))
cmd.select('cys23', 'n. N&r. cys w. %s of n. OD1&r. asn'%(d*5.87))
cmd.select('cys24', 'n. N&r. cys w. %s of n. ND2&r. asn'%(d*4.56))
cmd.select('cys25', 'n. CB&r. cys w. %s of n. O&r. gly'%(d*7.87))
cmd.select('cys26', 'n. CB&r. cys w. %s of n. C&r. gly'%(d*8.47))
cmd.select('cys27', 'n. CB&r. cys w. %s of n. CA&r. gly'%(d*7.94))
cmd.select('cys28', 'n. CB&r. cys w. %s of n. N&r. gly'%(d*6.61))
cmd.select('cys29', 'n. SG&r. cys w. %s of n. O&r. gly'%(d*7.48))
cmd.select('cys30', 'n. SG&r. cys w. %s of n. C&r. gly'%(d*8.33))
cmd.select('cys31', 'n. SG&r. cys w. %s of n. CA&r. gly'%(d*8.17))
cmd.select('cys32', 'n. SG&r. cys w. %s of n. N&r. gly'%(d*6.98))
cmd.select('cys33', 'n. O&r. cys w. %s of n. O&r. gly'%(d*9.31))
cmd.select('cys34', 'n. O&r. cys w. %s of n. C&r. gly'%(d*9.51))
cmd.select('cys35', 'n. O&r. cys w. %s of n. CA&r. gly'%(d*8.49))
cmd.select('cys36', 'n. O&r. cys w. %s of n. N&r. gly'%(d*7.29))
cmd.select('cys37', 'n. C&r. cys w. %s of n. O&r. gly'%(d*9.47))
cmd.select('cys38', 'n. C&r. cys w. %s of n. C&r. gly'%(d*9.82))
cmd.select('cys39', 'n. C&r. cys w. %s of n. CA&r. gly'%(d*8.94))
cmd.select('cys40', 'n. C&r. cys w. %s of n. N&r. gly'%(d*7.64))
cmd.select('cys41', 'n. CA&r. cys w. %s of n. O&r. gly'%(d*8.83))
cmd.select('cys42', 'n. CA&r. cys w. %s of n. C&r. gly'%(d*9.36))
cmd.select('cys43', 'n. CA&r. cys w. %s of n. CA&r. gly'%(d*8.71))
cmd.select('cys44', 'n. CA&r. cys w. %s of n. N&r. gly'%(d*7.45))
cmd.select('cys45', 'n. N&r. cys w. %s of n. O&r. gly'%(d*8.35))
cmd.select('cys46', 'n. N&r. cys w. %s of n. C&r. gly'%(d*8.88))
cmd.select('cys47', 'n. N&r. cys w. %s of n. CA&r. gly'%(d*8.26))
cmd.select('cys48', 'n. N&r. cys w. %s of n. N&r. gly'%(d*7.18))
cmd.select('cys',' br. cys1&br. cys2&br. cys3&br. cys4&br. cys5&br. cys6&br. cys7&br. cys8&br. cys9&br. cys10&br. cys11&br. cys12&br. cys13&br. cys14&br. cys15&br. cys16&br. cys17&br. cys18&br. cys19&br. cys20&br. cys21&br. cys22&br. cys23&br. cys24&br. cys25&br. cys26&br. cys27&br. cys28&br. cys29&br. cys30&br. cys31&br. cys32&br. cys33&br. cys34&br. cys35&br. cys36&br. cys37&br. cys38&br. cys39&br. cys40&br. cys41&br. cys42&br. cys43&br. cys44&br. cys45&br. cys46&br. cys47&br. cys48')
cmd.delete('cys1')
cmd.delete('cys2')
cmd.delete('cys3')
cmd.delete('cys4')
cmd.delete('cys5')
cmd.delete('cys6')
cmd.delete('cys7')
cmd.delete('cys8')
cmd.delete('cys9')
cmd.delete('cys10')
cmd.delete('cys11')
cmd.delete('cys12')
cmd.delete('cys13')
cmd.delete('cys14')
cmd.delete('cys15')
cmd.delete('cys16')
cmd.delete('cys17')
cmd.delete('cys18')
cmd.delete('cys19')
cmd.delete('cys20')
cmd.delete('cys21')
cmd.delete('cys22')
cmd.delete('cys23')
cmd.delete('cys24')
cmd.delete('cys25')
cmd.delete('cys26')
cmd.delete('cys27')
cmd.delete('cys28')
cmd.delete('cys29')
cmd.delete('cys30')
cmd.delete('cys31')
cmd.delete('cys32')
cmd.delete('cys33')
cmd.delete('cys34')
cmd.delete('cys35')
cmd.delete('cys36')
cmd.delete('cys37')
cmd.delete('cys38')
cmd.delete('cys39')
cmd.delete('cys40')
cmd.delete('cys41')
cmd.delete('cys42')
cmd.delete('cys43')
cmd.delete('cys44')
cmd.delete('cys45')
cmd.delete('cys46')
cmd.delete('cys47')
cmd.delete('cys48')
cmd.select('asn1', 'n. CB&r. asn w. %s of n. CB&cys'%(d*5.31))
cmd.select('asn2', 'n. CB&r. asn w. %s of n. SG&cys'%(d*6.68))
cmd.select('asn3', 'n. CB&r. asn w. %s of n. O&cys'%(d*4.60))
cmd.select('asn4', 'n. CB&r. asn w. %s of n. C&cys'%(d*5.12))
cmd.select('asn5', 'n. CB&r. asn w. %s of n. CA&cys'%(d*5.71))
cmd.select('asn6', 'n. CB&r. asn w. %s of n. N&cys'%(d*5.94))
cmd.select('asn7', 'n. CG&r. asn w. %s of n. CB&cys'%(d*5.49))
cmd.select('asn8', 'n. CG&r. asn w. %s of n. SG&cys'%(d*6.77))
cmd.select('asn9', 'n. CG&r. asn w. %s of n. O&cys'%(d*4.16))
cmd.select('asn10', 'n. CG&r. asn w. %s of n. C&cys'%(d*5.00))
cmd.select('asn11', 'n. CG&r. asn w. %s of n. CA&cys'%(d*5.52))
cmd.select('asn12', 'n. CG&r. asn w. %s of n. N&cys'%(d*5.28))
cmd.select('asn13', 'n. OD1&r. asn w. %s of n. CB&cys'%(d*6.44))
cmd.select('asn14', 'n. OD1&r. asn w. %s of n. SG&cys'%(d*7.81))
cmd.select('asn15', 'n. OD1&r. asn w. %s of n. O&cys'%(d*4.37))
cmd.select('asn16', 'n. OD1&r. asn w. %s of n. C&cys'%(d*5.45))
cmd.select('asn17', 'n. OD1&r. asn w. %s of n. CA&cys'%(d*6.20))
cmd.select('asn18', 'n. OD1&r. asn w. %s of n. N&cys'%(d*5.87))
cmd.select('asn19', 'n. ND2&r. asn w. %s of n. CB&cys'%(d*5.03))
cmd.select('asn20', 'n. ND2&r. asn w. %s of n. SG&cys'%(d*5.99))
cmd.select('asn21', 'n. ND2&r. asn w. %s of n. O&cys'%(d*4.37))
cmd.select('asn22', 'n. ND2&r. asn w. %s of n. C&cys'%(d*5.04))
cmd.select('asn23', 'n. ND2&r. asn w. %s of n. CA&cys'%(d*5.11))
cmd.select('asn24', 'n. ND2&r. asn w. %s of n. N&cys'%(d*4.56))
cmd.select('asn25', 'n. CB&r. asn w. %s of n. O&r. gly'%(d*7.22))
cmd.select('asn26', 'n. CB&r. asn w. %s of n. C&r. gly'%(d*7.06))
cmd.select('asn27', 'n. CB&r. asn w. %s of n. CA&r. gly'%(d*5.82))
cmd.select('asn28', 'n. CB&r. asn w. %s of n. N&r. gly'%(d*4.58))
cmd.select('asn29', 'n. CG&r. asn w. %s of n. O&r. gly'%(d*7.14))
cmd.select('asn30', 'n. CG&r. asn w. %s of n. C&r. gly'%(d*6.97))
cmd.select('asn31', 'n. CG&r. asn w. %s of n. CA&r. gly'%(d*5.70))
cmd.select('asn32', 'n. CG&r. asn w. %s of n. N&r. gly'%(d*4.69))
cmd.select('asn33', 'n. OD1&r. asn w. %s of n. O&r. gly'%(d*8.12))
cmd.select('asn34', 'n. OD1&r. asn w. %s of n. C&r. gly'%(d*7.83))
cmd.select('asn35', 'n. OD1&r. asn w. %s of n. CA&r. gly'%(d*6.47))
cmd.select('asn36', 'n. OD1&r. asn w. %s of n. N&r. gly'%(d*5.67))
cmd.select('asn37', 'n. ND2&r. asn w. %s of n. O&r. gly'%(d*6.30))
cmd.select('asn38', 'n. ND2&r. asn w. %s of n. C&r. gly'%(d*6.32))
cmd.select('asn39', 'n. ND2&r. asn w. %s of n. CA&r. gly'%(d*5.25))
cmd.select('asn40', 'n. ND2&r. asn w. %s of n. N&r. gly'%(d*4.28))
cmd.select('asn',' br. asn1&br. asn2&br. asn3&br. asn4&br. asn5&br. asn6&br. asn7&br. asn8&br. asn9&br. asn10&br. asn11&br. asn12&br. asn13&br. asn14&br. asn15&br. asn16&br. asn17&br. asn18&br. asn19&br. asn20&br. asn21&br. asn22&br. asn23&br. asn24&br. asn25&br. asn26&br. asn27&br. asn28&br. asn29&br. asn30&br. asn31&br. asn32&br. asn33&br. asn34&br. asn35&br. asn36&br. asn37&br. asn38&br. asn39&br. asn40')
cmd.delete('asn1')
cmd.delete('asn2')
cmd.delete('asn3')
cmd.delete('asn4')
cmd.delete('asn5')
cmd.delete('asn6')
cmd.delete('asn7')
cmd.delete('asn8')
cmd.delete('asn9')
cmd.delete('asn10')
cmd.delete('asn11')
cmd.delete('asn12')
cmd.delete('asn13')
cmd.delete('asn14')
cmd.delete('asn15')
cmd.delete('asn16')
cmd.delete('asn17')
cmd.delete('asn18')
cmd.delete('asn19')
cmd.delete('asn20')
cmd.delete('asn21')
cmd.delete('asn22')
cmd.delete('asn23')
cmd.delete('asn24')
cmd.delete('asn25')
cmd.delete('asn26')
cmd.delete('asn27')
cmd.delete('asn28')
cmd.delete('asn29')
cmd.delete('asn30')
cmd.delete('asn31')
cmd.delete('asn32')
cmd.delete('asn33')
cmd.delete('asn34')
cmd.delete('asn35')
cmd.delete('asn36')
cmd.delete('asn37')
cmd.delete('asn38')
cmd.delete('asn39')
cmd.delete('asn40')
cmd.select('gly1', 'n. O&r. gly w. %s of n. CB&cys'%(d*7.87))
cmd.select('gly2', 'n. O&r. gly w. %s of n. SG&cys'%(d*7.48))
cmd.select('gly3', 'n. O&r. gly w. %s of n. O&cys'%(d*9.31))
cmd.select('gly4', 'n. O&r. gly w. %s of n. C&cys'%(d*9.47))
cmd.select('gly5', 'n. O&r. gly w. %s of n. CA&cys'%(d*8.83))
cmd.select('gly6', 'n. O&r. gly w. %s of n. N&cys'%(d*8.35))
cmd.select('gly7', 'n. C&r. gly w. %s of n. CB&cys'%(d*8.47))
cmd.select('gly8', 'n. C&r. gly w. %s of n. SG&cys'%(d*8.33))
cmd.select('gly9', 'n. C&r. gly w. %s of n. O&cys'%(d*9.51))
cmd.select('gly10', 'n. C&r. gly w. %s of n. C&cys'%(d*9.82))
cmd.select('gly11', 'n. C&r. gly w. %s of n. CA&cys'%(d*9.36))
cmd.select('gly12', 'n. C&r. gly w. %s of n. N&cys'%(d*8.88))
cmd.select('gly13', 'n. CA&r. gly w. %s of n. CB&cys'%(d*7.94))
cmd.select('gly14', 'n. CA&r. gly w. %s of n. SG&cys'%(d*8.17))
cmd.select('gly15', 'n. CA&r. gly w. %s of n. O&cys'%(d*8.49))
cmd.select('gly16', 'n. CA&r. gly w. %s of n. C&cys'%(d*8.94))
cmd.select('gly17', 'n. CA&r. gly w. %s of n. CA&cys'%(d*8.71))
cmd.select('gly18', 'n. CA&r. gly w. %s of n. N&cys'%(d*8.26))
cmd.select('gly19', 'n. N&r. gly w. %s of n. CB&cys'%(d*6.61))
cmd.select('gly20', 'n. N&r. gly w. %s of n. SG&cys'%(d*6.98))
cmd.select('gly21', 'n. N&r. gly w. %s of n. O&cys'%(d*7.29))
cmd.select('gly22', 'n. N&r. gly w. %s of n. C&cys'%(d*7.64))
cmd.select('gly23', 'n. N&r. gly w. %s of n. CA&cys'%(d*7.45))
cmd.select('gly24', 'n. N&r. gly w. %s of n. N&cys'%(d*7.18))
cmd.select('gly25', 'n. O&r. gly w. %s of n. CB&asn'%(d*7.22))
cmd.select('gly26', 'n. O&r. gly w. %s of n. CG&asn'%(d*7.14))
cmd.select('gly27', 'n. O&r. gly w. %s of n. OD1&asn'%(d*8.12))
cmd.select('gly28', 'n. O&r. gly w. %s of n. ND2&asn'%(d*6.30))
cmd.select('gly29', 'n. C&r. gly w. %s of n. CB&asn'%(d*7.06))
cmd.select('gly30', 'n. C&r. gly w. %s of n. CG&asn'%(d*6.97))
cmd.select('gly31', 'n. C&r. gly w. %s of n. OD1&asn'%(d*7.83))
cmd.select('gly32', 'n. C&r. gly w. %s of n. ND2&asn'%(d*6.32))
cmd.select('gly33', 'n. CA&r. gly w. %s of n. CB&asn'%(d*5.82))
cmd.select('gly34', 'n. CA&r. gly w. %s of n. CG&asn'%(d*5.70))
cmd.select('gly35', 'n. CA&r. gly w. %s of n. OD1&asn'%(d*6.47))
cmd.select('gly36', 'n. CA&r. gly w. %s of n. ND2&asn'%(d*5.25))
cmd.select('gly37', 'n. N&r. gly w. %s of n. CB&asn'%(d*4.58))
cmd.select('gly38', 'n. N&r. gly w. %s of n. CG&asn'%(d*4.69))
cmd.select('gly39', 'n. N&r. gly w. %s of n. OD1&asn'%(d*5.67))
cmd.select('gly40', 'n. N&r. gly w. %s of n. ND2&asn'%(d*4.28))
cmd.select('gly',' br. gly1&br. gly2&br. gly3&br. gly4&br. gly5&br. gly6&br. gly7&br. gly8&br. gly9&br. gly10&br. gly11&br. gly12&br. gly13&br. gly14&br. gly15&br. gly16&br. gly17&br. gly18&br. gly19&br. gly20&br. gly21&br. gly22&br. gly23&br. gly24&br. gly25&br. gly26&br. gly27&br. gly28&br. gly29&br. gly30&br. gly31&br. gly32&br. gly33&br. gly34&br. gly35&br. gly36&br. gly37&br. gly38&br. gly39&br. gly40')
cmd.delete('gly1')
cmd.delete('gly2')
cmd.delete('gly3')
cmd.delete('gly4')
cmd.delete('gly5')
cmd.delete('gly6')
cmd.delete('gly7')
cmd.delete('gly8')
cmd.delete('gly9')
cmd.delete('gly10')
cmd.delete('gly11')
cmd.delete('gly12')
cmd.delete('gly13')
cmd.delete('gly14')
cmd.delete('gly15')
cmd.delete('gly16')
cmd.delete('gly17')
cmd.delete('gly18')
cmd.delete('gly19')
cmd.delete('gly20')
cmd.delete('gly21')
cmd.delete('gly22')
cmd.delete('gly23')
cmd.delete('gly24')
cmd.delete('gly25')
cmd.delete('gly26')
cmd.delete('gly27')
cmd.delete('gly28')
cmd.delete('gly29')
cmd.delete('gly30')
cmd.delete('gly31')
cmd.delete('gly32')
cmd.delete('gly33')
cmd.delete('gly34')
cmd.delete('gly35')
cmd.delete('gly36')
cmd.delete('gly37')
cmd.delete('gly38')
cmd.delete('gly39')
cmd.delete('gly40')
cmd.select('P_1ecg-C1A-N101A-G102A', 'cys|asn|gly')
cmd.delete('cys')
cmd.delete('asn')
cmd.delete('gly')
