'''
FUNC:S_1amr_2_6_1_1
PDB:1amr
EC:2.6.1.1
RESI:ile,trp,asp,lys
LOCI:a-73,140,222,258;
'''
IDSpec[(('trp','CE2'),('rasp','CG'))] = cmd.select('trp1', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+9.75,resSelectionSubs('asp','CG',subs)))
IDSpec[(('trp','CE2'),('rasp','OD1'))] = cmd.select('trp2', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+10.02,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('trp','CE2'),('rasp','OD2'))] = cmd.select('trp3', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+8.65,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('trp','CZ2'),('rasp','CG'))] = cmd.select('trp4', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+9.94,resSelectionSubs('asp','CG',subs)))
IDSpec[(('trp','CZ2'),('rasp','OD1'))] = cmd.select('trp5', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+10.03,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('trp','CZ2'),('rasp','OD2'))] = cmd.select('trp6', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+8.92,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('trp','NE1'),('rasp','CG'))] = cmd.select('trp7', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+10.68,resSelectionSubs('asp','CG',subs)))
IDSpec[(('trp','NE1'),('rasp','OD1'))] = cmd.select('trp8', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+10.99,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('trp','NE1'),('rasp','OD2'))] = cmd.select('trp9', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+9.58,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('trp','CE2'),('rlys','CD'))] = cmd.select('trp10', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+11.19,resSelectionSubs('lys','CD',subs)))
IDSpec[(('trp','CE2'),('rlys','CE'))] = cmd.select('trp11', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+9.74,resSelectionSubs('lys','CE',subs)))
IDSpec[(('trp','CE2'),('rlys','NZ'))] = cmd.select('trp12', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+9.66,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('trp','CZ2'),('rlys','CD'))] = cmd.select('trp13', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+11.02,resSelectionSubs('lys','CD',subs)))
IDSpec[(('trp','CZ2'),('rlys','CE'))] = cmd.select('trp14', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+9.63,resSelectionSubs('lys','CE',subs)))
IDSpec[(('trp','CZ2'),('rlys','NZ'))] = cmd.select('trp15', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+9.56,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('trp','NE1'),('rlys','CD'))] = cmd.select('trp16', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+11.28,resSelectionSubs('lys','CD',subs)))
IDSpec[(('trp','NE1'),('rlys','CE'))] = cmd.select('trp17', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+9.77,resSelectionSubs('lys','CE',subs)))
IDSpec[(('trp','NE1'),('rlys','NZ'))] = cmd.select('trp18', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+9.50,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('trp','CE2'),('rile','CD1'))] = cmd.select('trp19', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+28.46,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('trp','CE2'),('rile','CG1'))] = cmd.select('trp20', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+27.74,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('trp','CE2'),('rile','CG2'))] = cmd.select('trp21', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+25.61,resSelectionSubs('ile','CG2',subs)))
IDSpec[(('trp','CZ2'),('rile','CD1'))] = cmd.select('trp22', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+27.30,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('trp','CZ2'),('rile','CG1'))] = cmd.select('trp23', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+26.56,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('trp','CZ2'),('rile','CG2'))] = cmd.select('trp24', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+24.47,resSelectionSubs('ile','CG2',subs)))
IDSpec[(('trp','NE1'),('rile','CD1'))] = cmd.select('trp25', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+29.77,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('trp','NE1'),('rile','CG1'))] = cmd.select('trp26', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+29.03,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('trp','NE1'),('rile','CG2'))] = cmd.select('trp27', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+26.92,resSelectionSubs('ile','CG2',subs)))
IDSpec['trp'] = cmd.select('trp',' br. trp1&br. trp2&br. trp3&br. trp4&br. trp5&br. trp6&br. trp7&br. trp8&br. trp9&br. trp10&br. trp11&br. trp12&br. trp13&br. trp14&br. trp15&br. trp16&br. trp17&br. trp18&br. trp19&br. trp20&br. trp21&br. trp22&br. trp23&br. trp24&br. trp25&br. trp26&br. trp27')
IDSpec['r_trp'] = cmd.count_atoms(resSelectionSubs('trp', subs=subs, selection=True))
cmd.delete('trp1')
cmd.delete('trp2')
cmd.delete('trp3')
cmd.delete('trp4')
cmd.delete('trp5')
cmd.delete('trp6')
cmd.delete('trp7')
cmd.delete('trp8')
cmd.delete('trp9')
cmd.delete('trp10')
cmd.delete('trp11')
cmd.delete('trp12')
cmd.delete('trp13')
cmd.delete('trp14')
cmd.delete('trp15')
cmd.delete('trp16')
cmd.delete('trp17')
cmd.delete('trp18')
cmd.delete('trp19')
cmd.delete('trp20')
cmd.delete('trp21')
cmd.delete('trp22')
cmd.delete('trp23')
cmd.delete('trp24')
cmd.delete('trp25')
cmd.delete('trp26')
cmd.delete('trp27')
IDSpec[(('asp','CG'),('strp','CE2'))] = cmd.select('asp1', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+9.75,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('asp','CG'),('strp','CZ2'))] = cmd.select('asp2', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+9.94,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('asp','CG'),('strp','NE1'))] = cmd.select('asp3', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+10.68,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec[(('asp','OD1'),('strp','CE2'))] = cmd.select('asp4', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+10.02,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('asp','OD1'),('strp','CZ2'))] = cmd.select('asp5', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+10.03,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('asp','OD1'),('strp','NE1'))] = cmd.select('asp6', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+10.99,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec[(('asp','OD2'),('strp','CE2'))] = cmd.select('asp7', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+8.65,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('asp','OD2'),('strp','CZ2'))] = cmd.select('asp8', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+8.92,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('asp','OD2'),('strp','NE1'))] = cmd.select('asp9', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+9.58,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec[(('asp','CG'),('rlys','CD'))] = cmd.select('asp10', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+11.85,resSelectionSubs('lys','CD',subs)))
IDSpec[(('asp','CG'),('rlys','CE'))] = cmd.select('asp11', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+11.22,resSelectionSubs('lys','CE',subs)))
IDSpec[(('asp','CG'),('rlys','NZ'))] = cmd.select('asp12', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+12.33,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('asp','OD1'),('rlys','CD'))] = cmd.select('asp13', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+11.17,resSelectionSubs('lys','CD',subs)))
IDSpec[(('asp','OD1'),('rlys','CE'))] = cmd.select('asp14', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+10.66,resSelectionSubs('lys','CE',subs)))
IDSpec[(('asp','OD1'),('rlys','NZ'))] = cmd.select('asp15', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+11.86,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('asp','OD2'),('rlys','CD'))] = cmd.select('asp16', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.83,resSelectionSubs('lys','CD',subs)))
IDSpec[(('asp','OD2'),('rlys','CE'))] = cmd.select('asp17', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.01,resSelectionSubs('lys','CE',subs)))
IDSpec[(('asp','OD2'),('rlys','NZ'))] = cmd.select('asp18', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.99,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('asp','CG'),('rile','CD1'))] = cmd.select('asp19', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+25.81,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('asp','CG'),('rile','CG1'))] = cmd.select('asp20', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+25.20,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('asp','CG'),('rile','CG2'))] = cmd.select('asp21', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+22.79,resSelectionSubs('ile','CG2',subs)))
IDSpec[(('asp','OD1'),('rile','CD1'))] = cmd.select('asp22', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+25.01,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('asp','OD1'),('rile','CG1'))] = cmd.select('asp23', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+24.34,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('asp','OD1'),('rile','CG2'))] = cmd.select('asp24', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+21.96,resSelectionSubs('ile','CG2',subs)))
IDSpec[(('asp','OD2'),('rile','CD1'))] = cmd.select('asp25', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+26.26,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('asp','OD2'),('rile','CG1'))] = cmd.select('asp26', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+25.66,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('asp','OD2'),('rile','CG2'))] = cmd.select('asp27', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+23.26,resSelectionSubs('ile','CG2',subs)))
IDSpec['asp'] = cmd.select('asp',' br. asp1&br. asp2&br. asp3&br. asp4&br. asp5&br. asp6&br. asp7&br. asp8&br. asp9&br. asp10&br. asp11&br. asp12&br. asp13&br. asp14&br. asp15&br. asp16&br. asp17&br. asp18&br. asp19&br. asp20&br. asp21&br. asp22&br. asp23&br. asp24&br. asp25&br. asp26&br. asp27')
IDSpec['r_asp'] = cmd.count_atoms(resSelectionSubs('asp', subs=subs, selection=True))
cmd.delete('asp1')
cmd.delete('asp2')
cmd.delete('asp3')
cmd.delete('asp4')
cmd.delete('asp5')
cmd.delete('asp6')
cmd.delete('asp7')
cmd.delete('asp8')
cmd.delete('asp9')
cmd.delete('asp10')
cmd.delete('asp11')
cmd.delete('asp12')
cmd.delete('asp13')
cmd.delete('asp14')
cmd.delete('asp15')
cmd.delete('asp16')
cmd.delete('asp17')
cmd.delete('asp18')
cmd.delete('asp19')
cmd.delete('asp20')
cmd.delete('asp21')
cmd.delete('asp22')
cmd.delete('asp23')
cmd.delete('asp24')
cmd.delete('asp25')
cmd.delete('asp26')
cmd.delete('asp27')
IDSpec[(('lys','CD'),('strp','CE2'))] = cmd.select('lys1', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+11.19,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('lys','CD'),('strp','CZ2'))] = cmd.select('lys2', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+11.02,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('lys','CD'),('strp','NE1'))] = cmd.select('lys3', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+11.28,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec[(('lys','CE'),('strp','CE2'))] = cmd.select('lys4', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+9.74,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('lys','CE'),('strp','CZ2'))] = cmd.select('lys5', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+9.63,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('lys','CE'),('strp','NE1'))] = cmd.select('lys6', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+9.77,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec[(('lys','NZ'),('strp','CE2'))] = cmd.select('lys7', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+9.66,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('lys','NZ'),('strp','CZ2'))] = cmd.select('lys8', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+9.56,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('lys','NZ'),('strp','NE1'))] = cmd.select('lys9', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+9.50,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec[(('lys','CD'),('sasp','CG'))] = cmd.select('lys10', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+11.85,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('lys','CD'),('sasp','OD1'))] = cmd.select('lys11', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+11.17,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('lys','CD'),('sasp','OD2'))] = cmd.select('lys12', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+11.83,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('lys','CE'),('sasp','CG'))] = cmd.select('lys13', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+11.22,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('lys','CE'),('sasp','OD1'))] = cmd.select('lys14', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+10.66,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('lys','CE'),('sasp','OD2'))] = cmd.select('lys15', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+11.01,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('lys','NZ'),('sasp','CG'))] = cmd.select('lys16', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+12.33,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('lys','NZ'),('sasp','OD1'))] = cmd.select('lys17', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+11.86,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('lys','NZ'),('sasp','OD2'))] = cmd.select('lys18', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+11.99,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('lys','CD'),('rile','CD1'))] = cmd.select('lys19', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+28.66,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('lys','CD'),('rile','CG1'))] = cmd.select('lys20', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+27.57,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('lys','CD'),('rile','CG2'))] = cmd.select('lys21', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+25.65,resSelectionSubs('ile','CG2',subs)))
IDSpec[(('lys','CE'),('rile','CD1'))] = cmd.select('lys22', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+28.82,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('lys','CE'),('rile','CG1'))] = cmd.select('lys23', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+27.78,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('lys','CE'),('rile','CG2'))] = cmd.select('lys24', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+25.81,resSelectionSubs('ile','CG2',subs)))
IDSpec[(('lys','NZ'),('rile','CD1'))] = cmd.select('lys25', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+29.60,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('lys','NZ'),('rile','CG1'))] = cmd.select('lys26', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+28.55,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('lys','NZ'),('rile','CG2'))] = cmd.select('lys27', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+26.64,resSelectionSubs('ile','CG2',subs)))
IDSpec['lys'] = cmd.select('lys',' br. lys1&br. lys2&br. lys3&br. lys4&br. lys5&br. lys6&br. lys7&br. lys8&br. lys9&br. lys10&br. lys11&br. lys12&br. lys13&br. lys14&br. lys15&br. lys16&br. lys17&br. lys18&br. lys19&br. lys20&br. lys21&br. lys22&br. lys23&br. lys24&br. lys25&br. lys26&br. lys27')
IDSpec['r_lys'] = cmd.count_atoms(resSelectionSubs('lys', subs=subs, selection=True))
cmd.delete('lys1')
cmd.delete('lys2')
cmd.delete('lys3')
cmd.delete('lys4')
cmd.delete('lys5')
cmd.delete('lys6')
cmd.delete('lys7')
cmd.delete('lys8')
cmd.delete('lys9')
cmd.delete('lys10')
cmd.delete('lys11')
cmd.delete('lys12')
cmd.delete('lys13')
cmd.delete('lys14')
cmd.delete('lys15')
cmd.delete('lys16')
cmd.delete('lys17')
cmd.delete('lys18')
cmd.delete('lys19')
cmd.delete('lys20')
cmd.delete('lys21')
cmd.delete('lys22')
cmd.delete('lys23')
cmd.delete('lys24')
cmd.delete('lys25')
cmd.delete('lys26')
cmd.delete('lys27')
IDSpec[(('ile','CD1'),('strp','CE2'))] = cmd.select('ile1', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+28.46,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('ile','CD1'),('strp','CZ2'))] = cmd.select('ile2', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+27.30,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('ile','CD1'),('strp','NE1'))] = cmd.select('ile3', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+29.77,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec[(('ile','CG1'),('strp','CE2'))] = cmd.select('ile4', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+27.74,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('ile','CG1'),('strp','CZ2'))] = cmd.select('ile5', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+26.56,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('ile','CG1'),('strp','NE1'))] = cmd.select('ile6', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+29.03,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec[(('ile','CG2'),('strp','CE2'))] = cmd.select('ile7', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+25.61,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('ile','CG2'),('strp','CZ2'))] = cmd.select('ile8', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+24.47,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('ile','CG2'),('strp','NE1'))] = cmd.select('ile9', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+26.92,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec[(('ile','CD1'),('sasp','CG'))] = cmd.select('ile10', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+25.81,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('ile','CD1'),('sasp','OD1'))] = cmd.select('ile11', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+25.01,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('ile','CD1'),('sasp','OD2'))] = cmd.select('ile12', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+26.26,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('ile','CG1'),('sasp','CG'))] = cmd.select('ile13', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+25.20,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('ile','CG1'),('sasp','OD1'))] = cmd.select('ile14', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+24.34,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('ile','CG1'),('sasp','OD2'))] = cmd.select('ile15', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+25.66,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('ile','CG2'),('sasp','CG'))] = cmd.select('ile16', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+22.79,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('ile','CG2'),('sasp','OD1'))] = cmd.select('ile17', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+21.96,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('ile','CG2'),('sasp','OD2'))] = cmd.select('ile18', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+23.26,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('ile','CD1'),('slys','CD'))] = cmd.select('ile19', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+28.66,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('ile','CD1'),('slys','CE'))] = cmd.select('ile20', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+28.82,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('ile','CD1'),('slys','NZ'))] = cmd.select('ile21', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+29.60,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('ile','CG1'),('slys','CD'))] = cmd.select('ile22', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+27.57,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('ile','CG1'),('slys','CE'))] = cmd.select('ile23', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+27.78,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('ile','CG1'),('slys','NZ'))] = cmd.select('ile24', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+28.55,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('ile','CG2'),('slys','CD'))] = cmd.select('ile25', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+25.65,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('ile','CG2'),('slys','CE'))] = cmd.select('ile26', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+25.81,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('ile','CG2'),('slys','NZ'))] = cmd.select('ile27', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+26.64,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec['ile'] = cmd.select('ile',' br. ile1&br. ile2&br. ile3&br. ile4&br. ile5&br. ile6&br. ile7&br. ile8&br. ile9&br. ile10&br. ile11&br. ile12&br. ile13&br. ile14&br. ile15&br. ile16&br. ile17&br. ile18&br. ile19&br. ile20&br. ile21&br. ile22&br. ile23&br. ile24&br. ile25&br. ile26&br. ile27')
IDSpec['r_ile'] = cmd.count_atoms(resSelectionSubs('ile', subs=subs, selection=True))
cmd.delete('ile1')
cmd.delete('ile2')
cmd.delete('ile3')
cmd.delete('ile4')
cmd.delete('ile5')
cmd.delete('ile6')
cmd.delete('ile7')
cmd.delete('ile8')
cmd.delete('ile9')
cmd.delete('ile10')
cmd.delete('ile11')
cmd.delete('ile12')
cmd.delete('ile13')
cmd.delete('ile14')
cmd.delete('ile15')
cmd.delete('ile16')
cmd.delete('ile17')
cmd.delete('ile18')
cmd.delete('ile19')
cmd.delete('ile20')
cmd.delete('ile21')
cmd.delete('ile22')
cmd.delete('ile23')
cmd.delete('ile24')
cmd.delete('ile25')
cmd.delete('ile26')
cmd.delete('ile27')
IDSpec['S_1amr_2_6_1_1'] = cmd.select('S_1amr_2_6_1_1', 'trp|asp|lys|ile')
cmd.delete('trp')
cmd.delete('asp')
cmd.delete('lys')
cmd.delete('ile')
