'''
FUNC:S_1n23_5_5_1_8
PDB:1n23
EC:5.5.1.8
RESI:trp,phe
LOCI:a-323,578;
'''
IDSpec[(('phe','CD1'),('rtrp','CE2'))] = cmd.select('phe1', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+7.96,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('phe','CD1'),('rtrp','CZ2'))] = cmd.select('phe2', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+7.95,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('phe','CD1'),('rtrp','NE1'))] = cmd.select('phe3', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+9.15,resSelectionSubs('trp','NE1',subs)))
IDSpec[(('phe','CE1'),('rtrp','CE2'))] = cmd.select('phe4', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+8.24,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('phe','CE1'),('rtrp','CZ2'))] = cmd.select('phe5', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+8.41,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('phe','CE1'),('rtrp','NE1'))] = cmd.select('phe6', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+9.29,resSelectionSubs('trp','NE1',subs)))
IDSpec[(('phe','CZ'),('rtrp','CE2'))] = cmd.select('phe7', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+9.23,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('phe','CZ'),('rtrp','CZ2'))] = cmd.select('phe8', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+9.31,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('phe','CZ'),('rtrp','NE1'))] = cmd.select('phe9', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+10.29,resSelectionSubs('trp','NE1',subs)))
IDSpec['phe'] = cmd.select('phe',' br. phe1&br. phe2&br. phe3&br. phe4&br. phe5&br. phe6&br. phe7&br. phe8&br. phe9')
IDSpec['r_phe'] = cmd.count_atoms(resSelectionSubs('phe', subs=subs, selection=True))
cmd.delete('phe1')
cmd.delete('phe2')
cmd.delete('phe3')
cmd.delete('phe4')
cmd.delete('phe5')
cmd.delete('phe6')
cmd.delete('phe7')
cmd.delete('phe8')
cmd.delete('phe9')
IDSpec[(('trp','CE2'),('sphe','CD1'))] = cmd.select('trp1', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+7.96,resSelectionSubs('phe','CD1',subs,selection=True)))
IDSpec[(('trp','CE2'),('sphe','CE1'))] = cmd.select('trp2', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+8.24,resSelectionSubs('phe','CE1',subs,selection=True)))
IDSpec[(('trp','CE2'),('sphe','CZ'))] = cmd.select('trp3', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+9.23,resSelectionSubs('phe','CZ',subs,selection=True)))
IDSpec[(('trp','CZ2'),('sphe','CD1'))] = cmd.select('trp4', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+7.95,resSelectionSubs('phe','CD1',subs,selection=True)))
IDSpec[(('trp','CZ2'),('sphe','CE1'))] = cmd.select('trp5', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+8.41,resSelectionSubs('phe','CE1',subs,selection=True)))
IDSpec[(('trp','CZ2'),('sphe','CZ'))] = cmd.select('trp6', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+9.31,resSelectionSubs('phe','CZ',subs,selection=True)))
IDSpec[(('trp','NE1'),('sphe','CD1'))] = cmd.select('trp7', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+9.15,resSelectionSubs('phe','CD1',subs,selection=True)))
IDSpec[(('trp','NE1'),('sphe','CE1'))] = cmd.select('trp8', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+9.29,resSelectionSubs('phe','CE1',subs,selection=True)))
IDSpec[(('trp','NE1'),('sphe','CZ'))] = cmd.select('trp9', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+10.29,resSelectionSubs('phe','CZ',subs,selection=True)))
IDSpec['trp'] = cmd.select('trp',' br. trp1&br. trp2&br. trp3&br. trp4&br. trp5&br. trp6&br. trp7&br. trp8&br. trp9')
IDSpec['r_trp'] = cmd.count_atoms(resSelectionSubs('trp', subs=subs, selection=True))
cmd.delete('trp1')
cmd.delete('trp2')
cmd.delete('trp3')
cmd.delete('trp4')
cmd.delete('trp5')
cmd.delete('trp6')
cmd.delete('trp7')
cmd.delete('trp8')
cmd.delete('trp9')
IDSpec['S_1n23_5_5_1_8'] = cmd.select('S_1n23_5_5_1_8', 'phe|trp')
cmd.delete('phe')
cmd.delete('trp')
