'''
FUNC:S_1p33_1_1_1_253
PDB:1p33
EC:1.1.1.253
RESI:arg,thr,asp,tyr,tyr,lys
LOCI:a-17,172,181,191,194,198;
'''
IDSpec[(('thr','CA'),('rlys','CD'))] = cmd.select('thr1', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+30.31,resSelectionSubs('lys','CD',subs)))
IDSpec[(('thr','CA'),('rlys','CE'))] = cmd.select('thr2', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+30.52,resSelectionSubs('lys','CE',subs)))
IDSpec[(('thr','CA'),('rlys','NZ'))] = cmd.select('thr3', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+29.27,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('thr','CB'),('rlys','CD'))] = cmd.select('thr4', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+31.48,resSelectionSubs('lys','CD',subs)))
IDSpec[(('thr','CB'),('rlys','CE'))] = cmd.select('thr5', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+31.67,resSelectionSubs('lys','CE',subs)))
IDSpec[(('thr','CB'),('rlys','NZ'))] = cmd.select('thr6', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+30.42,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('thr','OG1'),('rlys','CD'))] = cmd.select('thr7', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+31.04,resSelectionSubs('lys','CD',subs)))
IDSpec[(('thr','OG1'),('rlys','CE'))] = cmd.select('thr8', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+31.20,resSelectionSubs('lys','CE',subs)))
IDSpec[(('thr','OG1'),('rlys','NZ'))] = cmd.select('thr9', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+29.93,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('thr','CA'),('rtyr','CE1'))] = cmd.select('thr10', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+34.10,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('thr','CA'),('rtyr','CZ'))] = cmd.select('thr11', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+34.15,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('thr','CA'),('rtyr','OH'))] = cmd.select('thr12', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+33.26,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('thr','CB'),('rtyr','CE1'))] = cmd.select('thr13', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+35.24,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('thr','CB'),('rtyr','CZ'))] = cmd.select('thr14', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+35.26,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('thr','CB'),('rtyr','OH'))] = cmd.select('thr15', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+34.34,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('thr','OG1'),('rtyr','CE1'))] = cmd.select('thr16', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+34.75,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('thr','OG1'),('rtyr','CZ'))] = cmd.select('thr17', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+34.74,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('thr','OG1'),('rtyr','OH'))] = cmd.select('thr18', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+33.78,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('thr','CA'),('rtyr','CE1'))] = cmd.select('thr19', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+42.45,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('thr','CA'),('rtyr','CZ'))] = cmd.select('thr20', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+41.83,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('thr','CA'),('rtyr','OH'))] = cmd.select('thr21', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+42.43,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('thr','CB'),('rtyr','CE1'))] = cmd.select('thr22', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+43.54,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('thr','CB'),('rtyr','CZ'))] = cmd.select('thr23', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+42.92,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('thr','CB'),('rtyr','OH'))] = cmd.select('thr24', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+43.50,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('thr','OG1'),('rtyr','CE1'))] = cmd.select('thr25', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+42.97,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('thr','OG1'),('rtyr','CZ'))] = cmd.select('thr26', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+42.34,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('thr','OG1'),('rtyr','OH'))] = cmd.select('thr27', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+42.89,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('thr','CA'),('rasp','CG'))] = cmd.select('thr28', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+33.17,resSelectionSubs('asp','CG',subs)))
IDSpec[(('thr','CA'),('rasp','OD1'))] = cmd.select('thr29', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+33.60,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('thr','CA'),('rasp','OD2'))] = cmd.select('thr30', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+33.76,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('thr','CB'),('rasp','CG'))] = cmd.select('thr31', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+34.17,resSelectionSubs('asp','CG',subs)))
IDSpec[(('thr','CB'),('rasp','OD1'))] = cmd.select('thr32', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+34.56,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('thr','CB'),('rasp','OD2'))] = cmd.select('thr33', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+34.77,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('thr','OG1'),('rasp','CG'))] = cmd.select('thr34', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+33.54,resSelectionSubs('asp','CG',subs)))
IDSpec[(('thr','OG1'),('rasp','OD1'))] = cmd.select('thr35', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+33.91,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('thr','OG1'),('rasp','OD2'))] = cmd.select('thr36', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+34.15,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('thr','CA'),('rarg','CZ'))] = cmd.select('thr37', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+34.80,resSelectionSubs('arg','CZ',subs)))
IDSpec[(('thr','CA'),('rarg','NE'))] = cmd.select('thr38', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+34.13,resSelectionSubs('arg','NE',subs)))
IDSpec[(('thr','CA'),('rarg','NH1'))] = cmd.select('thr39', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+35.43,resSelectionSubs('arg','NH1',subs)))
IDSpec[(('thr','CB'),('rarg','CZ'))] = cmd.select('thr40', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+35.63,resSelectionSubs('arg','CZ',subs)))
IDSpec[(('thr','CB'),('rarg','NE'))] = cmd.select('thr41', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+34.98,resSelectionSubs('arg','NE',subs)))
IDSpec[(('thr','CB'),('rarg','NH1'))] = cmd.select('thr42', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+36.20,resSelectionSubs('arg','NH1',subs)))
IDSpec[(('thr','OG1'),('rarg','CZ'))] = cmd.select('thr43', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+34.79,resSelectionSubs('arg','CZ',subs)))
IDSpec[(('thr','OG1'),('rarg','NE'))] = cmd.select('thr44', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+34.18,resSelectionSubs('arg','NE',subs)))
IDSpec[(('thr','OG1'),('rarg','NH1'))] = cmd.select('thr45', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+35.33,resSelectionSubs('arg','NH1',subs)))
IDSpec['thr'] = cmd.select('thr',' br. thr1&br. thr2&br. thr3&br. thr4&br. thr5&br. thr6&br. thr7&br. thr8&br. thr9&br. thr10&br. thr11&br. thr12&br. thr13&br. thr14&br. thr15&br. thr16&br. thr17&br. thr18&br. thr19&br. thr20&br. thr21&br. thr22&br. thr23&br. thr24&br. thr25&br. thr26&br. thr27&br. thr28&br. thr29&br. thr30&br. thr31&br. thr32&br. thr33&br. thr34&br. thr35&br. thr36&br. thr37&br. thr38&br. thr39&br. thr40&br. thr41&br. thr42&br. thr43&br. thr44&br. thr45')
IDSpec['r_thr'] = cmd.count_atoms(resSelectionSubs('thr', subs=subs, selection=True))
cmd.delete('thr1')
cmd.delete('thr2')
cmd.delete('thr3')
cmd.delete('thr4')
cmd.delete('thr5')
cmd.delete('thr6')
cmd.delete('thr7')
cmd.delete('thr8')
cmd.delete('thr9')
cmd.delete('thr10')
cmd.delete('thr11')
cmd.delete('thr12')
cmd.delete('thr13')
cmd.delete('thr14')
cmd.delete('thr15')
cmd.delete('thr16')
cmd.delete('thr17')
cmd.delete('thr18')
cmd.delete('thr19')
cmd.delete('thr20')
cmd.delete('thr21')
cmd.delete('thr22')
cmd.delete('thr23')
cmd.delete('thr24')
cmd.delete('thr25')
cmd.delete('thr26')
cmd.delete('thr27')
cmd.delete('thr28')
cmd.delete('thr29')
cmd.delete('thr30')
cmd.delete('thr31')
cmd.delete('thr32')
cmd.delete('thr33')
cmd.delete('thr34')
cmd.delete('thr35')
cmd.delete('thr36')
cmd.delete('thr37')
cmd.delete('thr38')
cmd.delete('thr39')
cmd.delete('thr40')
cmd.delete('thr41')
cmd.delete('thr42')
cmd.delete('thr43')
cmd.delete('thr44')
cmd.delete('thr45')
IDSpec[(('lys','CD'),('sthr','CA'))] = cmd.select('lys1', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+30.31,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('lys','CD'),('sthr','CB'))] = cmd.select('lys2', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+31.48,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('lys','CD'),('sthr','OG1'))] = cmd.select('lys3', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+31.04,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('lys','CE'),('sthr','CA'))] = cmd.select('lys4', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+30.52,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('lys','CE'),('sthr','CB'))] = cmd.select('lys5', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+31.67,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('lys','CE'),('sthr','OG1'))] = cmd.select('lys6', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+31.20,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('lys','NZ'),('sthr','CA'))] = cmd.select('lys7', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+29.27,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('lys','NZ'),('sthr','CB'))] = cmd.select('lys8', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+30.42,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('lys','NZ'),('sthr','OG1'))] = cmd.select('lys9', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+29.93,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('lys','CD'),('rtyr','CE1'))] = cmd.select('lys10', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+6.49,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('lys','CD'),('rtyr','CZ'))] = cmd.select('lys11', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+6.36,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('lys','CD'),('rtyr','OH'))] = cmd.select('lys12', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+6.10,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('lys','CE'),('rtyr','CE1'))] = cmd.select('lys13', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+5.68,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('lys','CE'),('rtyr','CZ'))] = cmd.select('lys14', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+5.82,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('lys','CE'),('rtyr','OH'))] = cmd.select('lys15', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+5.50,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('lys','NZ'),('rtyr','CE1'))] = cmd.select('lys16', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+6.83,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('lys','NZ'),('rtyr','CZ'))] = cmd.select('lys17', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+7.05,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('lys','NZ'),('rtyr','OH'))] = cmd.select('lys18', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+6.50,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('lys','CD'),('rtyr','CE1'))] = cmd.select('lys19', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+14.59,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('lys','CD'),('rtyr','CZ'))] = cmd.select('lys20', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+14.23,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('lys','CD'),('rtyr','OH'))] = cmd.select('lys21', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+15.18,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('lys','CE'),('rtyr','CE1'))] = cmd.select('lys22', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+14.11,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('lys','CE'),('rtyr','CZ'))] = cmd.select('lys23', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+13.60,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('lys','CE'),('rtyr','OH'))] = cmd.select('lys24', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+14.45,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('lys','NZ'),('rtyr','CE1'))] = cmd.select('lys25', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+15.28,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('lys','NZ'),('rtyr','CZ'))] = cmd.select('lys26', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+14.68,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('lys','NZ'),('rtyr','OH'))] = cmd.select('lys27', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+15.43,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('lys','CD'),('rasp','CG'))] = cmd.select('lys28', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+7.57,resSelectionSubs('asp','CG',subs)))
IDSpec[(('lys','CD'),('rasp','OD1'))] = cmd.select('lys29', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+8.72,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('lys','CD'),('rasp','OD2'))] = cmd.select('lys30', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+7.53,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('lys','CE'),('rasp','CG'))] = cmd.select('lys31', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+7.80,resSelectionSubs('asp','CG',subs)))
IDSpec[(('lys','CE'),('rasp','OD1'))] = cmd.select('lys32', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+9.02,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('lys','CE'),('rasp','OD2'))] = cmd.select('lys33', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+7.49,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('lys','NZ'),('rasp','CG'))] = cmd.select('lys34', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+8.61,resSelectionSubs('asp','CG',subs)))
IDSpec[(('lys','NZ'),('rasp','OD1'))] = cmd.select('lys35', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+9.77,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('lys','NZ'),('rasp','OD2'))] = cmd.select('lys36', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+8.37,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('lys','CD'),('rarg','CZ'))] = cmd.select('lys37', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+15.83,resSelectionSubs('arg','CZ',subs)))
IDSpec[(('lys','CD'),('rarg','NE'))] = cmd.select('lys38', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+15.57,resSelectionSubs('arg','NE',subs)))
IDSpec[(('lys','CD'),('rarg','NH1'))] = cmd.select('lys39', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+17.08,resSelectionSubs('arg','NH1',subs)))
IDSpec[(('lys','CE'),('rarg','CZ'))] = cmd.select('lys40', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+14.46,resSelectionSubs('arg','CZ',subs)))
IDSpec[(('lys','CE'),('rarg','NE'))] = cmd.select('lys41', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+14.15,resSelectionSubs('arg','NE',subs)))
IDSpec[(('lys','CE'),('rarg','NH1'))] = cmd.select('lys42', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+15.73,resSelectionSubs('arg','NH1',subs)))
IDSpec[(('lys','NZ'),('rarg','CZ'))] = cmd.select('lys43', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+14.00,resSelectionSubs('arg','CZ',subs)))
IDSpec[(('lys','NZ'),('rarg','NE'))] = cmd.select('lys44', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+13.61,resSelectionSubs('arg','NE',subs)))
IDSpec[(('lys','NZ'),('rarg','NH1'))] = cmd.select('lys45', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+15.27,resSelectionSubs('arg','NH1',subs)))
IDSpec['lys'] = cmd.select('lys',' br. lys1&br. lys2&br. lys3&br. lys4&br. lys5&br. lys6&br. lys7&br. lys8&br. lys9&br. lys10&br. lys11&br. lys12&br. lys13&br. lys14&br. lys15&br. lys16&br. lys17&br. lys18&br. lys19&br. lys20&br. lys21&br. lys22&br. lys23&br. lys24&br. lys25&br. lys26&br. lys27&br. lys28&br. lys29&br. lys30&br. lys31&br. lys32&br. lys33&br. lys34&br. lys35&br. lys36&br. lys37&br. lys38&br. lys39&br. lys40&br. lys41&br. lys42&br. lys43&br. lys44&br. lys45')
IDSpec['r_lys'] = cmd.count_atoms(resSelectionSubs('lys', subs=subs, selection=True))
cmd.delete('lys1')
cmd.delete('lys2')
cmd.delete('lys3')
cmd.delete('lys4')
cmd.delete('lys5')
cmd.delete('lys6')
cmd.delete('lys7')
cmd.delete('lys8')
cmd.delete('lys9')
cmd.delete('lys10')
cmd.delete('lys11')
cmd.delete('lys12')
cmd.delete('lys13')
cmd.delete('lys14')
cmd.delete('lys15')
cmd.delete('lys16')
cmd.delete('lys17')
cmd.delete('lys18')
cmd.delete('lys19')
cmd.delete('lys20')
cmd.delete('lys21')
cmd.delete('lys22')
cmd.delete('lys23')
cmd.delete('lys24')
cmd.delete('lys25')
cmd.delete('lys26')
cmd.delete('lys27')
cmd.delete('lys28')
cmd.delete('lys29')
cmd.delete('lys30')
cmd.delete('lys31')
cmd.delete('lys32')
cmd.delete('lys33')
cmd.delete('lys34')
cmd.delete('lys35')
cmd.delete('lys36')
cmd.delete('lys37')
cmd.delete('lys38')
cmd.delete('lys39')
cmd.delete('lys40')
cmd.delete('lys41')
cmd.delete('lys42')
cmd.delete('lys43')
cmd.delete('lys44')
cmd.delete('lys45')
IDSpec[(('tyr','CE1'),('sthr','CA'))] = cmd.select('tyr1', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+34.10,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('tyr','CE1'),('sthr','CB'))] = cmd.select('tyr2', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+35.24,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('tyr','CE1'),('sthr','OG1'))] = cmd.select('tyr3', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+34.75,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sthr','CA'))] = cmd.select('tyr4', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+34.15,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sthr','CB'))] = cmd.select('tyr5', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+35.26,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sthr','OG1'))] = cmd.select('tyr6', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+34.74,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('tyr','OH'),('sthr','CA'))] = cmd.select('tyr7', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+33.26,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('tyr','OH'),('sthr','CB'))] = cmd.select('tyr8', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+34.34,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('tyr','OH'),('sthr','OG1'))] = cmd.select('tyr9', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+33.78,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('tyr','CE1'),('slys','CD'))] = cmd.select('tyr10', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+6.49,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('tyr','CE1'),('slys','CE'))] = cmd.select('tyr11', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+5.68,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('tyr','CE1'),('slys','NZ'))] = cmd.select('tyr12', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+6.83,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('tyr','CZ'),('slys','CD'))] = cmd.select('tyr13', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+6.36,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('tyr','CZ'),('slys','CE'))] = cmd.select('tyr14', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+5.82,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('tyr','CZ'),('slys','NZ'))] = cmd.select('tyr15', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+7.05,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('tyr','OH'),('slys','CD'))] = cmd.select('tyr16', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+6.10,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('tyr','OH'),('slys','CE'))] = cmd.select('tyr17', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+5.50,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('tyr','OH'),('slys','NZ'))] = cmd.select('tyr18', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+6.50,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('tyr','CE1'),('rtyr','CE1'))] = cmd.select('tyr19', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10.53,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('tyr','CE1'),('rtyr','CZ'))] = cmd.select('tyr20', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+9.97,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('tyr','CE1'),('rtyr','OH'))] = cmd.select('tyr21', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10.85,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('tyr','CZ'),('rtyr','CE1'))] = cmd.select('tyr22', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+10.38,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('tyr','CZ'),('rtyr','CZ'))] = cmd.select('tyr23', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+9.96,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('tyr','CZ'),('rtyr','OH'))] = cmd.select('tyr24', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+10.87,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('tyr','OH'),('rtyr','CE1'))] = cmd.select('tyr25', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+11.25,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('tyr','OH'),('rtyr','CZ'))] = cmd.select('tyr26', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+10.81,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('tyr','OH'),('rtyr','OH'))] = cmd.select('tyr27', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+11.61,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('tyr','CE1'),('rasp','CG'))] = cmd.select('tyr28', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+7.84,resSelectionSubs('asp','CG',subs)))
IDSpec[(('tyr','CE1'),('rasp','OD1'))] = cmd.select('tyr29', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+9.00,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('tyr','CE1'),('rasp','OD2'))] = cmd.select('tyr30', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+6.90,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('tyr','CZ'),('rasp','CG'))] = cmd.select('tyr31', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+6.52,resSelectionSubs('asp','CG',subs)))
IDSpec[(('tyr','CZ'),('rasp','OD1'))] = cmd.select('tyr32', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+7.64,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('tyr','CZ'),('rasp','OD2'))] = cmd.select('tyr33', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+5.56,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('tyr','OH'),('rasp','CG'))] = cmd.select('tyr34', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+5.64,resSelectionSubs('asp','CG',subs)))
IDSpec[(('tyr','OH'),('rasp','OD1'))] = cmd.select('tyr35', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+6.80,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('tyr','OH'),('rasp','OD2'))] = cmd.select('tyr36', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+4.71,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('tyr','CE1'),('rarg','CZ'))] = cmd.select('tyr37', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+13.62,resSelectionSubs('arg','CZ',subs)))
IDSpec[(('tyr','CE1'),('rarg','NE'))] = cmd.select('tyr38', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+13.48,resSelectionSubs('arg','NE',subs)))
IDSpec[(('tyr','CE1'),('rarg','NH1'))] = cmd.select('tyr39', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+14.86,resSelectionSubs('arg','NH1',subs)))
IDSpec[(('tyr','CZ'),('rarg','CZ'))] = cmd.select('tyr40', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+13.82,resSelectionSubs('arg','CZ',subs)))
IDSpec[(('tyr','CZ'),('rarg','NE'))] = cmd.select('tyr41', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+13.81,resSelectionSubs('arg','NE',subs)))
IDSpec[(('tyr','CZ'),('rarg','NH1'))] = cmd.select('tyr42', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+15.02,resSelectionSubs('arg','NH1',subs)))
IDSpec[(('tyr','OH'),('rarg','CZ'))] = cmd.select('tyr43', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+13.19,resSelectionSubs('arg','CZ',subs)))
IDSpec[(('tyr','OH'),('rarg','NE'))] = cmd.select('tyr44', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+13.23,resSelectionSubs('arg','NE',subs)))
IDSpec[(('tyr','OH'),('rarg','NH1'))] = cmd.select('tyr45', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+14.38,resSelectionSubs('arg','NH1',subs)))
IDSpec['tyr'] = cmd.select('tyr',' br. tyr1&br. tyr2&br. tyr3&br. tyr4&br. tyr5&br. tyr6&br. tyr7&br. tyr8&br. tyr9&br. tyr10&br. tyr11&br. tyr12&br. tyr13&br. tyr14&br. tyr15&br. tyr16&br. tyr17&br. tyr18&br. tyr19&br. tyr20&br. tyr21&br. tyr22&br. tyr23&br. tyr24&br. tyr25&br. tyr26&br. tyr27&br. tyr28&br. tyr29&br. tyr30&br. tyr31&br. tyr32&br. tyr33&br. tyr34&br. tyr35&br. tyr36&br. tyr37&br. tyr38&br. tyr39&br. tyr40&br. tyr41&br. tyr42&br. tyr43&br. tyr44&br. tyr45')
IDSpec['r_tyr'] = cmd.count_atoms(resSelectionSubs('tyr', subs=subs, selection=True))
cmd.delete('tyr1')
cmd.delete('tyr2')
cmd.delete('tyr3')
cmd.delete('tyr4')
cmd.delete('tyr5')
cmd.delete('tyr6')
cmd.delete('tyr7')
cmd.delete('tyr8')
cmd.delete('tyr9')
cmd.delete('tyr10')
cmd.delete('tyr11')
cmd.delete('tyr12')
cmd.delete('tyr13')
cmd.delete('tyr14')
cmd.delete('tyr15')
cmd.delete('tyr16')
cmd.delete('tyr17')
cmd.delete('tyr18')
cmd.delete('tyr19')
cmd.delete('tyr20')
cmd.delete('tyr21')
cmd.delete('tyr22')
cmd.delete('tyr23')
cmd.delete('tyr24')
cmd.delete('tyr25')
cmd.delete('tyr26')
cmd.delete('tyr27')
cmd.delete('tyr28')
cmd.delete('tyr29')
cmd.delete('tyr30')
cmd.delete('tyr31')
cmd.delete('tyr32')
cmd.delete('tyr33')
cmd.delete('tyr34')
cmd.delete('tyr35')
cmd.delete('tyr36')
cmd.delete('tyr37')
cmd.delete('tyr38')
cmd.delete('tyr39')
cmd.delete('tyr40')
cmd.delete('tyr41')
cmd.delete('tyr42')
cmd.delete('tyr43')
cmd.delete('tyr44')
cmd.delete('tyr45')
IDSpec[(('tyr_i','CE1'),('sthr','CA'))] = cmd.select('tyr_i1', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+42.45,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('sthr','CB'))] = cmd.select('tyr_i2', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+43.54,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('sthr','OG1'))] = cmd.select('tyr_i3', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+42.97,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('sthr','CA'))] = cmd.select('tyr_i4', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+41.83,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('sthr','CB'))] = cmd.select('tyr_i5', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+42.92,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('sthr','OG1'))] = cmd.select('tyr_i6', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+42.34,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('sthr','CA'))] = cmd.select('tyr_i7', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+42.43,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('sthr','CB'))] = cmd.select('tyr_i8', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+43.50,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('sthr','OG1'))] = cmd.select('tyr_i9', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+42.89,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('slys','CD'))] = cmd.select('tyr_i10', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+14.59,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('slys','CE'))] = cmd.select('tyr_i11', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+14.11,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('slys','NZ'))] = cmd.select('tyr_i12', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+15.28,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('slys','CD'))] = cmd.select('tyr_i13', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+14.23,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('slys','CE'))] = cmd.select('tyr_i14', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+13.60,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('slys','NZ'))] = cmd.select('tyr_i15', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+14.68,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('slys','CD'))] = cmd.select('tyr_i16', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+15.18,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('slys','CE'))] = cmd.select('tyr_i17', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+14.45,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('slys','NZ'))] = cmd.select('tyr_i18', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+15.43,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('styr','CE1'))] = cmd.select('tyr_i19', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10.53,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('styr','CZ'))] = cmd.select('tyr_i20', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10.38,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('styr','OH'))] = cmd.select('tyr_i21', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+11.25,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('styr','CE1'))] = cmd.select('tyr_i22', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+9.97,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('styr','CZ'))] = cmd.select('tyr_i23', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+9.96,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('styr','OH'))] = cmd.select('tyr_i24', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+10.81,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('styr','CE1'))] = cmd.select('tyr_i25', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+10.85,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('styr','CZ'))] = cmd.select('tyr_i26', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+10.87,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('styr','OH'))] = cmd.select('tyr_i27', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+11.61,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('rasp','CG'))] = cmd.select('tyr_i28', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+12.63,resSelectionSubs('asp','CG',subs)))
IDSpec[(('tyr_i','CE1'),('rasp','OD1'))] = cmd.select('tyr_i29', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+12.97,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('tyr_i','CE1'),('rasp','OD2'))] = cmd.select('tyr_i30', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+11.59,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('tyr_i','CZ'),('rasp','CG'))] = cmd.select('tyr_i31', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+12.56,resSelectionSubs('asp','CG',subs)))
IDSpec[(('tyr_i','CZ'),('rasp','OD1'))] = cmd.select('tyr_i32', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+13.00,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('tyr_i','CZ'),('rasp','OD2'))] = cmd.select('tyr_i33', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+11.44,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('tyr_i','OH'),('rasp','CG'))] = cmd.select('tyr_i34', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+13.38,resSelectionSubs('asp','CG',subs)))
IDSpec[(('tyr_i','OH'),('rasp','OD1'))] = cmd.select('tyr_i35', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+13.80,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('tyr_i','OH'),('rasp','OD2'))] = cmd.select('tyr_i36', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+12.24,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('tyr_i','CE1'),('rarg','CZ'))] = cmd.select('tyr_i37', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+16.36,resSelectionSubs('arg','CZ',subs)))
IDSpec[(('tyr_i','CE1'),('rarg','NE'))] = cmd.select('tyr_i38', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+16.76,resSelectionSubs('arg','NE',subs)))
IDSpec[(('tyr_i','CE1'),('rarg','NH1'))] = cmd.select('tyr_i39', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+17.17,resSelectionSubs('arg','NH1',subs)))
IDSpec[(('tyr_i','CZ'),('rarg','CZ'))] = cmd.select('tyr_i40', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+15.19,resSelectionSubs('arg','CZ',subs)))
IDSpec[(('tyr_i','CZ'),('rarg','NE'))] = cmd.select('tyr_i41', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+15.54,resSelectionSubs('arg','NE',subs)))
IDSpec[(('tyr_i','CZ'),('rarg','NH1'))] = cmd.select('tyr_i42', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+16.01,resSelectionSubs('arg','NH1',subs)))
IDSpec[(('tyr_i','OH'),('rarg','CZ'))] = cmd.select('tyr_i43', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+14.68,resSelectionSubs('arg','CZ',subs)))
IDSpec[(('tyr_i','OH'),('rarg','NE'))] = cmd.select('tyr_i44', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+15.09,resSelectionSubs('arg','NE',subs)))
IDSpec[(('tyr_i','OH'),('rarg','NH1'))] = cmd.select('tyr_i45', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+15.41,resSelectionSubs('arg','NH1',subs)))
IDSpec['tyr_i'] = cmd.select('tyr_i',' br. tyr_i1&br. tyr_i2&br. tyr_i3&br. tyr_i4&br. tyr_i5&br. tyr_i6&br. tyr_i7&br. tyr_i8&br. tyr_i9&br. tyr_i10&br. tyr_i11&br. tyr_i12&br. tyr_i13&br. tyr_i14&br. tyr_i15&br. tyr_i16&br. tyr_i17&br. tyr_i18&br. tyr_i19&br. tyr_i20&br. tyr_i21&br. tyr_i22&br. tyr_i23&br. tyr_i24&br. tyr_i25&br. tyr_i26&br. tyr_i27&br. tyr_i28&br. tyr_i29&br. tyr_i30&br. tyr_i31&br. tyr_i32&br. tyr_i33&br. tyr_i34&br. tyr_i35&br. tyr_i36&br. tyr_i37&br. tyr_i38&br. tyr_i39&br. tyr_i40&br. tyr_i41&br. tyr_i42&br. tyr_i43&br. tyr_i44&br. tyr_i45')
IDSpec['r_tyr_i'] = cmd.count_atoms(resSelectionSubs('tyr_i', subs=subs, selection=True))
cmd.delete('tyr_i1')
cmd.delete('tyr_i2')
cmd.delete('tyr_i3')
cmd.delete('tyr_i4')
cmd.delete('tyr_i5')
cmd.delete('tyr_i6')
cmd.delete('tyr_i7')
cmd.delete('tyr_i8')
cmd.delete('tyr_i9')
cmd.delete('tyr_i10')
cmd.delete('tyr_i11')
cmd.delete('tyr_i12')
cmd.delete('tyr_i13')
cmd.delete('tyr_i14')
cmd.delete('tyr_i15')
cmd.delete('tyr_i16')
cmd.delete('tyr_i17')
cmd.delete('tyr_i18')
cmd.delete('tyr_i19')
cmd.delete('tyr_i20')
cmd.delete('tyr_i21')
cmd.delete('tyr_i22')
cmd.delete('tyr_i23')
cmd.delete('tyr_i24')
cmd.delete('tyr_i25')
cmd.delete('tyr_i26')
cmd.delete('tyr_i27')
cmd.delete('tyr_i28')
cmd.delete('tyr_i29')
cmd.delete('tyr_i30')
cmd.delete('tyr_i31')
cmd.delete('tyr_i32')
cmd.delete('tyr_i33')
cmd.delete('tyr_i34')
cmd.delete('tyr_i35')
cmd.delete('tyr_i36')
cmd.delete('tyr_i37')
cmd.delete('tyr_i38')
cmd.delete('tyr_i39')
cmd.delete('tyr_i40')
cmd.delete('tyr_i41')
cmd.delete('tyr_i42')
cmd.delete('tyr_i43')
cmd.delete('tyr_i44')
cmd.delete('tyr_i45')
IDSpec[(('asp','CG'),('sthr','CA'))] = cmd.select('asp1', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+33.17,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('asp','CG'),('sthr','CB'))] = cmd.select('asp2', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+34.17,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('asp','CG'),('sthr','OG1'))] = cmd.select('asp3', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+33.54,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('asp','OD1'),('sthr','CA'))] = cmd.select('asp4', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+33.60,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('asp','OD1'),('sthr','CB'))] = cmd.select('asp5', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+34.56,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('asp','OD1'),('sthr','OG1'))] = cmd.select('asp6', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+33.91,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('asp','OD2'),('sthr','CA'))] = cmd.select('asp7', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+33.76,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('asp','OD2'),('sthr','CB'))] = cmd.select('asp8', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+34.77,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('asp','OD2'),('sthr','OG1'))] = cmd.select('asp9', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+34.15,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('asp','CG'),('slys','CD'))] = cmd.select('asp10', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.57,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('asp','CG'),('slys','CE'))] = cmd.select('asp11', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.80,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('asp','CG'),('slys','NZ'))] = cmd.select('asp12', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+8.61,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('asp','OD1'),('slys','CD'))] = cmd.select('asp13', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.72,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('asp','OD1'),('slys','CE'))] = cmd.select('asp14', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.02,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('asp','OD1'),('slys','NZ'))] = cmd.select('asp15', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.77,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('asp','OD2'),('slys','CD'))] = cmd.select('asp16', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.53,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('asp','OD2'),('slys','CE'))] = cmd.select('asp17', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.49,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('asp','OD2'),('slys','NZ'))] = cmd.select('asp18', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+8.37,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('asp','CG'),('styr','CE1'))] = cmd.select('asp19', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.84,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('asp','CG'),('styr','CZ'))] = cmd.select('asp20', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.52,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('asp','CG'),('styr','OH'))] = cmd.select('asp21', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+5.64,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('asp','OD1'),('styr','CE1'))] = cmd.select('asp22', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.00,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('asp','OD1'),('styr','CZ'))] = cmd.select('asp23', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.64,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('asp','OD1'),('styr','OH'))] = cmd.select('asp24', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+6.80,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('asp','OD2'),('styr','CE1'))] = cmd.select('asp25', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.90,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('asp','OD2'),('styr','CZ'))] = cmd.select('asp26', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+5.56,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('asp','OD2'),('styr','OH'))] = cmd.select('asp27', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+4.71,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('asp','CG'),('styr_i','CE1'))] = cmd.select('asp28', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+12.63,resSelectionSubs('tyr_i','CE1',subs,selection=True)))
IDSpec[(('asp','CG'),('styr_i','CZ'))] = cmd.select('asp29', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+12.56,resSelectionSubs('tyr_i','CZ',subs,selection=True)))
IDSpec[(('asp','CG'),('styr_i','OH'))] = cmd.select('asp30', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+13.38,resSelectionSubs('tyr_i','OH',subs,selection=True)))
IDSpec[(('asp','OD1'),('styr_i','CE1'))] = cmd.select('asp31', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+12.97,resSelectionSubs('tyr_i','CE1',subs,selection=True)))
IDSpec[(('asp','OD1'),('styr_i','CZ'))] = cmd.select('asp32', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+13.00,resSelectionSubs('tyr_i','CZ',subs,selection=True)))
IDSpec[(('asp','OD1'),('styr_i','OH'))] = cmd.select('asp33', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+13.80,resSelectionSubs('tyr_i','OH',subs,selection=True)))
IDSpec[(('asp','OD2'),('styr_i','CE1'))] = cmd.select('asp34', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.59,resSelectionSubs('tyr_i','CE1',subs,selection=True)))
IDSpec[(('asp','OD2'),('styr_i','CZ'))] = cmd.select('asp35', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.44,resSelectionSubs('tyr_i','CZ',subs,selection=True)))
IDSpec[(('asp','OD2'),('styr_i','OH'))] = cmd.select('asp36', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+12.24,resSelectionSubs('tyr_i','OH',subs,selection=True)))
IDSpec[(('asp','CG'),('rarg','CZ'))] = cmd.select('asp37', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+15.00,resSelectionSubs('arg','CZ',subs)))
IDSpec[(('asp','CG'),('rarg','NE'))] = cmd.select('asp38', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+15.29,resSelectionSubs('arg','NE',subs)))
IDSpec[(('asp','CG'),('rarg','NH1'))] = cmd.select('asp39', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+16.01,resSelectionSubs('arg','NH1',subs)))
IDSpec[(('asp','OD1'),('rarg','CZ'))] = cmd.select('asp40', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+15.52,resSelectionSubs('arg','CZ',subs)))
IDSpec[(('asp','OD1'),('rarg','NE'))] = cmd.select('asp41', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+15.91,resSelectionSubs('arg','NE',subs)))
IDSpec[(('asp','OD1'),('rarg','NH1'))] = cmd.select('asp42', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+16.46,resSelectionSubs('arg','NH1',subs)))
IDSpec[(('asp','OD2'),('rarg','CZ'))] = cmd.select('asp43', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+14.16,resSelectionSubs('arg','CZ',subs)))
IDSpec[(('asp','OD2'),('rarg','NE'))] = cmd.select('asp44', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+14.45,resSelectionSubs('arg','NE',subs)))
IDSpec[(('asp','OD2'),('rarg','NH1'))] = cmd.select('asp45', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+15.20,resSelectionSubs('arg','NH1',subs)))
IDSpec['asp'] = cmd.select('asp',' br. asp1&br. asp2&br. asp3&br. asp4&br. asp5&br. asp6&br. asp7&br. asp8&br. asp9&br. asp10&br. asp11&br. asp12&br. asp13&br. asp14&br. asp15&br. asp16&br. asp17&br. asp18&br. asp19&br. asp20&br. asp21&br. asp22&br. asp23&br. asp24&br. asp25&br. asp26&br. asp27&br. asp28&br. asp29&br. asp30&br. asp31&br. asp32&br. asp33&br. asp34&br. asp35&br. asp36&br. asp37&br. asp38&br. asp39&br. asp40&br. asp41&br. asp42&br. asp43&br. asp44&br. asp45')
IDSpec['r_asp'] = cmd.count_atoms(resSelectionSubs('asp', subs=subs, selection=True))
cmd.delete('asp1')
cmd.delete('asp2')
cmd.delete('asp3')
cmd.delete('asp4')
cmd.delete('asp5')
cmd.delete('asp6')
cmd.delete('asp7')
cmd.delete('asp8')
cmd.delete('asp9')
cmd.delete('asp10')
cmd.delete('asp11')
cmd.delete('asp12')
cmd.delete('asp13')
cmd.delete('asp14')
cmd.delete('asp15')
cmd.delete('asp16')
cmd.delete('asp17')
cmd.delete('asp18')
cmd.delete('asp19')
cmd.delete('asp20')
cmd.delete('asp21')
cmd.delete('asp22')
cmd.delete('asp23')
cmd.delete('asp24')
cmd.delete('asp25')
cmd.delete('asp26')
cmd.delete('asp27')
cmd.delete('asp28')
cmd.delete('asp29')
cmd.delete('asp30')
cmd.delete('asp31')
cmd.delete('asp32')
cmd.delete('asp33')
cmd.delete('asp34')
cmd.delete('asp35')
cmd.delete('asp36')
cmd.delete('asp37')
cmd.delete('asp38')
cmd.delete('asp39')
cmd.delete('asp40')
cmd.delete('asp41')
cmd.delete('asp42')
cmd.delete('asp43')
cmd.delete('asp44')
cmd.delete('asp45')
IDSpec[(('arg','CZ'),('sthr','CA'))] = cmd.select('arg1', '%s w. %s of %s'%(resSelectionSubs('arg','CZ',subs),d+34.80,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('arg','CZ'),('sthr','CB'))] = cmd.select('arg2', '%s w. %s of %s'%(resSelectionSubs('arg','CZ',subs),d+35.63,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('arg','CZ'),('sthr','OG1'))] = cmd.select('arg3', '%s w. %s of %s'%(resSelectionSubs('arg','CZ',subs),d+34.79,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('arg','NE'),('sthr','CA'))] = cmd.select('arg4', '%s w. %s of %s'%(resSelectionSubs('arg','NE',subs),d+34.13,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('arg','NE'),('sthr','CB'))] = cmd.select('arg5', '%s w. %s of %s'%(resSelectionSubs('arg','NE',subs),d+34.98,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('arg','NE'),('sthr','OG1'))] = cmd.select('arg6', '%s w. %s of %s'%(resSelectionSubs('arg','NE',subs),d+34.18,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('arg','NH1'),('sthr','CA'))] = cmd.select('arg7', '%s w. %s of %s'%(resSelectionSubs('arg','NH1',subs),d+35.43,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('arg','NH1'),('sthr','CB'))] = cmd.select('arg8', '%s w. %s of %s'%(resSelectionSubs('arg','NH1',subs),d+36.20,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('arg','NH1'),('sthr','OG1'))] = cmd.select('arg9', '%s w. %s of %s'%(resSelectionSubs('arg','NH1',subs),d+35.33,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('arg','CZ'),('slys','CD'))] = cmd.select('arg10', '%s w. %s of %s'%(resSelectionSubs('arg','CZ',subs),d+15.83,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('arg','CZ'),('slys','CE'))] = cmd.select('arg11', '%s w. %s of %s'%(resSelectionSubs('arg','CZ',subs),d+14.46,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('arg','CZ'),('slys','NZ'))] = cmd.select('arg12', '%s w. %s of %s'%(resSelectionSubs('arg','CZ',subs),d+14.00,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('arg','NE'),('slys','CD'))] = cmd.select('arg13', '%s w. %s of %s'%(resSelectionSubs('arg','NE',subs),d+15.57,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('arg','NE'),('slys','CE'))] = cmd.select('arg14', '%s w. %s of %s'%(resSelectionSubs('arg','NE',subs),d+14.15,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('arg','NE'),('slys','NZ'))] = cmd.select('arg15', '%s w. %s of %s'%(resSelectionSubs('arg','NE',subs),d+13.61,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('arg','NH1'),('slys','CD'))] = cmd.select('arg16', '%s w. %s of %s'%(resSelectionSubs('arg','NH1',subs),d+17.08,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('arg','NH1'),('slys','CE'))] = cmd.select('arg17', '%s w. %s of %s'%(resSelectionSubs('arg','NH1',subs),d+15.73,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('arg','NH1'),('slys','NZ'))] = cmd.select('arg18', '%s w. %s of %s'%(resSelectionSubs('arg','NH1',subs),d+15.27,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('arg','CZ'),('styr','CE1'))] = cmd.select('arg19', '%s w. %s of %s'%(resSelectionSubs('arg','CZ',subs),d+13.62,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('arg','CZ'),('styr','CZ'))] = cmd.select('arg20', '%s w. %s of %s'%(resSelectionSubs('arg','CZ',subs),d+13.82,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('arg','CZ'),('styr','OH'))] = cmd.select('arg21', '%s w. %s of %s'%(resSelectionSubs('arg','CZ',subs),d+13.19,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('arg','NE'),('styr','CE1'))] = cmd.select('arg22', '%s w. %s of %s'%(resSelectionSubs('arg','NE',subs),d+13.48,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('arg','NE'),('styr','CZ'))] = cmd.select('arg23', '%s w. %s of %s'%(resSelectionSubs('arg','NE',subs),d+13.81,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('arg','NE'),('styr','OH'))] = cmd.select('arg24', '%s w. %s of %s'%(resSelectionSubs('arg','NE',subs),d+13.23,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('arg','NH1'),('styr','CE1'))] = cmd.select('arg25', '%s w. %s of %s'%(resSelectionSubs('arg','NH1',subs),d+14.86,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('arg','NH1'),('styr','CZ'))] = cmd.select('arg26', '%s w. %s of %s'%(resSelectionSubs('arg','NH1',subs),d+15.02,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('arg','NH1'),('styr','OH'))] = cmd.select('arg27', '%s w. %s of %s'%(resSelectionSubs('arg','NH1',subs),d+14.38,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('arg','CZ'),('styr_i','CE1'))] = cmd.select('arg28', '%s w. %s of %s'%(resSelectionSubs('arg','CZ',subs),d+16.36,resSelectionSubs('tyr_i','CE1',subs,selection=True)))
IDSpec[(('arg','CZ'),('styr_i','CZ'))] = cmd.select('arg29', '%s w. %s of %s'%(resSelectionSubs('arg','CZ',subs),d+15.19,resSelectionSubs('tyr_i','CZ',subs,selection=True)))
IDSpec[(('arg','CZ'),('styr_i','OH'))] = cmd.select('arg30', '%s w. %s of %s'%(resSelectionSubs('arg','CZ',subs),d+14.68,resSelectionSubs('tyr_i','OH',subs,selection=True)))
IDSpec[(('arg','NE'),('styr_i','CE1'))] = cmd.select('arg31', '%s w. %s of %s'%(resSelectionSubs('arg','NE',subs),d+16.76,resSelectionSubs('tyr_i','CE1',subs,selection=True)))
IDSpec[(('arg','NE'),('styr_i','CZ'))] = cmd.select('arg32', '%s w. %s of %s'%(resSelectionSubs('arg','NE',subs),d+15.54,resSelectionSubs('tyr_i','CZ',subs,selection=True)))
IDSpec[(('arg','NE'),('styr_i','OH'))] = cmd.select('arg33', '%s w. %s of %s'%(resSelectionSubs('arg','NE',subs),d+15.09,resSelectionSubs('tyr_i','OH',subs,selection=True)))
IDSpec[(('arg','NH1'),('styr_i','CE1'))] = cmd.select('arg34', '%s w. %s of %s'%(resSelectionSubs('arg','NH1',subs),d+17.17,resSelectionSubs('tyr_i','CE1',subs,selection=True)))
IDSpec[(('arg','NH1'),('styr_i','CZ'))] = cmd.select('arg35', '%s w. %s of %s'%(resSelectionSubs('arg','NH1',subs),d+16.01,resSelectionSubs('tyr_i','CZ',subs,selection=True)))
IDSpec[(('arg','NH1'),('styr_i','OH'))] = cmd.select('arg36', '%s w. %s of %s'%(resSelectionSubs('arg','NH1',subs),d+15.41,resSelectionSubs('tyr_i','OH',subs,selection=True)))
IDSpec[(('arg','CZ'),('sasp','CG'))] = cmd.select('arg37', '%s w. %s of %s'%(resSelectionSubs('arg','CZ',subs),d+15.00,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('arg','CZ'),('sasp','OD1'))] = cmd.select('arg38', '%s w. %s of %s'%(resSelectionSubs('arg','CZ',subs),d+15.52,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('arg','CZ'),('sasp','OD2'))] = cmd.select('arg39', '%s w. %s of %s'%(resSelectionSubs('arg','CZ',subs),d+14.16,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('arg','NE'),('sasp','CG'))] = cmd.select('arg40', '%s w. %s of %s'%(resSelectionSubs('arg','NE',subs),d+15.29,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('arg','NE'),('sasp','OD1'))] = cmd.select('arg41', '%s w. %s of %s'%(resSelectionSubs('arg','NE',subs),d+15.91,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('arg','NE'),('sasp','OD2'))] = cmd.select('arg42', '%s w. %s of %s'%(resSelectionSubs('arg','NE',subs),d+14.45,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('arg','NH1'),('sasp','CG'))] = cmd.select('arg43', '%s w. %s of %s'%(resSelectionSubs('arg','NH1',subs),d+16.01,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('arg','NH1'),('sasp','OD1'))] = cmd.select('arg44', '%s w. %s of %s'%(resSelectionSubs('arg','NH1',subs),d+16.46,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('arg','NH1'),('sasp','OD2'))] = cmd.select('arg45', '%s w. %s of %s'%(resSelectionSubs('arg','NH1',subs),d+15.20,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec['arg'] = cmd.select('arg',' br. arg1&br. arg2&br. arg3&br. arg4&br. arg5&br. arg6&br. arg7&br. arg8&br. arg9&br. arg10&br. arg11&br. arg12&br. arg13&br. arg14&br. arg15&br. arg16&br. arg17&br. arg18&br. arg19&br. arg20&br. arg21&br. arg22&br. arg23&br. arg24&br. arg25&br. arg26&br. arg27&br. arg28&br. arg29&br. arg30&br. arg31&br. arg32&br. arg33&br. arg34&br. arg35&br. arg36&br. arg37&br. arg38&br. arg39&br. arg40&br. arg41&br. arg42&br. arg43&br. arg44&br. arg45')
IDSpec['r_arg'] = cmd.count_atoms(resSelectionSubs('arg', subs=subs, selection=True))
cmd.delete('arg1')
cmd.delete('arg2')
cmd.delete('arg3')
cmd.delete('arg4')
cmd.delete('arg5')
cmd.delete('arg6')
cmd.delete('arg7')
cmd.delete('arg8')
cmd.delete('arg9')
cmd.delete('arg10')
cmd.delete('arg11')
cmd.delete('arg12')
cmd.delete('arg13')
cmd.delete('arg14')
cmd.delete('arg15')
cmd.delete('arg16')
cmd.delete('arg17')
cmd.delete('arg18')
cmd.delete('arg19')
cmd.delete('arg20')
cmd.delete('arg21')
cmd.delete('arg22')
cmd.delete('arg23')
cmd.delete('arg24')
cmd.delete('arg25')
cmd.delete('arg26')
cmd.delete('arg27')
cmd.delete('arg28')
cmd.delete('arg29')
cmd.delete('arg30')
cmd.delete('arg31')
cmd.delete('arg32')
cmd.delete('arg33')
cmd.delete('arg34')
cmd.delete('arg35')
cmd.delete('arg36')
cmd.delete('arg37')
cmd.delete('arg38')
cmd.delete('arg39')
cmd.delete('arg40')
cmd.delete('arg41')
cmd.delete('arg42')
cmd.delete('arg43')
cmd.delete('arg44')
cmd.delete('arg45')
IDSpec['S_1p33_1_1_1_253'] = cmd.select('S_1p33_1_1_1_253', 'thr|lys|tyr|tyr_i|asp|arg')
cmd.delete('thr')
cmd.delete('lys')
cmd.delete('tyr')
cmd.delete('tyr_i')
cmd.delete('asp')
cmd.delete('arg')
