'''
FUNC:S_1q3r_3_6_4_9
PDB:1q3r
EC:3.6.4.9
RESI:asp,thr,thr,asp
LOCI:a-64,97,98,393;
'''
IDSpec[(('thr','CA'),('rthr','CA'))] = cmd.select('thr1', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+5.79,resSelectionSubs('thr','CA',subs)))
IDSpec[(('thr','CA'),('rthr','CB'))] = cmd.select('thr2', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+6.37,resSelectionSubs('thr','CB',subs)))
IDSpec[(('thr','CA'),('rthr','OG1'))] = cmd.select('thr3', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+6.15,resSelectionSubs('thr','OG1',subs)))
IDSpec[(('thr','CB'),('rthr','CA'))] = cmd.select('thr4', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+6.85,resSelectionSubs('thr','CA',subs)))
IDSpec[(('thr','CB'),('rthr','CB'))] = cmd.select('thr5', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+7.17,resSelectionSubs('thr','CB',subs)))
IDSpec[(('thr','CB'),('rthr','OG1'))] = cmd.select('thr6', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+6.52,resSelectionSubs('thr','OG1',subs)))
IDSpec[(('thr','OG1'),('rthr','CA'))] = cmd.select('thr7', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+7.02,resSelectionSubs('thr','CA',subs)))
IDSpec[(('thr','OG1'),('rthr','CB'))] = cmd.select('thr8', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+6.90,resSelectionSubs('thr','CB',subs)))
IDSpec[(('thr','OG1'),('rthr','OG1'))] = cmd.select('thr9', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+6.06,resSelectionSubs('thr','OG1',subs)))
IDSpec[(('thr','CA'),('rasp','CG'))] = cmd.select('thr10', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+9.89,resSelectionSubs('asp','CG',subs)))
IDSpec[(('thr','CA'),('rasp','OD1'))] = cmd.select('thr11', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+9.03,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('thr','CA'),('rasp','OD2'))] = cmd.select('thr12', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+10.65,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('thr','CB'),('rasp','CG'))] = cmd.select('thr13', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+9.66,resSelectionSubs('asp','CG',subs)))
IDSpec[(('thr','CB'),('rasp','OD1'))] = cmd.select('thr14', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+8.85,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('thr','CB'),('rasp','OD2'))] = cmd.select('thr15', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+10.56,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('thr','OG1'),('rasp','CG'))] = cmd.select('thr16', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+8.48,resSelectionSubs('asp','CG',subs)))
IDSpec[(('thr','OG1'),('rasp','OD1'))] = cmd.select('thr17', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+7.81,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('thr','OG1'),('rasp','OD2'))] = cmd.select('thr18', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+9.39,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('thr','CA'),('rasp','CG'))] = cmd.select('thr19', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+12.61,resSelectionSubs('asp','CG',subs)))
IDSpec[(('thr','CA'),('rasp','OD1'))] = cmd.select('thr20', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+12.29,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('thr','CA'),('rasp','OD2'))] = cmd.select('thr21', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+12.27,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('thr','CB'),('rasp','CG'))] = cmd.select('thr22', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+12.38,resSelectionSubs('asp','CG',subs)))
IDSpec[(('thr','CB'),('rasp','OD1'))] = cmd.select('thr23', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+12.24,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('thr','CB'),('rasp','OD2'))] = cmd.select('thr24', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+11.90,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('thr','OG1'),('rasp','CG'))] = cmd.select('thr25', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+11.74,resSelectionSubs('asp','CG',subs)))
IDSpec[(('thr','OG1'),('rasp','OD1'))] = cmd.select('thr26', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+11.65,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('thr','OG1'),('rasp','OD2'))] = cmd.select('thr27', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+11.14,resSelectionSubs('asp','OD2',subs)))
IDSpec['thr'] = cmd.select('thr',' br. thr1&br. thr2&br. thr3&br. thr4&br. thr5&br. thr6&br. thr7&br. thr8&br. thr9&br. thr10&br. thr11&br. thr12&br. thr13&br. thr14&br. thr15&br. thr16&br. thr17&br. thr18&br. thr19&br. thr20&br. thr21&br. thr22&br. thr23&br. thr24&br. thr25&br. thr26&br. thr27')
IDSpec['r_thr'] = cmd.count_atoms(resSelectionSubs('thr', subs=subs, selection=True))
cmd.delete('thr1')
cmd.delete('thr2')
cmd.delete('thr3')
cmd.delete('thr4')
cmd.delete('thr5')
cmd.delete('thr6')
cmd.delete('thr7')
cmd.delete('thr8')
cmd.delete('thr9')
cmd.delete('thr10')
cmd.delete('thr11')
cmd.delete('thr12')
cmd.delete('thr13')
cmd.delete('thr14')
cmd.delete('thr15')
cmd.delete('thr16')
cmd.delete('thr17')
cmd.delete('thr18')
cmd.delete('thr19')
cmd.delete('thr20')
cmd.delete('thr21')
cmd.delete('thr22')
cmd.delete('thr23')
cmd.delete('thr24')
cmd.delete('thr25')
cmd.delete('thr26')
cmd.delete('thr27')
IDSpec[(('thr_i','CA'),('sthr','CA'))] = cmd.select('thr_i1', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+5.79,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('thr_i','CA'),('sthr','CB'))] = cmd.select('thr_i2', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+6.85,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('thr_i','CA'),('sthr','OG1'))] = cmd.select('thr_i3', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+7.02,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('thr_i','CB'),('sthr','CA'))] = cmd.select('thr_i4', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+6.37,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('thr_i','CB'),('sthr','CB'))] = cmd.select('thr_i5', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+7.17,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('thr_i','CB'),('sthr','OG1'))] = cmd.select('thr_i6', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+6.90,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('thr_i','OG1'),('sthr','CA'))] = cmd.select('thr_i7', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+6.15,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('thr_i','OG1'),('sthr','CB'))] = cmd.select('thr_i8', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+6.52,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('thr_i','OG1'),('sthr','OG1'))] = cmd.select('thr_i9', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+6.06,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('thr_i','CA'),('rasp','CG'))] = cmd.select('thr_i10', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+8.82,resSelectionSubs('asp','CG',subs)))
IDSpec[(('thr_i','CA'),('rasp','OD1'))] = cmd.select('thr_i11', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+7.76,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('thr_i','CA'),('rasp','OD2'))] = cmd.select('thr_i12', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+9.28,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('thr_i','CB'),('rasp','CG'))] = cmd.select('thr_i13', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+7.41,resSelectionSubs('asp','CG',subs)))
IDSpec[(('thr_i','CB'),('rasp','OD1'))] = cmd.select('thr_i14', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+6.41,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('thr_i','CB'),('rasp','OD2'))] = cmd.select('thr_i15', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+7.79,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('thr_i','OG1'),('rasp','CG'))] = cmd.select('thr_i16', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+6.54,resSelectionSubs('asp','CG',subs)))
IDSpec[(('thr_i','OG1'),('rasp','OD1'))] = cmd.select('thr_i17', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+5.45,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('thr_i','OG1'),('rasp','OD2'))] = cmd.select('thr_i18', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+7.19,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('thr_i','CA'),('rasp','CG'))] = cmd.select('thr_i19', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+10.58,resSelectionSubs('asp','CG',subs)))
IDSpec[(('thr_i','CA'),('rasp','OD1'))] = cmd.select('thr_i20', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+9.89,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('thr_i','CA'),('rasp','OD2'))] = cmd.select('thr_i21', '%s w. %s of %s'%(resSelectionSubs('thr','CA',subs),d+10.61,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('thr_i','CB'),('rasp','CG'))] = cmd.select('thr_i22', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+9.71,resSelectionSubs('asp','CG',subs)))
IDSpec[(('thr_i','CB'),('rasp','OD1'))] = cmd.select('thr_i23', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+9.01,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('thr_i','CB'),('rasp','OD2'))] = cmd.select('thr_i24', '%s w. %s of %s'%(resSelectionSubs('thr','CB',subs),d+9.64,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('thr_i','OG1'),('rasp','CG'))] = cmd.select('thr_i25', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+8.92,resSelectionSubs('asp','CG',subs)))
IDSpec[(('thr_i','OG1'),('rasp','OD1'))] = cmd.select('thr_i26', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+8.42,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('thr_i','OG1'),('rasp','OD2'))] = cmd.select('thr_i27', '%s w. %s of %s'%(resSelectionSubs('thr','OG1',subs),d+8.69,resSelectionSubs('asp','OD2',subs)))
IDSpec['thr_i'] = cmd.select('thr_i',' br. thr_i1&br. thr_i2&br. thr_i3&br. thr_i4&br. thr_i5&br. thr_i6&br. thr_i7&br. thr_i8&br. thr_i9&br. thr_i10&br. thr_i11&br. thr_i12&br. thr_i13&br. thr_i14&br. thr_i15&br. thr_i16&br. thr_i17&br. thr_i18&br. thr_i19&br. thr_i20&br. thr_i21&br. thr_i22&br. thr_i23&br. thr_i24&br. thr_i25&br. thr_i26&br. thr_i27')
IDSpec['r_thr_i'] = cmd.count_atoms(resSelectionSubs('thr_i', subs=subs, selection=True))
cmd.delete('thr_i1')
cmd.delete('thr_i2')
cmd.delete('thr_i3')
cmd.delete('thr_i4')
cmd.delete('thr_i5')
cmd.delete('thr_i6')
cmd.delete('thr_i7')
cmd.delete('thr_i8')
cmd.delete('thr_i9')
cmd.delete('thr_i10')
cmd.delete('thr_i11')
cmd.delete('thr_i12')
cmd.delete('thr_i13')
cmd.delete('thr_i14')
cmd.delete('thr_i15')
cmd.delete('thr_i16')
cmd.delete('thr_i17')
cmd.delete('thr_i18')
cmd.delete('thr_i19')
cmd.delete('thr_i20')
cmd.delete('thr_i21')
cmd.delete('thr_i22')
cmd.delete('thr_i23')
cmd.delete('thr_i24')
cmd.delete('thr_i25')
cmd.delete('thr_i26')
cmd.delete('thr_i27')
IDSpec[(('asp','CG'),('sthr','CA'))] = cmd.select('asp1', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+9.89,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('asp','CG'),('sthr','CB'))] = cmd.select('asp2', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+9.66,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('asp','CG'),('sthr','OG1'))] = cmd.select('asp3', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+8.48,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('asp','OD1'),('sthr','CA'))] = cmd.select('asp4', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.03,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('asp','OD1'),('sthr','CB'))] = cmd.select('asp5', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.85,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('asp','OD1'),('sthr','OG1'))] = cmd.select('asp6', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.81,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('asp','OD2'),('sthr','CA'))] = cmd.select('asp7', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+10.65,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('asp','OD2'),('sthr','CB'))] = cmd.select('asp8', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+10.56,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('asp','OD2'),('sthr','OG1'))] = cmd.select('asp9', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+9.39,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('asp','CG'),('sthr_i','CA'))] = cmd.select('asp10', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+8.82,resSelectionSubs('thr_i','CA',subs,selection=True)))
IDSpec[(('asp','CG'),('sthr_i','CB'))] = cmd.select('asp11', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.41,resSelectionSubs('thr_i','CB',subs,selection=True)))
IDSpec[(('asp','CG'),('sthr_i','OG1'))] = cmd.select('asp12', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.54,resSelectionSubs('thr_i','OG1',subs,selection=True)))
IDSpec[(('asp','OD1'),('sthr_i','CA'))] = cmd.select('asp13', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.76,resSelectionSubs('thr_i','CA',subs,selection=True)))
IDSpec[(('asp','OD1'),('sthr_i','CB'))] = cmd.select('asp14', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+6.41,resSelectionSubs('thr_i','CB',subs,selection=True)))
IDSpec[(('asp','OD1'),('sthr_i','OG1'))] = cmd.select('asp15', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+5.45,resSelectionSubs('thr_i','OG1',subs,selection=True)))
IDSpec[(('asp','OD2'),('sthr_i','CA'))] = cmd.select('asp16', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+9.28,resSelectionSubs('thr_i','CA',subs,selection=True)))
IDSpec[(('asp','OD2'),('sthr_i','CB'))] = cmd.select('asp17', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.79,resSelectionSubs('thr_i','CB',subs,selection=True)))
IDSpec[(('asp','OD2'),('sthr_i','OG1'))] = cmd.select('asp18', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.19,resSelectionSubs('thr_i','OG1',subs,selection=True)))
IDSpec[(('asp','CG'),('rasp','CG'))] = cmd.select('asp19', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.64,resSelectionSubs('asp','CG',subs)))
IDSpec[(('asp','CG'),('rasp','OD1'))] = cmd.select('asp20', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.50,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('asp','CG'),('rasp','OD2'))] = cmd.select('asp21', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.85,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('asp','OD1'),('rasp','CG'))] = cmd.select('asp22', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.15,resSelectionSubs('asp','CG',subs)))
IDSpec[(('asp','OD1'),('rasp','OD1'))] = cmd.select('asp23', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+6.92,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('asp','OD1'),('rasp','OD2'))] = cmd.select('asp24', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+6.49,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('asp','OD2'),('rasp','CG'))] = cmd.select('asp25', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+8.10,resSelectionSubs('asp','CG',subs)))
IDSpec[(('asp','OD2'),('rasp','OD1'))] = cmd.select('asp26', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.81,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('asp','OD2'),('rasp','OD2'))] = cmd.select('asp27', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.44,resSelectionSubs('asp','OD2',subs)))
IDSpec['asp'] = cmd.select('asp',' br. asp1&br. asp2&br. asp3&br. asp4&br. asp5&br. asp6&br. asp7&br. asp8&br. asp9&br. asp10&br. asp11&br. asp12&br. asp13&br. asp14&br. asp15&br. asp16&br. asp17&br. asp18&br. asp19&br. asp20&br. asp21&br. asp22&br. asp23&br. asp24&br. asp25&br. asp26&br. asp27')
IDSpec['r_asp'] = cmd.count_atoms(resSelectionSubs('asp', subs=subs, selection=True))
cmd.delete('asp1')
cmd.delete('asp2')
cmd.delete('asp3')
cmd.delete('asp4')
cmd.delete('asp5')
cmd.delete('asp6')
cmd.delete('asp7')
cmd.delete('asp8')
cmd.delete('asp9')
cmd.delete('asp10')
cmd.delete('asp11')
cmd.delete('asp12')
cmd.delete('asp13')
cmd.delete('asp14')
cmd.delete('asp15')
cmd.delete('asp16')
cmd.delete('asp17')
cmd.delete('asp18')
cmd.delete('asp19')
cmd.delete('asp20')
cmd.delete('asp21')
cmd.delete('asp22')
cmd.delete('asp23')
cmd.delete('asp24')
cmd.delete('asp25')
cmd.delete('asp26')
cmd.delete('asp27')
IDSpec[(('asp_i','CG'),('sthr','CA'))] = cmd.select('asp_i1', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+12.61,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sthr','CB'))] = cmd.select('asp_i2', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+12.38,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sthr','OG1'))] = cmd.select('asp_i3', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+11.74,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sthr','CA'))] = cmd.select('asp_i4', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+12.29,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sthr','CB'))] = cmd.select('asp_i5', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+12.24,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sthr','OG1'))] = cmd.select('asp_i6', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+11.65,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sthr','CA'))] = cmd.select('asp_i7', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+12.27,resSelectionSubs('thr','CA',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sthr','CB'))] = cmd.select('asp_i8', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.90,resSelectionSubs('thr','CB',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sthr','OG1'))] = cmd.select('asp_i9', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.14,resSelectionSubs('thr','OG1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sthr_i','CA'))] = cmd.select('asp_i10', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+10.58,resSelectionSubs('thr_i','CA',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sthr_i','CB'))] = cmd.select('asp_i11', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+9.71,resSelectionSubs('thr_i','CB',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sthr_i','OG1'))] = cmd.select('asp_i12', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+8.92,resSelectionSubs('thr_i','OG1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sthr_i','CA'))] = cmd.select('asp_i13', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.89,resSelectionSubs('thr_i','CA',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sthr_i','CB'))] = cmd.select('asp_i14', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.01,resSelectionSubs('thr_i','CB',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sthr_i','OG1'))] = cmd.select('asp_i15', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.42,resSelectionSubs('thr_i','OG1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sthr_i','CA'))] = cmd.select('asp_i16', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+10.61,resSelectionSubs('thr_i','CA',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sthr_i','CB'))] = cmd.select('asp_i17', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+9.64,resSelectionSubs('thr_i','CB',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sthr_i','OG1'))] = cmd.select('asp_i18', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+8.69,resSelectionSubs('thr_i','OG1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasp','CG'))] = cmd.select('asp_i19', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.64,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasp','OD1'))] = cmd.select('asp_i20', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.15,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasp','OD2'))] = cmd.select('asp_i21', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+8.10,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasp','CG'))] = cmd.select('asp_i22', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.50,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasp','OD1'))] = cmd.select('asp_i23', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+6.92,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasp','OD2'))] = cmd.select('asp_i24', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.81,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasp','CG'))] = cmd.select('asp_i25', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.85,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasp','OD1'))] = cmd.select('asp_i26', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.49,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasp','OD2'))] = cmd.select('asp_i27', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.44,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec['asp_i'] = cmd.select('asp_i',' br. asp_i1&br. asp_i2&br. asp_i3&br. asp_i4&br. asp_i5&br. asp_i6&br. asp_i7&br. asp_i8&br. asp_i9&br. asp_i10&br. asp_i11&br. asp_i12&br. asp_i13&br. asp_i14&br. asp_i15&br. asp_i16&br. asp_i17&br. asp_i18&br. asp_i19&br. asp_i20&br. asp_i21&br. asp_i22&br. asp_i23&br. asp_i24&br. asp_i25&br. asp_i26&br. asp_i27')
IDSpec['r_asp_i'] = cmd.count_atoms(resSelectionSubs('asp_i', subs=subs, selection=True))
cmd.delete('asp_i1')
cmd.delete('asp_i2')
cmd.delete('asp_i3')
cmd.delete('asp_i4')
cmd.delete('asp_i5')
cmd.delete('asp_i6')
cmd.delete('asp_i7')
cmd.delete('asp_i8')
cmd.delete('asp_i9')
cmd.delete('asp_i10')
cmd.delete('asp_i11')
cmd.delete('asp_i12')
cmd.delete('asp_i13')
cmd.delete('asp_i14')
cmd.delete('asp_i15')
cmd.delete('asp_i16')
cmd.delete('asp_i17')
cmd.delete('asp_i18')
cmd.delete('asp_i19')
cmd.delete('asp_i20')
cmd.delete('asp_i21')
cmd.delete('asp_i22')
cmd.delete('asp_i23')
cmd.delete('asp_i24')
cmd.delete('asp_i25')
cmd.delete('asp_i26')
cmd.delete('asp_i27')
IDSpec['S_1q3r_3_6_4_9'] = cmd.select('S_1q3r_3_6_4_9', 'thr|thr_i|asp|asp_i')
cmd.delete('thr')
cmd.delete('thr_i')
cmd.delete('asp')
cmd.delete('asp_i')
