'''
FUNC:S_1rpx_5_1_3_1
PDB:1rpx
EC:5.1.3.1
RESI:gln,his,asp,his,asn,asp
LOCI:a-34,41,43,74,126,185;
'''
IDSpec[(('gln','CD'),('rasp','CG'))] = cmd.select('gln1', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+25.61,resSelectionSubs('asp','CG',subs)))
IDSpec[(('gln','CD'),('rasp','OD1'))] = cmd.select('gln2', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+25.22,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('gln','CD'),('rasp','OD2'))] = cmd.select('gln3', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+25.70,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('gln','NE2'),('rasp','CG'))] = cmd.select('gln4', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+26.83,resSelectionSubs('asp','CG',subs)))
IDSpec[(('gln','NE2'),('rasp','OD1'))] = cmd.select('gln5', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+26.42,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('gln','NE2'),('rasp','OD2'))] = cmd.select('gln6', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+26.89,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('gln','OE1'),('rasp','CG'))] = cmd.select('gln7', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+25.32,resSelectionSubs('asp','CG',subs)))
IDSpec[(('gln','OE1'),('rasp','OD1'))] = cmd.select('gln8', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+24.97,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('gln','OE1'),('rasp','OD2'))] = cmd.select('gln9', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+25.40,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('gln','CD'),('rhis','CE1'))] = cmd.select('gln10', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+29.00,resSelectionSubs('his','CE1',subs)))
IDSpec[(('gln','CD'),('rhis','ND1'))] = cmd.select('gln11', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+27.71,resSelectionSubs('his','ND1',subs)))
IDSpec[(('gln','CD'),('rhis','NE2'))] = cmd.select('gln12', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+29.71,resSelectionSubs('his','NE2',subs)))
IDSpec[(('gln','NE2'),('rhis','CE1'))] = cmd.select('gln13', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+30.15,resSelectionSubs('his','CE1',subs)))
IDSpec[(('gln','NE2'),('rhis','ND1'))] = cmd.select('gln14', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+28.86,resSelectionSubs('his','ND1',subs)))
IDSpec[(('gln','NE2'),('rhis','NE2'))] = cmd.select('gln15', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+30.85,resSelectionSubs('his','NE2',subs)))
IDSpec[(('gln','OE1'),('rhis','CE1'))] = cmd.select('gln16', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+28.60,resSelectionSubs('his','CE1',subs)))
IDSpec[(('gln','OE1'),('rhis','ND1'))] = cmd.select('gln17', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+27.32,resSelectionSubs('his','ND1',subs)))
IDSpec[(('gln','OE1'),('rhis','NE2'))] = cmd.select('gln18', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+29.28,resSelectionSubs('his','NE2',subs)))
IDSpec[(('gln','CD'),('rasp_i','CG'))] = cmd.select('gln19', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+24.50,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('gln','CD'),('rasp_i','OD1'))] = cmd.select('gln20', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+25.17,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('gln','CD'),('rasp_i','OD2'))] = cmd.select('gln21', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+23.56,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('gln','NE2'),('rasp_i','CG'))] = cmd.select('gln22', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+25.57,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('gln','NE2'),('rasp_i','OD1'))] = cmd.select('gln23', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+26.26,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('gln','NE2'),('rasp_i','OD2'))] = cmd.select('gln24', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+24.63,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('gln','OE1'),('rasp_i','CG'))] = cmd.select('gln25', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+24.29,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('gln','OE1'),('rasp_i','OD1'))] = cmd.select('gln26', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+24.90,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('gln','OE1'),('rasp_i','OD2'))] = cmd.select('gln27', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+23.38,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('gln','CD'),('rhis_i','CE1'))] = cmd.select('gln28', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+23.42,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('gln','CD'),('rhis_i','ND1'))] = cmd.select('gln29', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+22.11,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('gln','CD'),('rhis_i','NE2'))] = cmd.select('gln30', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+23.67,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('gln','NE2'),('rhis_i','CE1'))] = cmd.select('gln31', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+24.61,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('gln','NE2'),('rhis_i','ND1'))] = cmd.select('gln32', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+23.31,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('gln','NE2'),('rhis_i','NE2'))] = cmd.select('gln33', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+24.84,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('gln','OE1'),('rhis_i','CE1'))] = cmd.select('gln34', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+22.93,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('gln','OE1'),('rhis_i','ND1'))] = cmd.select('gln35', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+21.62,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('gln','OE1'),('rhis_i','NE2'))] = cmd.select('gln36', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+23.25,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('gln','CD'),('rasn','CG'))] = cmd.select('gln37', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+36.49,resSelectionSubs('asn','CG',subs)))
IDSpec[(('gln','CD'),('rasn','ND2'))] = cmd.select('gln38', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+37.51,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('gln','CD'),('rasn','OD1'))] = cmd.select('gln39', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+35.30,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('gln','NE2'),('rasn','CG'))] = cmd.select('gln40', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+37.67,resSelectionSubs('asn','CG',subs)))
IDSpec[(('gln','NE2'),('rasn','ND2'))] = cmd.select('gln41', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+38.68,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('gln','NE2'),('rasn','OD1'))] = cmd.select('gln42', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+36.47,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('gln','OE1'),('rasn','CG'))] = cmd.select('gln43', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+36.13,resSelectionSubs('asn','CG',subs)))
IDSpec[(('gln','OE1'),('rasn','ND2'))] = cmd.select('gln44', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+37.16,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('gln','OE1'),('rasn','OD1'))] = cmd.select('gln45', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+34.94,resSelectionSubs('asn','OD1',subs)))
IDSpec['gln'] = cmd.select('gln',' br. gln1&br. gln2&br. gln3&br. gln4&br. gln5&br. gln6&br. gln7&br. gln8&br. gln9&br. gln10&br. gln11&br. gln12&br. gln13&br. gln14&br. gln15&br. gln16&br. gln17&br. gln18&br. gln19&br. gln20&br. gln21&br. gln22&br. gln23&br. gln24&br. gln25&br. gln26&br. gln27&br. gln28&br. gln29&br. gln30&br. gln31&br. gln32&br. gln33&br. gln34&br. gln35&br. gln36&br. gln37&br. gln38&br. gln39&br. gln40&br. gln41&br. gln42&br. gln43&br. gln44&br. gln45')
IDSpec['r_gln'] = cmd.count_atoms(resSelectionSubs('gln', subs=subs, selection=True))
cmd.delete('gln1')
cmd.delete('gln2')
cmd.delete('gln3')
cmd.delete('gln4')
cmd.delete('gln5')
cmd.delete('gln6')
cmd.delete('gln7')
cmd.delete('gln8')
cmd.delete('gln9')
cmd.delete('gln10')
cmd.delete('gln11')
cmd.delete('gln12')
cmd.delete('gln13')
cmd.delete('gln14')
cmd.delete('gln15')
cmd.delete('gln16')
cmd.delete('gln17')
cmd.delete('gln18')
cmd.delete('gln19')
cmd.delete('gln20')
cmd.delete('gln21')
cmd.delete('gln22')
cmd.delete('gln23')
cmd.delete('gln24')
cmd.delete('gln25')
cmd.delete('gln26')
cmd.delete('gln27')
cmd.delete('gln28')
cmd.delete('gln29')
cmd.delete('gln30')
cmd.delete('gln31')
cmd.delete('gln32')
cmd.delete('gln33')
cmd.delete('gln34')
cmd.delete('gln35')
cmd.delete('gln36')
cmd.delete('gln37')
cmd.delete('gln38')
cmd.delete('gln39')
cmd.delete('gln40')
cmd.delete('gln41')
cmd.delete('gln42')
cmd.delete('gln43')
cmd.delete('gln44')
cmd.delete('gln45')
IDSpec[(('asp','CG'),('sgln','CD'))] = cmd.select('asp1', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+25.61,resSelectionSubs('gln','CD',subs,selection=True)))
IDSpec[(('asp','CG'),('sgln','NE2'))] = cmd.select('asp2', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+26.83,resSelectionSubs('gln','NE2',subs,selection=True)))
IDSpec[(('asp','CG'),('sgln','OE1'))] = cmd.select('asp3', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+25.32,resSelectionSubs('gln','OE1',subs,selection=True)))
IDSpec[(('asp','OD1'),('sgln','CD'))] = cmd.select('asp4', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+25.22,resSelectionSubs('gln','CD',subs,selection=True)))
IDSpec[(('asp','OD1'),('sgln','NE2'))] = cmd.select('asp5', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+26.42,resSelectionSubs('gln','NE2',subs,selection=True)))
IDSpec[(('asp','OD1'),('sgln','OE1'))] = cmd.select('asp6', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+24.97,resSelectionSubs('gln','OE1',subs,selection=True)))
IDSpec[(('asp','OD2'),('sgln','CD'))] = cmd.select('asp7', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+25.70,resSelectionSubs('gln','CD',subs,selection=True)))
IDSpec[(('asp','OD2'),('sgln','NE2'))] = cmd.select('asp8', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+26.89,resSelectionSubs('gln','NE2',subs,selection=True)))
IDSpec[(('asp','OD2'),('sgln','OE1'))] = cmd.select('asp9', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+25.40,resSelectionSubs('gln','OE1',subs,selection=True)))
IDSpec[(('asp','CG'),('rhis','CE1'))] = cmd.select('asp10', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+8.11,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp','CG'),('rhis','ND1'))] = cmd.select('asp11', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.66,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp','CG'),('rhis','NE2'))] = cmd.select('asp12', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+9.36,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp','OD1'),('rhis','CE1'))] = cmd.select('asp13', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.20,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp','OD1'),('rhis','ND1'))] = cmd.select('asp14', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.76,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp','OD1'),('rhis','NE2'))] = cmd.select('asp15', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+10.48,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp','OD2'),('rhis','CE1'))] = cmd.select('asp16', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.11,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp','OD2'),('rhis','ND1'))] = cmd.select('asp17', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.57,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp','OD2'),('rhis','NE2'))] = cmd.select('asp18', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+8.37,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp','CG'),('rasp_i','CG'))] = cmd.select('asp19', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.73,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('asp','CG'),('rasp_i','OD1'))] = cmd.select('asp20', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.04,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('asp','CG'),('rasp_i','OD2'))] = cmd.select('asp21', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.55,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('asp','OD1'),('rasp_i','CG'))] = cmd.select('asp22', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.08,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('asp','OD1'),('rasp_i','OD1'))] = cmd.select('asp23', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.61,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('asp','OD1'),('rasp_i','OD2'))] = cmd.select('asp24', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.67,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('asp','OD2'),('rasp_i','CG'))] = cmd.select('asp25', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.64,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('asp','OD2'),('rasp_i','OD1'))] = cmd.select('asp26', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+5.85,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('asp','OD2'),('rasp_i','OD2'))] = cmd.select('asp27', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.63,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('asp','CG'),('rhis_i','CE1'))] = cmd.select('asp28', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.50,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('asp','CG'),('rhis_i','ND1'))] = cmd.select('asp29', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+8.14,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('asp','CG'),('rhis_i','NE2'))] = cmd.select('asp30', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.69,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('asp','OD1'),('rhis_i','CE1'))] = cmd.select('asp31', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.36,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('asp','OD1'),('rhis_i','ND1'))] = cmd.select('asp32', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.82,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('asp','OD1'),('rhis_i','NE2'))] = cmd.select('asp33', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.50,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('asp','OD2'),('rhis_i','CE1'))] = cmd.select('asp34', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.86,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('asp','OD2'),('rhis_i','ND1'))] = cmd.select('asp35', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.64,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('asp','OD2'),('rhis_i','NE2'))] = cmd.select('asp36', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+5.89,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('asp','CG'),('rasn','CG'))] = cmd.select('asp37', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+13.41,resSelectionSubs('asn','CG',subs)))
IDSpec[(('asp','CG'),('rasn','ND2'))] = cmd.select('asp38', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+14.59,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('asp','CG'),('rasn','OD1'))] = cmd.select('asp39', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+12.35,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('asp','OD1'),('rasn','CG'))] = cmd.select('asp40', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+14.19,resSelectionSubs('asn','CG',subs)))
IDSpec[(('asp','OD1'),('rasn','ND2'))] = cmd.select('asp41', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+15.37,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('asp','OD1'),('rasn','OD1'))] = cmd.select('asp42', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+13.18,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('asp','OD2'),('rasn','CG'))] = cmd.select('asp43', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+12.99,resSelectionSubs('asn','CG',subs)))
IDSpec[(('asp','OD2'),('rasn','ND2'))] = cmd.select('asp44', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+14.11,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('asp','OD2'),('rasn','OD1'))] = cmd.select('asp45', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.88,resSelectionSubs('asn','OD1',subs)))
IDSpec['asp'] = cmd.select('asp',' br. asp1&br. asp2&br. asp3&br. asp4&br. asp5&br. asp6&br. asp7&br. asp8&br. asp9&br. asp10&br. asp11&br. asp12&br. asp13&br. asp14&br. asp15&br. asp16&br. asp17&br. asp18&br. asp19&br. asp20&br. asp21&br. asp22&br. asp23&br. asp24&br. asp25&br. asp26&br. asp27&br. asp28&br. asp29&br. asp30&br. asp31&br. asp32&br. asp33&br. asp34&br. asp35&br. asp36&br. asp37&br. asp38&br. asp39&br. asp40&br. asp41&br. asp42&br. asp43&br. asp44&br. asp45')
IDSpec['r_asp'] = cmd.count_atoms(resSelectionSubs('asp', subs=subs, selection=True))
cmd.delete('asp1')
cmd.delete('asp2')
cmd.delete('asp3')
cmd.delete('asp4')
cmd.delete('asp5')
cmd.delete('asp6')
cmd.delete('asp7')
cmd.delete('asp8')
cmd.delete('asp9')
cmd.delete('asp10')
cmd.delete('asp11')
cmd.delete('asp12')
cmd.delete('asp13')
cmd.delete('asp14')
cmd.delete('asp15')
cmd.delete('asp16')
cmd.delete('asp17')
cmd.delete('asp18')
cmd.delete('asp19')
cmd.delete('asp20')
cmd.delete('asp21')
cmd.delete('asp22')
cmd.delete('asp23')
cmd.delete('asp24')
cmd.delete('asp25')
cmd.delete('asp26')
cmd.delete('asp27')
cmd.delete('asp28')
cmd.delete('asp29')
cmd.delete('asp30')
cmd.delete('asp31')
cmd.delete('asp32')
cmd.delete('asp33')
cmd.delete('asp34')
cmd.delete('asp35')
cmd.delete('asp36')
cmd.delete('asp37')
cmd.delete('asp38')
cmd.delete('asp39')
cmd.delete('asp40')
cmd.delete('asp41')
cmd.delete('asp42')
cmd.delete('asp43')
cmd.delete('asp44')
cmd.delete('asp45')
IDSpec[(('his','CE1'),('sgln','CD'))] = cmd.select('his1', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+29.00,resSelectionSubs('gln','CD',subs,selection=True)))
IDSpec[(('his','CE1'),('sgln','NE2'))] = cmd.select('his2', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+30.15,resSelectionSubs('gln','NE2',subs,selection=True)))
IDSpec[(('his','CE1'),('sgln','OE1'))] = cmd.select('his3', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+28.60,resSelectionSubs('gln','OE1',subs,selection=True)))
IDSpec[(('his','ND1'),('sgln','CD'))] = cmd.select('his4', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+27.71,resSelectionSubs('gln','CD',subs,selection=True)))
IDSpec[(('his','ND1'),('sgln','NE2'))] = cmd.select('his5', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+28.86,resSelectionSubs('gln','NE2',subs,selection=True)))
IDSpec[(('his','ND1'),('sgln','OE1'))] = cmd.select('his6', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+27.32,resSelectionSubs('gln','OE1',subs,selection=True)))
IDSpec[(('his','NE2'),('sgln','CD'))] = cmd.select('his7', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+29.71,resSelectionSubs('gln','CD',subs,selection=True)))
IDSpec[(('his','NE2'),('sgln','NE2'))] = cmd.select('his8', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+30.85,resSelectionSubs('gln','NE2',subs,selection=True)))
IDSpec[(('his','NE2'),('sgln','OE1'))] = cmd.select('his9', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+29.28,resSelectionSubs('gln','OE1',subs,selection=True)))
IDSpec[(('his','CE1'),('sasp','CG'))] = cmd.select('his10', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+8.11,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his','CE1'),('sasp','OD1'))] = cmd.select('his11', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+9.20,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his','CE1'),('sasp','OD2'))] = cmd.select('his12', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.11,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his','ND1'),('sasp','CG'))] = cmd.select('his13', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.66,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his','ND1'),('sasp','OD1'))] = cmd.select('his14', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+8.76,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his','ND1'),('sasp','OD2'))] = cmd.select('his15', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+6.57,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his','NE2'),('sasp','CG'))] = cmd.select('his16', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+9.36,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his','NE2'),('sasp','OD1'))] = cmd.select('his17', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+10.48,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his','NE2'),('sasp','OD2'))] = cmd.select('his18', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+8.37,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his','CE1'),('rasp_i','CG'))] = cmd.select('his19', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.83,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('his','CE1'),('rasp_i','OD1'))] = cmd.select('his20', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.65,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('his','CE1'),('rasp_i','OD2'))] = cmd.select('his21', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+8.81,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('his','ND1'),('rasp_i','CG'))] = cmd.select('his22', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+6.88,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('his','ND1'),('rasp_i','OD1'))] = cmd.select('his23', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+5.69,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('his','ND1'),('rasp_i','OD2'))] = cmd.select('his24', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.85,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('his','NE2'),('rasp_i','CG'))] = cmd.select('his25', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+8.76,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('his','NE2'),('rasp_i','OD1'))] = cmd.select('his26', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+7.63,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('his','NE2'),('rasp_i','OD2'))] = cmd.select('his27', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+9.82,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('his','CE1'),('rhis_i','CE1'))] = cmd.select('his28', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.95,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('his','CE1'),('rhis_i','ND1'))] = cmd.select('his29', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+9.23,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('his','CE1'),('rhis_i','NE2'))] = cmd.select('his30', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.39,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('his','ND1'),('rhis_i','CE1'))] = cmd.select('his31', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+6.73,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('his','ND1'),('rhis_i','ND1'))] = cmd.select('his32', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.99,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('his','ND1'),('rhis_i','NE2'))] = cmd.select('his33', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+6.15,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('his','NE2'),('rhis_i','CE1'))] = cmd.select('his34', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+8.55,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('his','NE2'),('rhis_i','ND1'))] = cmd.select('his35', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+9.84,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('his','NE2'),('rhis_i','NE2'))] = cmd.select('his36', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+8.18,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('his','CE1'),('rasn','CG'))] = cmd.select('his37', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+9.89,resSelectionSubs('asn','CG',subs)))
IDSpec[(('his','CE1'),('rasn','ND2'))] = cmd.select('his38', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+10.74,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('his','CE1'),('rasn','OD1'))] = cmd.select('his39', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+8.65,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('his','ND1'),('rasn','CG'))] = cmd.select('his40', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+11.21,resSelectionSubs('asn','CG',subs)))
IDSpec[(('his','ND1'),('rasn','ND2'))] = cmd.select('his41', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+12.07,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('his','ND1'),('rasn','OD1'))] = cmd.select('his42', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+9.96,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('his','NE2'),('rasn','CG'))] = cmd.select('his43', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+9.73,resSelectionSubs('asn','CG',subs)))
IDSpec[(('his','NE2'),('rasn','ND2'))] = cmd.select('his44', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+10.47,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('his','NE2'),('rasn','OD1'))] = cmd.select('his45', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+8.52,resSelectionSubs('asn','OD1',subs)))
IDSpec['his'] = cmd.select('his',' br. his1&br. his2&br. his3&br. his4&br. his5&br. his6&br. his7&br. his8&br. his9&br. his10&br. his11&br. his12&br. his13&br. his14&br. his15&br. his16&br. his17&br. his18&br. his19&br. his20&br. his21&br. his22&br. his23&br. his24&br. his25&br. his26&br. his27&br. his28&br. his29&br. his30&br. his31&br. his32&br. his33&br. his34&br. his35&br. his36&br. his37&br. his38&br. his39&br. his40&br. his41&br. his42&br. his43&br. his44&br. his45')
IDSpec['r_his'] = cmd.count_atoms(resSelectionSubs('his', subs=subs, selection=True))
cmd.delete('his1')
cmd.delete('his2')
cmd.delete('his3')
cmd.delete('his4')
cmd.delete('his5')
cmd.delete('his6')
cmd.delete('his7')
cmd.delete('his8')
cmd.delete('his9')
cmd.delete('his10')
cmd.delete('his11')
cmd.delete('his12')
cmd.delete('his13')
cmd.delete('his14')
cmd.delete('his15')
cmd.delete('his16')
cmd.delete('his17')
cmd.delete('his18')
cmd.delete('his19')
cmd.delete('his20')
cmd.delete('his21')
cmd.delete('his22')
cmd.delete('his23')
cmd.delete('his24')
cmd.delete('his25')
cmd.delete('his26')
cmd.delete('his27')
cmd.delete('his28')
cmd.delete('his29')
cmd.delete('his30')
cmd.delete('his31')
cmd.delete('his32')
cmd.delete('his33')
cmd.delete('his34')
cmd.delete('his35')
cmd.delete('his36')
cmd.delete('his37')
cmd.delete('his38')
cmd.delete('his39')
cmd.delete('his40')
cmd.delete('his41')
cmd.delete('his42')
cmd.delete('his43')
cmd.delete('his44')
cmd.delete('his45')
IDSpec[(('asp_i','CG'),('sgln','CD'))] = cmd.select('asp_i1', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+24.50,resSelectionSubs('gln','CD',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sgln','NE2'))] = cmd.select('asp_i2', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+25.57,resSelectionSubs('gln','NE2',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sgln','OE1'))] = cmd.select('asp_i3', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+24.29,resSelectionSubs('gln','OE1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sgln','CD'))] = cmd.select('asp_i4', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+25.17,resSelectionSubs('gln','CD',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sgln','NE2'))] = cmd.select('asp_i5', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+26.26,resSelectionSubs('gln','NE2',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sgln','OE1'))] = cmd.select('asp_i6', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+24.90,resSelectionSubs('gln','OE1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sgln','CD'))] = cmd.select('asp_i7', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+23.56,resSelectionSubs('gln','CD',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sgln','NE2'))] = cmd.select('asp_i8', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+24.63,resSelectionSubs('gln','NE2',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sgln','OE1'))] = cmd.select('asp_i9', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+23.38,resSelectionSubs('gln','OE1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasp','CG'))] = cmd.select('asp_i10', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.73,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasp','OD1'))] = cmd.select('asp_i11', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+8.08,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasp','OD2'))] = cmd.select('asp_i12', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.64,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasp','CG'))] = cmd.select('asp_i13', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.04,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasp','OD1'))] = cmd.select('asp_i14', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.61,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasp','OD2'))] = cmd.select('asp_i15', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+5.85,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasp','CG'))] = cmd.select('asp_i16', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.55,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasp','OD1'))] = cmd.select('asp_i17', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.67,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasp','OD2'))] = cmd.select('asp_i18', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.63,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asp_i','CG'),('shis','CE1'))] = cmd.select('asp_i19', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.83,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('shis','ND1'))] = cmd.select('asp_i20', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.88,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('shis','NE2'))] = cmd.select('asp_i21', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+8.76,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('shis','CE1'))] = cmd.select('asp_i22', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+6.65,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('shis','ND1'))] = cmd.select('asp_i23', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+5.69,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('shis','NE2'))] = cmd.select('asp_i24', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.63,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('shis','CE1'))] = cmd.select('asp_i25', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+8.81,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('shis','ND1'))] = cmd.select('asp_i26', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.85,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('shis','NE2'))] = cmd.select('asp_i27', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+9.82,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asp_i','CG'),('rhis_i','CE1'))] = cmd.select('asp_i28', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.28,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('asp_i','CG'),('rhis_i','ND1'))] = cmd.select('asp_i29', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.74,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('asp_i','CG'),('rhis_i','NE2'))] = cmd.select('asp_i30', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.04,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('asp_i','OD1'),('rhis_i','CE1'))] = cmd.select('asp_i31', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+6.60,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('asp_i','OD1'),('rhis_i','ND1'))] = cmd.select('asp_i32', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.30,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('asp_i','OD1'),('rhis_i','NE2'))] = cmd.select('asp_i33', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+5.35,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('asp_i','OD2'),('rhis_i','CE1'))] = cmd.select('asp_i34', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.47,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('asp_i','OD2'),('rhis_i','ND1'))] = cmd.select('asp_i35', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.70,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('asp_i','OD2'),('rhis_i','NE2'))] = cmd.select('asp_i36', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.23,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('asp_i','CG'),('rasn','CG'))] = cmd.select('asp_i37', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+14.82,resSelectionSubs('asn','CG',subs)))
IDSpec[(('asp_i','CG'),('rasn','ND2'))] = cmd.select('asp_i38', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+15.61,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('asp_i','CG'),('rasn','OD1'))] = cmd.select('asp_i39', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+13.60,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('asp_i','OD1'),('rasn','CG'))] = cmd.select('asp_i40', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+13.83,resSelectionSubs('asn','CG',subs)))
IDSpec[(('asp_i','OD1'),('rasn','ND2'))] = cmd.select('asp_i41', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+14.66,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('asp_i','OD1'),('rasn','OD1'))] = cmd.select('asp_i42', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+12.60,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('asp_i','OD2'),('rasn','CG'))] = cmd.select('asp_i43', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+15.69,resSelectionSubs('asn','CG',subs)))
IDSpec[(('asp_i','OD2'),('rasn','ND2'))] = cmd.select('asp_i44', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+16.53,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('asp_i','OD2'),('rasn','OD1'))] = cmd.select('asp_i45', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+14.49,resSelectionSubs('asn','OD1',subs)))
IDSpec['asp_i'] = cmd.select('asp_i',' br. asp_i1&br. asp_i2&br. asp_i3&br. asp_i4&br. asp_i5&br. asp_i6&br. asp_i7&br. asp_i8&br. asp_i9&br. asp_i10&br. asp_i11&br. asp_i12&br. asp_i13&br. asp_i14&br. asp_i15&br. asp_i16&br. asp_i17&br. asp_i18&br. asp_i19&br. asp_i20&br. asp_i21&br. asp_i22&br. asp_i23&br. asp_i24&br. asp_i25&br. asp_i26&br. asp_i27&br. asp_i28&br. asp_i29&br. asp_i30&br. asp_i31&br. asp_i32&br. asp_i33&br. asp_i34&br. asp_i35&br. asp_i36&br. asp_i37&br. asp_i38&br. asp_i39&br. asp_i40&br. asp_i41&br. asp_i42&br. asp_i43&br. asp_i44&br. asp_i45')
IDSpec['r_asp_i'] = cmd.count_atoms(resSelectionSubs('asp_i', subs=subs, selection=True))
cmd.delete('asp_i1')
cmd.delete('asp_i2')
cmd.delete('asp_i3')
cmd.delete('asp_i4')
cmd.delete('asp_i5')
cmd.delete('asp_i6')
cmd.delete('asp_i7')
cmd.delete('asp_i8')
cmd.delete('asp_i9')
cmd.delete('asp_i10')
cmd.delete('asp_i11')
cmd.delete('asp_i12')
cmd.delete('asp_i13')
cmd.delete('asp_i14')
cmd.delete('asp_i15')
cmd.delete('asp_i16')
cmd.delete('asp_i17')
cmd.delete('asp_i18')
cmd.delete('asp_i19')
cmd.delete('asp_i20')
cmd.delete('asp_i21')
cmd.delete('asp_i22')
cmd.delete('asp_i23')
cmd.delete('asp_i24')
cmd.delete('asp_i25')
cmd.delete('asp_i26')
cmd.delete('asp_i27')
cmd.delete('asp_i28')
cmd.delete('asp_i29')
cmd.delete('asp_i30')
cmd.delete('asp_i31')
cmd.delete('asp_i32')
cmd.delete('asp_i33')
cmd.delete('asp_i34')
cmd.delete('asp_i35')
cmd.delete('asp_i36')
cmd.delete('asp_i37')
cmd.delete('asp_i38')
cmd.delete('asp_i39')
cmd.delete('asp_i40')
cmd.delete('asp_i41')
cmd.delete('asp_i42')
cmd.delete('asp_i43')
cmd.delete('asp_i44')
cmd.delete('asp_i45')
IDSpec[(('his_i','CE1'),('sgln','CD'))] = cmd.select('his_i1', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+23.42,resSelectionSubs('gln','CD',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sgln','NE2'))] = cmd.select('his_i2', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+24.61,resSelectionSubs('gln','NE2',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sgln','OE1'))] = cmd.select('his_i3', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+22.93,resSelectionSubs('gln','OE1',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sgln','CD'))] = cmd.select('his_i4', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+22.11,resSelectionSubs('gln','CD',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sgln','NE2'))] = cmd.select('his_i5', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+23.31,resSelectionSubs('gln','NE2',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sgln','OE1'))] = cmd.select('his_i6', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+21.62,resSelectionSubs('gln','OE1',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sgln','CD'))] = cmd.select('his_i7', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+23.67,resSelectionSubs('gln','CD',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sgln','NE2'))] = cmd.select('his_i8', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+24.84,resSelectionSubs('gln','NE2',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sgln','OE1'))] = cmd.select('his_i9', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+23.25,resSelectionSubs('gln','OE1',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sasp','CG'))] = cmd.select('his_i10', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.50,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sasp','OD1'))] = cmd.select('his_i11', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+8.36,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sasp','OD2'))] = cmd.select('his_i12', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.86,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sasp','CG'))] = cmd.select('his_i13', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+8.14,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sasp','OD1'))] = cmd.select('his_i14', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+8.82,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sasp','OD2'))] = cmd.select('his_i15', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.64,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sasp','CG'))] = cmd.select('his_i16', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.69,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sasp','OD1'))] = cmd.select('his_i17', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+7.50,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sasp','OD2'))] = cmd.select('his_i18', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+5.89,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his_i','CE1'),('shis','CE1'))] = cmd.select('his_i19', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.95,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('his_i','CE1'),('shis','ND1'))] = cmd.select('his_i20', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.73,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('his_i','CE1'),('shis','NE2'))] = cmd.select('his_i21', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+8.55,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('his_i','ND1'),('shis','CE1'))] = cmd.select('his_i22', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+9.23,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('his_i','ND1'),('shis','ND1'))] = cmd.select('his_i23', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.99,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('his_i','ND1'),('shis','NE2'))] = cmd.select('his_i24', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+9.84,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('his_i','NE2'),('shis','CE1'))] = cmd.select('his_i25', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+7.39,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('his_i','NE2'),('shis','ND1'))] = cmd.select('his_i26', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.15,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('his_i','NE2'),('shis','NE2'))] = cmd.select('his_i27', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+8.18,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sasp_i','CG'))] = cmd.select('his_i28', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.28,resSelectionSubs('asp_i','CG',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sasp_i','OD1'))] = cmd.select('his_i29', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.60,resSelectionSubs('asp_i','OD1',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sasp_i','OD2'))] = cmd.select('his_i30', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.47,resSelectionSubs('asp_i','OD2',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sasp_i','CG'))] = cmd.select('his_i31', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.74,resSelectionSubs('asp_i','CG',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sasp_i','OD1'))] = cmd.select('his_i32', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.30,resSelectionSubs('asp_i','OD1',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sasp_i','OD2'))] = cmd.select('his_i33', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.70,resSelectionSubs('asp_i','OD2',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sasp_i','CG'))] = cmd.select('his_i34', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.04,resSelectionSubs('asp_i','CG',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sasp_i','OD1'))] = cmd.select('his_i35', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+5.35,resSelectionSubs('asp_i','OD1',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sasp_i','OD2'))] = cmd.select('his_i36', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.23,resSelectionSubs('asp_i','OD2',subs,selection=True)))
IDSpec[(('his_i','CE1'),('rasn','CG'))] = cmd.select('his_i37', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+15.51,resSelectionSubs('asn','CG',subs)))
IDSpec[(('his_i','CE1'),('rasn','ND2'))] = cmd.select('his_i38', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+16.51,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('his_i','CE1'),('rasn','OD1'))] = cmd.select('his_i39', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+14.31,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('his_i','ND1'),('rasn','CG'))] = cmd.select('his_i40', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+16.81,resSelectionSubs('asn','CG',subs)))
IDSpec[(('his_i','ND1'),('rasn','ND2'))] = cmd.select('his_i41', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+17.81,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('his_i','ND1'),('rasn','OD1'))] = cmd.select('his_i42', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+15.61,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('his_i','NE2'),('rasn','CG'))] = cmd.select('his_i43', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+14.99,resSelectionSubs('asn','CG',subs)))
IDSpec[(('his_i','NE2'),('rasn','ND2'))] = cmd.select('his_i44', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+15.97,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('his_i','NE2'),('rasn','OD1'))] = cmd.select('his_i45', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+13.77,resSelectionSubs('asn','OD1',subs)))
IDSpec['his_i'] = cmd.select('his_i',' br. his_i1&br. his_i2&br. his_i3&br. his_i4&br. his_i5&br. his_i6&br. his_i7&br. his_i8&br. his_i9&br. his_i10&br. his_i11&br. his_i12&br. his_i13&br. his_i14&br. his_i15&br. his_i16&br. his_i17&br. his_i18&br. his_i19&br. his_i20&br. his_i21&br. his_i22&br. his_i23&br. his_i24&br. his_i25&br. his_i26&br. his_i27&br. his_i28&br. his_i29&br. his_i30&br. his_i31&br. his_i32&br. his_i33&br. his_i34&br. his_i35&br. his_i36&br. his_i37&br. his_i38&br. his_i39&br. his_i40&br. his_i41&br. his_i42&br. his_i43&br. his_i44&br. his_i45')
IDSpec['r_his_i'] = cmd.count_atoms(resSelectionSubs('his_i', subs=subs, selection=True))
cmd.delete('his_i1')
cmd.delete('his_i2')
cmd.delete('his_i3')
cmd.delete('his_i4')
cmd.delete('his_i5')
cmd.delete('his_i6')
cmd.delete('his_i7')
cmd.delete('his_i8')
cmd.delete('his_i9')
cmd.delete('his_i10')
cmd.delete('his_i11')
cmd.delete('his_i12')
cmd.delete('his_i13')
cmd.delete('his_i14')
cmd.delete('his_i15')
cmd.delete('his_i16')
cmd.delete('his_i17')
cmd.delete('his_i18')
cmd.delete('his_i19')
cmd.delete('his_i20')
cmd.delete('his_i21')
cmd.delete('his_i22')
cmd.delete('his_i23')
cmd.delete('his_i24')
cmd.delete('his_i25')
cmd.delete('his_i26')
cmd.delete('his_i27')
cmd.delete('his_i28')
cmd.delete('his_i29')
cmd.delete('his_i30')
cmd.delete('his_i31')
cmd.delete('his_i32')
cmd.delete('his_i33')
cmd.delete('his_i34')
cmd.delete('his_i35')
cmd.delete('his_i36')
cmd.delete('his_i37')
cmd.delete('his_i38')
cmd.delete('his_i39')
cmd.delete('his_i40')
cmd.delete('his_i41')
cmd.delete('his_i42')
cmd.delete('his_i43')
cmd.delete('his_i44')
cmd.delete('his_i45')
IDSpec[(('asn','CG'),('sgln','CD'))] = cmd.select('asn1', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+36.49,resSelectionSubs('gln','CD',subs,selection=True)))
IDSpec[(('asn','CG'),('sgln','NE2'))] = cmd.select('asn2', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+37.67,resSelectionSubs('gln','NE2',subs,selection=True)))
IDSpec[(('asn','CG'),('sgln','OE1'))] = cmd.select('asn3', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+36.13,resSelectionSubs('gln','OE1',subs,selection=True)))
IDSpec[(('asn','ND2'),('sgln','CD'))] = cmd.select('asn4', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+37.51,resSelectionSubs('gln','CD',subs,selection=True)))
IDSpec[(('asn','ND2'),('sgln','NE2'))] = cmd.select('asn5', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+38.68,resSelectionSubs('gln','NE2',subs,selection=True)))
IDSpec[(('asn','ND2'),('sgln','OE1'))] = cmd.select('asn6', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+37.16,resSelectionSubs('gln','OE1',subs,selection=True)))
IDSpec[(('asn','OD1'),('sgln','CD'))] = cmd.select('asn7', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+35.30,resSelectionSubs('gln','CD',subs,selection=True)))
IDSpec[(('asn','OD1'),('sgln','NE2'))] = cmd.select('asn8', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+36.47,resSelectionSubs('gln','NE2',subs,selection=True)))
IDSpec[(('asn','OD1'),('sgln','OE1'))] = cmd.select('asn9', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+34.94,resSelectionSubs('gln','OE1',subs,selection=True)))
IDSpec[(('asn','CG'),('sasp','CG'))] = cmd.select('asn10', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+13.41,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asn','CG'),('sasp','OD1'))] = cmd.select('asn11', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+14.19,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asn','CG'),('sasp','OD2'))] = cmd.select('asn12', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+12.99,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asn','ND2'),('sasp','CG'))] = cmd.select('asn13', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+14.59,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asn','ND2'),('sasp','OD1'))] = cmd.select('asn14', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+15.37,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asn','ND2'),('sasp','OD2'))] = cmd.select('asn15', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+14.11,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asn','OD1'),('sasp','CG'))] = cmd.select('asn16', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+12.35,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asn','OD1'),('sasp','OD1'))] = cmd.select('asn17', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+13.18,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asn','OD1'),('sasp','OD2'))] = cmd.select('asn18', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+11.88,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asn','CG'),('shis','CE1'))] = cmd.select('asn19', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+9.89,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asn','CG'),('shis','ND1'))] = cmd.select('asn20', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+11.21,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asn','CG'),('shis','NE2'))] = cmd.select('asn21', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+9.73,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asn','ND2'),('shis','CE1'))] = cmd.select('asn22', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+10.74,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asn','ND2'),('shis','ND1'))] = cmd.select('asn23', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+12.07,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asn','ND2'),('shis','NE2'))] = cmd.select('asn24', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+10.47,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asn','OD1'),('shis','CE1'))] = cmd.select('asn25', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+8.65,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asn','OD1'),('shis','ND1'))] = cmd.select('asn26', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+9.96,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asn','OD1'),('shis','NE2'))] = cmd.select('asn27', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+8.52,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asn','CG'),('sasp_i','CG'))] = cmd.select('asn28', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+14.82,resSelectionSubs('asp_i','CG',subs,selection=True)))
IDSpec[(('asn','CG'),('sasp_i','OD1'))] = cmd.select('asn29', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+13.83,resSelectionSubs('asp_i','OD1',subs,selection=True)))
IDSpec[(('asn','CG'),('sasp_i','OD2'))] = cmd.select('asn30', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+15.69,resSelectionSubs('asp_i','OD2',subs,selection=True)))
IDSpec[(('asn','ND2'),('sasp_i','CG'))] = cmd.select('asn31', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+15.61,resSelectionSubs('asp_i','CG',subs,selection=True)))
IDSpec[(('asn','ND2'),('sasp_i','OD1'))] = cmd.select('asn32', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+14.66,resSelectionSubs('asp_i','OD1',subs,selection=True)))
IDSpec[(('asn','ND2'),('sasp_i','OD2'))] = cmd.select('asn33', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+16.53,resSelectionSubs('asp_i','OD2',subs,selection=True)))
IDSpec[(('asn','OD1'),('sasp_i','CG'))] = cmd.select('asn34', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+13.60,resSelectionSubs('asp_i','CG',subs,selection=True)))
IDSpec[(('asn','OD1'),('sasp_i','OD1'))] = cmd.select('asn35', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+12.60,resSelectionSubs('asp_i','OD1',subs,selection=True)))
IDSpec[(('asn','OD1'),('sasp_i','OD2'))] = cmd.select('asn36', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+14.49,resSelectionSubs('asp_i','OD2',subs,selection=True)))
IDSpec[(('asn','CG'),('shis_i','CE1'))] = cmd.select('asn37', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+15.51,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('asn','CG'),('shis_i','ND1'))] = cmd.select('asn38', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+16.81,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('asn','CG'),('shis_i','NE2'))] = cmd.select('asn39', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+14.99,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('asn','ND2'),('shis_i','CE1'))] = cmd.select('asn40', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+16.51,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('asn','ND2'),('shis_i','ND1'))] = cmd.select('asn41', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+17.81,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('asn','ND2'),('shis_i','NE2'))] = cmd.select('asn42', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+15.97,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('asn','OD1'),('shis_i','CE1'))] = cmd.select('asn43', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+14.31,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('asn','OD1'),('shis_i','ND1'))] = cmd.select('asn44', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+15.61,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('asn','OD1'),('shis_i','NE2'))] = cmd.select('asn45', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+13.77,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec['asn'] = cmd.select('asn',' br. asn1&br. asn2&br. asn3&br. asn4&br. asn5&br. asn6&br. asn7&br. asn8&br. asn9&br. asn10&br. asn11&br. asn12&br. asn13&br. asn14&br. asn15&br. asn16&br. asn17&br. asn18&br. asn19&br. asn20&br. asn21&br. asn22&br. asn23&br. asn24&br. asn25&br. asn26&br. asn27&br. asn28&br. asn29&br. asn30&br. asn31&br. asn32&br. asn33&br. asn34&br. asn35&br. asn36&br. asn37&br. asn38&br. asn39&br. asn40&br. asn41&br. asn42&br. asn43&br. asn44&br. asn45')
IDSpec['r_asn'] = cmd.count_atoms(resSelectionSubs('asn', subs=subs, selection=True))
cmd.delete('asn1')
cmd.delete('asn2')
cmd.delete('asn3')
cmd.delete('asn4')
cmd.delete('asn5')
cmd.delete('asn6')
cmd.delete('asn7')
cmd.delete('asn8')
cmd.delete('asn9')
cmd.delete('asn10')
cmd.delete('asn11')
cmd.delete('asn12')
cmd.delete('asn13')
cmd.delete('asn14')
cmd.delete('asn15')
cmd.delete('asn16')
cmd.delete('asn17')
cmd.delete('asn18')
cmd.delete('asn19')
cmd.delete('asn20')
cmd.delete('asn21')
cmd.delete('asn22')
cmd.delete('asn23')
cmd.delete('asn24')
cmd.delete('asn25')
cmd.delete('asn26')
cmd.delete('asn27')
cmd.delete('asn28')
cmd.delete('asn29')
cmd.delete('asn30')
cmd.delete('asn31')
cmd.delete('asn32')
cmd.delete('asn33')
cmd.delete('asn34')
cmd.delete('asn35')
cmd.delete('asn36')
cmd.delete('asn37')
cmd.delete('asn38')
cmd.delete('asn39')
cmd.delete('asn40')
cmd.delete('asn41')
cmd.delete('asn42')
cmd.delete('asn43')
cmd.delete('asn44')
cmd.delete('asn45')
IDSpec['S_1rpx_5_1_3_1'] = cmd.select('S_1rpx_5_1_3_1', 'gln|asp|his|asp_i|his_i|asn')
cmd.delete('gln')
cmd.delete('asp')
cmd.delete('his')
cmd.delete('asp_i')
cmd.delete('his_i')
cmd.delete('asn')
