'''
FUNC:S_1vle_1_97_1_2
PDB:1vle
EC:1.97.1.2
RESI:his,his,trp,asp,ser,trp,tyr
LOCI:w-144,145,147,174,175,176,404;
'''
IDSpec[(('ser','CA'),('rtyr','CE1'))] = cmd.select('ser1', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+14.15,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('ser','CA'),('rtyr','CZ'))] = cmd.select('ser2', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+13.67,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('ser','CA'),('rtyr','OH'))] = cmd.select('ser3', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+12.33,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('ser','CB'),('rtyr','CE1'))] = cmd.select('ser4', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+12.72,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('ser','CB'),('rtyr','CZ'))] = cmd.select('ser5', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+12.19,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('ser','CB'),('rtyr','OH'))] = cmd.select('ser6', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+10.86,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('ser','OG'),('rtyr','CE1'))] = cmd.select('ser7', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+11.95,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('ser','OG'),('rtyr','CZ'))] = cmd.select('ser8', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+11.39,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('ser','OG'),('rtyr','OH'))] = cmd.select('ser9', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+10.04,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('ser','CA'),('rasp','CG'))] = cmd.select('ser10', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+6.29,resSelectionSubs('asp','CG',subs)))
IDSpec[(('ser','CA'),('rasp','OD1'))] = cmd.select('ser11', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+5.49,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('ser','CA'),('rasp','OD2'))] = cmd.select('ser12', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+7.44,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('ser','CB'),('rasp','CG'))] = cmd.select('ser13', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+6.57,resSelectionSubs('asp','CG',subs)))
IDSpec[(('ser','CB'),('rasp','OD1'))] = cmd.select('ser14', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+5.50,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('ser','CB'),('rasp','OD2'))] = cmd.select('ser15', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+7.55,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('ser','OG'),('rasp','CG'))] = cmd.select('ser16', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+5.99,resSelectionSubs('asp','CG',subs)))
IDSpec[(('ser','OG'),('rasp','OD1'))] = cmd.select('ser17', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+5.00,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('ser','OG'),('rasp','OD2'))] = cmd.select('ser18', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+6.74,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('ser','CA'),('rhis','CE1'))] = cmd.select('ser19', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+9.99,resSelectionSubs('his','CE1',subs)))
IDSpec[(('ser','CA'),('rhis','ND1'))] = cmd.select('ser20', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+11.21,resSelectionSubs('his','ND1',subs)))
IDSpec[(('ser','CA'),('rhis','NE2'))] = cmd.select('ser21', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+9.16,resSelectionSubs('his','NE2',subs)))
IDSpec[(('ser','CB'),('rhis','CE1'))] = cmd.select('ser22', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+8.80,resSelectionSubs('his','CE1',subs)))
IDSpec[(('ser','CB'),('rhis','ND1'))] = cmd.select('ser23', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+10.07,resSelectionSubs('his','ND1',subs)))
IDSpec[(('ser','CB'),('rhis','NE2'))] = cmd.select('ser24', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+8.12,resSelectionSubs('his','NE2',subs)))
IDSpec[(('ser','OG'),('rhis','CE1'))] = cmd.select('ser25', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+7.52,resSelectionSubs('his','CE1',subs)))
IDSpec[(('ser','OG'),('rhis','ND1'))] = cmd.select('ser26', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+8.75,resSelectionSubs('his','ND1',subs)))
IDSpec[(('ser','OG'),('rhis','NE2'))] = cmd.select('ser27', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+6.74,resSelectionSubs('his','NE2',subs)))
IDSpec[(('ser','CA'),('rtrp','CE2'))] = cmd.select('ser28', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+7.15,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('ser','CA'),('rtrp','CZ2'))] = cmd.select('ser29', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+7.57,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('ser','CA'),('rtrp','NE1'))] = cmd.select('ser30', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+7.84,resSelectionSubs('trp','NE1',subs)))
IDSpec[(('ser','CB'),('rtrp','CE2'))] = cmd.select('ser31', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+6.28,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('ser','CB'),('rtrp','CZ2'))] = cmd.select('ser32', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+6.42,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('ser','CB'),('rtrp','NE1'))] = cmd.select('ser33', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+7.10,resSelectionSubs('trp','NE1',subs)))
IDSpec[(('ser','OG'),('rtrp','CE2'))] = cmd.select('ser34', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+7.27,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('ser','OG'),('rtrp','CZ2'))] = cmd.select('ser35', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+7.05,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('ser','OG'),('rtrp','NE1'))] = cmd.select('ser36', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+8.23,resSelectionSubs('trp','NE1',subs)))
IDSpec[(('ser','CA'),('rhis_i','CE1'))] = cmd.select('ser37', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+20.47,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('ser','CA'),('rhis_i','ND1'))] = cmd.select('ser38', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+19.36,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('ser','CA'),('rhis_i','NE2'))] = cmd.select('ser39', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+20.28,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('ser','CB'),('rhis_i','CE1'))] = cmd.select('ser40', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+19.38,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('ser','CB'),('rhis_i','ND1'))] = cmd.select('ser41', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+18.24,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('ser','CB'),('rhis_i','NE2'))] = cmd.select('ser42', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+19.26,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('ser','OG'),('rhis_i','CE1'))] = cmd.select('ser43', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+18.12,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('ser','OG'),('rhis_i','ND1'))] = cmd.select('ser44', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+16.98,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('ser','OG'),('rhis_i','NE2'))] = cmd.select('ser45', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+18.00,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('ser','CA'),('rtrp_i','CE2'))] = cmd.select('ser46', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+18.76,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('ser','CA'),('rtrp_i','CZ2'))] = cmd.select('ser47', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+17.78,resSelectionSubs('trp_i','CZ2',subs)))
IDSpec[(('ser','CA'),('rtrp_i','NE1'))] = cmd.select('ser48', '%s w. %s of %s'%(resSelectionSubs('ser','CA',subs),d+20.10,resSelectionSubs('trp_i','NE1',subs)))
IDSpec[(('ser','CB'),('rtrp_i','CE2'))] = cmd.select('ser49', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+17.31,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('ser','CB'),('rtrp_i','CZ2'))] = cmd.select('ser50', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+16.31,resSelectionSubs('trp_i','CZ2',subs)))
cmd.select('ser50',' br. ser1&br. ser2&br. ser3&br. ser4&br. ser5&br. ser6&br. ser7&br. ser8&br. ser9&br. ser10&br. ser11&br. ser12&br. ser13&br. ser14&br. ser15&br. ser16&br. ser17&br. ser18&br. ser19&br. ser20&br. ser21&br. ser22&br. ser23&br. ser24&br. ser25&br. ser26&br. ser27&br. ser28&br. ser29&br. ser30&br. ser31&br. ser32&br. ser33&br. ser34&br. ser35&br. ser36&br. ser37&br. ser38&br. ser39&br. ser40&br. ser41&br. ser42&br. ser43&br. ser44&br. ser45&br. ser46&br. ser47&br. ser48&br. ser49&br. ser50')
cmd.delete('ser1')
cmd.delete('ser2')
cmd.delete('ser3')
cmd.delete('ser4')
cmd.delete('ser5')
cmd.delete('ser6')
cmd.delete('ser7')
cmd.delete('ser8')
cmd.delete('ser9')
cmd.delete('ser10')
cmd.delete('ser11')
cmd.delete('ser12')
cmd.delete('ser13')
cmd.delete('ser14')
cmd.delete('ser15')
cmd.delete('ser16')
cmd.delete('ser17')
cmd.delete('ser18')
cmd.delete('ser19')
cmd.delete('ser20')
cmd.delete('ser21')
cmd.delete('ser22')
cmd.delete('ser23')
cmd.delete('ser24')
cmd.delete('ser25')
cmd.delete('ser26')
cmd.delete('ser27')
cmd.delete('ser28')
cmd.delete('ser29')
cmd.delete('ser30')
cmd.delete('ser31')
cmd.delete('ser32')
cmd.delete('ser33')
cmd.delete('ser34')
cmd.delete('ser35')
cmd.delete('ser36')
cmd.delete('ser37')
cmd.delete('ser38')
cmd.delete('ser39')
cmd.delete('ser40')
cmd.delete('ser41')
cmd.delete('ser42')
cmd.delete('ser43')
cmd.delete('ser44')
cmd.delete('ser45')
cmd.delete('ser46')
cmd.delete('ser47')
cmd.delete('ser48')
cmd.delete('ser49')
IDSpec[(('ser','CB'),('rtrp_i','NE1'))] = cmd.select('ser51', '%s w. %s of %s'%(resSelectionSubs('ser','CB',subs),d+18.66,resSelectionSubs('trp_i','NE1',subs)))
IDSpec[(('ser','OG'),('rtrp_i','CE2'))] = cmd.select('ser52', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+16.40,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('ser','OG'),('rtrp_i','CZ2'))] = cmd.select('ser53', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+15.47,resSelectionSubs('trp_i','CZ2',subs)))
IDSpec[(('ser','OG'),('rtrp_i','NE1'))] = cmd.select('ser54', '%s w. %s of %s'%(resSelectionSubs('ser','OG',subs),d+17.75,resSelectionSubs('trp_i','NE1',subs)))
IDSpec['ser'] = cmd.select('ser',' ser50&br. ser51&br. ser52&br. ser53&br. ser54')
IDSpec['r_ser'] = cmd.count_atoms(resSelectionSubs('ser', subs=subs, selection=True))
cmd.delete('ser50')
cmd.delete('ser51')
cmd.delete('ser52')
cmd.delete('ser53')
cmd.delete('ser54')
IDSpec[(('tyr','CE1'),('sser','CA'))] = cmd.select('tyr1', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+14.15,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('tyr','CE1'),('sser','CB'))] = cmd.select('tyr2', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+12.72,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('tyr','CE1'),('sser','OG'))] = cmd.select('tyr3', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+11.95,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sser','CA'))] = cmd.select('tyr4', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+13.67,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sser','CB'))] = cmd.select('tyr5', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+12.19,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sser','OG'))] = cmd.select('tyr6', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+11.39,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('tyr','OH'),('sser','CA'))] = cmd.select('tyr7', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+12.33,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('tyr','OH'),('sser','CB'))] = cmd.select('tyr8', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+10.86,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('tyr','OH'),('sser','OG'))] = cmd.select('tyr9', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+10.04,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('tyr','CE1'),('rasp','CG'))] = cmd.select('tyr10', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+13.38,resSelectionSubs('asp','CG',subs)))
IDSpec[(('tyr','CE1'),('rasp','OD1'))] = cmd.select('tyr11', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+12.63,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('tyr','CE1'),('rasp','OD2'))] = cmd.select('tyr12', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+13.05,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('tyr','CZ'),('rasp','CG'))] = cmd.select('tyr13', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+13.21,resSelectionSubs('asp','CG',subs)))
IDSpec[(('tyr','CZ'),('rasp','OD1'))] = cmd.select('tyr14', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+12.42,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('tyr','CZ'),('rasp','OD2'))] = cmd.select('tyr15', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+12.94,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('tyr','OH'),('rasp','CG'))] = cmd.select('tyr16', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+12.02,resSelectionSubs('asp','CG',subs)))
IDSpec[(('tyr','OH'),('rasp','OD1'))] = cmd.select('tyr17', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+11.20,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('tyr','OH'),('rasp','OD2'))] = cmd.select('tyr18', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+11.82,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('tyr','CE1'),('rhis','CE1'))] = cmd.select('tyr19', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+8.23,resSelectionSubs('his','CE1',subs)))
IDSpec[(('tyr','CE1'),('rhis','ND1'))] = cmd.select('tyr20', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+8.15,resSelectionSubs('his','ND1',subs)))
IDSpec[(('tyr','CE1'),('rhis','NE2'))] = cmd.select('tyr21', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+9.33,resSelectionSubs('his','NE2',subs)))
IDSpec[(('tyr','CZ'),('rhis','CE1'))] = cmd.select('tyr22', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+7.42,resSelectionSubs('his','CE1',subs)))
IDSpec[(('tyr','CZ'),('rhis','ND1'))] = cmd.select('tyr23', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+7.37,resSelectionSubs('his','ND1',subs)))
IDSpec[(('tyr','CZ'),('rhis','NE2'))] = cmd.select('tyr24', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+8.63,resSelectionSubs('his','NE2',subs)))
IDSpec[(('tyr','OH'),('rhis','CE1'))] = cmd.select('tyr25', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+6.26,resSelectionSubs('his','CE1',subs)))
IDSpec[(('tyr','OH'),('rhis','ND1'))] = cmd.select('tyr26', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+6.45,resSelectionSubs('his','ND1',subs)))
IDSpec[(('tyr','OH'),('rhis','NE2'))] = cmd.select('tyr27', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+7.44,resSelectionSubs('his','NE2',subs)))
IDSpec[(('tyr','CE1'),('rtrp','CE2'))] = cmd.select('tyr28', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+12.21,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('tyr','CE1'),('rtrp','CZ2'))] = cmd.select('tyr29', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10.81,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('tyr','CE1'),('rtrp','NE1'))] = cmd.select('tyr30', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+13.12,resSelectionSubs('trp','NE1',subs)))
IDSpec[(('tyr','CZ'),('rtrp','CE2'))] = cmd.select('tyr31', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+11.96,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('tyr','CZ'),('rtrp','CZ2'))] = cmd.select('tyr32', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+10.59,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('tyr','CZ'),('rtrp','NE1'))] = cmd.select('tyr33', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+12.81,resSelectionSubs('trp','NE1',subs)))
IDSpec[(('tyr','OH'),('rtrp','CE2'))] = cmd.select('tyr34', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+10.88,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('tyr','OH'),('rtrp','CZ2'))] = cmd.select('tyr35', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+9.54,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('tyr','OH'),('rtrp','NE1'))] = cmd.select('tyr36', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+11.76,resSelectionSubs('trp','NE1',subs)))
IDSpec[(('tyr','CE1'),('rhis_i','CE1'))] = cmd.select('tyr37', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+11.28,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('tyr','CE1'),('rhis_i','ND1'))] = cmd.select('tyr38', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10.33,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('tyr','CE1'),('rhis_i','NE2'))] = cmd.select('tyr39', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+11.62,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('tyr','CZ'),('rhis_i','CE1'))] = cmd.select('tyr40', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+11.65,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('tyr','CZ'),('rhis_i','ND1'))] = cmd.select('tyr41', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+10.57,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('tyr','CZ'),('rhis_i','NE2'))] = cmd.select('tyr42', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+12.07,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('tyr','OH'),('rhis_i','CE1'))] = cmd.select('tyr43', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+12.35,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('tyr','OH'),('rhis_i','ND1'))] = cmd.select('tyr44', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+11.22,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('tyr','OH'),('rhis_i','NE2'))] = cmd.select('tyr45', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+12.69,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('tyr','CE1'),('rtrp_i','CE2'))] = cmd.select('tyr46', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+9.67,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('tyr','CE1'),('rtrp_i','CZ2'))] = cmd.select('tyr47', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+8.91,resSelectionSubs('trp_i','CZ2',subs)))
IDSpec[(('tyr','CE1'),('rtrp_i','NE1'))] = cmd.select('tyr48', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10.86,resSelectionSubs('trp_i','NE1',subs)))
IDSpec[(('tyr','CZ'),('rtrp_i','CE2'))] = cmd.select('tyr49', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+8.82,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('tyr','CZ'),('rtrp_i','CZ2'))] = cmd.select('tyr50', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+7.96,resSelectionSubs('trp_i','CZ2',subs)))
cmd.select('tyr50',' br. tyr1&br. tyr2&br. tyr3&br. tyr4&br. tyr5&br. tyr6&br. tyr7&br. tyr8&br. tyr9&br. tyr10&br. tyr11&br. tyr12&br. tyr13&br. tyr14&br. tyr15&br. tyr16&br. tyr17&br. tyr18&br. tyr19&br. tyr20&br. tyr21&br. tyr22&br. tyr23&br. tyr24&br. tyr25&br. tyr26&br. tyr27&br. tyr28&br. tyr29&br. tyr30&br. tyr31&br. tyr32&br. tyr33&br. tyr34&br. tyr35&br. tyr36&br. tyr37&br. tyr38&br. tyr39&br. tyr40&br. tyr41&br. tyr42&br. tyr43&br. tyr44&br. tyr45&br. tyr46&br. tyr47&br. tyr48&br. tyr49&br. tyr50')
cmd.delete('tyr1')
cmd.delete('tyr2')
cmd.delete('tyr3')
cmd.delete('tyr4')
cmd.delete('tyr5')
cmd.delete('tyr6')
cmd.delete('tyr7')
cmd.delete('tyr8')
cmd.delete('tyr9')
cmd.delete('tyr10')
cmd.delete('tyr11')
cmd.delete('tyr12')
cmd.delete('tyr13')
cmd.delete('tyr14')
cmd.delete('tyr15')
cmd.delete('tyr16')
cmd.delete('tyr17')
cmd.delete('tyr18')
cmd.delete('tyr19')
cmd.delete('tyr20')
cmd.delete('tyr21')
cmd.delete('tyr22')
cmd.delete('tyr23')
cmd.delete('tyr24')
cmd.delete('tyr25')
cmd.delete('tyr26')
cmd.delete('tyr27')
cmd.delete('tyr28')
cmd.delete('tyr29')
cmd.delete('tyr30')
cmd.delete('tyr31')
cmd.delete('tyr32')
cmd.delete('tyr33')
cmd.delete('tyr34')
cmd.delete('tyr35')
cmd.delete('tyr36')
cmd.delete('tyr37')
cmd.delete('tyr38')
cmd.delete('tyr39')
cmd.delete('tyr40')
cmd.delete('tyr41')
cmd.delete('tyr42')
cmd.delete('tyr43')
cmd.delete('tyr44')
cmd.delete('tyr45')
cmd.delete('tyr46')
cmd.delete('tyr47')
cmd.delete('tyr48')
cmd.delete('tyr49')
IDSpec[(('tyr','CZ'),('rtrp_i','NE1'))] = cmd.select('tyr51', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+10.09,resSelectionSubs('trp_i','NE1',subs)))
IDSpec[(('tyr','OH'),('rtrp_i','CE2'))] = cmd.select('tyr52', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+9.51,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('tyr','OH'),('rtrp_i','CZ2'))] = cmd.select('tyr53', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+8.58,resSelectionSubs('trp_i','CZ2',subs)))
IDSpec[(('tyr','OH'),('rtrp_i','NE1'))] = cmd.select('tyr54', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+10.83,resSelectionSubs('trp_i','NE1',subs)))
IDSpec['tyr'] = cmd.select('tyr',' tyr50&br. tyr51&br. tyr52&br. tyr53&br. tyr54')
IDSpec['r_tyr'] = cmd.count_atoms(resSelectionSubs('tyr', subs=subs, selection=True))
cmd.delete('tyr50')
cmd.delete('tyr51')
cmd.delete('tyr52')
cmd.delete('tyr53')
cmd.delete('tyr54')
IDSpec[(('asp','CG'),('sser','CA'))] = cmd.select('asp1', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.29,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('asp','CG'),('sser','CB'))] = cmd.select('asp2', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.57,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('asp','CG'),('sser','OG'))] = cmd.select('asp3', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+5.99,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('asp','OD1'),('sser','CA'))] = cmd.select('asp4', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+5.49,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('asp','OD1'),('sser','CB'))] = cmd.select('asp5', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+5.50,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('asp','OD1'),('sser','OG'))] = cmd.select('asp6', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+5.00,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('asp','OD2'),('sser','CA'))] = cmd.select('asp7', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.44,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('asp','OD2'),('sser','CB'))] = cmd.select('asp8', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.55,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('asp','OD2'),('sser','OG'))] = cmd.select('asp9', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.74,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('asp','CG'),('styr','CE1'))] = cmd.select('asp10', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+13.38,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('asp','CG'),('styr','CZ'))] = cmd.select('asp11', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+13.21,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('asp','CG'),('styr','OH'))] = cmd.select('asp12', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+12.02,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('asp','OD1'),('styr','CE1'))] = cmd.select('asp13', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+12.63,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('asp','OD1'),('styr','CZ'))] = cmd.select('asp14', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+12.42,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('asp','OD1'),('styr','OH'))] = cmd.select('asp15', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+11.20,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('asp','OD2'),('styr','CE1'))] = cmd.select('asp16', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+13.05,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('asp','OD2'),('styr','CZ'))] = cmd.select('asp17', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+12.94,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('asp','OD2'),('styr','OH'))] = cmd.select('asp18', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.82,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('asp','CG'),('rhis','CE1'))] = cmd.select('asp19', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+9.29,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp','CG'),('rhis','ND1'))] = cmd.select('asp20', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+10.13,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp','CG'),('rhis','NE2'))] = cmd.select('asp21', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+8.21,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp','OD1'),('rhis','CE1'))] = cmd.select('asp22', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.74,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp','OD1'),('rhis','ND1'))] = cmd.select('asp23', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.72,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp','OD1'),('rhis','NE2'))] = cmd.select('asp24', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.78,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp','OD2'),('rhis','CE1'))] = cmd.select('asp25', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+8.99,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp','OD2'),('rhis','ND1'))] = cmd.select('asp26', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+9.67,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp','OD2'),('rhis','NE2'))] = cmd.select('asp27', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.90,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp','CG'),('rtrp','CE2'))] = cmd.select('asp28', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+9.53,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('asp','CG'),('rtrp','CZ2'))] = cmd.select('asp29', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+9.36,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('asp','CG'),('rtrp','NE1'))] = cmd.select('asp30', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+10.70,resSelectionSubs('trp','NE1',subs)))
IDSpec[(('asp','OD1'),('rtrp','CE2'))] = cmd.select('asp31', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.32,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('asp','OD1'),('rtrp','CZ2'))] = cmd.select('asp32', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.13,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('asp','OD1'),('rtrp','NE1'))] = cmd.select('asp33', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.51,resSelectionSubs('trp','NE1',subs)))
IDSpec[(('asp','OD2'),('rtrp','CE2'))] = cmd.select('asp34', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+10.41,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('asp','OD2'),('rtrp','CZ2'))] = cmd.select('asp35', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+10.08,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('asp','OD2'),('rtrp','NE1'))] = cmd.select('asp36', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.65,resSelectionSubs('trp','NE1',subs)))
IDSpec[(('asp','CG'),('rhis_i','CE1'))] = cmd.select('asp37', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+18.02,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('asp','CG'),('rhis_i','ND1'))] = cmd.select('asp38', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+17.06,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('asp','CG'),('rhis_i','NE2'))] = cmd.select('asp39', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+17.57,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('asp','OD1'),('rhis_i','CE1'))] = cmd.select('asp40', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+17.95,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('asp','OD1'),('rhis_i','ND1'))] = cmd.select('asp41', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+16.95,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('asp','OD1'),('rhis_i','NE2'))] = cmd.select('asp42', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+17.59,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('asp','OD2'),('rhis_i','CE1'))] = cmd.select('asp43', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+17.05,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('asp','OD2'),('rhis_i','ND1'))] = cmd.select('asp44', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+16.13,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('asp','OD2'),('rhis_i','NE2'))] = cmd.select('asp45', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+16.56,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('asp','CG'),('rtrp_i','CE2'))] = cmd.select('asp46', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+18.72,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('asp','CG'),('rtrp_i','CZ2'))] = cmd.select('asp47', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+17.98,resSelectionSubs('trp_i','CZ2',subs)))
IDSpec[(('asp','CG'),('rtrp_i','NE1'))] = cmd.select('asp48', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+20.09,resSelectionSubs('trp_i','NE1',subs)))
IDSpec[(('asp','OD1'),('rtrp_i','CE2'))] = cmd.select('asp49', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+18.04,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('asp','OD1'),('rtrp_i','CZ2'))] = cmd.select('asp50', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+17.22,resSelectionSubs('trp_i','CZ2',subs)))
cmd.select('asp50',' br. asp1&br. asp2&br. asp3&br. asp4&br. asp5&br. asp6&br. asp7&br. asp8&br. asp9&br. asp10&br. asp11&br. asp12&br. asp13&br. asp14&br. asp15&br. asp16&br. asp17&br. asp18&br. asp19&br. asp20&br. asp21&br. asp22&br. asp23&br. asp24&br. asp25&br. asp26&br. asp27&br. asp28&br. asp29&br. asp30&br. asp31&br. asp32&br. asp33&br. asp34&br. asp35&br. asp36&br. asp37&br. asp38&br. asp39&br. asp40&br. asp41&br. asp42&br. asp43&br. asp44&br. asp45&br. asp46&br. asp47&br. asp48&br. asp49&br. asp50')
cmd.delete('asp1')
cmd.delete('asp2')
cmd.delete('asp3')
cmd.delete('asp4')
cmd.delete('asp5')
cmd.delete('asp6')
cmd.delete('asp7')
cmd.delete('asp8')
cmd.delete('asp9')
cmd.delete('asp10')
cmd.delete('asp11')
cmd.delete('asp12')
cmd.delete('asp13')
cmd.delete('asp14')
cmd.delete('asp15')
cmd.delete('asp16')
cmd.delete('asp17')
cmd.delete('asp18')
cmd.delete('asp19')
cmd.delete('asp20')
cmd.delete('asp21')
cmd.delete('asp22')
cmd.delete('asp23')
cmd.delete('asp24')
cmd.delete('asp25')
cmd.delete('asp26')
cmd.delete('asp27')
cmd.delete('asp28')
cmd.delete('asp29')
cmd.delete('asp30')
cmd.delete('asp31')
cmd.delete('asp32')
cmd.delete('asp33')
cmd.delete('asp34')
cmd.delete('asp35')
cmd.delete('asp36')
cmd.delete('asp37')
cmd.delete('asp38')
cmd.delete('asp39')
cmd.delete('asp40')
cmd.delete('asp41')
cmd.delete('asp42')
cmd.delete('asp43')
cmd.delete('asp44')
cmd.delete('asp45')
cmd.delete('asp46')
cmd.delete('asp47')
cmd.delete('asp48')
cmd.delete('asp49')
IDSpec[(('asp','OD1'),('rtrp_i','NE1'))] = cmd.select('asp51', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+19.41,resSelectionSubs('trp_i','NE1',subs)))
IDSpec[(('asp','OD2'),('rtrp_i','CE2'))] = cmd.select('asp52', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+18.39,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('asp','OD2'),('rtrp_i','CZ2'))] = cmd.select('asp53', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+17.72,resSelectionSubs('trp_i','CZ2',subs)))
IDSpec[(('asp','OD2'),('rtrp_i','NE1'))] = cmd.select('asp54', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+19.74,resSelectionSubs('trp_i','NE1',subs)))
IDSpec['asp'] = cmd.select('asp',' asp50&br. asp51&br. asp52&br. asp53&br. asp54')
IDSpec['r_asp'] = cmd.count_atoms(resSelectionSubs('asp', subs=subs, selection=True))
cmd.delete('asp50')
cmd.delete('asp51')
cmd.delete('asp52')
cmd.delete('asp53')
cmd.delete('asp54')
IDSpec[(('his','CE1'),('sser','CA'))] = cmd.select('his1', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+9.99,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('his','CE1'),('sser','CB'))] = cmd.select('his2', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+8.80,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('his','CE1'),('sser','OG'))] = cmd.select('his3', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.52,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('his','ND1'),('sser','CA'))] = cmd.select('his4', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+11.21,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('his','ND1'),('sser','CB'))] = cmd.select('his5', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+10.07,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('his','ND1'),('sser','OG'))] = cmd.select('his6', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+8.75,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('his','NE2'),('sser','CA'))] = cmd.select('his7', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+9.16,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('his','NE2'),('sser','CB'))] = cmd.select('his8', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+8.12,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('his','NE2'),('sser','OG'))] = cmd.select('his9', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.74,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('his','CE1'),('styr','CE1'))] = cmd.select('his10', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+8.23,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('his','CE1'),('styr','CZ'))] = cmd.select('his11', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.42,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('his','CE1'),('styr','OH'))] = cmd.select('his12', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.26,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('his','ND1'),('styr','CE1'))] = cmd.select('his13', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+8.15,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('his','ND1'),('styr','CZ'))] = cmd.select('his14', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.37,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('his','ND1'),('styr','OH'))] = cmd.select('his15', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+6.45,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('his','NE2'),('styr','CE1'))] = cmd.select('his16', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+9.33,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('his','NE2'),('styr','CZ'))] = cmd.select('his17', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+8.63,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('his','NE2'),('styr','OH'))] = cmd.select('his18', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+7.44,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('his','CE1'),('sasp','CG'))] = cmd.select('his19', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+9.29,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his','CE1'),('sasp','OD1'))] = cmd.select('his20', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+8.74,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his','CE1'),('sasp','OD2'))] = cmd.select('his21', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+8.99,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his','ND1'),('sasp','CG'))] = cmd.select('his22', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+10.13,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his','ND1'),('sasp','OD1'))] = cmd.select('his23', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+9.72,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his','ND1'),('sasp','OD2'))] = cmd.select('his24', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+9.67,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his','NE2'),('sasp','CG'))] = cmd.select('his25', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+8.21,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his','NE2'),('sasp','OD1'))] = cmd.select('his26', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+7.78,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his','NE2'),('sasp','OD2'))] = cmd.select('his27', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+7.90,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his','CE1'),('rtrp','CE2'))] = cmd.select('his28', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+10.87,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('his','CE1'),('rtrp','CZ2'))] = cmd.select('his29', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+9.83,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('his','CE1'),('rtrp','NE1'))] = cmd.select('his30', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+11.89,resSelectionSubs('trp','NE1',subs)))
IDSpec[(('his','ND1'),('rtrp','CE2'))] = cmd.select('his31', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+12.13,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('his','ND1'),('rtrp','CZ2'))] = cmd.select('his32', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+11.05,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('his','ND1'),('rtrp','NE1'))] = cmd.select('his33', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+13.16,resSelectionSubs('trp','NE1',subs)))
IDSpec[(('his','NE2'),('rtrp','CE2'))] = cmd.select('his34', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+10.74,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('his','NE2'),('rtrp','CZ2'))] = cmd.select('his35', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+9.83,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('his','NE2'),('rtrp','NE1'))] = cmd.select('his36', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+11.80,resSelectionSubs('trp','NE1',subs)))
IDSpec[(('his','CE1'),('rhis_i','CE1'))] = cmd.select('his37', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+13.08,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('his','CE1'),('rhis_i','ND1'))] = cmd.select('his38', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+11.85,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('his','CE1'),('rhis_i','NE2'))] = cmd.select('his39', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+13.19,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('his','ND1'),('rhis_i','CE1'))] = cmd.select('his40', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+11.93,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('his','ND1'),('rhis_i','ND1'))] = cmd.select('his41', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+10.67,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('his','ND1'),('rhis_i','NE2'))] = cmd.select('his42', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+12.06,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('his','NE2'),('rhis_i','CE1'))] = cmd.select('his43', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+13.77,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('his','NE2'),('rhis_i','ND1'))] = cmd.select('his44', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+12.57,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('his','NE2'),('rhis_i','NE2'))] = cmd.select('his45', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+13.76,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('his','CE1'),('rtrp_i','CE2'))] = cmd.select('his46', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+11.53,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('his','CE1'),('rtrp_i','CZ2'))] = cmd.select('his47', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+10.88,resSelectionSubs('trp_i','CZ2',subs)))
IDSpec[(('his','CE1'),('rtrp_i','NE1'))] = cmd.select('his48', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+12.88,resSelectionSubs('trp_i','NE1',subs)))
IDSpec[(('his','ND1'),('rtrp_i','CE2'))] = cmd.select('his49', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+10.92,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('his','ND1'),('rtrp_i','CZ2'))] = cmd.select('his50', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+10.44,resSelectionSubs('trp_i','CZ2',subs)))
cmd.select('his50',' br. his1&br. his2&br. his3&br. his4&br. his5&br. his6&br. his7&br. his8&br. his9&br. his10&br. his11&br. his12&br. his13&br. his14&br. his15&br. his16&br. his17&br. his18&br. his19&br. his20&br. his21&br. his22&br. his23&br. his24&br. his25&br. his26&br. his27&br. his28&br. his29&br. his30&br. his31&br. his32&br. his33&br. his34&br. his35&br. his36&br. his37&br. his38&br. his39&br. his40&br. his41&br. his42&br. his43&br. his44&br. his45&br. his46&br. his47&br. his48&br. his49&br. his50')
cmd.delete('his1')
cmd.delete('his2')
cmd.delete('his3')
cmd.delete('his4')
cmd.delete('his5')
cmd.delete('his6')
cmd.delete('his7')
cmd.delete('his8')
cmd.delete('his9')
cmd.delete('his10')
cmd.delete('his11')
cmd.delete('his12')
cmd.delete('his13')
cmd.delete('his14')
cmd.delete('his15')
cmd.delete('his16')
cmd.delete('his17')
cmd.delete('his18')
cmd.delete('his19')
cmd.delete('his20')
cmd.delete('his21')
cmd.delete('his22')
cmd.delete('his23')
cmd.delete('his24')
cmd.delete('his25')
cmd.delete('his26')
cmd.delete('his27')
cmd.delete('his28')
cmd.delete('his29')
cmd.delete('his30')
cmd.delete('his31')
cmd.delete('his32')
cmd.delete('his33')
cmd.delete('his34')
cmd.delete('his35')
cmd.delete('his36')
cmd.delete('his37')
cmd.delete('his38')
cmd.delete('his39')
cmd.delete('his40')
cmd.delete('his41')
cmd.delete('his42')
cmd.delete('his43')
cmd.delete('his44')
cmd.delete('his45')
cmd.delete('his46')
cmd.delete('his47')
cmd.delete('his48')
cmd.delete('his49')
IDSpec[(('his','ND1'),('rtrp_i','NE1'))] = cmd.select('his51', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+12.24,resSelectionSubs('trp_i','NE1',subs)))
IDSpec[(('his','NE2'),('rtrp_i','CE2'))] = cmd.select('his52', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+12.78,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('his','NE2'),('rtrp_i','CZ2'))] = cmd.select('his53', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+12.16,resSelectionSubs('trp_i','CZ2',subs)))
IDSpec[(('his','NE2'),('rtrp_i','NE1'))] = cmd.select('his54', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+14.12,resSelectionSubs('trp_i','NE1',subs)))
IDSpec['his'] = cmd.select('his',' his50&br. his51&br. his52&br. his53&br. his54')
IDSpec['r_his'] = cmd.count_atoms(resSelectionSubs('his', subs=subs, selection=True))
cmd.delete('his50')
cmd.delete('his51')
cmd.delete('his52')
cmd.delete('his53')
cmd.delete('his54')
IDSpec[(('trp','CE2'),('sser','CA'))] = cmd.select('trp1', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+7.15,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('trp','CE2'),('sser','CB'))] = cmd.select('trp2', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+6.28,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('trp','CE2'),('sser','OG'))] = cmd.select('trp3', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+7.27,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('trp','CZ2'),('sser','CA'))] = cmd.select('trp4', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+7.57,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('trp','CZ2'),('sser','CB'))] = cmd.select('trp5', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+6.42,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('trp','CZ2'),('sser','OG'))] = cmd.select('trp6', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+7.05,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('trp','NE1'),('sser','CA'))] = cmd.select('trp7', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+7.84,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('trp','NE1'),('sser','CB'))] = cmd.select('trp8', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+7.10,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('trp','NE1'),('sser','OG'))] = cmd.select('trp9', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+8.23,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('trp','CE2'),('styr','CE1'))] = cmd.select('trp10', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+12.21,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('trp','CE2'),('styr','CZ'))] = cmd.select('trp11', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+11.96,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('trp','CE2'),('styr','OH'))] = cmd.select('trp12', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+10.88,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('trp','CZ2'),('styr','CE1'))] = cmd.select('trp13', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+10.81,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('trp','CZ2'),('styr','CZ'))] = cmd.select('trp14', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+10.59,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('trp','CZ2'),('styr','OH'))] = cmd.select('trp15', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+9.54,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('trp','NE1'),('styr','CE1'))] = cmd.select('trp16', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+13.12,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('trp','NE1'),('styr','CZ'))] = cmd.select('trp17', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+12.81,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('trp','NE1'),('styr','OH'))] = cmd.select('trp18', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+11.76,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('trp','CE2'),('sasp','CG'))] = cmd.select('trp19', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+9.53,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('trp','CE2'),('sasp','OD1'))] = cmd.select('trp20', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+8.32,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('trp','CE2'),('sasp','OD2'))] = cmd.select('trp21', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+10.41,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('trp','CZ2'),('sasp','CG'))] = cmd.select('trp22', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+9.36,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('trp','CZ2'),('sasp','OD1'))] = cmd.select('trp23', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+8.13,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('trp','CZ2'),('sasp','OD2'))] = cmd.select('trp24', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+10.08,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('trp','NE1'),('sasp','CG'))] = cmd.select('trp25', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+10.70,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('trp','NE1'),('sasp','OD1'))] = cmd.select('trp26', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+9.51,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('trp','NE1'),('sasp','OD2'))] = cmd.select('trp27', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+11.65,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('trp','CE2'),('shis','CE1'))] = cmd.select('trp28', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+10.87,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('trp','CE2'),('shis','ND1'))] = cmd.select('trp29', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+12.13,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('trp','CE2'),('shis','NE2'))] = cmd.select('trp30', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+10.74,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('trp','CZ2'),('shis','CE1'))] = cmd.select('trp31', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+9.83,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('trp','CZ2'),('shis','ND1'))] = cmd.select('trp32', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+11.05,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('trp','CZ2'),('shis','NE2'))] = cmd.select('trp33', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+9.83,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('trp','NE1'),('shis','CE1'))] = cmd.select('trp34', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+11.89,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('trp','NE1'),('shis','ND1'))] = cmd.select('trp35', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+13.16,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('trp','NE1'),('shis','NE2'))] = cmd.select('trp36', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+11.80,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('trp','CE2'),('rhis_i','CE1'))] = cmd.select('trp37', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+20.41,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('trp','CE2'),('rhis_i','ND1'))] = cmd.select('trp38', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+19.35,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('trp','CE2'),('rhis_i','NE2'))] = cmd.select('trp39', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+20.36,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('trp','CZ2'),('rhis_i','CE1'))] = cmd.select('trp40', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+19.08,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('trp','CZ2'),('rhis_i','ND1'))] = cmd.select('trp41', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+18.03,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('trp','CZ2'),('rhis_i','NE2'))] = cmd.select('trp42', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+19.06,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('trp','NE1'),('rhis_i','CE1'))] = cmd.select('trp43', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+21.54,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('trp','NE1'),('rhis_i','ND1'))] = cmd.select('trp44', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+20.47,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('trp','NE1'),('rhis_i','NE2'))] = cmd.select('trp45', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+21.54,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('trp','CE2'),('rtrp_i','CE2'))] = cmd.select('trp46', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+17.69,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('trp','CE2'),('rtrp_i','CZ2'))] = cmd.select('trp47', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+16.49,resSelectionSubs('trp_i','CZ2',subs)))
IDSpec[(('trp','CE2'),('rtrp_i','NE1'))] = cmd.select('trp48', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+18.98,resSelectionSubs('trp_i','NE1',subs)))
IDSpec[(('trp','CZ2'),('rtrp_i','CE2'))] = cmd.select('trp49', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+16.46,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('trp','CZ2'),('rtrp_i','CZ2'))] = cmd.select('trp50', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+15.28,resSelectionSubs('trp_i','CZ2',subs)))
cmd.select('trp50',' br. trp1&br. trp2&br. trp3&br. trp4&br. trp5&br. trp6&br. trp7&br. trp8&br. trp9&br. trp10&br. trp11&br. trp12&br. trp13&br. trp14&br. trp15&br. trp16&br. trp17&br. trp18&br. trp19&br. trp20&br. trp21&br. trp22&br. trp23&br. trp24&br. trp25&br. trp26&br. trp27&br. trp28&br. trp29&br. trp30&br. trp31&br. trp32&br. trp33&br. trp34&br. trp35&br. trp36&br. trp37&br. trp38&br. trp39&br. trp40&br. trp41&br. trp42&br. trp43&br. trp44&br. trp45&br. trp46&br. trp47&br. trp48&br. trp49&br. trp50')
cmd.delete('trp1')
cmd.delete('trp2')
cmd.delete('trp3')
cmd.delete('trp4')
cmd.delete('trp5')
cmd.delete('trp6')
cmd.delete('trp7')
cmd.delete('trp8')
cmd.delete('trp9')
cmd.delete('trp10')
cmd.delete('trp11')
cmd.delete('trp12')
cmd.delete('trp13')
cmd.delete('trp14')
cmd.delete('trp15')
cmd.delete('trp16')
cmd.delete('trp17')
cmd.delete('trp18')
cmd.delete('trp19')
cmd.delete('trp20')
cmd.delete('trp21')
cmd.delete('trp22')
cmd.delete('trp23')
cmd.delete('trp24')
cmd.delete('trp25')
cmd.delete('trp26')
cmd.delete('trp27')
cmd.delete('trp28')
cmd.delete('trp29')
cmd.delete('trp30')
cmd.delete('trp31')
cmd.delete('trp32')
cmd.delete('trp33')
cmd.delete('trp34')
cmd.delete('trp35')
cmd.delete('trp36')
cmd.delete('trp37')
cmd.delete('trp38')
cmd.delete('trp39')
cmd.delete('trp40')
cmd.delete('trp41')
cmd.delete('trp42')
cmd.delete('trp43')
cmd.delete('trp44')
cmd.delete('trp45')
cmd.delete('trp46')
cmd.delete('trp47')
cmd.delete('trp48')
cmd.delete('trp49')
IDSpec[(('trp','CZ2'),('rtrp_i','NE1'))] = cmd.select('trp51', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+17.76,resSelectionSubs('trp_i','NE1',subs)))
IDSpec[(('trp','NE1'),('rtrp_i','CE2'))] = cmd.select('trp52', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+18.26,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('trp','NE1'),('rtrp_i','CZ2'))] = cmd.select('trp53', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+17.00,resSelectionSubs('trp_i','CZ2',subs)))
IDSpec[(('trp','NE1'),('rtrp_i','NE1'))] = cmd.select('trp54', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+19.52,resSelectionSubs('trp_i','NE1',subs)))
IDSpec['trp'] = cmd.select('trp',' trp50&br. trp51&br. trp52&br. trp53&br. trp54')
IDSpec['r_trp'] = cmd.count_atoms(resSelectionSubs('trp', subs=subs, selection=True))
cmd.delete('trp50')
cmd.delete('trp51')
cmd.delete('trp52')
cmd.delete('trp53')
cmd.delete('trp54')
IDSpec[(('his_i','CE1'),('sser','CA'))] = cmd.select('his_i1', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+20.47,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sser','CB'))] = cmd.select('his_i2', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+19.38,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sser','OG'))] = cmd.select('his_i3', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+18.12,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sser','CA'))] = cmd.select('his_i4', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+19.36,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sser','CB'))] = cmd.select('his_i5', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+18.24,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sser','OG'))] = cmd.select('his_i6', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+16.98,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sser','CA'))] = cmd.select('his_i7', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+20.28,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sser','CB'))] = cmd.select('his_i8', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+19.26,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sser','OG'))] = cmd.select('his_i9', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+18.00,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('his_i','CE1'),('styr','CE1'))] = cmd.select('his_i10', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+11.28,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('his_i','CE1'),('styr','CZ'))] = cmd.select('his_i11', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+11.65,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('his_i','CE1'),('styr','OH'))] = cmd.select('his_i12', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+12.35,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('his_i','ND1'),('styr','CE1'))] = cmd.select('his_i13', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+10.33,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('his_i','ND1'),('styr','CZ'))] = cmd.select('his_i14', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+10.57,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('his_i','ND1'),('styr','OH'))] = cmd.select('his_i15', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+11.22,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('his_i','NE2'),('styr','CE1'))] = cmd.select('his_i16', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+11.62,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('his_i','NE2'),('styr','CZ'))] = cmd.select('his_i17', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+12.07,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('his_i','NE2'),('styr','OH'))] = cmd.select('his_i18', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+12.69,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sasp','CG'))] = cmd.select('his_i19', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+18.02,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sasp','OD1'))] = cmd.select('his_i20', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+17.95,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sasp','OD2'))] = cmd.select('his_i21', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+17.05,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sasp','CG'))] = cmd.select('his_i22', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+17.06,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sasp','OD1'))] = cmd.select('his_i23', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+16.95,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sasp','OD2'))] = cmd.select('his_i24', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+16.13,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sasp','CG'))] = cmd.select('his_i25', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+17.57,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sasp','OD1'))] = cmd.select('his_i26', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+17.59,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sasp','OD2'))] = cmd.select('his_i27', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+16.56,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his_i','CE1'),('shis','CE1'))] = cmd.select('his_i28', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+13.08,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('his_i','CE1'),('shis','ND1'))] = cmd.select('his_i29', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+11.93,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('his_i','CE1'),('shis','NE2'))] = cmd.select('his_i30', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+13.77,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('his_i','ND1'),('shis','CE1'))] = cmd.select('his_i31', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+11.85,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('his_i','ND1'),('shis','ND1'))] = cmd.select('his_i32', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+10.67,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('his_i','ND1'),('shis','NE2'))] = cmd.select('his_i33', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+12.57,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('his_i','NE2'),('shis','CE1'))] = cmd.select('his_i34', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+13.19,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('his_i','NE2'),('shis','ND1'))] = cmd.select('his_i35', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+12.06,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('his_i','NE2'),('shis','NE2'))] = cmd.select('his_i36', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+13.76,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('his_i','CE1'),('strp','CE2'))] = cmd.select('his_i37', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+20.41,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('his_i','CE1'),('strp','CZ2'))] = cmd.select('his_i38', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+19.08,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('his_i','CE1'),('strp','NE1'))] = cmd.select('his_i39', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+21.54,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec[(('his_i','ND1'),('strp','CE2'))] = cmd.select('his_i40', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+19.35,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('his_i','ND1'),('strp','CZ2'))] = cmd.select('his_i41', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+18.03,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('his_i','ND1'),('strp','NE1'))] = cmd.select('his_i42', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+20.47,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec[(('his_i','NE2'),('strp','CE2'))] = cmd.select('his_i43', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+20.36,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('his_i','NE2'),('strp','CZ2'))] = cmd.select('his_i44', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+19.06,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('his_i','NE2'),('strp','NE1'))] = cmd.select('his_i45', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+21.54,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec[(('his_i','CE1'),('rtrp_i','CE2'))] = cmd.select('his_i46', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+12.07,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('his_i','CE1'),('rtrp_i','CZ2'))] = cmd.select('his_i47', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+12.71,resSelectionSubs('trp_i','CZ2',subs)))
IDSpec[(('his_i','CE1'),('rtrp_i','NE1'))] = cmd.select('his_i48', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+12.57,resSelectionSubs('trp_i','NE1',subs)))
IDSpec[(('his_i','ND1'),('rtrp_i','CE2'))] = cmd.select('his_i49', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+11.07,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('his_i','ND1'),('rtrp_i','CZ2'))] = cmd.select('his_i50', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+11.65,resSelectionSubs('trp_i','CZ2',subs)))
cmd.select('his_i50',' br. his_i1&br. his_i2&br. his_i3&br. his_i4&br. his_i5&br. his_i6&br. his_i7&br. his_i8&br. his_i9&br. his_i10&br. his_i11&br. his_i12&br. his_i13&br. his_i14&br. his_i15&br. his_i16&br. his_i17&br. his_i18&br. his_i19&br. his_i20&br. his_i21&br. his_i22&br. his_i23&br. his_i24&br. his_i25&br. his_i26&br. his_i27&br. his_i28&br. his_i29&br. his_i30&br. his_i31&br. his_i32&br. his_i33&br. his_i34&br. his_i35&br. his_i36&br. his_i37&br. his_i38&br. his_i39&br. his_i40&br. his_i41&br. his_i42&br. his_i43&br. his_i44&br. his_i45&br. his_i46&br. his_i47&br. his_i48&br. his_i49&br. his_i50')
cmd.delete('his_i1')
cmd.delete('his_i2')
cmd.delete('his_i3')
cmd.delete('his_i4')
cmd.delete('his_i5')
cmd.delete('his_i6')
cmd.delete('his_i7')
cmd.delete('his_i8')
cmd.delete('his_i9')
cmd.delete('his_i10')
cmd.delete('his_i11')
cmd.delete('his_i12')
cmd.delete('his_i13')
cmd.delete('his_i14')
cmd.delete('his_i15')
cmd.delete('his_i16')
cmd.delete('his_i17')
cmd.delete('his_i18')
cmd.delete('his_i19')
cmd.delete('his_i20')
cmd.delete('his_i21')
cmd.delete('his_i22')
cmd.delete('his_i23')
cmd.delete('his_i24')
cmd.delete('his_i25')
cmd.delete('his_i26')
cmd.delete('his_i27')
cmd.delete('his_i28')
cmd.delete('his_i29')
cmd.delete('his_i30')
cmd.delete('his_i31')
cmd.delete('his_i32')
cmd.delete('his_i33')
cmd.delete('his_i34')
cmd.delete('his_i35')
cmd.delete('his_i36')
cmd.delete('his_i37')
cmd.delete('his_i38')
cmd.delete('his_i39')
cmd.delete('his_i40')
cmd.delete('his_i41')
cmd.delete('his_i42')
cmd.delete('his_i43')
cmd.delete('his_i44')
cmd.delete('his_i45')
cmd.delete('his_i46')
cmd.delete('his_i47')
cmd.delete('his_i48')
cmd.delete('his_i49')
IDSpec[(('his_i','ND1'),('rtrp_i','NE1'))] = cmd.select('his_i51', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+11.67,resSelectionSubs('trp_i','NE1',subs)))
IDSpec[(('his_i','NE2'),('rtrp_i','CE2'))] = cmd.select('his_i52', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+13.16,resSelectionSubs('trp_i','CE2',subs)))
IDSpec[(('his_i','NE2'),('rtrp_i','CZ2'))] = cmd.select('his_i53', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+13.71,resSelectionSubs('trp_i','CZ2',subs)))
IDSpec[(('his_i','NE2'),('rtrp_i','NE1'))] = cmd.select('his_i54', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+13.74,resSelectionSubs('trp_i','NE1',subs)))
IDSpec['his_i'] = cmd.select('his_i',' his_i50&br. his_i51&br. his_i52&br. his_i53&br. his_i54')
IDSpec['r_his_i'] = cmd.count_atoms(resSelectionSubs('his_i', subs=subs, selection=True))
cmd.delete('his_i50')
cmd.delete('his_i51')
cmd.delete('his_i52')
cmd.delete('his_i53')
cmd.delete('his_i54')
IDSpec[(('trp_i','CE2'),('sser','CA'))] = cmd.select('trp_i1', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+18.76,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('trp_i','CE2'),('sser','CB'))] = cmd.select('trp_i2', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+17.31,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('trp_i','CE2'),('sser','OG'))] = cmd.select('trp_i3', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+16.40,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('trp_i','CZ2'),('sser','CA'))] = cmd.select('trp_i4', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+17.78,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('trp_i','CZ2'),('sser','CB'))] = cmd.select('trp_i5', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+16.31,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('trp_i','CZ2'),('sser','OG'))] = cmd.select('trp_i6', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+15.47,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('sser','CA'))] = cmd.select('trp_i7', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+20.10,resSelectionSubs('ser','CA',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('sser','CB'))] = cmd.select('trp_i8', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+18.66,resSelectionSubs('ser','CB',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('sser','OG'))] = cmd.select('trp_i9', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+17.75,resSelectionSubs('ser','OG',subs,selection=True)))
IDSpec[(('trp_i','CE2'),('styr','CE1'))] = cmd.select('trp_i10', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+9.67,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('trp_i','CE2'),('styr','CZ'))] = cmd.select('trp_i11', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+8.82,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('trp_i','CE2'),('styr','OH'))] = cmd.select('trp_i12', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+9.51,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('trp_i','CZ2'),('styr','CE1'))] = cmd.select('trp_i13', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+8.91,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('trp_i','CZ2'),('styr','CZ'))] = cmd.select('trp_i14', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+7.96,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('trp_i','CZ2'),('styr','OH'))] = cmd.select('trp_i15', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+8.58,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('styr','CE1'))] = cmd.select('trp_i16', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+10.86,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('styr','CZ'))] = cmd.select('trp_i17', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+10.09,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('styr','OH'))] = cmd.select('trp_i18', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+10.83,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('trp_i','CE2'),('sasp','CG'))] = cmd.select('trp_i19', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+18.72,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('trp_i','CE2'),('sasp','OD1'))] = cmd.select('trp_i20', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+18.04,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('trp_i','CE2'),('sasp','OD2'))] = cmd.select('trp_i21', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+18.39,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('trp_i','CZ2'),('sasp','CG'))] = cmd.select('trp_i22', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+17.98,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('trp_i','CZ2'),('sasp','OD1'))] = cmd.select('trp_i23', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+17.22,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('trp_i','CZ2'),('sasp','OD2'))] = cmd.select('trp_i24', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+17.72,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('sasp','CG'))] = cmd.select('trp_i25', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+20.09,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('sasp','OD1'))] = cmd.select('trp_i26', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+19.41,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('sasp','OD2'))] = cmd.select('trp_i27', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+19.74,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('trp_i','CE2'),('shis','CE1'))] = cmd.select('trp_i28', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+11.53,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('trp_i','CE2'),('shis','ND1'))] = cmd.select('trp_i29', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+10.92,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('trp_i','CE2'),('shis','NE2'))] = cmd.select('trp_i30', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+12.78,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('trp_i','CZ2'),('shis','CE1'))] = cmd.select('trp_i31', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+10.88,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('trp_i','CZ2'),('shis','ND1'))] = cmd.select('trp_i32', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+10.44,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('trp_i','CZ2'),('shis','NE2'))] = cmd.select('trp_i33', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+12.16,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('shis','CE1'))] = cmd.select('trp_i34', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+12.88,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('shis','ND1'))] = cmd.select('trp_i35', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+12.24,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('shis','NE2'))] = cmd.select('trp_i36', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+14.12,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('trp_i','CE2'),('strp','CE2'))] = cmd.select('trp_i37', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+17.69,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('trp_i','CE2'),('strp','CZ2'))] = cmd.select('trp_i38', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+16.46,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('trp_i','CE2'),('strp','NE1'))] = cmd.select('trp_i39', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+18.26,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec[(('trp_i','CZ2'),('strp','CE2'))] = cmd.select('trp_i40', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+16.49,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('trp_i','CZ2'),('strp','CZ2'))] = cmd.select('trp_i41', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+15.28,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('trp_i','CZ2'),('strp','NE1'))] = cmd.select('trp_i42', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+17.00,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('strp','CE2'))] = cmd.select('trp_i43', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+18.98,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('strp','CZ2'))] = cmd.select('trp_i44', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+17.76,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('strp','NE1'))] = cmd.select('trp_i45', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+19.52,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec[(('trp_i','CE2'),('shis_i','CE1'))] = cmd.select('trp_i46', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+12.07,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('trp_i','CE2'),('shis_i','ND1'))] = cmd.select('trp_i47', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+11.07,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('trp_i','CE2'),('shis_i','NE2'))] = cmd.select('trp_i48', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+13.16,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('trp_i','CZ2'),('shis_i','CE1'))] = cmd.select('trp_i49', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+12.71,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('trp_i','CZ2'),('shis_i','ND1'))] = cmd.select('trp_i50', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+11.65,resSelectionSubs('his_i','ND1',subs,selection=True)))
cmd.select('trp_i50',' br. trp_i1&br. trp_i2&br. trp_i3&br. trp_i4&br. trp_i5&br. trp_i6&br. trp_i7&br. trp_i8&br. trp_i9&br. trp_i10&br. trp_i11&br. trp_i12&br. trp_i13&br. trp_i14&br. trp_i15&br. trp_i16&br. trp_i17&br. trp_i18&br. trp_i19&br. trp_i20&br. trp_i21&br. trp_i22&br. trp_i23&br. trp_i24&br. trp_i25&br. trp_i26&br. trp_i27&br. trp_i28&br. trp_i29&br. trp_i30&br. trp_i31&br. trp_i32&br. trp_i33&br. trp_i34&br. trp_i35&br. trp_i36&br. trp_i37&br. trp_i38&br. trp_i39&br. trp_i40&br. trp_i41&br. trp_i42&br. trp_i43&br. trp_i44&br. trp_i45&br. trp_i46&br. trp_i47&br. trp_i48&br. trp_i49&br. trp_i50')
cmd.delete('trp_i1')
cmd.delete('trp_i2')
cmd.delete('trp_i3')
cmd.delete('trp_i4')
cmd.delete('trp_i5')
cmd.delete('trp_i6')
cmd.delete('trp_i7')
cmd.delete('trp_i8')
cmd.delete('trp_i9')
cmd.delete('trp_i10')
cmd.delete('trp_i11')
cmd.delete('trp_i12')
cmd.delete('trp_i13')
cmd.delete('trp_i14')
cmd.delete('trp_i15')
cmd.delete('trp_i16')
cmd.delete('trp_i17')
cmd.delete('trp_i18')
cmd.delete('trp_i19')
cmd.delete('trp_i20')
cmd.delete('trp_i21')
cmd.delete('trp_i22')
cmd.delete('trp_i23')
cmd.delete('trp_i24')
cmd.delete('trp_i25')
cmd.delete('trp_i26')
cmd.delete('trp_i27')
cmd.delete('trp_i28')
cmd.delete('trp_i29')
cmd.delete('trp_i30')
cmd.delete('trp_i31')
cmd.delete('trp_i32')
cmd.delete('trp_i33')
cmd.delete('trp_i34')
cmd.delete('trp_i35')
cmd.delete('trp_i36')
cmd.delete('trp_i37')
cmd.delete('trp_i38')
cmd.delete('trp_i39')
cmd.delete('trp_i40')
cmd.delete('trp_i41')
cmd.delete('trp_i42')
cmd.delete('trp_i43')
cmd.delete('trp_i44')
cmd.delete('trp_i45')
cmd.delete('trp_i46')
cmd.delete('trp_i47')
cmd.delete('trp_i48')
cmd.delete('trp_i49')
IDSpec[(('trp_i','CZ2'),('shis_i','NE2'))] = cmd.select('trp_i51', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+13.71,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('shis_i','CE1'))] = cmd.select('trp_i52', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+12.57,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('shis_i','ND1'))] = cmd.select('trp_i53', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+11.67,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('trp_i','NE1'),('shis_i','NE2'))] = cmd.select('trp_i54', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+13.74,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec['trp_i'] = cmd.select('trp_i',' trp_i50&br. trp_i51&br. trp_i52&br. trp_i53&br. trp_i54')
IDSpec['r_trp_i'] = cmd.count_atoms(resSelectionSubs('trp_i', subs=subs, selection=True))
cmd.delete('trp_i50')
cmd.delete('trp_i51')
cmd.delete('trp_i52')
cmd.delete('trp_i53')
cmd.delete('trp_i54')
IDSpec['S_1vle_1_97_1_2'] = cmd.select('S_1vle_1_97_1_2', 'ser|tyr|asp|his|trp|his_i|trp_i')
cmd.delete('ser')
cmd.delete('tyr')
cmd.delete('asp')
cmd.delete('his')
cmd.delete('trp')
cmd.delete('his_i')
cmd.delete('trp_i')
