'''
FUNC:S_1ybh_2_2_1_6
PDB:1ybh
EC:2.2.1.6
RESI:val,gly,met,his
LOCI:a-485,511,513,643;
'''
IDSpec[(('his','CE1'),('rval','CA'))] = cmd.select('his1', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+21.07,resSelectionSubs('val','CA',subs)))
IDSpec[(('his','CE1'),('rval','CB'))] = cmd.select('his2', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+21.88,resSelectionSubs('val','CB',subs)))
IDSpec[(('his','CE1'),('rval','CG1'))] = cmd.select('his3', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+21.72,resSelectionSubs('val','CG1',subs)))
IDSpec[(('his','ND1'),('rval','CA'))] = cmd.select('his4', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+20.07,resSelectionSubs('val','CA',subs)))
IDSpec[(('his','ND1'),('rval','CB'))] = cmd.select('his5', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+20.95,resSelectionSubs('val','CB',subs)))
IDSpec[(('his','ND1'),('rval','CG1'))] = cmd.select('his6', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+20.84,resSelectionSubs('val','CG1',subs)))
IDSpec[(('his','NE2'),('rval','CA'))] = cmd.select('his7', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+20.65,resSelectionSubs('val','CA',subs)))
IDSpec[(('his','NE2'),('rval','CB'))] = cmd.select('his8', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+21.40,resSelectionSubs('val','CB',subs)))
IDSpec[(('his','NE2'),('rval','CG1'))] = cmd.select('his9', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+21.15,resSelectionSubs('val','CG1',subs)))
IDSpec[(('his','CE1'),('rmet','CE'))] = cmd.select('his10', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+18.95,resSelectionSubs('met','CE',subs)))
IDSpec[(('his','CE1'),('rmet','CG'))] = cmd.select('his11', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+20.85,resSelectionSubs('met','CG',subs)))
IDSpec[(('his','CE1'),('rmet','SD'))] = cmd.select('his12', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+19.80,resSelectionSubs('met','SD',subs)))
IDSpec[(('his','ND1'),('rmet','CE'))] = cmd.select('his13', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+18.13,resSelectionSubs('met','CE',subs)))
IDSpec[(('his','ND1'),('rmet','CG'))] = cmd.select('his14', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+19.99,resSelectionSubs('met','CG',subs)))
IDSpec[(('his','ND1'),('rmet','SD'))] = cmd.select('his15', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+19.03,resSelectionSubs('met','SD',subs)))
IDSpec[(('his','NE2'),('rmet','CE'))] = cmd.select('his16', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+18.53,resSelectionSubs('met','CE',subs)))
IDSpec[(('his','NE2'),('rmet','CG'))] = cmd.select('his17', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+20.37,resSelectionSubs('met','CG',subs)))
IDSpec[(('his','NE2'),('rmet','SD'))] = cmd.select('his18', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+19.28,resSelectionSubs('met','SD',subs)))
IDSpec[(('his','CE1'),('rgly','CA'))] = cmd.select('his19', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+25.93,resSelectionSubs('gly','CA',subs)))
IDSpec[(('his','CE1'),('rgly','N'))] = cmd.select('his20', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+27.34,resSelectionSubs('gly','N',subs)))
IDSpec[(('his','CE1'),('rgly','O'))] = cmd.select('his21', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+24.52,resSelectionSubs('gly','O',subs)))
IDSpec[(('his','ND1'),('rgly','CA'))] = cmd.select('his22', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+25.08,resSelectionSubs('gly','CA',subs)))
IDSpec[(('his','ND1'),('rgly','N'))] = cmd.select('his23', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+26.50,resSelectionSubs('gly','N',subs)))
IDSpec[(('his','ND1'),('rgly','O'))] = cmd.select('his24', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+23.71,resSelectionSubs('gly','O',subs)))
IDSpec[(('his','NE2'),('rgly','CA'))] = cmd.select('his25', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+25.32,resSelectionSubs('gly','CA',subs)))
IDSpec[(('his','NE2'),('rgly','N'))] = cmd.select('his26', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+26.71,resSelectionSubs('gly','N',subs)))
IDSpec[(('his','NE2'),('rgly','O'))] = cmd.select('his27', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+23.90,resSelectionSubs('gly','O',subs)))
IDSpec['his'] = cmd.select('his',' br. his1&br. his2&br. his3&br. his4&br. his5&br. his6&br. his7&br. his8&br. his9&br. his10&br. his11&br. his12&br. his13&br. his14&br. his15&br. his16&br. his17&br. his18&br. his19&br. his20&br. his21&br. his22&br. his23&br. his24&br. his25&br. his26&br. his27')
IDSpec['r_his'] = cmd.count_atoms(resSelectionSubs('his', subs=subs, selection=True))
cmd.delete('his1')
cmd.delete('his2')
cmd.delete('his3')
cmd.delete('his4')
cmd.delete('his5')
cmd.delete('his6')
cmd.delete('his7')
cmd.delete('his8')
cmd.delete('his9')
cmd.delete('his10')
cmd.delete('his11')
cmd.delete('his12')
cmd.delete('his13')
cmd.delete('his14')
cmd.delete('his15')
cmd.delete('his16')
cmd.delete('his17')
cmd.delete('his18')
cmd.delete('his19')
cmd.delete('his20')
cmd.delete('his21')
cmd.delete('his22')
cmd.delete('his23')
cmd.delete('his24')
cmd.delete('his25')
cmd.delete('his26')
cmd.delete('his27')
IDSpec[(('val','CA'),('shis','CE1'))] = cmd.select('val1', '%s w. %s of %s'%(resSelectionSubs('val','CA',subs),d+21.07,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('val','CA'),('shis','ND1'))] = cmd.select('val2', '%s w. %s of %s'%(resSelectionSubs('val','CA',subs),d+20.07,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('val','CA'),('shis','NE2'))] = cmd.select('val3', '%s w. %s of %s'%(resSelectionSubs('val','CA',subs),d+20.65,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('val','CB'),('shis','CE1'))] = cmd.select('val4', '%s w. %s of %s'%(resSelectionSubs('val','CB',subs),d+21.88,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('val','CB'),('shis','ND1'))] = cmd.select('val5', '%s w. %s of %s'%(resSelectionSubs('val','CB',subs),d+20.95,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('val','CB'),('shis','NE2'))] = cmd.select('val6', '%s w. %s of %s'%(resSelectionSubs('val','CB',subs),d+21.40,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('val','CG1'),('shis','CE1'))] = cmd.select('val7', '%s w. %s of %s'%(resSelectionSubs('val','CG1',subs),d+21.72,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('val','CG1'),('shis','ND1'))] = cmd.select('val8', '%s w. %s of %s'%(resSelectionSubs('val','CG1',subs),d+20.84,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('val','CG1'),('shis','NE2'))] = cmd.select('val9', '%s w. %s of %s'%(resSelectionSubs('val','CG1',subs),d+21.15,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('val','CA'),('rmet','CE'))] = cmd.select('val10', '%s w. %s of %s'%(resSelectionSubs('val','CA',subs),d+8.68,resSelectionSubs('met','CE',subs)))
IDSpec[(('val','CA'),('rmet','CG'))] = cmd.select('val11', '%s w. %s of %s'%(resSelectionSubs('val','CA',subs),d+6.73,resSelectionSubs('met','CG',subs)))
IDSpec[(('val','CA'),('rmet','SD'))] = cmd.select('val12', '%s w. %s of %s'%(resSelectionSubs('val','CA',subs),d+8.08,resSelectionSubs('met','SD',subs)))
IDSpec[(('val','CB'),('rmet','CE'))] = cmd.select('val13', '%s w. %s of %s'%(resSelectionSubs('val','CB',subs),d+8.47,resSelectionSubs('met','CE',subs)))
IDSpec[(('val','CB'),('rmet','CG'))] = cmd.select('val14', '%s w. %s of %s'%(resSelectionSubs('val','CB',subs),d+6.08,resSelectionSubs('met','CG',subs)))
IDSpec[(('val','CB'),('rmet','SD'))] = cmd.select('val15', '%s w. %s of %s'%(resSelectionSubs('val','CB',subs),d+7.51,resSelectionSubs('met','SD',subs)))
IDSpec[(('val','CG1'),('rmet','CE'))] = cmd.select('val16', '%s w. %s of %s'%(resSelectionSubs('val','CG1',subs),d+9.06,resSelectionSubs('met','CE',subs)))
IDSpec[(('val','CG1'),('rmet','CG'))] = cmd.select('val17', '%s w. %s of %s'%(resSelectionSubs('val','CG1',subs),d+6.76,resSelectionSubs('met','CG',subs)))
IDSpec[(('val','CG1'),('rmet','SD'))] = cmd.select('val18', '%s w. %s of %s'%(resSelectionSubs('val','CG1',subs),d+7.87,resSelectionSubs('met','SD',subs)))
IDSpec[(('val','CA'),('rgly','CA'))] = cmd.select('val19', '%s w. %s of %s'%(resSelectionSubs('val','CA',subs),d+7.87,resSelectionSubs('gly','CA',subs)))
IDSpec[(('val','CA'),('rgly','N'))] = cmd.select('val20', '%s w. %s of %s'%(resSelectionSubs('val','CA',subs),d+9.28,resSelectionSubs('gly','N',subs)))
IDSpec[(('val','CA'),('rgly','O'))] = cmd.select('val21', '%s w. %s of %s'%(resSelectionSubs('val','CA',subs),d+7.37,resSelectionSubs('gly','O',subs)))
IDSpec[(('val','CB'),('rgly','CA'))] = cmd.select('val22', '%s w. %s of %s'%(resSelectionSubs('val','CB',subs),d+6.55,resSelectionSubs('gly','CA',subs)))
IDSpec[(('val','CB'),('rgly','N'))] = cmd.select('val23', '%s w. %s of %s'%(resSelectionSubs('val','CB',subs),d+7.99,resSelectionSubs('gly','N',subs)))
IDSpec[(('val','CB'),('rgly','O'))] = cmd.select('val24', '%s w. %s of %s'%(resSelectionSubs('val','CB',subs),d+5.83,resSelectionSubs('gly','O',subs)))
IDSpec[(('val','CG1'),('rgly','CA'))] = cmd.select('val25', '%s w. %s of %s'%(resSelectionSubs('val','CG1',subs),d+6.28,resSelectionSubs('gly','CA',subs)))
IDSpec[(('val','CG1'),('rgly','N'))] = cmd.select('val26', '%s w. %s of %s'%(resSelectionSubs('val','CG1',subs),d+7.71,resSelectionSubs('gly','N',subs)))
IDSpec[(('val','CG1'),('rgly','O'))] = cmd.select('val27', '%s w. %s of %s'%(resSelectionSubs('val','CG1',subs),d+5.65,resSelectionSubs('gly','O',subs)))
IDSpec['val'] = cmd.select('val',' br. val1&br. val2&br. val3&br. val4&br. val5&br. val6&br. val7&br. val8&br. val9&br. val10&br. val11&br. val12&br. val13&br. val14&br. val15&br. val16&br. val17&br. val18&br. val19&br. val20&br. val21&br. val22&br. val23&br. val24&br. val25&br. val26&br. val27')
IDSpec['r_val'] = cmd.count_atoms(resSelectionSubs('val', subs=subs, selection=True))
cmd.delete('val1')
cmd.delete('val2')
cmd.delete('val3')
cmd.delete('val4')
cmd.delete('val5')
cmd.delete('val6')
cmd.delete('val7')
cmd.delete('val8')
cmd.delete('val9')
cmd.delete('val10')
cmd.delete('val11')
cmd.delete('val12')
cmd.delete('val13')
cmd.delete('val14')
cmd.delete('val15')
cmd.delete('val16')
cmd.delete('val17')
cmd.delete('val18')
cmd.delete('val19')
cmd.delete('val20')
cmd.delete('val21')
cmd.delete('val22')
cmd.delete('val23')
cmd.delete('val24')
cmd.delete('val25')
cmd.delete('val26')
cmd.delete('val27')
IDSpec[(('met','CE'),('shis','CE1'))] = cmd.select('met1', '%s w. %s of %s'%(resSelectionSubs('met','CE',subs),d+18.95,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('met','CE'),('shis','ND1'))] = cmd.select('met2', '%s w. %s of %s'%(resSelectionSubs('met','CE',subs),d+18.13,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('met','CE'),('shis','NE2'))] = cmd.select('met3', '%s w. %s of %s'%(resSelectionSubs('met','CE',subs),d+18.53,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('met','CG'),('shis','CE1'))] = cmd.select('met4', '%s w. %s of %s'%(resSelectionSubs('met','CG',subs),d+20.85,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('met','CG'),('shis','ND1'))] = cmd.select('met5', '%s w. %s of %s'%(resSelectionSubs('met','CG',subs),d+19.99,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('met','CG'),('shis','NE2'))] = cmd.select('met6', '%s w. %s of %s'%(resSelectionSubs('met','CG',subs),d+20.37,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('met','SD'),('shis','CE1'))] = cmd.select('met7', '%s w. %s of %s'%(resSelectionSubs('met','SD',subs),d+19.80,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('met','SD'),('shis','ND1'))] = cmd.select('met8', '%s w. %s of %s'%(resSelectionSubs('met','SD',subs),d+19.03,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('met','SD'),('shis','NE2'))] = cmd.select('met9', '%s w. %s of %s'%(resSelectionSubs('met','SD',subs),d+19.28,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('met','CE'),('sval','CA'))] = cmd.select('met10', '%s w. %s of %s'%(resSelectionSubs('met','CE',subs),d+8.68,resSelectionSubs('val','CA',subs,selection=True)))
IDSpec[(('met','CE'),('sval','CB'))] = cmd.select('met11', '%s w. %s of %s'%(resSelectionSubs('met','CE',subs),d+8.47,resSelectionSubs('val','CB',subs,selection=True)))
IDSpec[(('met','CE'),('sval','CG1'))] = cmd.select('met12', '%s w. %s of %s'%(resSelectionSubs('met','CE',subs),d+9.06,resSelectionSubs('val','CG1',subs,selection=True)))
IDSpec[(('met','CG'),('sval','CA'))] = cmd.select('met13', '%s w. %s of %s'%(resSelectionSubs('met','CG',subs),d+6.73,resSelectionSubs('val','CA',subs,selection=True)))
IDSpec[(('met','CG'),('sval','CB'))] = cmd.select('met14', '%s w. %s of %s'%(resSelectionSubs('met','CG',subs),d+6.08,resSelectionSubs('val','CB',subs,selection=True)))
IDSpec[(('met','CG'),('sval','CG1'))] = cmd.select('met15', '%s w. %s of %s'%(resSelectionSubs('met','CG',subs),d+6.76,resSelectionSubs('val','CG1',subs,selection=True)))
IDSpec[(('met','SD'),('sval','CA'))] = cmd.select('met16', '%s w. %s of %s'%(resSelectionSubs('met','SD',subs),d+8.08,resSelectionSubs('val','CA',subs,selection=True)))
IDSpec[(('met','SD'),('sval','CB'))] = cmd.select('met17', '%s w. %s of %s'%(resSelectionSubs('met','SD',subs),d+7.51,resSelectionSubs('val','CB',subs,selection=True)))
IDSpec[(('met','SD'),('sval','CG1'))] = cmd.select('met18', '%s w. %s of %s'%(resSelectionSubs('met','SD',subs),d+7.87,resSelectionSubs('val','CG1',subs,selection=True)))
IDSpec[(('met','CE'),('rgly','CA'))] = cmd.select('met19', '%s w. %s of %s'%(resSelectionSubs('met','CE',subs),d+11.81,resSelectionSubs('gly','CA',subs)))
IDSpec[(('met','CE'),('rgly','N'))] = cmd.select('met20', '%s w. %s of %s'%(resSelectionSubs('met','CE',subs),d+13.04,resSelectionSubs('gly','N',subs)))
IDSpec[(('met','CE'),('rgly','O'))] = cmd.select('met21', '%s w. %s of %s'%(resSelectionSubs('met','CE',subs),d+9.71,resSelectionSubs('gly','O',subs)))
IDSpec[(('met','CG'),('rgly','CA'))] = cmd.select('met22', '%s w. %s of %s'%(resSelectionSubs('met','CG',subs),d+9.06,resSelectionSubs('gly','CA',subs)))
IDSpec[(('met','CG'),('rgly','N'))] = cmd.select('met23', '%s w. %s of %s'%(resSelectionSubs('met','CG',subs),d+10.29,resSelectionSubs('gly','N',subs)))
IDSpec[(('met','CG'),('rgly','O'))] = cmd.select('met24', '%s w. %s of %s'%(resSelectionSubs('met','CG',subs),d+7.02,resSelectionSubs('gly','O',subs)))
IDSpec[(('met','SD'),('rgly','CA'))] = cmd.select('met25', '%s w. %s of %s'%(resSelectionSubs('met','SD',subs),d+10.37,resSelectionSubs('gly','CA',subs)))
IDSpec[(('met','SD'),('rgly','N'))] = cmd.select('met26', '%s w. %s of %s'%(resSelectionSubs('met','SD',subs),d+11.58,resSelectionSubs('gly','N',subs)))
IDSpec[(('met','SD'),('rgly','O'))] = cmd.select('met27', '%s w. %s of %s'%(resSelectionSubs('met','SD',subs),d+8.18,resSelectionSubs('gly','O',subs)))
IDSpec['met'] = cmd.select('met',' br. met1&br. met2&br. met3&br. met4&br. met5&br. met6&br. met7&br. met8&br. met9&br. met10&br. met11&br. met12&br. met13&br. met14&br. met15&br. met16&br. met17&br. met18&br. met19&br. met20&br. met21&br. met22&br. met23&br. met24&br. met25&br. met26&br. met27')
IDSpec['r_met'] = cmd.count_atoms(resSelectionSubs('met', subs=subs, selection=True))
cmd.delete('met1')
cmd.delete('met2')
cmd.delete('met3')
cmd.delete('met4')
cmd.delete('met5')
cmd.delete('met6')
cmd.delete('met7')
cmd.delete('met8')
cmd.delete('met9')
cmd.delete('met10')
cmd.delete('met11')
cmd.delete('met12')
cmd.delete('met13')
cmd.delete('met14')
cmd.delete('met15')
cmd.delete('met16')
cmd.delete('met17')
cmd.delete('met18')
cmd.delete('met19')
cmd.delete('met20')
cmd.delete('met21')
cmd.delete('met22')
cmd.delete('met23')
cmd.delete('met24')
cmd.delete('met25')
cmd.delete('met26')
cmd.delete('met27')
IDSpec[(('gly','CA'),('shis','CE1'))] = cmd.select('gly1', '%s w. %s of %s'%(resSelectionSubs('gly','CA',subs),d+25.93,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('gly','CA'),('shis','ND1'))] = cmd.select('gly2', '%s w. %s of %s'%(resSelectionSubs('gly','CA',subs),d+25.08,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('gly','CA'),('shis','NE2'))] = cmd.select('gly3', '%s w. %s of %s'%(resSelectionSubs('gly','CA',subs),d+25.32,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('gly','N'),('shis','CE1'))] = cmd.select('gly4', '%s w. %s of %s'%(resSelectionSubs('gly','N',subs),d+27.34,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('gly','N'),('shis','ND1'))] = cmd.select('gly5', '%s w. %s of %s'%(resSelectionSubs('gly','N',subs),d+26.50,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('gly','N'),('shis','NE2'))] = cmd.select('gly6', '%s w. %s of %s'%(resSelectionSubs('gly','N',subs),d+26.71,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('gly','O'),('shis','CE1'))] = cmd.select('gly7', '%s w. %s of %s'%(resSelectionSubs('gly','O',subs),d+24.52,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('gly','O'),('shis','ND1'))] = cmd.select('gly8', '%s w. %s of %s'%(resSelectionSubs('gly','O',subs),d+23.71,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('gly','O'),('shis','NE2'))] = cmd.select('gly9', '%s w. %s of %s'%(resSelectionSubs('gly','O',subs),d+23.90,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('gly','CA'),('sval','CA'))] = cmd.select('gly10', '%s w. %s of %s'%(resSelectionSubs('gly','CA',subs),d+7.87,resSelectionSubs('val','CA',subs,selection=True)))
IDSpec[(('gly','CA'),('sval','CB'))] = cmd.select('gly11', '%s w. %s of %s'%(resSelectionSubs('gly','CA',subs),d+6.55,resSelectionSubs('val','CB',subs,selection=True)))
IDSpec[(('gly','CA'),('sval','CG1'))] = cmd.select('gly12', '%s w. %s of %s'%(resSelectionSubs('gly','CA',subs),d+6.28,resSelectionSubs('val','CG1',subs,selection=True)))
IDSpec[(('gly','N'),('sval','CA'))] = cmd.select('gly13', '%s w. %s of %s'%(resSelectionSubs('gly','N',subs),d+9.28,resSelectionSubs('val','CA',subs,selection=True)))
IDSpec[(('gly','N'),('sval','CB'))] = cmd.select('gly14', '%s w. %s of %s'%(resSelectionSubs('gly','N',subs),d+7.99,resSelectionSubs('val','CB',subs,selection=True)))
IDSpec[(('gly','N'),('sval','CG1'))] = cmd.select('gly15', '%s w. %s of %s'%(resSelectionSubs('gly','N',subs),d+7.71,resSelectionSubs('val','CG1',subs,selection=True)))
IDSpec[(('gly','O'),('sval','CA'))] = cmd.select('gly16', '%s w. %s of %s'%(resSelectionSubs('gly','O',subs),d+7.37,resSelectionSubs('val','CA',subs,selection=True)))
IDSpec[(('gly','O'),('sval','CB'))] = cmd.select('gly17', '%s w. %s of %s'%(resSelectionSubs('gly','O',subs),d+5.83,resSelectionSubs('val','CB',subs,selection=True)))
IDSpec[(('gly','O'),('sval','CG1'))] = cmd.select('gly18', '%s w. %s of %s'%(resSelectionSubs('gly','O',subs),d+5.65,resSelectionSubs('val','CG1',subs,selection=True)))
IDSpec[(('gly','CA'),('smet','CE'))] = cmd.select('gly19', '%s w. %s of %s'%(resSelectionSubs('gly','CA',subs),d+11.81,resSelectionSubs('met','CE',subs,selection=True)))
IDSpec[(('gly','CA'),('smet','CG'))] = cmd.select('gly20', '%s w. %s of %s'%(resSelectionSubs('gly','CA',subs),d+9.06,resSelectionSubs('met','CG',subs,selection=True)))
IDSpec[(('gly','CA'),('smet','SD'))] = cmd.select('gly21', '%s w. %s of %s'%(resSelectionSubs('gly','CA',subs),d+10.37,resSelectionSubs('met','SD',subs,selection=True)))
IDSpec[(('gly','N'),('smet','CE'))] = cmd.select('gly22', '%s w. %s of %s'%(resSelectionSubs('gly','N',subs),d+13.04,resSelectionSubs('met','CE',subs,selection=True)))
IDSpec[(('gly','N'),('smet','CG'))] = cmd.select('gly23', '%s w. %s of %s'%(resSelectionSubs('gly','N',subs),d+10.29,resSelectionSubs('met','CG',subs,selection=True)))
IDSpec[(('gly','N'),('smet','SD'))] = cmd.select('gly24', '%s w. %s of %s'%(resSelectionSubs('gly','N',subs),d+11.58,resSelectionSubs('met','SD',subs,selection=True)))
IDSpec[(('gly','O'),('smet','CE'))] = cmd.select('gly25', '%s w. %s of %s'%(resSelectionSubs('gly','O',subs),d+9.71,resSelectionSubs('met','CE',subs,selection=True)))
IDSpec[(('gly','O'),('smet','CG'))] = cmd.select('gly26', '%s w. %s of %s'%(resSelectionSubs('gly','O',subs),d+7.02,resSelectionSubs('met','CG',subs,selection=True)))
IDSpec[(('gly','O'),('smet','SD'))] = cmd.select('gly27', '%s w. %s of %s'%(resSelectionSubs('gly','O',subs),d+8.18,resSelectionSubs('met','SD',subs,selection=True)))
IDSpec['gly'] = cmd.select('gly',' br. gly1&br. gly2&br. gly3&br. gly4&br. gly5&br. gly6&br. gly7&br. gly8&br. gly9&br. gly10&br. gly11&br. gly12&br. gly13&br. gly14&br. gly15&br. gly16&br. gly17&br. gly18&br. gly19&br. gly20&br. gly21&br. gly22&br. gly23&br. gly24&br. gly25&br. gly26&br. gly27')
IDSpec['r_gly'] = cmd.count_atoms(resSelectionSubs('gly', subs=subs, selection=True))
cmd.delete('gly1')
cmd.delete('gly2')
cmd.delete('gly3')
cmd.delete('gly4')
cmd.delete('gly5')
cmd.delete('gly6')
cmd.delete('gly7')
cmd.delete('gly8')
cmd.delete('gly9')
cmd.delete('gly10')
cmd.delete('gly11')
cmd.delete('gly12')
cmd.delete('gly13')
cmd.delete('gly14')
cmd.delete('gly15')
cmd.delete('gly16')
cmd.delete('gly17')
cmd.delete('gly18')
cmd.delete('gly19')
cmd.delete('gly20')
cmd.delete('gly21')
cmd.delete('gly22')
cmd.delete('gly23')
cmd.delete('gly24')
cmd.delete('gly25')
cmd.delete('gly26')
cmd.delete('gly27')
IDSpec['S_1ybh_2_2_1_6'] = cmd.select('S_1ybh_2_2_1_6', 'his|val|met|gly')
cmd.delete('his')
cmd.delete('val')
cmd.delete('met')
cmd.delete('gly')
