'''
FUNC:S_2c9h_2_3_1_41
PDB:2c9h
EC:2.3.1.41
RESI:his,lys,his,phe,phe
LOCI:a-333,365,370,430,432;
'''
IDSpec[(('phe','CD1'),('rhis','CE1'))] = cmd.select('phe1', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+9.05,resSelectionSubs('his','CE1',subs)))
IDSpec[(('phe','CD1'),('rhis','ND1'))] = cmd.select('phe2', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+9.86,resSelectionSubs('his','ND1',subs)))
IDSpec[(('phe','CD1'),('rhis','NE2'))] = cmd.select('phe3', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+9.72,resSelectionSubs('his','NE2',subs)))
IDSpec[(('phe','CE1'),('rhis','CE1'))] = cmd.select('phe4', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+8.86,resSelectionSubs('his','CE1',subs)))
IDSpec[(('phe','CE1'),('rhis','ND1'))] = cmd.select('phe5', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+9.46,resSelectionSubs('his','ND1',subs)))
IDSpec[(('phe','CE1'),('rhis','NE2'))] = cmd.select('phe6', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+9.70,resSelectionSubs('his','NE2',subs)))
IDSpec[(('phe','CZ'),('rhis','CE1'))] = cmd.select('phe7', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+9.45,resSelectionSubs('his','CE1',subs)))
IDSpec[(('phe','CZ'),('rhis','ND1'))] = cmd.select('phe8', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+9.91,resSelectionSubs('his','ND1',subs)))
IDSpec[(('phe','CZ'),('rhis','NE2'))] = cmd.select('phe9', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+10.24,resSelectionSubs('his','NE2',subs)))
IDSpec[(('phe','CD1'),('rhis_i','CE1'))] = cmd.select('phe10', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+10.68,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('phe','CD1'),('rhis_i','ND1'))] = cmd.select('phe11', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+11.88,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('phe','CD1'),('rhis_i','NE2'))] = cmd.select('phe12', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+9.97,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('phe','CE1'),('rhis_i','CE1'))] = cmd.select('phe13', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+10.97,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('phe','CE1'),('rhis_i','ND1'))] = cmd.select('phe14', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+12.20,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('phe','CE1'),('rhis_i','NE2'))] = cmd.select('phe15', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+10.20,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('phe','CZ'),('rhis_i','CE1'))] = cmd.select('phe16', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+12.01,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('phe','CZ'),('rhis_i','ND1'))] = cmd.select('phe17', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+13.28,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('phe','CZ'),('rhis_i','NE2'))] = cmd.select('phe18', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+11.31,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('phe','CD1'),('rphe_i','CD1'))] = cmd.select('phe19', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+12.99,resSelectionSubs('phe_i','CD1',subs)))
IDSpec[(('phe','CD1'),('rphe_i','CE1'))] = cmd.select('phe20', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+14.28,resSelectionSubs('phe_i','CE1',subs)))
IDSpec[(('phe','CD1'),('rphe_i','CZ'))] = cmd.select('phe21', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+14.63,resSelectionSubs('phe_i','CZ',subs)))
IDSpec[(('phe','CE1'),('rphe_i','CD1'))] = cmd.select('phe22', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+13.76,resSelectionSubs('phe_i','CD1',subs)))
IDSpec[(('phe','CE1'),('rphe_i','CE1'))] = cmd.select('phe23', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+14.99,resSelectionSubs('phe_i','CE1',subs)))
IDSpec[(('phe','CE1'),('rphe_i','CZ'))] = cmd.select('phe24', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+15.22,resSelectionSubs('phe_i','CZ',subs)))
IDSpec[(('phe','CZ'),('rphe_i','CD1'))] = cmd.select('phe25', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+15.10,resSelectionSubs('phe_i','CD1',subs)))
IDSpec[(('phe','CZ'),('rphe_i','CE1'))] = cmd.select('phe26', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+16.34,resSelectionSubs('phe_i','CE1',subs)))
IDSpec[(('phe','CZ'),('rphe_i','CZ'))] = cmd.select('phe27', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+16.58,resSelectionSubs('phe_i','CZ',subs)))
IDSpec[(('phe','CD1'),('rlys','CD'))] = cmd.select('phe28', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+13.79,resSelectionSubs('lys','CD',subs)))
IDSpec[(('phe','CD1'),('rlys','CE'))] = cmd.select('phe29', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+13.22,resSelectionSubs('lys','CE',subs)))
IDSpec[(('phe','CD1'),('rlys','NZ'))] = cmd.select('phe30', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+13.82,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('phe','CE1'),('rlys','CD'))] = cmd.select('phe31', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+13.52,resSelectionSubs('lys','CD',subs)))
IDSpec[(('phe','CE1'),('rlys','CE'))] = cmd.select('phe32', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+13.12,resSelectionSubs('lys','CE',subs)))
IDSpec[(('phe','CE1'),('rlys','NZ'))] = cmd.select('phe33', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+13.84,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('phe','CZ'),('rlys','CD'))] = cmd.select('phe34', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+14.17,resSelectionSubs('lys','CD',subs)))
IDSpec[(('phe','CZ'),('rlys','CE'))] = cmd.select('phe35', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+13.83,resSelectionSubs('lys','CE',subs)))
IDSpec[(('phe','CZ'),('rlys','NZ'))] = cmd.select('phe36', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+14.68,resSelectionSubs('lys','NZ',subs)))
IDSpec['phe'] = cmd.select('phe',' br. phe1&br. phe2&br. phe3&br. phe4&br. phe5&br. phe6&br. phe7&br. phe8&br. phe9&br. phe10&br. phe11&br. phe12&br. phe13&br. phe14&br. phe15&br. phe16&br. phe17&br. phe18&br. phe19&br. phe20&br. phe21&br. phe22&br. phe23&br. phe24&br. phe25&br. phe26&br. phe27&br. phe28&br. phe29&br. phe30&br. phe31&br. phe32&br. phe33&br. phe34&br. phe35&br. phe36')
IDSpec['r_phe'] = cmd.count_atoms(resSelectionSubs('phe', subs=subs, selection=True))
cmd.delete('phe1')
cmd.delete('phe2')
cmd.delete('phe3')
cmd.delete('phe4')
cmd.delete('phe5')
cmd.delete('phe6')
cmd.delete('phe7')
cmd.delete('phe8')
cmd.delete('phe9')
cmd.delete('phe10')
cmd.delete('phe11')
cmd.delete('phe12')
cmd.delete('phe13')
cmd.delete('phe14')
cmd.delete('phe15')
cmd.delete('phe16')
cmd.delete('phe17')
cmd.delete('phe18')
cmd.delete('phe19')
cmd.delete('phe20')
cmd.delete('phe21')
cmd.delete('phe22')
cmd.delete('phe23')
cmd.delete('phe24')
cmd.delete('phe25')
cmd.delete('phe26')
cmd.delete('phe27')
cmd.delete('phe28')
cmd.delete('phe29')
cmd.delete('phe30')
cmd.delete('phe31')
cmd.delete('phe32')
cmd.delete('phe33')
cmd.delete('phe34')
cmd.delete('phe35')
cmd.delete('phe36')
IDSpec[(('his','CE1'),('sphe','CD1'))] = cmd.select('his1', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+9.05,resSelectionSubs('phe','CD1',subs,selection=True)))
IDSpec[(('his','CE1'),('sphe','CE1'))] = cmd.select('his2', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+8.86,resSelectionSubs('phe','CE1',subs,selection=True)))
IDSpec[(('his','CE1'),('sphe','CZ'))] = cmd.select('his3', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+9.45,resSelectionSubs('phe','CZ',subs,selection=True)))
IDSpec[(('his','ND1'),('sphe','CD1'))] = cmd.select('his4', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+9.86,resSelectionSubs('phe','CD1',subs,selection=True)))
IDSpec[(('his','ND1'),('sphe','CE1'))] = cmd.select('his5', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+9.46,resSelectionSubs('phe','CE1',subs,selection=True)))
IDSpec[(('his','ND1'),('sphe','CZ'))] = cmd.select('his6', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+9.91,resSelectionSubs('phe','CZ',subs,selection=True)))
IDSpec[(('his','NE2'),('sphe','CD1'))] = cmd.select('his7', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+9.72,resSelectionSubs('phe','CD1',subs,selection=True)))
IDSpec[(('his','NE2'),('sphe','CE1'))] = cmd.select('his8', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+9.70,resSelectionSubs('phe','CE1',subs,selection=True)))
IDSpec[(('his','NE2'),('sphe','CZ'))] = cmd.select('his9', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+10.24,resSelectionSubs('phe','CZ',subs,selection=True)))
IDSpec[(('his','CE1'),('rhis_i','CE1'))] = cmd.select('his10', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.20,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('his','CE1'),('rhis_i','ND1'))] = cmd.select('his11', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.39,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('his','CE1'),('rhis_i','NE2'))] = cmd.select('his12', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.21,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('his','ND1'),('rhis_i','CE1'))] = cmd.select('his13', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.08,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('his','ND1'),('rhis_i','ND1'))] = cmd.select('his14', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+8.14,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('his','ND1'),('rhis_i','NE2'))] = cmd.select('his15', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.06,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('his','NE2'),('rhis_i','CE1'))] = cmd.select('his16', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.12,resSelectionSubs('his_i','CE1',subs)))
IDSpec[(('his','NE2'),('rhis_i','ND1'))] = cmd.select('his17', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+7.24,resSelectionSubs('his_i','ND1',subs)))
IDSpec[(('his','NE2'),('rhis_i','NE2'))] = cmd.select('his18', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.52,resSelectionSubs('his_i','NE2',subs)))
IDSpec[(('his','CE1'),('rphe_i','CD1'))] = cmd.select('his19', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+12.11,resSelectionSubs('phe_i','CD1',subs)))
IDSpec[(('his','CE1'),('rphe_i','CE1'))] = cmd.select('his20', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+13.05,resSelectionSubs('phe_i','CE1',subs)))
IDSpec[(('his','CE1'),('rphe_i','CZ'))] = cmd.select('his21', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+13.04,resSelectionSubs('phe_i','CZ',subs)))
IDSpec[(('his','ND1'),('rphe_i','CD1'))] = cmd.select('his22', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+13.12,resSelectionSubs('phe_i','CD1',subs)))
IDSpec[(('his','ND1'),('rphe_i','CE1'))] = cmd.select('his23', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+13.99,resSelectionSubs('phe_i','CE1',subs)))
IDSpec[(('his','ND1'),('rphe_i','CZ'))] = cmd.select('his24', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+13.87,resSelectionSubs('phe_i','CZ',subs)))
IDSpec[(('his','NE2'),('rphe_i','CD1'))] = cmd.select('his25', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+12.16,resSelectionSubs('phe_i','CD1',subs)))
IDSpec[(('his','NE2'),('rphe_i','CE1'))] = cmd.select('his26', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+13.09,resSelectionSubs('phe_i','CE1',subs)))
IDSpec[(('his','NE2'),('rphe_i','CZ'))] = cmd.select('his27', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+13.17,resSelectionSubs('phe_i','CZ',subs)))
IDSpec[(('his','CE1'),('rlys','CD'))] = cmd.select('his28', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.03,resSelectionSubs('lys','CD',subs)))
IDSpec[(('his','CE1'),('rlys','CE'))] = cmd.select('his29', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.49,resSelectionSubs('lys','CE',subs)))
IDSpec[(('his','CE1'),('rlys','NZ'))] = cmd.select('his30', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.52,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('his','ND1'),('rlys','CD'))] = cmd.select('his31', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+6.50,resSelectionSubs('lys','CD',subs)))
IDSpec[(('his','ND1'),('rlys','CE'))] = cmd.select('his32', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+6.34,resSelectionSubs('lys','CE',subs)))
IDSpec[(('his','ND1'),('rlys','NZ'))] = cmd.select('his33', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.60,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('his','NE2'),('rlys','CD'))] = cmd.select('his34', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+7.03,resSelectionSubs('lys','CD',subs)))
IDSpec[(('his','NE2'),('rlys','CE'))] = cmd.select('his35', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.21,resSelectionSubs('lys','CE',subs)))
IDSpec[(('his','NE2'),('rlys','NZ'))] = cmd.select('his36', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+7.23,resSelectionSubs('lys','NZ',subs)))
IDSpec['his'] = cmd.select('his',' br. his1&br. his2&br. his3&br. his4&br. his5&br. his6&br. his7&br. his8&br. his9&br. his10&br. his11&br. his12&br. his13&br. his14&br. his15&br. his16&br. his17&br. his18&br. his19&br. his20&br. his21&br. his22&br. his23&br. his24&br. his25&br. his26&br. his27&br. his28&br. his29&br. his30&br. his31&br. his32&br. his33&br. his34&br. his35&br. his36')
IDSpec['r_his'] = cmd.count_atoms(resSelectionSubs('his', subs=subs, selection=True))
cmd.delete('his1')
cmd.delete('his2')
cmd.delete('his3')
cmd.delete('his4')
cmd.delete('his5')
cmd.delete('his6')
cmd.delete('his7')
cmd.delete('his8')
cmd.delete('his9')
cmd.delete('his10')
cmd.delete('his11')
cmd.delete('his12')
cmd.delete('his13')
cmd.delete('his14')
cmd.delete('his15')
cmd.delete('his16')
cmd.delete('his17')
cmd.delete('his18')
cmd.delete('his19')
cmd.delete('his20')
cmd.delete('his21')
cmd.delete('his22')
cmd.delete('his23')
cmd.delete('his24')
cmd.delete('his25')
cmd.delete('his26')
cmd.delete('his27')
cmd.delete('his28')
cmd.delete('his29')
cmd.delete('his30')
cmd.delete('his31')
cmd.delete('his32')
cmd.delete('his33')
cmd.delete('his34')
cmd.delete('his35')
cmd.delete('his36')
IDSpec[(('his_i','CE1'),('sphe','CD1'))] = cmd.select('his_i1', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+10.68,resSelectionSubs('phe','CD1',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sphe','CE1'))] = cmd.select('his_i2', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+10.97,resSelectionSubs('phe','CE1',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sphe','CZ'))] = cmd.select('his_i3', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+12.01,resSelectionSubs('phe','CZ',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sphe','CD1'))] = cmd.select('his_i4', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+11.88,resSelectionSubs('phe','CD1',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sphe','CE1'))] = cmd.select('his_i5', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+12.20,resSelectionSubs('phe','CE1',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sphe','CZ'))] = cmd.select('his_i6', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+13.28,resSelectionSubs('phe','CZ',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sphe','CD1'))] = cmd.select('his_i7', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+9.97,resSelectionSubs('phe','CD1',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sphe','CE1'))] = cmd.select('his_i8', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+10.20,resSelectionSubs('phe','CE1',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sphe','CZ'))] = cmd.select('his_i9', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+11.31,resSelectionSubs('phe','CZ',subs,selection=True)))
IDSpec[(('his_i','CE1'),('shis','CE1'))] = cmd.select('his_i10', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.20,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('his_i','CE1'),('shis','ND1'))] = cmd.select('his_i11', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.08,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('his_i','CE1'),('shis','NE2'))] = cmd.select('his_i12', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.12,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('his_i','ND1'),('shis','CE1'))] = cmd.select('his_i13', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.39,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('his_i','ND1'),('shis','ND1'))] = cmd.select('his_i14', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+8.14,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('his_i','ND1'),('shis','NE2'))] = cmd.select('his_i15', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.24,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('his_i','NE2'),('shis','CE1'))] = cmd.select('his_i16', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.21,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('his_i','NE2'),('shis','ND1'))] = cmd.select('his_i17', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+7.06,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('his_i','NE2'),('shis','NE2'))] = cmd.select('his_i18', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.52,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('his_i','CE1'),('rphe_i','CD1'))] = cmd.select('his_i19', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+8.34,resSelectionSubs('phe_i','CD1',subs)))
IDSpec[(('his_i','CE1'),('rphe_i','CE1'))] = cmd.select('his_i20', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+9.11,resSelectionSubs('phe_i','CE1',subs)))
IDSpec[(('his_i','CE1'),('rphe_i','CZ'))] = cmd.select('his_i21', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+9.11,resSelectionSubs('phe_i','CZ',subs)))
IDSpec[(('his_i','ND1'),('rphe_i','CD1'))] = cmd.select('his_i22', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.84,resSelectionSubs('phe_i','CD1',subs)))
IDSpec[(('his_i','ND1'),('rphe_i','CE1'))] = cmd.select('his_i23', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+8.40,resSelectionSubs('phe_i','CE1',subs)))
IDSpec[(('his_i','ND1'),('rphe_i','CZ'))] = cmd.select('his_i24', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+8.30,resSelectionSubs('phe_i','CZ',subs)))
IDSpec[(('his_i','NE2'),('rphe_i','CD1'))] = cmd.select('his_i25', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+8.12,resSelectionSubs('phe_i','CD1',subs)))
IDSpec[(('his_i','NE2'),('rphe_i','CE1'))] = cmd.select('his_i26', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+8.94,resSelectionSubs('phe_i','CE1',subs)))
IDSpec[(('his_i','NE2'),('rphe_i','CZ'))] = cmd.select('his_i27', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+8.84,resSelectionSubs('phe_i','CZ',subs)))
IDSpec[(('his_i','CE1'),('rlys','CD'))] = cmd.select('his_i28', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.24,resSelectionSubs('lys','CD',subs)))
IDSpec[(('his_i','CE1'),('rlys','CE'))] = cmd.select('his_i29', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.06,resSelectionSubs('lys','CE',subs)))
IDSpec[(('his_i','CE1'),('rlys','NZ'))] = cmd.select('his_i30', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+5.76,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('his_i','ND1'),('rlys','CD'))] = cmd.select('his_i31', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.34,resSelectionSubs('lys','CD',subs)))
IDSpec[(('his_i','ND1'),('rlys','CE'))] = cmd.select('his_i32', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+6.16,resSelectionSubs('lys','CE',subs)))
IDSpec[(('his_i','ND1'),('rlys','NZ'))] = cmd.select('his_i33', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+5.37,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('his_i','NE2'),('rlys','CD'))] = cmd.select('his_i34', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+7.64,resSelectionSubs('lys','CD',subs)))
IDSpec[(('his_i','NE2'),('rlys','CE'))] = cmd.select('his_i35', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.74,resSelectionSubs('lys','CE',subs)))
IDSpec[(('his_i','NE2'),('rlys','NZ'))] = cmd.select('his_i36', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.55,resSelectionSubs('lys','NZ',subs)))
IDSpec['his_i'] = cmd.select('his_i',' br. his_i1&br. his_i2&br. his_i3&br. his_i4&br. his_i5&br. his_i6&br. his_i7&br. his_i8&br. his_i9&br. his_i10&br. his_i11&br. his_i12&br. his_i13&br. his_i14&br. his_i15&br. his_i16&br. his_i17&br. his_i18&br. his_i19&br. his_i20&br. his_i21&br. his_i22&br. his_i23&br. his_i24&br. his_i25&br. his_i26&br. his_i27&br. his_i28&br. his_i29&br. his_i30&br. his_i31&br. his_i32&br. his_i33&br. his_i34&br. his_i35&br. his_i36')
IDSpec['r_his_i'] = cmd.count_atoms(resSelectionSubs('his_i', subs=subs, selection=True))
cmd.delete('his_i1')
cmd.delete('his_i2')
cmd.delete('his_i3')
cmd.delete('his_i4')
cmd.delete('his_i5')
cmd.delete('his_i6')
cmd.delete('his_i7')
cmd.delete('his_i8')
cmd.delete('his_i9')
cmd.delete('his_i10')
cmd.delete('his_i11')
cmd.delete('his_i12')
cmd.delete('his_i13')
cmd.delete('his_i14')
cmd.delete('his_i15')
cmd.delete('his_i16')
cmd.delete('his_i17')
cmd.delete('his_i18')
cmd.delete('his_i19')
cmd.delete('his_i20')
cmd.delete('his_i21')
cmd.delete('his_i22')
cmd.delete('his_i23')
cmd.delete('his_i24')
cmd.delete('his_i25')
cmd.delete('his_i26')
cmd.delete('his_i27')
cmd.delete('his_i28')
cmd.delete('his_i29')
cmd.delete('his_i30')
cmd.delete('his_i31')
cmd.delete('his_i32')
cmd.delete('his_i33')
cmd.delete('his_i34')
cmd.delete('his_i35')
cmd.delete('his_i36')
IDSpec[(('phe_i','CD1'),('sphe','CD1'))] = cmd.select('phe_i1', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+12.99,resSelectionSubs('phe','CD1',subs,selection=True)))
IDSpec[(('phe_i','CD1'),('sphe','CE1'))] = cmd.select('phe_i2', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+13.76,resSelectionSubs('phe','CE1',subs,selection=True)))
IDSpec[(('phe_i','CD1'),('sphe','CZ'))] = cmd.select('phe_i3', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+15.10,resSelectionSubs('phe','CZ',subs,selection=True)))
IDSpec[(('phe_i','CE1'),('sphe','CD1'))] = cmd.select('phe_i4', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+14.28,resSelectionSubs('phe','CD1',subs,selection=True)))
IDSpec[(('phe_i','CE1'),('sphe','CE1'))] = cmd.select('phe_i5', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+14.99,resSelectionSubs('phe','CE1',subs,selection=True)))
IDSpec[(('phe_i','CE1'),('sphe','CZ'))] = cmd.select('phe_i6', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+16.34,resSelectionSubs('phe','CZ',subs,selection=True)))
IDSpec[(('phe_i','CZ'),('sphe','CD1'))] = cmd.select('phe_i7', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+14.63,resSelectionSubs('phe','CD1',subs,selection=True)))
IDSpec[(('phe_i','CZ'),('sphe','CE1'))] = cmd.select('phe_i8', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+15.22,resSelectionSubs('phe','CE1',subs,selection=True)))
IDSpec[(('phe_i','CZ'),('sphe','CZ'))] = cmd.select('phe_i9', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+16.58,resSelectionSubs('phe','CZ',subs,selection=True)))
IDSpec[(('phe_i','CD1'),('shis','CE1'))] = cmd.select('phe_i10', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+12.11,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('phe_i','CD1'),('shis','ND1'))] = cmd.select('phe_i11', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+13.12,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('phe_i','CD1'),('shis','NE2'))] = cmd.select('phe_i12', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+12.16,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('phe_i','CE1'),('shis','CE1'))] = cmd.select('phe_i13', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+13.05,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('phe_i','CE1'),('shis','ND1'))] = cmd.select('phe_i14', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+13.99,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('phe_i','CE1'),('shis','NE2'))] = cmd.select('phe_i15', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+13.09,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('phe_i','CZ'),('shis','CE1'))] = cmd.select('phe_i16', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+13.04,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('phe_i','CZ'),('shis','ND1'))] = cmd.select('phe_i17', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+13.87,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('phe_i','CZ'),('shis','NE2'))] = cmd.select('phe_i18', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+13.17,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('phe_i','CD1'),('shis_i','CE1'))] = cmd.select('phe_i19', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+8.34,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('phe_i','CD1'),('shis_i','ND1'))] = cmd.select('phe_i20', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+7.84,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('phe_i','CD1'),('shis_i','NE2'))] = cmd.select('phe_i21', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+8.12,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('phe_i','CE1'),('shis_i','CE1'))] = cmd.select('phe_i22', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+9.11,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('phe_i','CE1'),('shis_i','ND1'))] = cmd.select('phe_i23', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+8.40,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('phe_i','CE1'),('shis_i','NE2'))] = cmd.select('phe_i24', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+8.94,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('phe_i','CZ'),('shis_i','CE1'))] = cmd.select('phe_i25', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+9.11,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('phe_i','CZ'),('shis_i','ND1'))] = cmd.select('phe_i26', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+8.30,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('phe_i','CZ'),('shis_i','NE2'))] = cmd.select('phe_i27', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+8.84,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('phe_i','CD1'),('rlys','CD'))] = cmd.select('phe_i28', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+13.02,resSelectionSubs('lys','CD',subs)))
IDSpec[(('phe_i','CD1'),('rlys','CE'))] = cmd.select('phe_i29', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+11.97,resSelectionSubs('lys','CE',subs)))
IDSpec[(('phe_i','CD1'),('rlys','NZ'))] = cmd.select('phe_i30', '%s w. %s of %s'%(resSelectionSubs('phe','CD1',subs),d+11.02,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('phe_i','CE1'),('rlys','CD'))] = cmd.select('phe_i31', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+13.43,resSelectionSubs('lys','CD',subs)))
IDSpec[(('phe_i','CE1'),('rlys','CE'))] = cmd.select('phe_i32', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+12.44,resSelectionSubs('lys','CE',subs)))
IDSpec[(('phe_i','CE1'),('rlys','NZ'))] = cmd.select('phe_i33', '%s w. %s of %s'%(resSelectionSubs('phe','CE1',subs),d+11.35,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('phe_i','CZ'),('rlys','CD'))] = cmd.select('phe_i34', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+12.97,resSelectionSubs('lys','CD',subs)))
IDSpec[(('phe_i','CZ'),('rlys','CE'))] = cmd.select('phe_i35', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+12.13,resSelectionSubs('lys','CE',subs)))
IDSpec[(('phe_i','CZ'),('rlys','NZ'))] = cmd.select('phe_i36', '%s w. %s of %s'%(resSelectionSubs('phe','CZ',subs),d+11.00,resSelectionSubs('lys','NZ',subs)))
IDSpec['phe_i'] = cmd.select('phe_i',' br. phe_i1&br. phe_i2&br. phe_i3&br. phe_i4&br. phe_i5&br. phe_i6&br. phe_i7&br. phe_i8&br. phe_i9&br. phe_i10&br. phe_i11&br. phe_i12&br. phe_i13&br. phe_i14&br. phe_i15&br. phe_i16&br. phe_i17&br. phe_i18&br. phe_i19&br. phe_i20&br. phe_i21&br. phe_i22&br. phe_i23&br. phe_i24&br. phe_i25&br. phe_i26&br. phe_i27&br. phe_i28&br. phe_i29&br. phe_i30&br. phe_i31&br. phe_i32&br. phe_i33&br. phe_i34&br. phe_i35&br. phe_i36')
IDSpec['r_phe_i'] = cmd.count_atoms(resSelectionSubs('phe_i', subs=subs, selection=True))
cmd.delete('phe_i1')
cmd.delete('phe_i2')
cmd.delete('phe_i3')
cmd.delete('phe_i4')
cmd.delete('phe_i5')
cmd.delete('phe_i6')
cmd.delete('phe_i7')
cmd.delete('phe_i8')
cmd.delete('phe_i9')
cmd.delete('phe_i10')
cmd.delete('phe_i11')
cmd.delete('phe_i12')
cmd.delete('phe_i13')
cmd.delete('phe_i14')
cmd.delete('phe_i15')
cmd.delete('phe_i16')
cmd.delete('phe_i17')
cmd.delete('phe_i18')
cmd.delete('phe_i19')
cmd.delete('phe_i20')
cmd.delete('phe_i21')
cmd.delete('phe_i22')
cmd.delete('phe_i23')
cmd.delete('phe_i24')
cmd.delete('phe_i25')
cmd.delete('phe_i26')
cmd.delete('phe_i27')
cmd.delete('phe_i28')
cmd.delete('phe_i29')
cmd.delete('phe_i30')
cmd.delete('phe_i31')
cmd.delete('phe_i32')
cmd.delete('phe_i33')
cmd.delete('phe_i34')
cmd.delete('phe_i35')
cmd.delete('phe_i36')
IDSpec[(('lys','CD'),('sphe','CD1'))] = cmd.select('lys1', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+13.79,resSelectionSubs('phe','CD1',subs,selection=True)))
IDSpec[(('lys','CD'),('sphe','CE1'))] = cmd.select('lys2', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+13.52,resSelectionSubs('phe','CE1',subs,selection=True)))
IDSpec[(('lys','CD'),('sphe','CZ'))] = cmd.select('lys3', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+14.17,resSelectionSubs('phe','CZ',subs,selection=True)))
IDSpec[(('lys','CE'),('sphe','CD1'))] = cmd.select('lys4', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+13.22,resSelectionSubs('phe','CD1',subs,selection=True)))
IDSpec[(('lys','CE'),('sphe','CE1'))] = cmd.select('lys5', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+13.12,resSelectionSubs('phe','CE1',subs,selection=True)))
IDSpec[(('lys','CE'),('sphe','CZ'))] = cmd.select('lys6', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+13.83,resSelectionSubs('phe','CZ',subs,selection=True)))
IDSpec[(('lys','NZ'),('sphe','CD1'))] = cmd.select('lys7', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+13.82,resSelectionSubs('phe','CD1',subs,selection=True)))
IDSpec[(('lys','NZ'),('sphe','CE1'))] = cmd.select('lys8', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+13.84,resSelectionSubs('phe','CE1',subs,selection=True)))
IDSpec[(('lys','NZ'),('sphe','CZ'))] = cmd.select('lys9', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+14.68,resSelectionSubs('phe','CZ',subs,selection=True)))
IDSpec[(('lys','CD'),('shis','CE1'))] = cmd.select('lys10', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+7.03,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('lys','CD'),('shis','ND1'))] = cmd.select('lys11', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+6.50,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('lys','CD'),('shis','NE2'))] = cmd.select('lys12', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+7.03,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('lys','CE'),('shis','CE1'))] = cmd.select('lys13', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+6.49,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('lys','CE'),('shis','ND1'))] = cmd.select('lys14', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+6.34,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('lys','CE'),('shis','NE2'))] = cmd.select('lys15', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+6.21,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('lys','NZ'),('shis','CE1'))] = cmd.select('lys16', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+7.52,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('lys','NZ'),('shis','ND1'))] = cmd.select('lys17', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+7.60,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('lys','NZ'),('shis','NE2'))] = cmd.select('lys18', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+7.23,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('lys','CD'),('shis_i','CE1'))] = cmd.select('lys19', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+7.24,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('lys','CD'),('shis_i','ND1'))] = cmd.select('lys20', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+7.34,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('lys','CD'),('shis_i','NE2'))] = cmd.select('lys21', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+7.64,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('lys','CE'),('shis_i','CE1'))] = cmd.select('lys22', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+6.06,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('lys','CE'),('shis_i','ND1'))] = cmd.select('lys23', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+6.16,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('lys','CE'),('shis_i','NE2'))] = cmd.select('lys24', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+6.74,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('lys','NZ'),('shis_i','CE1'))] = cmd.select('lys25', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+5.76,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('lys','NZ'),('shis_i','ND1'))] = cmd.select('lys26', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+5.37,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('lys','NZ'),('shis_i','NE2'))] = cmd.select('lys27', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+6.55,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('lys','CD'),('sphe_i','CD1'))] = cmd.select('lys28', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+13.02,resSelectionSubs('phe_i','CD1',subs,selection=True)))
IDSpec[(('lys','CD'),('sphe_i','CE1'))] = cmd.select('lys29', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+13.43,resSelectionSubs('phe_i','CE1',subs,selection=True)))
IDSpec[(('lys','CD'),('sphe_i','CZ'))] = cmd.select('lys30', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+12.97,resSelectionSubs('phe_i','CZ',subs,selection=True)))
IDSpec[(('lys','CE'),('sphe_i','CD1'))] = cmd.select('lys31', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+11.97,resSelectionSubs('phe_i','CD1',subs,selection=True)))
IDSpec[(('lys','CE'),('sphe_i','CE1'))] = cmd.select('lys32', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+12.44,resSelectionSubs('phe_i','CE1',subs,selection=True)))
IDSpec[(('lys','CE'),('sphe_i','CZ'))] = cmd.select('lys33', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+12.13,resSelectionSubs('phe_i','CZ',subs,selection=True)))
IDSpec[(('lys','NZ'),('sphe_i','CD1'))] = cmd.select('lys34', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+11.02,resSelectionSubs('phe_i','CD1',subs,selection=True)))
IDSpec[(('lys','NZ'),('sphe_i','CE1'))] = cmd.select('lys35', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+11.35,resSelectionSubs('phe_i','CE1',subs,selection=True)))
IDSpec[(('lys','NZ'),('sphe_i','CZ'))] = cmd.select('lys36', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+11.00,resSelectionSubs('phe_i','CZ',subs,selection=True)))
IDSpec['lys'] = cmd.select('lys',' br. lys1&br. lys2&br. lys3&br. lys4&br. lys5&br. lys6&br. lys7&br. lys8&br. lys9&br. lys10&br. lys11&br. lys12&br. lys13&br. lys14&br. lys15&br. lys16&br. lys17&br. lys18&br. lys19&br. lys20&br. lys21&br. lys22&br. lys23&br. lys24&br. lys25&br. lys26&br. lys27&br. lys28&br. lys29&br. lys30&br. lys31&br. lys32&br. lys33&br. lys34&br. lys35&br. lys36')
IDSpec['r_lys'] = cmd.count_atoms(resSelectionSubs('lys', subs=subs, selection=True))
cmd.delete('lys1')
cmd.delete('lys2')
cmd.delete('lys3')
cmd.delete('lys4')
cmd.delete('lys5')
cmd.delete('lys6')
cmd.delete('lys7')
cmd.delete('lys8')
cmd.delete('lys9')
cmd.delete('lys10')
cmd.delete('lys11')
cmd.delete('lys12')
cmd.delete('lys13')
cmd.delete('lys14')
cmd.delete('lys15')
cmd.delete('lys16')
cmd.delete('lys17')
cmd.delete('lys18')
cmd.delete('lys19')
cmd.delete('lys20')
cmd.delete('lys21')
cmd.delete('lys22')
cmd.delete('lys23')
cmd.delete('lys24')
cmd.delete('lys25')
cmd.delete('lys26')
cmd.delete('lys27')
cmd.delete('lys28')
cmd.delete('lys29')
cmd.delete('lys30')
cmd.delete('lys31')
cmd.delete('lys32')
cmd.delete('lys33')
cmd.delete('lys34')
cmd.delete('lys35')
cmd.delete('lys36')
IDSpec['S_2c9h_2_3_1_41'] = cmd.select('S_2c9h_2_3_1_41', 'phe|his|his_i|phe_i|lys')
cmd.delete('phe')
cmd.delete('his')
cmd.delete('his_i')
cmd.delete('phe_i')
cmd.delete('lys')
