'''
FUNC:S_2j63_4_2_99_18
PDB:2j63
EC:4.2.99.18
RESI:asn,tyr,asp,asn,asp,his
LOCI:a-136,276,335,337,411,437;
'''
IDSpec[(('asn','CG'),('rasn_i','CG'))] = cmd.select('asn1', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+9.88,resSelectionSubs('asn_i','CG',subs)))
IDSpec[(('asn','CG'),('rasn_i','ND2'))] = cmd.select('asn2', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+9.46,resSelectionSubs('asn_i','ND2',subs)))
IDSpec[(('asn','CG'),('rasn_i','OD1'))] = cmd.select('asn3', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+9.55,resSelectionSubs('asn_i','OD1',subs)))
IDSpec[(('asn','ND2'),('rasn_i','CG'))] = cmd.select('asn4', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+8.62,resSelectionSubs('asn_i','CG',subs)))
IDSpec[(('asn','ND2'),('rasn_i','ND2'))] = cmd.select('asn5', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+8.15,resSelectionSubs('asn_i','ND2',subs)))
IDSpec[(('asn','ND2'),('rasn_i','OD1'))] = cmd.select('asn6', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+8.38,resSelectionSubs('asn_i','OD1',subs)))
IDSpec[(('asn','OD1'),('rasn_i','CG'))] = cmd.select('asn7', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+10.72,resSelectionSubs('asn_i','CG',subs)))
IDSpec[(('asn','OD1'),('rasn_i','ND2'))] = cmd.select('asn8', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+10.22,resSelectionSubs('asn_i','ND2',subs)))
IDSpec[(('asn','OD1'),('rasn_i','OD1'))] = cmd.select('asn9', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+10.37,resSelectionSubs('asn_i','OD1',subs)))
IDSpec[(('asn','CG'),('rasp','CG'))] = cmd.select('asn10', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+6.68,resSelectionSubs('asp','CG',subs)))
IDSpec[(('asn','CG'),('rasp','OD1'))] = cmd.select('asn11', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+7.87,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('asn','CG'),('rasp','OD2'))] = cmd.select('asn12', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+5.83,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('asn','ND2'),('rasp','CG'))] = cmd.select('asn13', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+5.66,resSelectionSubs('asp','CG',subs)))
IDSpec[(('asn','ND2'),('rasp','OD1'))] = cmd.select('asn14', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+6.84,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('asn','ND2'),('rasp','OD2'))] = cmd.select('asn15', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+4.72,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('asn','OD1'),('rasp','CG'))] = cmd.select('asn16', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+7.83,resSelectionSubs('asp','CG',subs)))
IDSpec[(('asn','OD1'),('rasp','OD1'))] = cmd.select('asn17', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+9.01,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('asn','OD1'),('rasp','OD2'))] = cmd.select('asn18', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+6.89,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('asn','CG'),('rasp_i','CG'))] = cmd.select('asn19', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+8.31,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('asn','CG'),('rasp_i','OD1'))] = cmd.select('asn20', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+8.43,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('asn','CG'),('rasp_i','OD2'))] = cmd.select('asn21', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+7.30,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('asn','ND2'),('rasp_i','CG'))] = cmd.select('asn22', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+8.26,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('asn','ND2'),('rasp_i','OD1'))] = cmd.select('asn23', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+8.44,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('asn','ND2'),('rasp_i','OD2'))] = cmd.select('asn24', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+7.20,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('asn','OD1'),('rasp_i','CG'))] = cmd.select('asn25', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+9.43,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('asn','OD1'),('rasp_i','OD1'))] = cmd.select('asn26', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+9.48,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('asn','OD1'),('rasp_i','OD2'))] = cmd.select('asn27', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+8.47,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('asn','CG'),('rhis','CE1'))] = cmd.select('asn28', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+5.72,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asn','CG'),('rhis','ND1'))] = cmd.select('asn29', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+5.56,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asn','CG'),('rhis','NE2'))] = cmd.select('asn30', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+6.19,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asn','ND2'),('rhis','CE1'))] = cmd.select('asn31', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+5.60,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asn','ND2'),('rhis','ND1'))] = cmd.select('asn32', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+5.91,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asn','ND2'),('rhis','NE2'))] = cmd.select('asn33', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+5.96,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asn','OD1'),('rhis','CE1'))] = cmd.select('asn34', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+6.36,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asn','OD1'),('rhis','ND1'))] = cmd.select('asn35', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+6.00,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asn','OD1'),('rhis','NE2'))] = cmd.select('asn36', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+7.09,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asn','CG'),('rtyr','CE1'))] = cmd.select('asn37', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+6.91,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('asn','CG'),('rtyr','CZ'))] = cmd.select('asn38', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+7.66,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('asn','CG'),('rtyr','OH'))] = cmd.select('asn39', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+8.04,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('asn','ND2'),('rtyr','CE1'))] = cmd.select('asn40', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+5.68,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('asn','ND2'),('rtyr','CZ'))] = cmd.select('asn41', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+6.57,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('asn','ND2'),('rtyr','OH'))] = cmd.select('asn42', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+7.00,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('asn','OD1'),('rtyr','CE1'))] = cmd.select('asn43', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+7.39,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('asn','OD1'),('rtyr','CZ'))] = cmd.select('asn44', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+7.88,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('asn','OD1'),('rtyr','OH'))] = cmd.select('asn45', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+8.13,resSelectionSubs('tyr','OH',subs)))
IDSpec['asn'] = cmd.select('asn',' br. asn1&br. asn2&br. asn3&br. asn4&br. asn5&br. asn6&br. asn7&br. asn8&br. asn9&br. asn10&br. asn11&br. asn12&br. asn13&br. asn14&br. asn15&br. asn16&br. asn17&br. asn18&br. asn19&br. asn20&br. asn21&br. asn22&br. asn23&br. asn24&br. asn25&br. asn26&br. asn27&br. asn28&br. asn29&br. asn30&br. asn31&br. asn32&br. asn33&br. asn34&br. asn35&br. asn36&br. asn37&br. asn38&br. asn39&br. asn40&br. asn41&br. asn42&br. asn43&br. asn44&br. asn45')
IDSpec['r_asn'] = cmd.count_atoms(resSelectionSubs('asn', subs=subs, selection=True))
cmd.delete('asn1')
cmd.delete('asn2')
cmd.delete('asn3')
cmd.delete('asn4')
cmd.delete('asn5')
cmd.delete('asn6')
cmd.delete('asn7')
cmd.delete('asn8')
cmd.delete('asn9')
cmd.delete('asn10')
cmd.delete('asn11')
cmd.delete('asn12')
cmd.delete('asn13')
cmd.delete('asn14')
cmd.delete('asn15')
cmd.delete('asn16')
cmd.delete('asn17')
cmd.delete('asn18')
cmd.delete('asn19')
cmd.delete('asn20')
cmd.delete('asn21')
cmd.delete('asn22')
cmd.delete('asn23')
cmd.delete('asn24')
cmd.delete('asn25')
cmd.delete('asn26')
cmd.delete('asn27')
cmd.delete('asn28')
cmd.delete('asn29')
cmd.delete('asn30')
cmd.delete('asn31')
cmd.delete('asn32')
cmd.delete('asn33')
cmd.delete('asn34')
cmd.delete('asn35')
cmd.delete('asn36')
cmd.delete('asn37')
cmd.delete('asn38')
cmd.delete('asn39')
cmd.delete('asn40')
cmd.delete('asn41')
cmd.delete('asn42')
cmd.delete('asn43')
cmd.delete('asn44')
cmd.delete('asn45')
IDSpec[(('asn_i','CG'),('sasn','CG'))] = cmd.select('asn_i1', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+9.88,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('asn_i','CG'),('sasn','ND2'))] = cmd.select('asn_i2', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+8.62,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('asn_i','CG'),('sasn','OD1'))] = cmd.select('asn_i3', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+10.72,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('asn_i','ND2'),('sasn','CG'))] = cmd.select('asn_i4', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+9.46,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('asn_i','ND2'),('sasn','ND2'))] = cmd.select('asn_i5', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+8.15,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('asn_i','ND2'),('sasn','OD1'))] = cmd.select('asn_i6', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+10.22,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('asn_i','OD1'),('sasn','CG'))] = cmd.select('asn_i7', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+9.55,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('asn_i','OD1'),('sasn','ND2'))] = cmd.select('asn_i8', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+8.38,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('asn_i','OD1'),('sasn','OD1'))] = cmd.select('asn_i9', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+10.37,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('asn_i','CG'),('rasp','CG'))] = cmd.select('asn_i10', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+6.24,resSelectionSubs('asp','CG',subs)))
IDSpec[(('asn_i','CG'),('rasp','OD1'))] = cmd.select('asn_i11', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+5.56,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('asn_i','CG'),('rasp','OD2'))] = cmd.select('asn_i12', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+6.30,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('asn_i','ND2'),('rasp','CG'))] = cmd.select('asn_i13', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+6.28,resSelectionSubs('asp','CG',subs)))
IDSpec[(('asn_i','ND2'),('rasp','OD1'))] = cmd.select('asn_i14', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+5.94,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('asn_i','ND2'),('rasp','OD2'))] = cmd.select('asn_i15', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+6.20,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('asn_i','OD1'),('rasp','CG'))] = cmd.select('asn_i16', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+6.17,resSelectionSubs('asp','CG',subs)))
IDSpec[(('asn_i','OD1'),('rasp','OD1'))] = cmd.select('asn_i17', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+5.51,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('asn_i','OD1'),('rasp','OD2'))] = cmd.select('asn_i18', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+6.05,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('asn_i','CG'),('rasp_i','CG'))] = cmd.select('asn_i19', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+10.27,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('asn_i','CG'),('rasp_i','OD1'))] = cmd.select('asn_i20', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+10.35,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('asn_i','CG'),('rasp_i','OD2'))] = cmd.select('asn_i21', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+9.72,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('asn_i','ND2'),('rasp_i','CG'))] = cmd.select('asn_i22', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+10.73,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('asn_i','ND2'),('rasp_i','OD1'))] = cmd.select('asn_i23', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+10.90,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('asn_i','ND2'),('rasp_i','OD2'))] = cmd.select('asn_i24', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+10.01,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('asn_i','OD1'),('rasp_i','CG'))] = cmd.select('asn_i25', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+9.84,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('asn_i','OD1'),('rasp_i','OD1'))] = cmd.select('asn_i26', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+9.74,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('asn_i','OD1'),('rasp_i','OD2'))] = cmd.select('asn_i27', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+9.38,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('asn_i','CG'),('rhis','CE1'))] = cmd.select('asn_i28', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+8.65,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asn_i','CG'),('rhis','ND1'))] = cmd.select('asn_i29', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+9.94,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asn_i','CG'),('rhis','NE2'))] = cmd.select('asn_i30', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+8.34,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asn_i','ND2'),('rhis','CE1'))] = cmd.select('asn_i31', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+8.82,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asn_i','ND2'),('rhis','ND1'))] = cmd.select('asn_i32', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+10.06,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asn_i','ND2'),('rhis','NE2'))] = cmd.select('asn_i33', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+8.67,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asn_i','OD1'),('rhis','CE1'))] = cmd.select('asn_i34', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+7.80,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asn_i','OD1'),('rhis','ND1'))] = cmd.select('asn_i35', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+9.12,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asn_i','OD1'),('rhis','NE2'))] = cmd.select('asn_i36', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+7.53,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asn_i','CG'),('rtyr','CE1'))] = cmd.select('asn_i37', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+6.91,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('asn_i','CG'),('rtyr','CZ'))] = cmd.select('asn_i38', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+7.65,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('asn_i','CG'),('rtyr','OH'))] = cmd.select('asn_i39', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+7.64,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('asn_i','ND2'),('rtyr','CE1'))] = cmd.select('asn_i40', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+5.83,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('asn_i','ND2'),('rtyr','CZ'))] = cmd.select('asn_i41', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+6.45,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('asn_i','ND2'),('rtyr','OH'))] = cmd.select('asn_i42', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+6.53,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('asn_i','OD1'),('rtyr','CE1'))] = cmd.select('asn_i43', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+7.28,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('asn_i','OD1'),('rtyr','CZ'))] = cmd.select('asn_i44', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+8.03,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('asn_i','OD1'),('rtyr','OH'))] = cmd.select('asn_i45', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+7.85,resSelectionSubs('tyr','OH',subs)))
IDSpec['asn_i'] = cmd.select('asn_i',' br. asn_i1&br. asn_i2&br. asn_i3&br. asn_i4&br. asn_i5&br. asn_i6&br. asn_i7&br. asn_i8&br. asn_i9&br. asn_i10&br. asn_i11&br. asn_i12&br. asn_i13&br. asn_i14&br. asn_i15&br. asn_i16&br. asn_i17&br. asn_i18&br. asn_i19&br. asn_i20&br. asn_i21&br. asn_i22&br. asn_i23&br. asn_i24&br. asn_i25&br. asn_i26&br. asn_i27&br. asn_i28&br. asn_i29&br. asn_i30&br. asn_i31&br. asn_i32&br. asn_i33&br. asn_i34&br. asn_i35&br. asn_i36&br. asn_i37&br. asn_i38&br. asn_i39&br. asn_i40&br. asn_i41&br. asn_i42&br. asn_i43&br. asn_i44&br. asn_i45')
IDSpec['r_asn_i'] = cmd.count_atoms(resSelectionSubs('asn_i', subs=subs, selection=True))
cmd.delete('asn_i1')
cmd.delete('asn_i2')
cmd.delete('asn_i3')
cmd.delete('asn_i4')
cmd.delete('asn_i5')
cmd.delete('asn_i6')
cmd.delete('asn_i7')
cmd.delete('asn_i8')
cmd.delete('asn_i9')
cmd.delete('asn_i10')
cmd.delete('asn_i11')
cmd.delete('asn_i12')
cmd.delete('asn_i13')
cmd.delete('asn_i14')
cmd.delete('asn_i15')
cmd.delete('asn_i16')
cmd.delete('asn_i17')
cmd.delete('asn_i18')
cmd.delete('asn_i19')
cmd.delete('asn_i20')
cmd.delete('asn_i21')
cmd.delete('asn_i22')
cmd.delete('asn_i23')
cmd.delete('asn_i24')
cmd.delete('asn_i25')
cmd.delete('asn_i26')
cmd.delete('asn_i27')
cmd.delete('asn_i28')
cmd.delete('asn_i29')
cmd.delete('asn_i30')
cmd.delete('asn_i31')
cmd.delete('asn_i32')
cmd.delete('asn_i33')
cmd.delete('asn_i34')
cmd.delete('asn_i35')
cmd.delete('asn_i36')
cmd.delete('asn_i37')
cmd.delete('asn_i38')
cmd.delete('asn_i39')
cmd.delete('asn_i40')
cmd.delete('asn_i41')
cmd.delete('asn_i42')
cmd.delete('asn_i43')
cmd.delete('asn_i44')
cmd.delete('asn_i45')
IDSpec[(('asp','CG'),('sasn','CG'))] = cmd.select('asp1', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.68,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('asp','CG'),('sasn','ND2'))] = cmd.select('asp2', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+5.66,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('asp','CG'),('sasn','OD1'))] = cmd.select('asp3', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.83,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('asp','OD1'),('sasn','CG'))] = cmd.select('asp4', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.87,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('asp','OD1'),('sasn','ND2'))] = cmd.select('asp5', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+6.84,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('asp','OD1'),('sasn','OD1'))] = cmd.select('asp6', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.01,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('asp','OD2'),('sasn','CG'))] = cmd.select('asp7', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+5.83,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('asp','OD2'),('sasn','ND2'))] = cmd.select('asp8', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+4.72,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('asp','OD2'),('sasn','OD1'))] = cmd.select('asp9', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.89,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('asp','CG'),('sasn_i','CG'))] = cmd.select('asp10', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.24,resSelectionSubs('asn_i','CG',subs,selection=True)))
IDSpec[(('asp','CG'),('sasn_i','ND2'))] = cmd.select('asp11', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.28,resSelectionSubs('asn_i','ND2',subs,selection=True)))
IDSpec[(('asp','CG'),('sasn_i','OD1'))] = cmd.select('asp12', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.17,resSelectionSubs('asn_i','OD1',subs,selection=True)))
IDSpec[(('asp','OD1'),('sasn_i','CG'))] = cmd.select('asp13', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+5.56,resSelectionSubs('asn_i','CG',subs,selection=True)))
IDSpec[(('asp','OD1'),('sasn_i','ND2'))] = cmd.select('asp14', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+5.94,resSelectionSubs('asn_i','ND2',subs,selection=True)))
IDSpec[(('asp','OD1'),('sasn_i','OD1'))] = cmd.select('asp15', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+5.51,resSelectionSubs('asn_i','OD1',subs,selection=True)))
IDSpec[(('asp','OD2'),('sasn_i','CG'))] = cmd.select('asp16', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.30,resSelectionSubs('asn_i','CG',subs,selection=True)))
IDSpec[(('asp','OD2'),('sasn_i','ND2'))] = cmd.select('asp17', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.20,resSelectionSubs('asn_i','ND2',subs,selection=True)))
IDSpec[(('asp','OD2'),('sasn_i','OD1'))] = cmd.select('asp18', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.05,resSelectionSubs('asn_i','OD1',subs,selection=True)))
IDSpec[(('asp','CG'),('rasp_i','CG'))] = cmd.select('asp19', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.68,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('asp','CG'),('rasp_i','OD1'))] = cmd.select('asp20', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.08,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('asp','CG'),('rasp_i','OD2'))] = cmd.select('asp21', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+5.79,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('asp','OD1'),('rasp_i','CG'))] = cmd.select('asp22', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+6.87,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('asp','OD1'),('rasp_i','OD1'))] = cmd.select('asp23', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.20,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('asp','OD1'),('rasp_i','OD2'))] = cmd.select('asp24', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+6.22,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('asp','OD2'),('rasp_i','CG'))] = cmd.select('asp25', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.21,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('asp','OD2'),('rasp_i','OD1'))] = cmd.select('asp26', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.40,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('asp','OD2'),('rasp_i','OD2'))] = cmd.select('asp27', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.31,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('asp','CG'),('rhis','CE1'))] = cmd.select('asp28', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.38,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp','CG'),('rhis','ND1'))] = cmd.select('asp29', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.33,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp','CG'),('rhis','NE2'))] = cmd.select('asp30', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+5.70,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp','OD1'),('rhis','CE1'))] = cmd.select('asp31', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+6.98,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp','OD1'),('rhis','ND1'))] = cmd.select('asp32', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.04,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp','OD1'),('rhis','NE2'))] = cmd.select('asp33', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+6.15,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp','OD2'),('rhis','CE1'))] = cmd.select('asp34', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+5.49,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp','OD2'),('rhis','ND1'))] = cmd.select('asp35', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.48,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp','OD2'),('rhis','NE2'))] = cmd.select('asp36', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+5.14,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp','CG'),('rtyr','CE1'))] = cmd.select('asp37', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.25,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('asp','CG'),('rtyr','CZ'))] = cmd.select('asp38', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.58,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('asp','CG'),('rtyr','OH'))] = cmd.select('asp39', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+8.14,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('asp','OD1'),('rtyr','CE1'))] = cmd.select('asp40', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+6.97,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('asp','OD1'),('rtyr','CZ'))] = cmd.select('asp41', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.26,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('asp','OD1'),('rtyr','OH'))] = cmd.select('asp42', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.73,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('asp','OD2'),('rtyr','CE1'))] = cmd.select('asp43', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+5.65,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('asp','OD2'),('rtyr','CZ'))] = cmd.select('asp44', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.89,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('asp','OD2'),('rtyr','OH'))] = cmd.select('asp45', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.29,resSelectionSubs('tyr','OH',subs)))
IDSpec['asp'] = cmd.select('asp',' br. asp1&br. asp2&br. asp3&br. asp4&br. asp5&br. asp6&br. asp7&br. asp8&br. asp9&br. asp10&br. asp11&br. asp12&br. asp13&br. asp14&br. asp15&br. asp16&br. asp17&br. asp18&br. asp19&br. asp20&br. asp21&br. asp22&br. asp23&br. asp24&br. asp25&br. asp26&br. asp27&br. asp28&br. asp29&br. asp30&br. asp31&br. asp32&br. asp33&br. asp34&br. asp35&br. asp36&br. asp37&br. asp38&br. asp39&br. asp40&br. asp41&br. asp42&br. asp43&br. asp44&br. asp45')
IDSpec['r_asp'] = cmd.count_atoms(resSelectionSubs('asp', subs=subs, selection=True))
cmd.delete('asp1')
cmd.delete('asp2')
cmd.delete('asp3')
cmd.delete('asp4')
cmd.delete('asp5')
cmd.delete('asp6')
cmd.delete('asp7')
cmd.delete('asp8')
cmd.delete('asp9')
cmd.delete('asp10')
cmd.delete('asp11')
cmd.delete('asp12')
cmd.delete('asp13')
cmd.delete('asp14')
cmd.delete('asp15')
cmd.delete('asp16')
cmd.delete('asp17')
cmd.delete('asp18')
cmd.delete('asp19')
cmd.delete('asp20')
cmd.delete('asp21')
cmd.delete('asp22')
cmd.delete('asp23')
cmd.delete('asp24')
cmd.delete('asp25')
cmd.delete('asp26')
cmd.delete('asp27')
cmd.delete('asp28')
cmd.delete('asp29')
cmd.delete('asp30')
cmd.delete('asp31')
cmd.delete('asp32')
cmd.delete('asp33')
cmd.delete('asp34')
cmd.delete('asp35')
cmd.delete('asp36')
cmd.delete('asp37')
cmd.delete('asp38')
cmd.delete('asp39')
cmd.delete('asp40')
cmd.delete('asp41')
cmd.delete('asp42')
cmd.delete('asp43')
cmd.delete('asp44')
cmd.delete('asp45')
IDSpec[(('asp_i','CG'),('sasn','CG'))] = cmd.select('asp_i1', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+8.31,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasn','ND2'))] = cmd.select('asp_i2', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+8.26,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasn','OD1'))] = cmd.select('asp_i3', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+9.43,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasn','CG'))] = cmd.select('asp_i4', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.43,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasn','ND2'))] = cmd.select('asp_i5', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.44,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasn','OD1'))] = cmd.select('asp_i6', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.48,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasn','CG'))] = cmd.select('asp_i7', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.30,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasn','ND2'))] = cmd.select('asp_i8', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.20,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasn','OD1'))] = cmd.select('asp_i9', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+8.47,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasn_i','CG'))] = cmd.select('asp_i10', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+10.27,resSelectionSubs('asn_i','CG',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasn_i','ND2'))] = cmd.select('asp_i11', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+10.73,resSelectionSubs('asn_i','ND2',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasn_i','OD1'))] = cmd.select('asp_i12', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+9.84,resSelectionSubs('asn_i','OD1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasn_i','CG'))] = cmd.select('asp_i13', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+10.35,resSelectionSubs('asn_i','CG',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasn_i','ND2'))] = cmd.select('asp_i14', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+10.90,resSelectionSubs('asn_i','ND2',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasn_i','OD1'))] = cmd.select('asp_i15', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.74,resSelectionSubs('asn_i','OD1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasn_i','CG'))] = cmd.select('asp_i16', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+9.72,resSelectionSubs('asn_i','CG',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasn_i','ND2'))] = cmd.select('asp_i17', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+10.01,resSelectionSubs('asn_i','ND2',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasn_i','OD1'))] = cmd.select('asp_i18', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+9.38,resSelectionSubs('asn_i','OD1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasp','CG'))] = cmd.select('asp_i19', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.68,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasp','OD1'))] = cmd.select('asp_i20', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.87,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasp','OD2'))] = cmd.select('asp_i21', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.21,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasp','CG'))] = cmd.select('asp_i22', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.08,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasp','OD1'))] = cmd.select('asp_i23', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.20,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasp','OD2'))] = cmd.select('asp_i24', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.40,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasp','CG'))] = cmd.select('asp_i25', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+5.79,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasp','OD1'))] = cmd.select('asp_i26', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.22,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasp','OD2'))] = cmd.select('asp_i27', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.31,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asp_i','CG'),('rhis','CE1'))] = cmd.select('asp_i28', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.36,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp_i','CG'),('rhis','ND1'))] = cmd.select('asp_i29', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.51,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp_i','CG'),('rhis','NE2'))] = cmd.select('asp_i30', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.16,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp_i','OD1'),('rhis','CE1'))] = cmd.select('asp_i31', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+6.82,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp_i','OD1'),('rhis','ND1'))] = cmd.select('asp_i32', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+6.92,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp_i','OD1'),('rhis','NE2'))] = cmd.select('asp_i33', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+5.62,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp_i','OD2'),('rhis','CE1'))] = cmd.select('asp_i34', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.93,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp_i','OD2'),('rhis','ND1'))] = cmd.select('asp_i35', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.13,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp_i','OD2'),('rhis','NE2'))] = cmd.select('asp_i36', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+5.83,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp_i','CG'),('rtyr','CE1'))] = cmd.select('asp_i37', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+10.63,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('asp_i','CG'),('rtyr','CZ'))] = cmd.select('asp_i38', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+11.94,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('asp_i','CG'),('rtyr','OH'))] = cmd.select('asp_i39', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+12.45,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('asp_i','OD1'),('rtyr','CE1'))] = cmd.select('asp_i40', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+10.97,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('asp_i','OD1'),('rtyr','CZ'))] = cmd.select('asp_i41', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+12.22,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('asp_i','OD1'),('rtyr','OH'))] = cmd.select('asp_i42', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+12.58,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('asp_i','OD2'),('rtyr','CE1'))] = cmd.select('asp_i43', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+9.55,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('asp_i','OD2'),('rtyr','CZ'))] = cmd.select('asp_i44', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+10.86,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('asp_i','OD2'),('rtyr','OH'))] = cmd.select('asp_i45', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.45,resSelectionSubs('tyr','OH',subs)))
IDSpec['asp_i'] = cmd.select('asp_i',' br. asp_i1&br. asp_i2&br. asp_i3&br. asp_i4&br. asp_i5&br. asp_i6&br. asp_i7&br. asp_i8&br. asp_i9&br. asp_i10&br. asp_i11&br. asp_i12&br. asp_i13&br. asp_i14&br. asp_i15&br. asp_i16&br. asp_i17&br. asp_i18&br. asp_i19&br. asp_i20&br. asp_i21&br. asp_i22&br. asp_i23&br. asp_i24&br. asp_i25&br. asp_i26&br. asp_i27&br. asp_i28&br. asp_i29&br. asp_i30&br. asp_i31&br. asp_i32&br. asp_i33&br. asp_i34&br. asp_i35&br. asp_i36&br. asp_i37&br. asp_i38&br. asp_i39&br. asp_i40&br. asp_i41&br. asp_i42&br. asp_i43&br. asp_i44&br. asp_i45')
IDSpec['r_asp_i'] = cmd.count_atoms(resSelectionSubs('asp_i', subs=subs, selection=True))
cmd.delete('asp_i1')
cmd.delete('asp_i2')
cmd.delete('asp_i3')
cmd.delete('asp_i4')
cmd.delete('asp_i5')
cmd.delete('asp_i6')
cmd.delete('asp_i7')
cmd.delete('asp_i8')
cmd.delete('asp_i9')
cmd.delete('asp_i10')
cmd.delete('asp_i11')
cmd.delete('asp_i12')
cmd.delete('asp_i13')
cmd.delete('asp_i14')
cmd.delete('asp_i15')
cmd.delete('asp_i16')
cmd.delete('asp_i17')
cmd.delete('asp_i18')
cmd.delete('asp_i19')
cmd.delete('asp_i20')
cmd.delete('asp_i21')
cmd.delete('asp_i22')
cmd.delete('asp_i23')
cmd.delete('asp_i24')
cmd.delete('asp_i25')
cmd.delete('asp_i26')
cmd.delete('asp_i27')
cmd.delete('asp_i28')
cmd.delete('asp_i29')
cmd.delete('asp_i30')
cmd.delete('asp_i31')
cmd.delete('asp_i32')
cmd.delete('asp_i33')
cmd.delete('asp_i34')
cmd.delete('asp_i35')
cmd.delete('asp_i36')
cmd.delete('asp_i37')
cmd.delete('asp_i38')
cmd.delete('asp_i39')
cmd.delete('asp_i40')
cmd.delete('asp_i41')
cmd.delete('asp_i42')
cmd.delete('asp_i43')
cmd.delete('asp_i44')
cmd.delete('asp_i45')
IDSpec[(('his','CE1'),('sasn','CG'))] = cmd.select('his1', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+5.72,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('his','CE1'),('sasn','ND2'))] = cmd.select('his2', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+5.60,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('his','CE1'),('sasn','OD1'))] = cmd.select('his3', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.36,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('his','ND1'),('sasn','CG'))] = cmd.select('his4', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+5.56,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('his','ND1'),('sasn','ND2'))] = cmd.select('his5', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+5.91,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('his','ND1'),('sasn','OD1'))] = cmd.select('his6', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+6.00,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('his','NE2'),('sasn','CG'))] = cmd.select('his7', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.19,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('his','NE2'),('sasn','ND2'))] = cmd.select('his8', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+5.96,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('his','NE2'),('sasn','OD1'))] = cmd.select('his9', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+7.09,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('his','CE1'),('sasn_i','CG'))] = cmd.select('his10', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+8.65,resSelectionSubs('asn_i','CG',subs,selection=True)))
IDSpec[(('his','CE1'),('sasn_i','ND2'))] = cmd.select('his11', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+8.82,resSelectionSubs('asn_i','ND2',subs,selection=True)))
IDSpec[(('his','CE1'),('sasn_i','OD1'))] = cmd.select('his12', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.80,resSelectionSubs('asn_i','OD1',subs,selection=True)))
IDSpec[(('his','ND1'),('sasn_i','CG'))] = cmd.select('his13', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+9.94,resSelectionSubs('asn_i','CG',subs,selection=True)))
IDSpec[(('his','ND1'),('sasn_i','ND2'))] = cmd.select('his14', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+10.06,resSelectionSubs('asn_i','ND2',subs,selection=True)))
IDSpec[(('his','ND1'),('sasn_i','OD1'))] = cmd.select('his15', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+9.12,resSelectionSubs('asn_i','OD1',subs,selection=True)))
IDSpec[(('his','NE2'),('sasn_i','CG'))] = cmd.select('his16', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+8.34,resSelectionSubs('asn_i','CG',subs,selection=True)))
IDSpec[(('his','NE2'),('sasn_i','ND2'))] = cmd.select('his17', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+8.67,resSelectionSubs('asn_i','ND2',subs,selection=True)))
IDSpec[(('his','NE2'),('sasn_i','OD1'))] = cmd.select('his18', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+7.53,resSelectionSubs('asn_i','OD1',subs,selection=True)))
IDSpec[(('his','CE1'),('sasp','CG'))] = cmd.select('his19', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.38,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his','CE1'),('sasp','OD1'))] = cmd.select('his20', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.98,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his','CE1'),('sasp','OD2'))] = cmd.select('his21', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+5.49,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his','ND1'),('sasp','CG'))] = cmd.select('his22', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.33,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his','ND1'),('sasp','OD1'))] = cmd.select('his23', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+8.04,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his','ND1'),('sasp','OD2'))] = cmd.select('his24', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+6.48,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his','NE2'),('sasp','CG'))] = cmd.select('his25', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+5.70,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his','NE2'),('sasp','OD1'))] = cmd.select('his26', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.15,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his','NE2'),('sasp','OD2'))] = cmd.select('his27', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+5.14,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his','CE1'),('sasp_i','CG'))] = cmd.select('his28', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.36,resSelectionSubs('asp_i','CG',subs,selection=True)))
IDSpec[(('his','CE1'),('sasp_i','OD1'))] = cmd.select('his29', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.82,resSelectionSubs('asp_i','OD1',subs,selection=True)))
IDSpec[(('his','CE1'),('sasp_i','OD2'))] = cmd.select('his30', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.93,resSelectionSubs('asp_i','OD2',subs,selection=True)))
IDSpec[(('his','ND1'),('sasp_i','CG'))] = cmd.select('his31', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.51,resSelectionSubs('asp_i','CG',subs,selection=True)))
IDSpec[(('his','ND1'),('sasp_i','OD1'))] = cmd.select('his32', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+6.92,resSelectionSubs('asp_i','OD1',subs,selection=True)))
IDSpec[(('his','ND1'),('sasp_i','OD2'))] = cmd.select('his33', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.13,resSelectionSubs('asp_i','OD2',subs,selection=True)))
IDSpec[(('his','NE2'),('sasp_i','CG'))] = cmd.select('his34', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.16,resSelectionSubs('asp_i','CG',subs,selection=True)))
IDSpec[(('his','NE2'),('sasp_i','OD1'))] = cmd.select('his35', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+5.62,resSelectionSubs('asp_i','OD1',subs,selection=True)))
IDSpec[(('his','NE2'),('sasp_i','OD2'))] = cmd.select('his36', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+5.83,resSelectionSubs('asp_i','OD2',subs,selection=True)))
IDSpec[(('his','CE1'),('rtyr','CE1'))] = cmd.select('his37', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+8.22,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('his','CE1'),('rtyr','CZ'))] = cmd.select('his38', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+9.06,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('his','CE1'),('rtyr','OH'))] = cmd.select('his39', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+8.94,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('his','ND1'),('rtyr','CE1'))] = cmd.select('his40', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+9.03,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('his','ND1'),('rtyr','CZ'))] = cmd.select('his41', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+9.83,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('his','ND1'),('rtyr','OH'))] = cmd.select('his42', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+9.74,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('his','NE2'),('rtyr','CE1'))] = cmd.select('his43', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+8.45,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('his','NE2'),('rtyr','CZ'))] = cmd.select('his44', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+9.48,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('his','NE2'),('rtyr','OH'))] = cmd.select('his45', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+9.52,resSelectionSubs('tyr','OH',subs)))
IDSpec['his'] = cmd.select('his',' br. his1&br. his2&br. his3&br. his4&br. his5&br. his6&br. his7&br. his8&br. his9&br. his10&br. his11&br. his12&br. his13&br. his14&br. his15&br. his16&br. his17&br. his18&br. his19&br. his20&br. his21&br. his22&br. his23&br. his24&br. his25&br. his26&br. his27&br. his28&br. his29&br. his30&br. his31&br. his32&br. his33&br. his34&br. his35&br. his36&br. his37&br. his38&br. his39&br. his40&br. his41&br. his42&br. his43&br. his44&br. his45')
IDSpec['r_his'] = cmd.count_atoms(resSelectionSubs('his', subs=subs, selection=True))
cmd.delete('his1')
cmd.delete('his2')
cmd.delete('his3')
cmd.delete('his4')
cmd.delete('his5')
cmd.delete('his6')
cmd.delete('his7')
cmd.delete('his8')
cmd.delete('his9')
cmd.delete('his10')
cmd.delete('his11')
cmd.delete('his12')
cmd.delete('his13')
cmd.delete('his14')
cmd.delete('his15')
cmd.delete('his16')
cmd.delete('his17')
cmd.delete('his18')
cmd.delete('his19')
cmd.delete('his20')
cmd.delete('his21')
cmd.delete('his22')
cmd.delete('his23')
cmd.delete('his24')
cmd.delete('his25')
cmd.delete('his26')
cmd.delete('his27')
cmd.delete('his28')
cmd.delete('his29')
cmd.delete('his30')
cmd.delete('his31')
cmd.delete('his32')
cmd.delete('his33')
cmd.delete('his34')
cmd.delete('his35')
cmd.delete('his36')
cmd.delete('his37')
cmd.delete('his38')
cmd.delete('his39')
cmd.delete('his40')
cmd.delete('his41')
cmd.delete('his42')
cmd.delete('his43')
cmd.delete('his44')
cmd.delete('his45')
IDSpec[(('tyr','CE1'),('sasn','CG'))] = cmd.select('tyr1', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+6.91,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('tyr','CE1'),('sasn','ND2'))] = cmd.select('tyr2', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+5.68,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('tyr','CE1'),('sasn','OD1'))] = cmd.select('tyr3', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+7.39,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sasn','CG'))] = cmd.select('tyr4', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+7.66,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sasn','ND2'))] = cmd.select('tyr5', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+6.57,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sasn','OD1'))] = cmd.select('tyr6', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+7.88,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('tyr','OH'),('sasn','CG'))] = cmd.select('tyr7', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+8.04,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('tyr','OH'),('sasn','ND2'))] = cmd.select('tyr8', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+7.00,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('tyr','OH'),('sasn','OD1'))] = cmd.select('tyr9', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+8.13,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('tyr','CE1'),('sasn_i','CG'))] = cmd.select('tyr10', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+6.91,resSelectionSubs('asn_i','CG',subs,selection=True)))
IDSpec[(('tyr','CE1'),('sasn_i','ND2'))] = cmd.select('tyr11', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+5.83,resSelectionSubs('asn_i','ND2',subs,selection=True)))
IDSpec[(('tyr','CE1'),('sasn_i','OD1'))] = cmd.select('tyr12', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+7.28,resSelectionSubs('asn_i','OD1',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sasn_i','CG'))] = cmd.select('tyr13', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+7.65,resSelectionSubs('asn_i','CG',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sasn_i','ND2'))] = cmd.select('tyr14', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+6.45,resSelectionSubs('asn_i','ND2',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sasn_i','OD1'))] = cmd.select('tyr15', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+8.03,resSelectionSubs('asn_i','OD1',subs,selection=True)))
IDSpec[(('tyr','OH'),('sasn_i','CG'))] = cmd.select('tyr16', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+7.64,resSelectionSubs('asn_i','CG',subs,selection=True)))
IDSpec[(('tyr','OH'),('sasn_i','ND2'))] = cmd.select('tyr17', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+6.53,resSelectionSubs('asn_i','ND2',subs,selection=True)))
IDSpec[(('tyr','OH'),('sasn_i','OD1'))] = cmd.select('tyr18', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+7.85,resSelectionSubs('asn_i','OD1',subs,selection=True)))
IDSpec[(('tyr','CE1'),('sasp','CG'))] = cmd.select('tyr19', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+6.25,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('tyr','CE1'),('sasp','OD1'))] = cmd.select('tyr20', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+6.97,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('tyr','CE1'),('sasp','OD2'))] = cmd.select('tyr21', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+5.65,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sasp','CG'))] = cmd.select('tyr22', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+7.58,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sasp','OD1'))] = cmd.select('tyr23', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+8.26,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sasp','OD2'))] = cmd.select('tyr24', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+6.89,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('tyr','OH'),('sasp','CG'))] = cmd.select('tyr25', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+8.14,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('tyr','OH'),('sasp','OD1'))] = cmd.select('tyr26', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+8.73,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('tyr','OH'),('sasp','OD2'))] = cmd.select('tyr27', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+7.29,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('tyr','CE1'),('sasp_i','CG'))] = cmd.select('tyr28', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10.63,resSelectionSubs('asp_i','CG',subs,selection=True)))
IDSpec[(('tyr','CE1'),('sasp_i','OD1'))] = cmd.select('tyr29', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10.97,resSelectionSubs('asp_i','OD1',subs,selection=True)))
IDSpec[(('tyr','CE1'),('sasp_i','OD2'))] = cmd.select('tyr30', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+9.55,resSelectionSubs('asp_i','OD2',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sasp_i','CG'))] = cmd.select('tyr31', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+11.94,resSelectionSubs('asp_i','CG',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sasp_i','OD1'))] = cmd.select('tyr32', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+12.22,resSelectionSubs('asp_i','OD1',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sasp_i','OD2'))] = cmd.select('tyr33', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+10.86,resSelectionSubs('asp_i','OD2',subs,selection=True)))
IDSpec[(('tyr','OH'),('sasp_i','CG'))] = cmd.select('tyr34', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+12.45,resSelectionSubs('asp_i','CG',subs,selection=True)))
IDSpec[(('tyr','OH'),('sasp_i','OD1'))] = cmd.select('tyr35', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+12.58,resSelectionSubs('asp_i','OD1',subs,selection=True)))
IDSpec[(('tyr','OH'),('sasp_i','OD2'))] = cmd.select('tyr36', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+11.45,resSelectionSubs('asp_i','OD2',subs,selection=True)))
IDSpec[(('tyr','CE1'),('shis','CE1'))] = cmd.select('tyr37', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+8.22,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('tyr','CE1'),('shis','ND1'))] = cmd.select('tyr38', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+9.03,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('tyr','CE1'),('shis','NE2'))] = cmd.select('tyr39', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+8.45,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('tyr','CZ'),('shis','CE1'))] = cmd.select('tyr40', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+9.06,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('tyr','CZ'),('shis','ND1'))] = cmd.select('tyr41', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+9.83,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('tyr','CZ'),('shis','NE2'))] = cmd.select('tyr42', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+9.48,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('tyr','OH'),('shis','CE1'))] = cmd.select('tyr43', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+8.94,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('tyr','OH'),('shis','ND1'))] = cmd.select('tyr44', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+9.74,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('tyr','OH'),('shis','NE2'))] = cmd.select('tyr45', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+9.52,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec['tyr'] = cmd.select('tyr',' br. tyr1&br. tyr2&br. tyr3&br. tyr4&br. tyr5&br. tyr6&br. tyr7&br. tyr8&br. tyr9&br. tyr10&br. tyr11&br. tyr12&br. tyr13&br. tyr14&br. tyr15&br. tyr16&br. tyr17&br. tyr18&br. tyr19&br. tyr20&br. tyr21&br. tyr22&br. tyr23&br. tyr24&br. tyr25&br. tyr26&br. tyr27&br. tyr28&br. tyr29&br. tyr30&br. tyr31&br. tyr32&br. tyr33&br. tyr34&br. tyr35&br. tyr36&br. tyr37&br. tyr38&br. tyr39&br. tyr40&br. tyr41&br. tyr42&br. tyr43&br. tyr44&br. tyr45')
IDSpec['r_tyr'] = cmd.count_atoms(resSelectionSubs('tyr', subs=subs, selection=True))
cmd.delete('tyr1')
cmd.delete('tyr2')
cmd.delete('tyr3')
cmd.delete('tyr4')
cmd.delete('tyr5')
cmd.delete('tyr6')
cmd.delete('tyr7')
cmd.delete('tyr8')
cmd.delete('tyr9')
cmd.delete('tyr10')
cmd.delete('tyr11')
cmd.delete('tyr12')
cmd.delete('tyr13')
cmd.delete('tyr14')
cmd.delete('tyr15')
cmd.delete('tyr16')
cmd.delete('tyr17')
cmd.delete('tyr18')
cmd.delete('tyr19')
cmd.delete('tyr20')
cmd.delete('tyr21')
cmd.delete('tyr22')
cmd.delete('tyr23')
cmd.delete('tyr24')
cmd.delete('tyr25')
cmd.delete('tyr26')
cmd.delete('tyr27')
cmd.delete('tyr28')
cmd.delete('tyr29')
cmd.delete('tyr30')
cmd.delete('tyr31')
cmd.delete('tyr32')
cmd.delete('tyr33')
cmd.delete('tyr34')
cmd.delete('tyr35')
cmd.delete('tyr36')
cmd.delete('tyr37')
cmd.delete('tyr38')
cmd.delete('tyr39')
cmd.delete('tyr40')
cmd.delete('tyr41')
cmd.delete('tyr42')
cmd.delete('tyr43')
cmd.delete('tyr44')
cmd.delete('tyr45')
IDSpec['S_2j63_4_2_99_18'] = cmd.select('S_2j63_4_2_99_18', 'asn|asn_i|asp|asp_i|his|tyr')
cmd.delete('asn')
cmd.delete('asn_i')
cmd.delete('asp')
cmd.delete('asp_i')
cmd.delete('his')
cmd.delete('tyr')
