'''
FUNC:S_2qb3_2_6_1_1
PDB:2qb3
EC:2.6.1.1
RESI:ile,trp,asp
LOCI:a-68,130,211;
'''
IDSpec[(('asp','CG'),('rtrp','CE2'))] = cmd.select('asp1', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+9.62,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('asp','CG'),('rtrp','CZ2'))] = cmd.select('asp2', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+9.79,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('asp','CG'),('rtrp','NE1'))] = cmd.select('asp3', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+10.50,resSelectionSubs('trp','NE1',subs)))
IDSpec[(('asp','OD1'),('rtrp','CE2'))] = cmd.select('asp4', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.73,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('asp','OD1'),('rtrp','CZ2'))] = cmd.select('asp5', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.83,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('asp','OD1'),('rtrp','NE1'))] = cmd.select('asp6', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+10.55,resSelectionSubs('trp','NE1',subs)))
IDSpec[(('asp','OD2'),('rtrp','CE2'))] = cmd.select('asp7', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+8.61,resSelectionSubs('trp','CE2',subs)))
IDSpec[(('asp','OD2'),('rtrp','CZ2'))] = cmd.select('asp8', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+8.81,resSelectionSubs('trp','CZ2',subs)))
IDSpec[(('asp','OD2'),('rtrp','NE1'))] = cmd.select('asp9', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+9.54,resSelectionSubs('trp','NE1',subs)))
IDSpec[(('asp','CG'),('rile','CD1'))] = cmd.select('asp10', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+25.67,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('asp','CG'),('rile','CG1'))] = cmd.select('asp11', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+25.06,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('asp','CG'),('rile','CG2'))] = cmd.select('asp12', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+22.60,resSelectionSubs('ile','CG2',subs)))
IDSpec[(('asp','OD1'),('rile','CD1'))] = cmd.select('asp13', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+25.56,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('asp','OD1'),('rile','CG1'))] = cmd.select('asp14', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+24.88,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('asp','OD1'),('rile','CG2'))] = cmd.select('asp15', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+22.46,resSelectionSubs('ile','CG2',subs)))
IDSpec[(('asp','OD2'),('rile','CD1'))] = cmd.select('asp16', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+25.81,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('asp','OD2'),('rile','CG1'))] = cmd.select('asp17', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+25.22,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('asp','OD2'),('rile','CG2'))] = cmd.select('asp18', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+22.77,resSelectionSubs('ile','CG2',subs)))
IDSpec['asp'] = cmd.select('asp',' br. asp1&br. asp2&br. asp3&br. asp4&br. asp5&br. asp6&br. asp7&br. asp8&br. asp9&br. asp10&br. asp11&br. asp12&br. asp13&br. asp14&br. asp15&br. asp16&br. asp17&br. asp18')
IDSpec['r_asp'] = cmd.count_atoms(resSelectionSubs('asp', subs=subs, selection=True))
cmd.delete('asp1')
cmd.delete('asp2')
cmd.delete('asp3')
cmd.delete('asp4')
cmd.delete('asp5')
cmd.delete('asp6')
cmd.delete('asp7')
cmd.delete('asp8')
cmd.delete('asp9')
cmd.delete('asp10')
cmd.delete('asp11')
cmd.delete('asp12')
cmd.delete('asp13')
cmd.delete('asp14')
cmd.delete('asp15')
cmd.delete('asp16')
cmd.delete('asp17')
cmd.delete('asp18')
IDSpec[(('trp','CE2'),('sasp','CG'))] = cmd.select('trp1', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+9.62,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('trp','CE2'),('sasp','OD1'))] = cmd.select('trp2', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+9.73,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('trp','CE2'),('sasp','OD2'))] = cmd.select('trp3', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+8.61,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('trp','CZ2'),('sasp','CG'))] = cmd.select('trp4', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+9.79,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('trp','CZ2'),('sasp','OD1'))] = cmd.select('trp5', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+9.83,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('trp','CZ2'),('sasp','OD2'))] = cmd.select('trp6', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+8.81,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('trp','NE1'),('sasp','CG'))] = cmd.select('trp7', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+10.50,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('trp','NE1'),('sasp','OD1'))] = cmd.select('trp8', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+10.55,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('trp','NE1'),('sasp','OD2'))] = cmd.select('trp9', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+9.54,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('trp','CE2'),('rile','CD1'))] = cmd.select('trp10', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+27.95,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('trp','CE2'),('rile','CG1'))] = cmd.select('trp11', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+27.22,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('trp','CE2'),('rile','CG2'))] = cmd.select('trp12', '%s w. %s of %s'%(resSelectionSubs('trp','CE2',subs),d+25.01,resSelectionSubs('ile','CG2',subs)))
IDSpec[(('trp','CZ2'),('rile','CD1'))] = cmd.select('trp13', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+26.71,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('trp','CZ2'),('rile','CG1'))] = cmd.select('trp14', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+25.95,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('trp','CZ2'),('rile','CG2'))] = cmd.select('trp15', '%s w. %s of %s'%(resSelectionSubs('trp','CZ2',subs),d+23.79,resSelectionSubs('ile','CG2',subs)))
IDSpec[(('trp','NE1'),('rile','CD1'))] = cmd.select('trp16', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+29.22,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('trp','NE1'),('rile','CG1'))] = cmd.select('trp17', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+28.46,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('trp','NE1'),('rile','CG2'))] = cmd.select('trp18', '%s w. %s of %s'%(resSelectionSubs('trp','NE1',subs),d+26.27,resSelectionSubs('ile','CG2',subs)))
IDSpec['trp'] = cmd.select('trp',' br. trp1&br. trp2&br. trp3&br. trp4&br. trp5&br. trp6&br. trp7&br. trp8&br. trp9&br. trp10&br. trp11&br. trp12&br. trp13&br. trp14&br. trp15&br. trp16&br. trp17&br. trp18')
IDSpec['r_trp'] = cmd.count_atoms(resSelectionSubs('trp', subs=subs, selection=True))
cmd.delete('trp1')
cmd.delete('trp2')
cmd.delete('trp3')
cmd.delete('trp4')
cmd.delete('trp5')
cmd.delete('trp6')
cmd.delete('trp7')
cmd.delete('trp8')
cmd.delete('trp9')
cmd.delete('trp10')
cmd.delete('trp11')
cmd.delete('trp12')
cmd.delete('trp13')
cmd.delete('trp14')
cmd.delete('trp15')
cmd.delete('trp16')
cmd.delete('trp17')
cmd.delete('trp18')
IDSpec[(('ile','CD1'),('sasp','CG'))] = cmd.select('ile1', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+25.67,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('ile','CD1'),('sasp','OD1'))] = cmd.select('ile2', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+25.56,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('ile','CD1'),('sasp','OD2'))] = cmd.select('ile3', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+25.81,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('ile','CG1'),('sasp','CG'))] = cmd.select('ile4', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+25.06,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('ile','CG1'),('sasp','OD1'))] = cmd.select('ile5', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+24.88,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('ile','CG1'),('sasp','OD2'))] = cmd.select('ile6', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+25.22,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('ile','CG2'),('sasp','CG'))] = cmd.select('ile7', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+22.60,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('ile','CG2'),('sasp','OD1'))] = cmd.select('ile8', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+22.46,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('ile','CG2'),('sasp','OD2'))] = cmd.select('ile9', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+22.77,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('ile','CD1'),('strp','CE2'))] = cmd.select('ile10', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+27.95,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('ile','CD1'),('strp','CZ2'))] = cmd.select('ile11', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+26.71,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('ile','CD1'),('strp','NE1'))] = cmd.select('ile12', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+29.22,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec[(('ile','CG1'),('strp','CE2'))] = cmd.select('ile13', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+27.22,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('ile','CG1'),('strp','CZ2'))] = cmd.select('ile14', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+25.95,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('ile','CG1'),('strp','NE1'))] = cmd.select('ile15', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+28.46,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec[(('ile','CG2'),('strp','CE2'))] = cmd.select('ile16', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+25.01,resSelectionSubs('trp','CE2',subs,selection=True)))
IDSpec[(('ile','CG2'),('strp','CZ2'))] = cmd.select('ile17', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+23.79,resSelectionSubs('trp','CZ2',subs,selection=True)))
IDSpec[(('ile','CG2'),('strp','NE1'))] = cmd.select('ile18', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+26.27,resSelectionSubs('trp','NE1',subs,selection=True)))
IDSpec['ile'] = cmd.select('ile',' br. ile1&br. ile2&br. ile3&br. ile4&br. ile5&br. ile6&br. ile7&br. ile8&br. ile9&br. ile10&br. ile11&br. ile12&br. ile13&br. ile14&br. ile15&br. ile16&br. ile17&br. ile18')
IDSpec['r_ile'] = cmd.count_atoms(resSelectionSubs('ile', subs=subs, selection=True))
cmd.delete('ile1')
cmd.delete('ile2')
cmd.delete('ile3')
cmd.delete('ile4')
cmd.delete('ile5')
cmd.delete('ile6')
cmd.delete('ile7')
cmd.delete('ile8')
cmd.delete('ile9')
cmd.delete('ile10')
cmd.delete('ile11')
cmd.delete('ile12')
cmd.delete('ile13')
cmd.delete('ile14')
cmd.delete('ile15')
cmd.delete('ile16')
cmd.delete('ile17')
cmd.delete('ile18')
IDSpec['S_2qb3_2_6_1_1'] = cmd.select('S_2qb3_2_6_1_1', 'asp|trp|ile')
cmd.delete('asp')
cmd.delete('trp')
cmd.delete('ile')
