'''
FUNC:S_2rk2_1_5_1_3
PDB:2rk2
EC:1.5.1.3
RESI:lys,gln,ile,tyr
LOCI:a-32,67,68,69;
'''
IDSpec[(('ile','CD1'),('rlys','CD'))] = cmd.select('ile1', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+10,resSelectionSubs('lys','CD',subs)))
IDSpec[(('ile','CD1'),('rlys','CE'))] = cmd.select('ile2', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+10,resSelectionSubs('lys','CE',subs)))
IDSpec[(('ile','CD1'),('rlys','NZ'))] = cmd.select('ile3', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+10,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('ile','CG1'),('rlys','CD'))] = cmd.select('ile4', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+10,resSelectionSubs('lys','CD',subs)))
IDSpec[(('ile','CG1'),('rlys','CE'))] = cmd.select('ile5', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+10,resSelectionSubs('lys','CE',subs)))
IDSpec[(('ile','CG1'),('rlys','NZ'))] = cmd.select('ile6', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+10,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('ile','CG2'),('rlys','CD'))] = cmd.select('ile7', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+10,resSelectionSubs('lys','CD',subs)))
IDSpec[(('ile','CG2'),('rlys','CE'))] = cmd.select('ile8', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+10,resSelectionSubs('lys','CE',subs)))
IDSpec[(('ile','CG2'),('rlys','NZ'))] = cmd.select('ile9', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+10,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('ile','CD1'),('rtyr','CE1'))] = cmd.select('ile10', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+10,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('ile','CD1'),('rtyr','CZ'))] = cmd.select('ile11', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+10,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('ile','CD1'),('rtyr','OH'))] = cmd.select('ile12', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+10,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('ile','CG1'),('rtyr','CE1'))] = cmd.select('ile13', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+10,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('ile','CG1'),('rtyr','CZ'))] = cmd.select('ile14', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+10,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('ile','CG1'),('rtyr','OH'))] = cmd.select('ile15', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+10,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('ile','CG2'),('rtyr','CE1'))] = cmd.select('ile16', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+10,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('ile','CG2'),('rtyr','CZ'))] = cmd.select('ile17', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+10,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('ile','CG2'),('rtyr','OH'))] = cmd.select('ile18', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+10,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('ile','CD1'),('rgln','CD'))] = cmd.select('ile19', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+10,resSelectionSubs('gln','CD',subs)))
IDSpec[(('ile','CD1'),('rgln','NE2'))] = cmd.select('ile20', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+10,resSelectionSubs('gln','NE2',subs)))
IDSpec[(('ile','CD1'),('rgln','OE1'))] = cmd.select('ile21', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+10,resSelectionSubs('gln','OE1',subs)))
IDSpec[(('ile','CG1'),('rgln','CD'))] = cmd.select('ile22', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+10,resSelectionSubs('gln','CD',subs)))
IDSpec[(('ile','CG1'),('rgln','NE2'))] = cmd.select('ile23', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+10,resSelectionSubs('gln','NE2',subs)))
IDSpec[(('ile','CG1'),('rgln','OE1'))] = cmd.select('ile24', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+10,resSelectionSubs('gln','OE1',subs)))
IDSpec[(('ile','CG2'),('rgln','CD'))] = cmd.select('ile25', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+10,resSelectionSubs('gln','CD',subs)))
IDSpec[(('ile','CG2'),('rgln','NE2'))] = cmd.select('ile26', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+10,resSelectionSubs('gln','NE2',subs)))
IDSpec[(('ile','CG2'),('rgln','OE1'))] = cmd.select('ile27', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+10,resSelectionSubs('gln','OE1',subs)))
IDSpec['ile'] = cmd.select('ile',' br. ile1&br. ile2&br. ile3&br. ile4&br. ile5&br. ile6&br. ile7&br. ile8&br. ile9&br. ile10&br. ile11&br. ile12&br. ile13&br. ile14&br. ile15&br. ile16&br. ile17&br. ile18&br. ile19&br. ile20&br. ile21&br. ile22&br. ile23&br. ile24&br. ile25&br. ile26&br. ile27')
IDSpec['r_ile'] = cmd.count_atoms(resSelectionSubs('ile', subs=subs, selection=True))
cmd.delete('ile1')
cmd.delete('ile2')
cmd.delete('ile3')
cmd.delete('ile4')
cmd.delete('ile5')
cmd.delete('ile6')
cmd.delete('ile7')
cmd.delete('ile8')
cmd.delete('ile9')
cmd.delete('ile10')
cmd.delete('ile11')
cmd.delete('ile12')
cmd.delete('ile13')
cmd.delete('ile14')
cmd.delete('ile15')
cmd.delete('ile16')
cmd.delete('ile17')
cmd.delete('ile18')
cmd.delete('ile19')
cmd.delete('ile20')
cmd.delete('ile21')
cmd.delete('ile22')
cmd.delete('ile23')
cmd.delete('ile24')
cmd.delete('ile25')
cmd.delete('ile26')
cmd.delete('ile27')
IDSpec[(('lys','CD'),('sile','CD1'))] = cmd.select('lys1', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+10,resSelectionSubs('ile','CD1',subs,selection=True)))
IDSpec[(('lys','CD'),('sile','CG1'))] = cmd.select('lys2', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+10,resSelectionSubs('ile','CG1',subs,selection=True)))
IDSpec[(('lys','CD'),('sile','CG2'))] = cmd.select('lys3', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+10,resSelectionSubs('ile','CG2',subs,selection=True)))
IDSpec[(('lys','CE'),('sile','CD1'))] = cmd.select('lys4', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+10,resSelectionSubs('ile','CD1',subs,selection=True)))
IDSpec[(('lys','CE'),('sile','CG1'))] = cmd.select('lys5', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+10,resSelectionSubs('ile','CG1',subs,selection=True)))
IDSpec[(('lys','CE'),('sile','CG2'))] = cmd.select('lys6', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+10,resSelectionSubs('ile','CG2',subs,selection=True)))
IDSpec[(('lys','NZ'),('sile','CD1'))] = cmd.select('lys7', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+10,resSelectionSubs('ile','CD1',subs,selection=True)))
IDSpec[(('lys','NZ'),('sile','CG1'))] = cmd.select('lys8', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+10,resSelectionSubs('ile','CG1',subs,selection=True)))
IDSpec[(('lys','NZ'),('sile','CG2'))] = cmd.select('lys9', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+10,resSelectionSubs('ile','CG2',subs,selection=True)))
IDSpec[(('lys','CD'),('rtyr','CE1'))] = cmd.select('lys10', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+10,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('lys','CD'),('rtyr','CZ'))] = cmd.select('lys11', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+10,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('lys','CD'),('rtyr','OH'))] = cmd.select('lys12', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+10,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('lys','CE'),('rtyr','CE1'))] = cmd.select('lys13', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+10,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('lys','CE'),('rtyr','CZ'))] = cmd.select('lys14', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+10,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('lys','CE'),('rtyr','OH'))] = cmd.select('lys15', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+10,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('lys','NZ'),('rtyr','CE1'))] = cmd.select('lys16', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+10,resSelectionSubs('tyr','CE1',subs)))
IDSpec[(('lys','NZ'),('rtyr','CZ'))] = cmd.select('lys17', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+10,resSelectionSubs('tyr','CZ',subs)))
IDSpec[(('lys','NZ'),('rtyr','OH'))] = cmd.select('lys18', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+10,resSelectionSubs('tyr','OH',subs)))
IDSpec[(('lys','CD'),('rgln','CD'))] = cmd.select('lys19', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+10,resSelectionSubs('gln','CD',subs)))
IDSpec[(('lys','CD'),('rgln','NE2'))] = cmd.select('lys20', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+10,resSelectionSubs('gln','NE2',subs)))
IDSpec[(('lys','CD'),('rgln','OE1'))] = cmd.select('lys21', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+10,resSelectionSubs('gln','OE1',subs)))
IDSpec[(('lys','CE'),('rgln','CD'))] = cmd.select('lys22', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+10,resSelectionSubs('gln','CD',subs)))
IDSpec[(('lys','CE'),('rgln','NE2'))] = cmd.select('lys23', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+10,resSelectionSubs('gln','NE2',subs)))
IDSpec[(('lys','CE'),('rgln','OE1'))] = cmd.select('lys24', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+10,resSelectionSubs('gln','OE1',subs)))
IDSpec[(('lys','NZ'),('rgln','CD'))] = cmd.select('lys25', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+10,resSelectionSubs('gln','CD',subs)))
IDSpec[(('lys','NZ'),('rgln','NE2'))] = cmd.select('lys26', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+10,resSelectionSubs('gln','NE2',subs)))
IDSpec[(('lys','NZ'),('rgln','OE1'))] = cmd.select('lys27', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+10,resSelectionSubs('gln','OE1',subs)))
IDSpec['lys'] = cmd.select('lys',' br. lys1&br. lys2&br. lys3&br. lys4&br. lys5&br. lys6&br. lys7&br. lys8&br. lys9&br. lys10&br. lys11&br. lys12&br. lys13&br. lys14&br. lys15&br. lys16&br. lys17&br. lys18&br. lys19&br. lys20&br. lys21&br. lys22&br. lys23&br. lys24&br. lys25&br. lys26&br. lys27')
IDSpec['r_lys'] = cmd.count_atoms(resSelectionSubs('lys', subs=subs, selection=True))
cmd.delete('lys1')
cmd.delete('lys2')
cmd.delete('lys3')
cmd.delete('lys4')
cmd.delete('lys5')
cmd.delete('lys6')
cmd.delete('lys7')
cmd.delete('lys8')
cmd.delete('lys9')
cmd.delete('lys10')
cmd.delete('lys11')
cmd.delete('lys12')
cmd.delete('lys13')
cmd.delete('lys14')
cmd.delete('lys15')
cmd.delete('lys16')
cmd.delete('lys17')
cmd.delete('lys18')
cmd.delete('lys19')
cmd.delete('lys20')
cmd.delete('lys21')
cmd.delete('lys22')
cmd.delete('lys23')
cmd.delete('lys24')
cmd.delete('lys25')
cmd.delete('lys26')
cmd.delete('lys27')
IDSpec[(('tyr','CE1'),('sile','CD1'))] = cmd.select('tyr1', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10,resSelectionSubs('ile','CD1',subs,selection=True)))
IDSpec[(('tyr','CE1'),('sile','CG1'))] = cmd.select('tyr2', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10,resSelectionSubs('ile','CG1',subs,selection=True)))
IDSpec[(('tyr','CE1'),('sile','CG2'))] = cmd.select('tyr3', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10,resSelectionSubs('ile','CG2',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sile','CD1'))] = cmd.select('tyr4', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+10,resSelectionSubs('ile','CD1',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sile','CG1'))] = cmd.select('tyr5', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+10,resSelectionSubs('ile','CG1',subs,selection=True)))
IDSpec[(('tyr','CZ'),('sile','CG2'))] = cmd.select('tyr6', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+10,resSelectionSubs('ile','CG2',subs,selection=True)))
IDSpec[(('tyr','OH'),('sile','CD1'))] = cmd.select('tyr7', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+10,resSelectionSubs('ile','CD1',subs,selection=True)))
IDSpec[(('tyr','OH'),('sile','CG1'))] = cmd.select('tyr8', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+10,resSelectionSubs('ile','CG1',subs,selection=True)))
IDSpec[(('tyr','OH'),('sile','CG2'))] = cmd.select('tyr9', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+10,resSelectionSubs('ile','CG2',subs,selection=True)))
IDSpec[(('tyr','CE1'),('slys','CD'))] = cmd.select('tyr10', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('tyr','CE1'),('slys','CE'))] = cmd.select('tyr11', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('tyr','CE1'),('slys','NZ'))] = cmd.select('tyr12', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('tyr','CZ'),('slys','CD'))] = cmd.select('tyr13', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+10,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('tyr','CZ'),('slys','CE'))] = cmd.select('tyr14', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+10,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('tyr','CZ'),('slys','NZ'))] = cmd.select('tyr15', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+10,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('tyr','OH'),('slys','CD'))] = cmd.select('tyr16', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+10,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('tyr','OH'),('slys','CE'))] = cmd.select('tyr17', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+10,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('tyr','OH'),('slys','NZ'))] = cmd.select('tyr18', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+10,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('tyr','CE1'),('rgln','CD'))] = cmd.select('tyr19', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10,resSelectionSubs('gln','CD',subs)))
IDSpec[(('tyr','CE1'),('rgln','NE2'))] = cmd.select('tyr20', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10,resSelectionSubs('gln','NE2',subs)))
IDSpec[(('tyr','CE1'),('rgln','OE1'))] = cmd.select('tyr21', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10,resSelectionSubs('gln','OE1',subs)))
IDSpec[(('tyr','CZ'),('rgln','CD'))] = cmd.select('tyr22', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+10,resSelectionSubs('gln','CD',subs)))
IDSpec[(('tyr','CZ'),('rgln','NE2'))] = cmd.select('tyr23', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+10,resSelectionSubs('gln','NE2',subs)))
IDSpec[(('tyr','CZ'),('rgln','OE1'))] = cmd.select('tyr24', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+10,resSelectionSubs('gln','OE1',subs)))
IDSpec[(('tyr','OH'),('rgln','CD'))] = cmd.select('tyr25', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+10,resSelectionSubs('gln','CD',subs)))
IDSpec[(('tyr','OH'),('rgln','NE2'))] = cmd.select('tyr26', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+10,resSelectionSubs('gln','NE2',subs)))
IDSpec[(('tyr','OH'),('rgln','OE1'))] = cmd.select('tyr27', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+10,resSelectionSubs('gln','OE1',subs)))
IDSpec['tyr'] = cmd.select('tyr',' br. tyr1&br. tyr2&br. tyr3&br. tyr4&br. tyr5&br. tyr6&br. tyr7&br. tyr8&br. tyr9&br. tyr10&br. tyr11&br. tyr12&br. tyr13&br. tyr14&br. tyr15&br. tyr16&br. tyr17&br. tyr18&br. tyr19&br. tyr20&br. tyr21&br. tyr22&br. tyr23&br. tyr24&br. tyr25&br. tyr26&br. tyr27')
IDSpec['r_tyr'] = cmd.count_atoms(resSelectionSubs('tyr', subs=subs, selection=True))
cmd.delete('tyr1')
cmd.delete('tyr2')
cmd.delete('tyr3')
cmd.delete('tyr4')
cmd.delete('tyr5')
cmd.delete('tyr6')
cmd.delete('tyr7')
cmd.delete('tyr8')
cmd.delete('tyr9')
cmd.delete('tyr10')
cmd.delete('tyr11')
cmd.delete('tyr12')
cmd.delete('tyr13')
cmd.delete('tyr14')
cmd.delete('tyr15')
cmd.delete('tyr16')
cmd.delete('tyr17')
cmd.delete('tyr18')
cmd.delete('tyr19')
cmd.delete('tyr20')
cmd.delete('tyr21')
cmd.delete('tyr22')
cmd.delete('tyr23')
cmd.delete('tyr24')
cmd.delete('tyr25')
cmd.delete('tyr26')
cmd.delete('tyr27')
IDSpec[(('gln','CD'),('sile','CD1'))] = cmd.select('gln1', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+10,resSelectionSubs('ile','CD1',subs,selection=True)))
IDSpec[(('gln','CD'),('sile','CG1'))] = cmd.select('gln2', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+10,resSelectionSubs('ile','CG1',subs,selection=True)))
IDSpec[(('gln','CD'),('sile','CG2'))] = cmd.select('gln3', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+10,resSelectionSubs('ile','CG2',subs,selection=True)))
IDSpec[(('gln','NE2'),('sile','CD1'))] = cmd.select('gln4', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+10,resSelectionSubs('ile','CD1',subs,selection=True)))
IDSpec[(('gln','NE2'),('sile','CG1'))] = cmd.select('gln5', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+10,resSelectionSubs('ile','CG1',subs,selection=True)))
IDSpec[(('gln','NE2'),('sile','CG2'))] = cmd.select('gln6', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+10,resSelectionSubs('ile','CG2',subs,selection=True)))
IDSpec[(('gln','OE1'),('sile','CD1'))] = cmd.select('gln7', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+10,resSelectionSubs('ile','CD1',subs,selection=True)))
IDSpec[(('gln','OE1'),('sile','CG1'))] = cmd.select('gln8', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+10,resSelectionSubs('ile','CG1',subs,selection=True)))
IDSpec[(('gln','OE1'),('sile','CG2'))] = cmd.select('gln9', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+10,resSelectionSubs('ile','CG2',subs,selection=True)))
IDSpec[(('gln','CD'),('slys','CD'))] = cmd.select('gln10', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+10,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('gln','CD'),('slys','CE'))] = cmd.select('gln11', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+10,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('gln','CD'),('slys','NZ'))] = cmd.select('gln12', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+10,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('gln','NE2'),('slys','CD'))] = cmd.select('gln13', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+10,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('gln','NE2'),('slys','CE'))] = cmd.select('gln14', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+10,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('gln','NE2'),('slys','NZ'))] = cmd.select('gln15', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+10,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('gln','OE1'),('slys','CD'))] = cmd.select('gln16', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+10,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('gln','OE1'),('slys','CE'))] = cmd.select('gln17', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+10,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('gln','OE1'),('slys','NZ'))] = cmd.select('gln18', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+10,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('gln','CD'),('styr','CE1'))] = cmd.select('gln19', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+10,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('gln','CD'),('styr','CZ'))] = cmd.select('gln20', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+10,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('gln','CD'),('styr','OH'))] = cmd.select('gln21', '%s w. %s of %s'%(resSelectionSubs('gln','CD',subs),d+10,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('gln','NE2'),('styr','CE1'))] = cmd.select('gln22', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+10,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('gln','NE2'),('styr','CZ'))] = cmd.select('gln23', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+10,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('gln','NE2'),('styr','OH'))] = cmd.select('gln24', '%s w. %s of %s'%(resSelectionSubs('gln','NE2',subs),d+10,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('gln','OE1'),('styr','CE1'))] = cmd.select('gln25', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+10,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('gln','OE1'),('styr','CZ'))] = cmd.select('gln26', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+10,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('gln','OE1'),('styr','OH'))] = cmd.select('gln27', '%s w. %s of %s'%(resSelectionSubs('gln','OE1',subs),d+10,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec['gln'] = cmd.select('gln',' br. gln1&br. gln2&br. gln3&br. gln4&br. gln5&br. gln6&br. gln7&br. gln8&br. gln9&br. gln10&br. gln11&br. gln12&br. gln13&br. gln14&br. gln15&br. gln16&br. gln17&br. gln18&br. gln19&br. gln20&br. gln21&br. gln22&br. gln23&br. gln24&br. gln25&br. gln26&br. gln27')
IDSpec['r_gln'] = cmd.count_atoms(resSelectionSubs('gln', subs=subs, selection=True))
cmd.delete('gln1')
cmd.delete('gln2')
cmd.delete('gln3')
cmd.delete('gln4')
cmd.delete('gln5')
cmd.delete('gln6')
cmd.delete('gln7')
cmd.delete('gln8')
cmd.delete('gln9')
cmd.delete('gln10')
cmd.delete('gln11')
cmd.delete('gln12')
cmd.delete('gln13')
cmd.delete('gln14')
cmd.delete('gln15')
cmd.delete('gln16')
cmd.delete('gln17')
cmd.delete('gln18')
cmd.delete('gln19')
cmd.delete('gln20')
cmd.delete('gln21')
cmd.delete('gln22')
cmd.delete('gln23')
cmd.delete('gln24')
cmd.delete('gln25')
cmd.delete('gln26')
cmd.delete('gln27')
IDSpec['S_2rk2_1_5_1_3'] = cmd.select('S_2rk2_1_5_1_3', 'ile|lys|tyr|gln')
cmd.delete('ile')
cmd.delete('lys')
cmd.delete('tyr')
cmd.delete('gln')
