'''
FUNC:S_2tmd_1_5_99_7
PDB:2tmd
EC:1.5.99.7
RESI:tyr,his,tyr,asp,asp
LOCI:a-169,172,174,260,267;
'''
IDSpec[(('tyr','CE1'),('rasp','CG'))] = cmd.select('tyr1', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+12.38,resSelectionSubs('asp','CG',subs)))
IDSpec[(('tyr','CE1'),('rasp','OD1'))] = cmd.select('tyr2', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+12.63,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('tyr','CE1'),('rasp','OD2'))] = cmd.select('tyr3', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+12.92,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('tyr','CZ'),('rasp','CG'))] = cmd.select('tyr4', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+12.30,resSelectionSubs('asp','CG',subs)))
IDSpec[(('tyr','CZ'),('rasp','OD1'))] = cmd.select('tyr5', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+12.39,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('tyr','CZ'),('rasp','OD2'))] = cmd.select('tyr6', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+12.95,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('tyr','OH'),('rasp','CG'))] = cmd.select('tyr7', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+12.51,resSelectionSubs('asp','CG',subs)))
IDSpec[(('tyr','OH'),('rasp','OD1'))] = cmd.select('tyr8', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+12.50,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('tyr','OH'),('rasp','OD2'))] = cmd.select('tyr9', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+13.14,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('tyr','CE1'),('rhis','CE1'))] = cmd.select('tyr10', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10.40,resSelectionSubs('his','CE1',subs)))
IDSpec[(('tyr','CE1'),('rhis','ND1'))] = cmd.select('tyr11', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+9.16,resSelectionSubs('his','ND1',subs)))
IDSpec[(('tyr','CE1'),('rhis','NE2'))] = cmd.select('tyr12', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10.73,resSelectionSubs('his','NE2',subs)))
IDSpec[(('tyr','CZ'),('rhis','CE1'))] = cmd.select('tyr13', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+9.31,resSelectionSubs('his','CE1',subs)))
IDSpec[(('tyr','CZ'),('rhis','ND1'))] = cmd.select('tyr14', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+8.13,resSelectionSubs('his','ND1',subs)))
IDSpec[(('tyr','CZ'),('rhis','NE2'))] = cmd.select('tyr15', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+9.67,resSelectionSubs('his','NE2',subs)))
IDSpec[(('tyr','OH'),('rhis','CE1'))] = cmd.select('tyr16', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+9.57,resSelectionSubs('his','CE1',subs)))
IDSpec[(('tyr','OH'),('rhis','ND1'))] = cmd.select('tyr17', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+8.51,resSelectionSubs('his','ND1',subs)))
IDSpec[(('tyr','OH'),('rhis','NE2'))] = cmd.select('tyr18', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+9.84,resSelectionSubs('his','NE2',subs)))
IDSpec[(('tyr','CE1'),('rtyr_i','CE1'))] = cmd.select('tyr19', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+9.24,resSelectionSubs('tyr_i','CE1',subs)))
IDSpec[(('tyr','CE1'),('rtyr_i','CZ'))] = cmd.select('tyr20', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+8.29,resSelectionSubs('tyr_i','CZ',subs)))
IDSpec[(('tyr','CE1'),('rtyr_i','OH'))] = cmd.select('tyr21', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+8.20,resSelectionSubs('tyr_i','OH',subs)))
IDSpec[(('tyr','CZ'),('rtyr_i','CE1'))] = cmd.select('tyr22', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+8.47,resSelectionSubs('tyr_i','CE1',subs)))
IDSpec[(('tyr','CZ'),('rtyr_i','CZ'))] = cmd.select('tyr23', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+7.39,resSelectionSubs('tyr_i','CZ',subs)))
IDSpec[(('tyr','CZ'),('rtyr_i','OH'))] = cmd.select('tyr24', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+7.10,resSelectionSubs('tyr_i','OH',subs)))
IDSpec[(('tyr','OH'),('rtyr_i','CE1'))] = cmd.select('tyr25', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+9.28,resSelectionSubs('tyr_i','CE1',subs)))
IDSpec[(('tyr','OH'),('rtyr_i','CZ'))] = cmd.select('tyr26', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+8.08,resSelectionSubs('tyr_i','CZ',subs)))
IDSpec[(('tyr','OH'),('rtyr_i','OH'))] = cmd.select('tyr27', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+7.54,resSelectionSubs('tyr_i','OH',subs)))
IDSpec[(('tyr','CE1'),('rasp_i','CG'))] = cmd.select('tyr28', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+14.40,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('tyr','CE1'),('rasp_i','OD1'))] = cmd.select('tyr29', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+15.42,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('tyr','CE1'),('rasp_i','OD2'))] = cmd.select('tyr30', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+13.49,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('tyr','CZ'),('rasp_i','CG'))] = cmd.select('tyr31', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+13.34,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('tyr','CZ'),('rasp_i','OD1'))] = cmd.select('tyr32', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+14.36,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('tyr','CZ'),('rasp_i','OD2'))] = cmd.select('tyr33', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+12.37,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('tyr','OH'),('rasp_i','CG'))] = cmd.select('tyr34', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+13.40,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('tyr','OH'),('rasp_i','OD1'))] = cmd.select('tyr35', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+14.47,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('tyr','OH'),('rasp_i','OD2'))] = cmd.select('tyr36', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+12.39,resSelectionSubs('asp_i','OD2',subs)))
IDSpec['tyr'] = cmd.select('tyr',' br. tyr1&br. tyr2&br. tyr3&br. tyr4&br. tyr5&br. tyr6&br. tyr7&br. tyr8&br. tyr9&br. tyr10&br. tyr11&br. tyr12&br. tyr13&br. tyr14&br. tyr15&br. tyr16&br. tyr17&br. tyr18&br. tyr19&br. tyr20&br. tyr21&br. tyr22&br. tyr23&br. tyr24&br. tyr25&br. tyr26&br. tyr27&br. tyr28&br. tyr29&br. tyr30&br. tyr31&br. tyr32&br. tyr33&br. tyr34&br. tyr35&br. tyr36')
IDSpec['r_tyr'] = cmd.count_atoms(resSelectionSubs('tyr', subs=subs, selection=True))
cmd.delete('tyr1')
cmd.delete('tyr2')
cmd.delete('tyr3')
cmd.delete('tyr4')
cmd.delete('tyr5')
cmd.delete('tyr6')
cmd.delete('tyr7')
cmd.delete('tyr8')
cmd.delete('tyr9')
cmd.delete('tyr10')
cmd.delete('tyr11')
cmd.delete('tyr12')
cmd.delete('tyr13')
cmd.delete('tyr14')
cmd.delete('tyr15')
cmd.delete('tyr16')
cmd.delete('tyr17')
cmd.delete('tyr18')
cmd.delete('tyr19')
cmd.delete('tyr20')
cmd.delete('tyr21')
cmd.delete('tyr22')
cmd.delete('tyr23')
cmd.delete('tyr24')
cmd.delete('tyr25')
cmd.delete('tyr26')
cmd.delete('tyr27')
cmd.delete('tyr28')
cmd.delete('tyr29')
cmd.delete('tyr30')
cmd.delete('tyr31')
cmd.delete('tyr32')
cmd.delete('tyr33')
cmd.delete('tyr34')
cmd.delete('tyr35')
cmd.delete('tyr36')
IDSpec[(('asp','CG'),('styr','CE1'))] = cmd.select('asp1', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+12.38,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('asp','CG'),('styr','CZ'))] = cmd.select('asp2', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+12.30,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('asp','CG'),('styr','OH'))] = cmd.select('asp3', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+12.51,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('asp','OD1'),('styr','CE1'))] = cmd.select('asp4', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+12.63,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('asp','OD1'),('styr','CZ'))] = cmd.select('asp5', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+12.39,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('asp','OD1'),('styr','OH'))] = cmd.select('asp6', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+12.50,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('asp','OD2'),('styr','CE1'))] = cmd.select('asp7', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+12.92,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('asp','OD2'),('styr','CZ'))] = cmd.select('asp8', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+12.95,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('asp','OD2'),('styr','OH'))] = cmd.select('asp9', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+13.14,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('asp','CG'),('rhis','CE1'))] = cmd.select('asp10', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+11.81,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp','CG'),('rhis','ND1'))] = cmd.select('asp11', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+11.49,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp','CG'),('rhis','NE2'))] = cmd.select('asp12', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+10.81,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp','OD1'),('rhis','CE1'))] = cmd.select('asp13', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+11.29,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp','OD1'),('rhis','ND1'))] = cmd.select('asp14', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+11.12,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp','OD1'),('rhis','NE2'))] = cmd.select('asp15', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+10.20,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp','OD2'),('rhis','CE1'))] = cmd.select('asp16', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+12.99,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp','OD2'),('rhis','ND1'))] = cmd.select('asp17', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+12.62,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp','OD2'),('rhis','NE2'))] = cmd.select('asp18', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+12.00,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp','CG'),('rtyr_i','CE1'))] = cmd.select('asp19', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+14.19,resSelectionSubs('tyr_i','CE1',subs)))
IDSpec[(('asp','CG'),('rtyr_i','CZ'))] = cmd.select('asp20', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+14.07,resSelectionSubs('tyr_i','CZ',subs)))
IDSpec[(('asp','CG'),('rtyr_i','OH'))] = cmd.select('asp21', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+13.41,resSelectionSubs('tyr_i','OH',subs)))
IDSpec[(('asp','OD1'),('rtyr_i','CE1'))] = cmd.select('asp22', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+14.08,resSelectionSubs('tyr_i','CE1',subs)))
IDSpec[(('asp','OD1'),('rtyr_i','CZ'))] = cmd.select('asp23', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+13.93,resSelectionSubs('tyr_i','CZ',subs)))
IDSpec[(('asp','OD1'),('rtyr_i','OH'))] = cmd.select('asp24', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+13.16,resSelectionSubs('tyr_i','OH',subs)))
IDSpec[(('asp','OD2'),('rtyr_i','CE1'))] = cmd.select('asp25', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+15.26,resSelectionSubs('tyr_i','CE1',subs)))
IDSpec[(('asp','OD2'),('rtyr_i','CZ'))] = cmd.select('asp26', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+15.10,resSelectionSubs('tyr_i','CZ',subs)))
IDSpec[(('asp','OD2'),('rtyr_i','OH'))] = cmd.select('asp27', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+14.45,resSelectionSubs('tyr_i','OH',subs)))
IDSpec[(('asp','CG'),('rasp_i','CG'))] = cmd.select('asp28', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+12.16,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('asp','CG'),('rasp_i','OD1'))] = cmd.select('asp29', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+13.14,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('asp','CG'),('rasp_i','OD2'))] = cmd.select('asp30', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+12.26,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('asp','OD1'),('rasp_i','CG'))] = cmd.select('asp31', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+11.29,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('asp','OD1'),('rasp_i','OD1'))] = cmd.select('asp32', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+12.28,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('asp','OD1'),('rasp_i','OD2'))] = cmd.select('asp33', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+11.42,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('asp','OD2'),('rasp_i','CG'))] = cmd.select('asp34', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+13.36,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('asp','OD2'),('rasp_i','OD1'))] = cmd.select('asp35', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+14.35,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('asp','OD2'),('rasp_i','OD2'))] = cmd.select('asp36', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+13.46,resSelectionSubs('asp_i','OD2',subs)))
IDSpec['asp'] = cmd.select('asp',' br. asp1&br. asp2&br. asp3&br. asp4&br. asp5&br. asp6&br. asp7&br. asp8&br. asp9&br. asp10&br. asp11&br. asp12&br. asp13&br. asp14&br. asp15&br. asp16&br. asp17&br. asp18&br. asp19&br. asp20&br. asp21&br. asp22&br. asp23&br. asp24&br. asp25&br. asp26&br. asp27&br. asp28&br. asp29&br. asp30&br. asp31&br. asp32&br. asp33&br. asp34&br. asp35&br. asp36')
IDSpec['r_asp'] = cmd.count_atoms(resSelectionSubs('asp', subs=subs, selection=True))
cmd.delete('asp1')
cmd.delete('asp2')
cmd.delete('asp3')
cmd.delete('asp4')
cmd.delete('asp5')
cmd.delete('asp6')
cmd.delete('asp7')
cmd.delete('asp8')
cmd.delete('asp9')
cmd.delete('asp10')
cmd.delete('asp11')
cmd.delete('asp12')
cmd.delete('asp13')
cmd.delete('asp14')
cmd.delete('asp15')
cmd.delete('asp16')
cmd.delete('asp17')
cmd.delete('asp18')
cmd.delete('asp19')
cmd.delete('asp20')
cmd.delete('asp21')
cmd.delete('asp22')
cmd.delete('asp23')
cmd.delete('asp24')
cmd.delete('asp25')
cmd.delete('asp26')
cmd.delete('asp27')
cmd.delete('asp28')
cmd.delete('asp29')
cmd.delete('asp30')
cmd.delete('asp31')
cmd.delete('asp32')
cmd.delete('asp33')
cmd.delete('asp34')
cmd.delete('asp35')
cmd.delete('asp36')
IDSpec[(('his','CE1'),('styr','CE1'))] = cmd.select('his1', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+10.40,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('his','CE1'),('styr','CZ'))] = cmd.select('his2', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+9.31,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('his','CE1'),('styr','OH'))] = cmd.select('his3', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+9.57,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('his','ND1'),('styr','CE1'))] = cmd.select('his4', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+9.16,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('his','ND1'),('styr','CZ'))] = cmd.select('his5', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+8.13,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('his','ND1'),('styr','OH'))] = cmd.select('his6', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+8.51,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('his','NE2'),('styr','CE1'))] = cmd.select('his7', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+10.73,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('his','NE2'),('styr','CZ'))] = cmd.select('his8', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+9.67,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('his','NE2'),('styr','OH'))] = cmd.select('his9', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+9.84,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('his','CE1'),('sasp','CG'))] = cmd.select('his10', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+11.81,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his','CE1'),('sasp','OD1'))] = cmd.select('his11', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+11.29,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his','CE1'),('sasp','OD2'))] = cmd.select('his12', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+12.99,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his','ND1'),('sasp','CG'))] = cmd.select('his13', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+11.49,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his','ND1'),('sasp','OD1'))] = cmd.select('his14', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+11.12,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his','ND1'),('sasp','OD2'))] = cmd.select('his15', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+12.62,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his','NE2'),('sasp','CG'))] = cmd.select('his16', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+10.81,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his','NE2'),('sasp','OD1'))] = cmd.select('his17', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+10.20,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his','NE2'),('sasp','OD2'))] = cmd.select('his18', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+12.00,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his','CE1'),('rtyr_i','CE1'))] = cmd.select('his19', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.45,resSelectionSubs('tyr_i','CE1',subs)))
IDSpec[(('his','CE1'),('rtyr_i','CZ'))] = cmd.select('his20', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.41,resSelectionSubs('tyr_i','CZ',subs)))
IDSpec[(('his','CE1'),('rtyr_i','OH'))] = cmd.select('his21', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+5.46,resSelectionSubs('tyr_i','OH',subs)))
IDSpec[(('his','ND1'),('rtyr_i','CE1'))] = cmd.select('his22', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+5.64,resSelectionSubs('tyr_i','CE1',subs)))
IDSpec[(('his','ND1'),('rtyr_i','CZ'))] = cmd.select('his23', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+5.47,resSelectionSubs('tyr_i','CZ',subs)))
IDSpec[(('his','ND1'),('rtyr_i','OH'))] = cmd.select('his24', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+4.56,resSelectionSubs('tyr_i','OH',subs)))
IDSpec[(('his','NE2'),('rtyr_i','CE1'))] = cmd.select('his25', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+7.63,resSelectionSubs('tyr_i','CE1',subs)))
IDSpec[(('his','NE2'),('rtyr_i','CZ'))] = cmd.select('his26', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+7.55,resSelectionSubs('tyr_i','CZ',subs)))
IDSpec[(('his','NE2'),('rtyr_i','OH'))] = cmd.select('his27', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.55,resSelectionSubs('tyr_i','OH',subs)))
IDSpec[(('his','CE1'),('rasp_i','CG'))] = cmd.select('his28', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+6.44,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('his','CE1'),('rasp_i','OD1'))] = cmd.select('his29', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.23,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('his','CE1'),('rasp_i','OD2'))] = cmd.select('his30', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+5.47,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('his','ND1'),('rasp_i','CG'))] = cmd.select('his31', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.66,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('his','ND1'),('rasp_i','OD1'))] = cmd.select('his32', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+8.48,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('his','ND1'),('rasp_i','OD2'))] = cmd.select('his33', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+6.74,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('his','NE2'),('rasp_i','CG'))] = cmd.select('his34', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+5.70,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('his','NE2'),('rasp_i','OD1'))] = cmd.select('his35', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.69,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('his','NE2'),('rasp_i','OD2'))] = cmd.select('his36', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+4.84,resSelectionSubs('asp_i','OD2',subs)))
IDSpec['his'] = cmd.select('his',' br. his1&br. his2&br. his3&br. his4&br. his5&br. his6&br. his7&br. his8&br. his9&br. his10&br. his11&br. his12&br. his13&br. his14&br. his15&br. his16&br. his17&br. his18&br. his19&br. his20&br. his21&br. his22&br. his23&br. his24&br. his25&br. his26&br. his27&br. his28&br. his29&br. his30&br. his31&br. his32&br. his33&br. his34&br. his35&br. his36')
IDSpec['r_his'] = cmd.count_atoms(resSelectionSubs('his', subs=subs, selection=True))
cmd.delete('his1')
cmd.delete('his2')
cmd.delete('his3')
cmd.delete('his4')
cmd.delete('his5')
cmd.delete('his6')
cmd.delete('his7')
cmd.delete('his8')
cmd.delete('his9')
cmd.delete('his10')
cmd.delete('his11')
cmd.delete('his12')
cmd.delete('his13')
cmd.delete('his14')
cmd.delete('his15')
cmd.delete('his16')
cmd.delete('his17')
cmd.delete('his18')
cmd.delete('his19')
cmd.delete('his20')
cmd.delete('his21')
cmd.delete('his22')
cmd.delete('his23')
cmd.delete('his24')
cmd.delete('his25')
cmd.delete('his26')
cmd.delete('his27')
cmd.delete('his28')
cmd.delete('his29')
cmd.delete('his30')
cmd.delete('his31')
cmd.delete('his32')
cmd.delete('his33')
cmd.delete('his34')
cmd.delete('his35')
cmd.delete('his36')
IDSpec[(('tyr_i','CE1'),('styr','CE1'))] = cmd.select('tyr_i1', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+9.24,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('styr','CZ'))] = cmd.select('tyr_i2', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+8.47,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('styr','OH'))] = cmd.select('tyr_i3', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+9.28,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('styr','CE1'))] = cmd.select('tyr_i4', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+8.29,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('styr','CZ'))] = cmd.select('tyr_i5', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+7.39,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('styr','OH'))] = cmd.select('tyr_i6', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+8.08,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('styr','CE1'))] = cmd.select('tyr_i7', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+8.20,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('styr','CZ'))] = cmd.select('tyr_i8', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+7.10,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('styr','OH'))] = cmd.select('tyr_i9', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+7.54,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('sasp','CG'))] = cmd.select('tyr_i10', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+14.19,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('sasp','OD1'))] = cmd.select('tyr_i11', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+14.08,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('sasp','OD2'))] = cmd.select('tyr_i12', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+15.26,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('sasp','CG'))] = cmd.select('tyr_i13', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+14.07,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('sasp','OD1'))] = cmd.select('tyr_i14', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+13.93,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('sasp','OD2'))] = cmd.select('tyr_i15', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+15.10,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('sasp','CG'))] = cmd.select('tyr_i16', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+13.41,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('sasp','OD1'))] = cmd.select('tyr_i17', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+13.16,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('sasp','OD2'))] = cmd.select('tyr_i18', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+14.45,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('shis','CE1'))] = cmd.select('tyr_i19', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+6.45,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('shis','ND1'))] = cmd.select('tyr_i20', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+5.64,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('shis','NE2'))] = cmd.select('tyr_i21', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+7.63,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('shis','CE1'))] = cmd.select('tyr_i22', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+6.41,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('shis','ND1'))] = cmd.select('tyr_i23', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+5.47,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('tyr_i','CZ'),('shis','NE2'))] = cmd.select('tyr_i24', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+7.55,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('shis','CE1'))] = cmd.select('tyr_i25', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+5.46,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('shis','ND1'))] = cmd.select('tyr_i26', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+4.56,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('tyr_i','OH'),('shis','NE2'))] = cmd.select('tyr_i27', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+6.55,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('tyr_i','CE1'),('rasp_i','CG'))] = cmd.select('tyr_i28', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+10.57,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('tyr_i','CE1'),('rasp_i','OD1'))] = cmd.select('tyr_i29', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+11.03,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('tyr_i','CE1'),('rasp_i','OD2'))] = cmd.select('tyr_i30', '%s w. %s of %s'%(resSelectionSubs('tyr','CE1',subs),d+9.70,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('tyr_i','CZ'),('rasp_i','CG'))] = cmd.select('tyr_i31', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+10.77,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('tyr_i','CZ'),('rasp_i','OD1'))] = cmd.select('tyr_i32', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+11.38,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('tyr_i','CZ'),('rasp_i','OD2'))] = cmd.select('tyr_i33', '%s w. %s of %s'%(resSelectionSubs('tyr','CZ',subs),d+9.79,resSelectionSubs('asp_i','OD2',subs)))
IDSpec[(('tyr_i','OH'),('rasp_i','CG'))] = cmd.select('tyr_i34', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+9.87,resSelectionSubs('asp_i','CG',subs)))
IDSpec[(('tyr_i','OH'),('rasp_i','OD1'))] = cmd.select('tyr_i35', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+10.58,resSelectionSubs('asp_i','OD1',subs)))
IDSpec[(('tyr_i','OH'),('rasp_i','OD2'))] = cmd.select('tyr_i36', '%s w. %s of %s'%(resSelectionSubs('tyr','OH',subs),d+8.81,resSelectionSubs('asp_i','OD2',subs)))
IDSpec['tyr_i'] = cmd.select('tyr_i',' br. tyr_i1&br. tyr_i2&br. tyr_i3&br. tyr_i4&br. tyr_i5&br. tyr_i6&br. tyr_i7&br. tyr_i8&br. tyr_i9&br. tyr_i10&br. tyr_i11&br. tyr_i12&br. tyr_i13&br. tyr_i14&br. tyr_i15&br. tyr_i16&br. tyr_i17&br. tyr_i18&br. tyr_i19&br. tyr_i20&br. tyr_i21&br. tyr_i22&br. tyr_i23&br. tyr_i24&br. tyr_i25&br. tyr_i26&br. tyr_i27&br. tyr_i28&br. tyr_i29&br. tyr_i30&br. tyr_i31&br. tyr_i32&br. tyr_i33&br. tyr_i34&br. tyr_i35&br. tyr_i36')
IDSpec['r_tyr_i'] = cmd.count_atoms(resSelectionSubs('tyr_i', subs=subs, selection=True))
cmd.delete('tyr_i1')
cmd.delete('tyr_i2')
cmd.delete('tyr_i3')
cmd.delete('tyr_i4')
cmd.delete('tyr_i5')
cmd.delete('tyr_i6')
cmd.delete('tyr_i7')
cmd.delete('tyr_i8')
cmd.delete('tyr_i9')
cmd.delete('tyr_i10')
cmd.delete('tyr_i11')
cmd.delete('tyr_i12')
cmd.delete('tyr_i13')
cmd.delete('tyr_i14')
cmd.delete('tyr_i15')
cmd.delete('tyr_i16')
cmd.delete('tyr_i17')
cmd.delete('tyr_i18')
cmd.delete('tyr_i19')
cmd.delete('tyr_i20')
cmd.delete('tyr_i21')
cmd.delete('tyr_i22')
cmd.delete('tyr_i23')
cmd.delete('tyr_i24')
cmd.delete('tyr_i25')
cmd.delete('tyr_i26')
cmd.delete('tyr_i27')
cmd.delete('tyr_i28')
cmd.delete('tyr_i29')
cmd.delete('tyr_i30')
cmd.delete('tyr_i31')
cmd.delete('tyr_i32')
cmd.delete('tyr_i33')
cmd.delete('tyr_i34')
cmd.delete('tyr_i35')
cmd.delete('tyr_i36')
IDSpec[(('asp_i','CG'),('styr','CE1'))] = cmd.select('asp_i1', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+14.40,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('styr','CZ'))] = cmd.select('asp_i2', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+13.34,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('asp_i','CG'),('styr','OH'))] = cmd.select('asp_i3', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+13.40,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('styr','CE1'))] = cmd.select('asp_i4', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+15.42,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('styr','CZ'))] = cmd.select('asp_i5', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+14.36,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('styr','OH'))] = cmd.select('asp_i6', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+14.47,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('styr','CE1'))] = cmd.select('asp_i7', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+13.49,resSelectionSubs('tyr','CE1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('styr','CZ'))] = cmd.select('asp_i8', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+12.37,resSelectionSubs('tyr','CZ',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('styr','OH'))] = cmd.select('asp_i9', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+12.39,resSelectionSubs('tyr','OH',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasp','CG'))] = cmd.select('asp_i10', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+12.16,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasp','OD1'))] = cmd.select('asp_i11', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+11.29,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasp','OD2'))] = cmd.select('asp_i12', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+13.36,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasp','CG'))] = cmd.select('asp_i13', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+13.14,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasp','OD1'))] = cmd.select('asp_i14', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+12.28,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasp','OD2'))] = cmd.select('asp_i15', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+14.35,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasp','CG'))] = cmd.select('asp_i16', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+12.26,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasp','OD1'))] = cmd.select('asp_i17', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.42,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasp','OD2'))] = cmd.select('asp_i18', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+13.46,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asp_i','CG'),('shis','CE1'))] = cmd.select('asp_i19', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.44,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('shis','ND1'))] = cmd.select('asp_i20', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.66,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('shis','NE2'))] = cmd.select('asp_i21', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+5.70,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('shis','CE1'))] = cmd.select('asp_i22', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.23,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('shis','ND1'))] = cmd.select('asp_i23', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.48,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('shis','NE2'))] = cmd.select('asp_i24', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+6.69,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('shis','CE1'))] = cmd.select('asp_i25', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+5.47,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('shis','ND1'))] = cmd.select('asp_i26', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.74,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('shis','NE2'))] = cmd.select('asp_i27', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+4.84,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asp_i','CG'),('styr_i','CE1'))] = cmd.select('asp_i28', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+10.57,resSelectionSubs('tyr_i','CE1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('styr_i','CZ'))] = cmd.select('asp_i29', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+10.77,resSelectionSubs('tyr_i','CZ',subs,selection=True)))
IDSpec[(('asp_i','CG'),('styr_i','OH'))] = cmd.select('asp_i30', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+9.87,resSelectionSubs('tyr_i','OH',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('styr_i','CE1'))] = cmd.select('asp_i31', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+11.03,resSelectionSubs('tyr_i','CE1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('styr_i','CZ'))] = cmd.select('asp_i32', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+11.38,resSelectionSubs('tyr_i','CZ',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('styr_i','OH'))] = cmd.select('asp_i33', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+10.58,resSelectionSubs('tyr_i','OH',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('styr_i','CE1'))] = cmd.select('asp_i34', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+9.70,resSelectionSubs('tyr_i','CE1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('styr_i','CZ'))] = cmd.select('asp_i35', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+9.79,resSelectionSubs('tyr_i','CZ',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('styr_i','OH'))] = cmd.select('asp_i36', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+8.81,resSelectionSubs('tyr_i','OH',subs,selection=True)))
IDSpec['asp_i'] = cmd.select('asp_i',' br. asp_i1&br. asp_i2&br. asp_i3&br. asp_i4&br. asp_i5&br. asp_i6&br. asp_i7&br. asp_i8&br. asp_i9&br. asp_i10&br. asp_i11&br. asp_i12&br. asp_i13&br. asp_i14&br. asp_i15&br. asp_i16&br. asp_i17&br. asp_i18&br. asp_i19&br. asp_i20&br. asp_i21&br. asp_i22&br. asp_i23&br. asp_i24&br. asp_i25&br. asp_i26&br. asp_i27&br. asp_i28&br. asp_i29&br. asp_i30&br. asp_i31&br. asp_i32&br. asp_i33&br. asp_i34&br. asp_i35&br. asp_i36')
IDSpec['r_asp_i'] = cmd.count_atoms(resSelectionSubs('asp_i', subs=subs, selection=True))
cmd.delete('asp_i1')
cmd.delete('asp_i2')
cmd.delete('asp_i3')
cmd.delete('asp_i4')
cmd.delete('asp_i5')
cmd.delete('asp_i6')
cmd.delete('asp_i7')
cmd.delete('asp_i8')
cmd.delete('asp_i9')
cmd.delete('asp_i10')
cmd.delete('asp_i11')
cmd.delete('asp_i12')
cmd.delete('asp_i13')
cmd.delete('asp_i14')
cmd.delete('asp_i15')
cmd.delete('asp_i16')
cmd.delete('asp_i17')
cmd.delete('asp_i18')
cmd.delete('asp_i19')
cmd.delete('asp_i20')
cmd.delete('asp_i21')
cmd.delete('asp_i22')
cmd.delete('asp_i23')
cmd.delete('asp_i24')
cmd.delete('asp_i25')
cmd.delete('asp_i26')
cmd.delete('asp_i27')
cmd.delete('asp_i28')
cmd.delete('asp_i29')
cmd.delete('asp_i30')
cmd.delete('asp_i31')
cmd.delete('asp_i32')
cmd.delete('asp_i33')
cmd.delete('asp_i34')
cmd.delete('asp_i35')
cmd.delete('asp_i36')
IDSpec['S_2tmd_1_5_99_7'] = cmd.select('S_2tmd_1_5_99_7', 'tyr|asp|his|tyr_i|asp_i')
cmd.delete('tyr')
cmd.delete('asp')
cmd.delete('his')
cmd.delete('tyr_i')
cmd.delete('asp_i')
