'''
FUNC:S_3daa_2_6_1_21
PDB:3daa
EC:2.6.1.21
RESI:ile,lys,glu,leu
LOCI:a-144,145,177,201;
'''
IDSpec[(('leu','CD1'),('rlys','CD'))] = cmd.select('leu1', '%s w. %s of %s'%(resSelectionSubs('leu','CD1',subs),d+6.41,resSelectionSubs('lys','CD',subs)))
IDSpec[(('leu','CD1'),('rlys','CE'))] = cmd.select('leu2', '%s w. %s of %s'%(resSelectionSubs('leu','CD1',subs),d+7.46,resSelectionSubs('lys','CE',subs)))
IDSpec[(('leu','CD1'),('rlys','NZ'))] = cmd.select('leu3', '%s w. %s of %s'%(resSelectionSubs('leu','CD1',subs),d+7.32,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('leu','CD2'),('rlys','CD'))] = cmd.select('leu4', '%s w. %s of %s'%(resSelectionSubs('leu','CD2',subs),d+5.89,resSelectionSubs('lys','CD',subs)))
IDSpec[(('leu','CD2'),('rlys','CE'))] = cmd.select('leu5', '%s w. %s of %s'%(resSelectionSubs('leu','CD2',subs),d+6.25,resSelectionSubs('lys','CE',subs)))
IDSpec[(('leu','CD2'),('rlys','NZ'))] = cmd.select('leu6', '%s w. %s of %s'%(resSelectionSubs('leu','CD2',subs),d+5.59,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('leu','CG'),('rlys','CD'))] = cmd.select('leu7', '%s w. %s of %s'%(resSelectionSubs('leu','CG',subs),d+6.80,resSelectionSubs('lys','CD',subs)))
IDSpec[(('leu','CG'),('rlys','CE'))] = cmd.select('leu8', '%s w. %s of %s'%(resSelectionSubs('leu','CG',subs),d+7.48,resSelectionSubs('lys','CE',subs)))
IDSpec[(('leu','CG'),('rlys','NZ'))] = cmd.select('leu9', '%s w. %s of %s'%(resSelectionSubs('leu','CG',subs),d+7.01,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('leu','CD1'),('rglu','CD'))] = cmd.select('leu10', '%s w. %s of %s'%(resSelectionSubs('leu','CD1',subs),d+8.93,resSelectionSubs('glu','CD',subs)))
IDSpec[(('leu','CD1'),('rglu','OE1'))] = cmd.select('leu11', '%s w. %s of %s'%(resSelectionSubs('leu','CD1',subs),d+8.21,resSelectionSubs('glu','OE1',subs)))
IDSpec[(('leu','CD1'),('rglu','OE2'))] = cmd.select('leu12', '%s w. %s of %s'%(resSelectionSubs('leu','CD1',subs),d+8.65,resSelectionSubs('glu','OE2',subs)))
IDSpec[(('leu','CD2'),('rglu','CD'))] = cmd.select('leu13', '%s w. %s of %s'%(resSelectionSubs('leu','CD2',subs),d+8.32,resSelectionSubs('glu','CD',subs)))
IDSpec[(('leu','CD2'),('rglu','OE1'))] = cmd.select('leu14', '%s w. %s of %s'%(resSelectionSubs('leu','CD2',subs),d+7.44,resSelectionSubs('glu','OE1',subs)))
IDSpec[(('leu','CD2'),('rglu','OE2'))] = cmd.select('leu15', '%s w. %s of %s'%(resSelectionSubs('leu','CD2',subs),d+8.36,resSelectionSubs('glu','OE2',subs)))
IDSpec[(('leu','CG'),('rglu','CD'))] = cmd.select('leu16', '%s w. %s of %s'%(resSelectionSubs('leu','CG',subs),d+7.97,resSelectionSubs('glu','CD',subs)))
IDSpec[(('leu','CG'),('rglu','OE1'))] = cmd.select('leu17', '%s w. %s of %s'%(resSelectionSubs('leu','CG',subs),d+7.09,resSelectionSubs('glu','OE1',subs)))
IDSpec[(('leu','CG'),('rglu','OE2'))] = cmd.select('leu18', '%s w. %s of %s'%(resSelectionSubs('leu','CG',subs),d+7.94,resSelectionSubs('glu','OE2',subs)))
IDSpec[(('leu','CD1'),('rile','CD1'))] = cmd.select('leu19', '%s w. %s of %s'%(resSelectionSubs('leu','CD1',subs),d+11.04,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('leu','CD1'),('rile','CG1'))] = cmd.select('leu20', '%s w. %s of %s'%(resSelectionSubs('leu','CD1',subs),d+9.61,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('leu','CD1'),('rile','CG2'))] = cmd.select('leu21', '%s w. %s of %s'%(resSelectionSubs('leu','CD1',subs),d+9.34,resSelectionSubs('ile','CG2',subs)))
IDSpec[(('leu','CD2'),('rile','CD1'))] = cmd.select('leu22', '%s w. %s of %s'%(resSelectionSubs('leu','CD2',subs),d+13.21,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('leu','CD2'),('rile','CG1'))] = cmd.select('leu23', '%s w. %s of %s'%(resSelectionSubs('leu','CD2',subs),d+11.85,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('leu','CD2'),('rile','CG2'))] = cmd.select('leu24', '%s w. %s of %s'%(resSelectionSubs('leu','CD2',subs),d+11.28,resSelectionSubs('ile','CG2',subs)))
IDSpec[(('leu','CG'),('rile','CD1'))] = cmd.select('leu25', '%s w. %s of %s'%(resSelectionSubs('leu','CG',subs),d+12.39,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('leu','CG'),('rile','CG1'))] = cmd.select('leu26', '%s w. %s of %s'%(resSelectionSubs('leu','CG',subs),d+10.98,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('leu','CG'),('rile','CG2'))] = cmd.select('leu27', '%s w. %s of %s'%(resSelectionSubs('leu','CG',subs),d+10.76,resSelectionSubs('ile','CG2',subs)))
IDSpec['leu'] = cmd.select('leu',' br. leu1&br. leu2&br. leu3&br. leu4&br. leu5&br. leu6&br. leu7&br. leu8&br. leu9&br. leu10&br. leu11&br. leu12&br. leu13&br. leu14&br. leu15&br. leu16&br. leu17&br. leu18&br. leu19&br. leu20&br. leu21&br. leu22&br. leu23&br. leu24&br. leu25&br. leu26&br. leu27')
IDSpec['r_leu'] = cmd.count_atoms(resSelectionSubs('leu', subs=subs, selection=True))
cmd.delete('leu1')
cmd.delete('leu2')
cmd.delete('leu3')
cmd.delete('leu4')
cmd.delete('leu5')
cmd.delete('leu6')
cmd.delete('leu7')
cmd.delete('leu8')
cmd.delete('leu9')
cmd.delete('leu10')
cmd.delete('leu11')
cmd.delete('leu12')
cmd.delete('leu13')
cmd.delete('leu14')
cmd.delete('leu15')
cmd.delete('leu16')
cmd.delete('leu17')
cmd.delete('leu18')
cmd.delete('leu19')
cmd.delete('leu20')
cmd.delete('leu21')
cmd.delete('leu22')
cmd.delete('leu23')
cmd.delete('leu24')
cmd.delete('leu25')
cmd.delete('leu26')
cmd.delete('leu27')
IDSpec[(('lys','CD'),('sleu','CD1'))] = cmd.select('lys1', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+6.41,resSelectionSubs('leu','CD1',subs,selection=True)))
IDSpec[(('lys','CD'),('sleu','CD2'))] = cmd.select('lys2', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+5.89,resSelectionSubs('leu','CD2',subs,selection=True)))
IDSpec[(('lys','CD'),('sleu','CG'))] = cmd.select('lys3', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+6.80,resSelectionSubs('leu','CG',subs,selection=True)))
IDSpec[(('lys','CE'),('sleu','CD1'))] = cmd.select('lys4', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+7.46,resSelectionSubs('leu','CD1',subs,selection=True)))
IDSpec[(('lys','CE'),('sleu','CD2'))] = cmd.select('lys5', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+6.25,resSelectionSubs('leu','CD2',subs,selection=True)))
IDSpec[(('lys','CE'),('sleu','CG'))] = cmd.select('lys6', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+7.48,resSelectionSubs('leu','CG',subs,selection=True)))
IDSpec[(('lys','NZ'),('sleu','CD1'))] = cmd.select('lys7', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+7.32,resSelectionSubs('leu','CD1',subs,selection=True)))
IDSpec[(('lys','NZ'),('sleu','CD2'))] = cmd.select('lys8', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+5.59,resSelectionSubs('leu','CD2',subs,selection=True)))
IDSpec[(('lys','NZ'),('sleu','CG'))] = cmd.select('lys9', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+7.01,resSelectionSubs('leu','CG',subs,selection=True)))
IDSpec[(('lys','CD'),('rglu','CD'))] = cmd.select('lys10', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+11.82,resSelectionSubs('glu','CD',subs)))
IDSpec[(('lys','CD'),('rglu','OE1'))] = cmd.select('lys11', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+11.12,resSelectionSubs('glu','OE1',subs)))
IDSpec[(('lys','CD'),('rglu','OE2'))] = cmd.select('lys12', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+11.59,resSelectionSubs('glu','OE2',subs)))
IDSpec[(('lys','CE'),('rglu','CD'))] = cmd.select('lys13', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+12.01,resSelectionSubs('glu','CD',subs)))
IDSpec[(('lys','CE'),('rglu','OE1'))] = cmd.select('lys14', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+11.30,resSelectionSubs('glu','OE1',subs)))
IDSpec[(('lys','CE'),('rglu','OE2'))] = cmd.select('lys15', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+11.90,resSelectionSubs('glu','OE2',subs)))
IDSpec[(('lys','NZ'),('rglu','CD'))] = cmd.select('lys16', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+10.84,resSelectionSubs('glu','CD',subs)))
IDSpec[(('lys','NZ'),('rglu','OE1'))] = cmd.select('lys17', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+10.16,resSelectionSubs('glu','OE1',subs)))
IDSpec[(('lys','NZ'),('rglu','OE2'))] = cmd.select('lys18', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+10.80,resSelectionSubs('glu','OE2',subs)))
IDSpec[(('lys','CD'),('rile','CD1'))] = cmd.select('lys19', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+12.88,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('lys','CD'),('rile','CG1'))] = cmd.select('lys20', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+11.66,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('lys','CD'),('rile','CG2'))] = cmd.select('lys21', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+10.20,resSelectionSubs('ile','CG2',subs)))
IDSpec[(('lys','CE'),('rile','CD1'))] = cmd.select('lys22', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+14.26,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('lys','CE'),('rile','CG1'))] = cmd.select('lys23', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+13.07,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('lys','CE'),('rile','CG2'))] = cmd.select('lys24', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+11.56,resSelectionSubs('ile','CG2',subs)))
IDSpec[(('lys','NZ'),('rile','CD1'))] = cmd.select('lys25', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+14.57,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('lys','NZ'),('rile','CG1'))] = cmd.select('lys26', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+13.38,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('lys','NZ'),('rile','CG2'))] = cmd.select('lys27', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+12.04,resSelectionSubs('ile','CG2',subs)))
IDSpec['lys'] = cmd.select('lys',' br. lys1&br. lys2&br. lys3&br. lys4&br. lys5&br. lys6&br. lys7&br. lys8&br. lys9&br. lys10&br. lys11&br. lys12&br. lys13&br. lys14&br. lys15&br. lys16&br. lys17&br. lys18&br. lys19&br. lys20&br. lys21&br. lys22&br. lys23&br. lys24&br. lys25&br. lys26&br. lys27')
IDSpec['r_lys'] = cmd.count_atoms(resSelectionSubs('lys', subs=subs, selection=True))
cmd.delete('lys1')
cmd.delete('lys2')
cmd.delete('lys3')
cmd.delete('lys4')
cmd.delete('lys5')
cmd.delete('lys6')
cmd.delete('lys7')
cmd.delete('lys8')
cmd.delete('lys9')
cmd.delete('lys10')
cmd.delete('lys11')
cmd.delete('lys12')
cmd.delete('lys13')
cmd.delete('lys14')
cmd.delete('lys15')
cmd.delete('lys16')
cmd.delete('lys17')
cmd.delete('lys18')
cmd.delete('lys19')
cmd.delete('lys20')
cmd.delete('lys21')
cmd.delete('lys22')
cmd.delete('lys23')
cmd.delete('lys24')
cmd.delete('lys25')
cmd.delete('lys26')
cmd.delete('lys27')
IDSpec[(('glu','CD'),('sleu','CD1'))] = cmd.select('glu1', '%s w. %s of %s'%(resSelectionSubs('glu','CD',subs),d+8.93,resSelectionSubs('leu','CD1',subs,selection=True)))
IDSpec[(('glu','CD'),('sleu','CD2'))] = cmd.select('glu2', '%s w. %s of %s'%(resSelectionSubs('glu','CD',subs),d+8.32,resSelectionSubs('leu','CD2',subs,selection=True)))
IDSpec[(('glu','CD'),('sleu','CG'))] = cmd.select('glu3', '%s w. %s of %s'%(resSelectionSubs('glu','CD',subs),d+7.97,resSelectionSubs('leu','CG',subs,selection=True)))
IDSpec[(('glu','OE1'),('sleu','CD1'))] = cmd.select('glu4', '%s w. %s of %s'%(resSelectionSubs('glu','OE1',subs),d+8.21,resSelectionSubs('leu','CD1',subs,selection=True)))
IDSpec[(('glu','OE1'),('sleu','CD2'))] = cmd.select('glu5', '%s w. %s of %s'%(resSelectionSubs('glu','OE1',subs),d+7.44,resSelectionSubs('leu','CD2',subs,selection=True)))
IDSpec[(('glu','OE1'),('sleu','CG'))] = cmd.select('glu6', '%s w. %s of %s'%(resSelectionSubs('glu','OE1',subs),d+7.09,resSelectionSubs('leu','CG',subs,selection=True)))
IDSpec[(('glu','OE2'),('sleu','CD1'))] = cmd.select('glu7', '%s w. %s of %s'%(resSelectionSubs('glu','OE2',subs),d+8.65,resSelectionSubs('leu','CD1',subs,selection=True)))
IDSpec[(('glu','OE2'),('sleu','CD2'))] = cmd.select('glu8', '%s w. %s of %s'%(resSelectionSubs('glu','OE2',subs),d+8.36,resSelectionSubs('leu','CD2',subs,selection=True)))
IDSpec[(('glu','OE2'),('sleu','CG'))] = cmd.select('glu9', '%s w. %s of %s'%(resSelectionSubs('glu','OE2',subs),d+7.94,resSelectionSubs('leu','CG',subs,selection=True)))
IDSpec[(('glu','CD'),('slys','CD'))] = cmd.select('glu10', '%s w. %s of %s'%(resSelectionSubs('glu','CD',subs),d+11.82,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('glu','CD'),('slys','CE'))] = cmd.select('glu11', '%s w. %s of %s'%(resSelectionSubs('glu','CD',subs),d+12.01,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('glu','CD'),('slys','NZ'))] = cmd.select('glu12', '%s w. %s of %s'%(resSelectionSubs('glu','CD',subs),d+10.84,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('glu','OE1'),('slys','CD'))] = cmd.select('glu13', '%s w. %s of %s'%(resSelectionSubs('glu','OE1',subs),d+11.12,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('glu','OE1'),('slys','CE'))] = cmd.select('glu14', '%s w. %s of %s'%(resSelectionSubs('glu','OE1',subs),d+11.30,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('glu','OE1'),('slys','NZ'))] = cmd.select('glu15', '%s w. %s of %s'%(resSelectionSubs('glu','OE1',subs),d+10.16,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('glu','OE2'),('slys','CD'))] = cmd.select('glu16', '%s w. %s of %s'%(resSelectionSubs('glu','OE2',subs),d+11.59,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('glu','OE2'),('slys','CE'))] = cmd.select('glu17', '%s w. %s of %s'%(resSelectionSubs('glu','OE2',subs),d+11.90,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('glu','OE2'),('slys','NZ'))] = cmd.select('glu18', '%s w. %s of %s'%(resSelectionSubs('glu','OE2',subs),d+10.80,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('glu','CD'),('rile','CD1'))] = cmd.select('glu19', '%s w. %s of %s'%(resSelectionSubs('glu','CD',subs),d+14.73,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('glu','CD'),('rile','CG1'))] = cmd.select('glu20', '%s w. %s of %s'%(resSelectionSubs('glu','CD',subs),d+13.67,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('glu','CD'),('rile','CG2'))] = cmd.select('glu21', '%s w. %s of %s'%(resSelectionSubs('glu','CD',subs),d+14.04,resSelectionSubs('ile','CG2',subs)))
IDSpec[(('glu','OE1'),('rile','CD1'))] = cmd.select('glu22', '%s w. %s of %s'%(resSelectionSubs('glu','OE1',subs),d+14.83,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('glu','OE1'),('rile','CG1'))] = cmd.select('glu23', '%s w. %s of %s'%(resSelectionSubs('glu','OE1',subs),d+13.67,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('glu','OE1'),('rile','CG2'))] = cmd.select('glu24', '%s w. %s of %s'%(resSelectionSubs('glu','OE1',subs),d+13.97,resSelectionSubs('ile','CG2',subs)))
IDSpec[(('glu','OE2'),('rile','CD1'))] = cmd.select('glu25', '%s w. %s of %s'%(resSelectionSubs('glu','OE2',subs),d+13.70,resSelectionSubs('ile','CD1',subs)))
IDSpec[(('glu','OE2'),('rile','CG1'))] = cmd.select('glu26', '%s w. %s of %s'%(resSelectionSubs('glu','OE2',subs),d+12.71,resSelectionSubs('ile','CG1',subs)))
IDSpec[(('glu','OE2'),('rile','CG2'))] = cmd.select('glu27', '%s w. %s of %s'%(resSelectionSubs('glu','OE2',subs),d+13.09,resSelectionSubs('ile','CG2',subs)))
IDSpec['glu'] = cmd.select('glu',' br. glu1&br. glu2&br. glu3&br. glu4&br. glu5&br. glu6&br. glu7&br. glu8&br. glu9&br. glu10&br. glu11&br. glu12&br. glu13&br. glu14&br. glu15&br. glu16&br. glu17&br. glu18&br. glu19&br. glu20&br. glu21&br. glu22&br. glu23&br. glu24&br. glu25&br. glu26&br. glu27')
IDSpec['r_glu'] = cmd.count_atoms(resSelectionSubs('glu', subs=subs, selection=True))
cmd.delete('glu1')
cmd.delete('glu2')
cmd.delete('glu3')
cmd.delete('glu4')
cmd.delete('glu5')
cmd.delete('glu6')
cmd.delete('glu7')
cmd.delete('glu8')
cmd.delete('glu9')
cmd.delete('glu10')
cmd.delete('glu11')
cmd.delete('glu12')
cmd.delete('glu13')
cmd.delete('glu14')
cmd.delete('glu15')
cmd.delete('glu16')
cmd.delete('glu17')
cmd.delete('glu18')
cmd.delete('glu19')
cmd.delete('glu20')
cmd.delete('glu21')
cmd.delete('glu22')
cmd.delete('glu23')
cmd.delete('glu24')
cmd.delete('glu25')
cmd.delete('glu26')
cmd.delete('glu27')
IDSpec[(('ile','CD1'),('sleu','CD1'))] = cmd.select('ile1', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+11.04,resSelectionSubs('leu','CD1',subs,selection=True)))
IDSpec[(('ile','CD1'),('sleu','CD2'))] = cmd.select('ile2', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+13.21,resSelectionSubs('leu','CD2',subs,selection=True)))
IDSpec[(('ile','CD1'),('sleu','CG'))] = cmd.select('ile3', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+12.39,resSelectionSubs('leu','CG',subs,selection=True)))
IDSpec[(('ile','CG1'),('sleu','CD1'))] = cmd.select('ile4', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+9.61,resSelectionSubs('leu','CD1',subs,selection=True)))
IDSpec[(('ile','CG1'),('sleu','CD2'))] = cmd.select('ile5', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+11.85,resSelectionSubs('leu','CD2',subs,selection=True)))
IDSpec[(('ile','CG1'),('sleu','CG'))] = cmd.select('ile6', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+10.98,resSelectionSubs('leu','CG',subs,selection=True)))
IDSpec[(('ile','CG2'),('sleu','CD1'))] = cmd.select('ile7', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+9.34,resSelectionSubs('leu','CD1',subs,selection=True)))
IDSpec[(('ile','CG2'),('sleu','CD2'))] = cmd.select('ile8', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+11.28,resSelectionSubs('leu','CD2',subs,selection=True)))
IDSpec[(('ile','CG2'),('sleu','CG'))] = cmd.select('ile9', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+10.76,resSelectionSubs('leu','CG',subs,selection=True)))
IDSpec[(('ile','CD1'),('slys','CD'))] = cmd.select('ile10', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+12.88,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('ile','CD1'),('slys','CE'))] = cmd.select('ile11', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+14.26,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('ile','CD1'),('slys','NZ'))] = cmd.select('ile12', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+14.57,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('ile','CG1'),('slys','CD'))] = cmd.select('ile13', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+11.66,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('ile','CG1'),('slys','CE'))] = cmd.select('ile14', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+13.07,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('ile','CG1'),('slys','NZ'))] = cmd.select('ile15', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+13.38,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('ile','CG2'),('slys','CD'))] = cmd.select('ile16', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+10.20,resSelectionSubs('lys','CD',subs,selection=True)))
IDSpec[(('ile','CG2'),('slys','CE'))] = cmd.select('ile17', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+11.56,resSelectionSubs('lys','CE',subs,selection=True)))
IDSpec[(('ile','CG2'),('slys','NZ'))] = cmd.select('ile18', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+12.04,resSelectionSubs('lys','NZ',subs,selection=True)))
IDSpec[(('ile','CD1'),('sglu','CD'))] = cmd.select('ile19', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+14.73,resSelectionSubs('glu','CD',subs,selection=True)))
IDSpec[(('ile','CD1'),('sglu','OE1'))] = cmd.select('ile20', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+14.83,resSelectionSubs('glu','OE1',subs,selection=True)))
IDSpec[(('ile','CD1'),('sglu','OE2'))] = cmd.select('ile21', '%s w. %s of %s'%(resSelectionSubs('ile','CD1',subs),d+13.70,resSelectionSubs('glu','OE2',subs,selection=True)))
IDSpec[(('ile','CG1'),('sglu','CD'))] = cmd.select('ile22', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+13.67,resSelectionSubs('glu','CD',subs,selection=True)))
IDSpec[(('ile','CG1'),('sglu','OE1'))] = cmd.select('ile23', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+13.67,resSelectionSubs('glu','OE1',subs,selection=True)))
IDSpec[(('ile','CG1'),('sglu','OE2'))] = cmd.select('ile24', '%s w. %s of %s'%(resSelectionSubs('ile','CG1',subs),d+12.71,resSelectionSubs('glu','OE2',subs,selection=True)))
IDSpec[(('ile','CG2'),('sglu','CD'))] = cmd.select('ile25', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+14.04,resSelectionSubs('glu','CD',subs,selection=True)))
IDSpec[(('ile','CG2'),('sglu','OE1'))] = cmd.select('ile26', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+13.97,resSelectionSubs('glu','OE1',subs,selection=True)))
IDSpec[(('ile','CG2'),('sglu','OE2'))] = cmd.select('ile27', '%s w. %s of %s'%(resSelectionSubs('ile','CG2',subs),d+13.09,resSelectionSubs('glu','OE2',subs,selection=True)))
IDSpec['ile'] = cmd.select('ile',' br. ile1&br. ile2&br. ile3&br. ile4&br. ile5&br. ile6&br. ile7&br. ile8&br. ile9&br. ile10&br. ile11&br. ile12&br. ile13&br. ile14&br. ile15&br. ile16&br. ile17&br. ile18&br. ile19&br. ile20&br. ile21&br. ile22&br. ile23&br. ile24&br. ile25&br. ile26&br. ile27')
IDSpec['r_ile'] = cmd.count_atoms(resSelectionSubs('ile', subs=subs, selection=True))
cmd.delete('ile1')
cmd.delete('ile2')
cmd.delete('ile3')
cmd.delete('ile4')
cmd.delete('ile5')
cmd.delete('ile6')
cmd.delete('ile7')
cmd.delete('ile8')
cmd.delete('ile9')
cmd.delete('ile10')
cmd.delete('ile11')
cmd.delete('ile12')
cmd.delete('ile13')
cmd.delete('ile14')
cmd.delete('ile15')
cmd.delete('ile16')
cmd.delete('ile17')
cmd.delete('ile18')
cmd.delete('ile19')
cmd.delete('ile20')
cmd.delete('ile21')
cmd.delete('ile22')
cmd.delete('ile23')
cmd.delete('ile24')
cmd.delete('ile25')
cmd.delete('ile26')
cmd.delete('ile27')
IDSpec['S_3daa_2_6_1_21'] = cmd.select('S_3daa_2_6_1_21', 'leu|lys|glu|ile')
cmd.delete('leu')
cmd.delete('lys')
cmd.delete('glu')
cmd.delete('ile')
