'''
FUNC:S_3gvp_3_3_1_1
PDB:3gvp
EC:3.3.1.1
RESI:his,asp,lys,asp,asn,cys,his
LOCI:a-234,310,365,369,370,374,480;
'''
IDSpec[(('his','CE1'),('rasp','CG'))] = cmd.select('his1', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+19.06,resSelectionSubs('asp','CG',subs)))
IDSpec[(('his','CE1'),('rasp','OD1'))] = cmd.select('his2', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+18.02,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('his','CE1'),('rasp','OD2'))] = cmd.select('his3', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+19.30,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('his','ND1'),('rasp','CG'))] = cmd.select('his4', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+18.26,resSelectionSubs('asp','CG',subs)))
IDSpec[(('his','ND1'),('rasp','OD1'))] = cmd.select('his5', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+17.24,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('his','ND1'),('rasp','OD2'))] = cmd.select('his6', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+18.44,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('his','NE2'),('rasp','CG'))] = cmd.select('his7', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+18.40,resSelectionSubs('asp','CG',subs)))
IDSpec[(('his','NE2'),('rasp','OD1'))] = cmd.select('his8', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+17.34,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('his','NE2'),('rasp','OD2'))] = cmd.select('his9', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+18.71,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('his','CE1'),('rcys','CA'))] = cmd.select('his10', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+18.31,resSelectionSubs('cys','CA',subs)))
IDSpec[(('his','CE1'),('rcys','CB'))] = cmd.select('his11', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+17.15,resSelectionSubs('cys','CB',subs)))
IDSpec[(('his','CE1'),('rcys','SG'))] = cmd.select('his12', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+15.86,resSelectionSubs('cys','SG',subs)))
IDSpec[(('his','ND1'),('rcys','CA'))] = cmd.select('his13', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+17.01,resSelectionSubs('cys','CA',subs)))
IDSpec[(('his','ND1'),('rcys','CB'))] = cmd.select('his14', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+15.87,resSelectionSubs('cys','CB',subs)))
IDSpec[(('his','ND1'),('rcys','SG'))] = cmd.select('his15', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+14.56,resSelectionSubs('cys','SG',subs)))
IDSpec[(('his','NE2'),('rcys','CA'))] = cmd.select('his16', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+18.98,resSelectionSubs('cys','CA',subs)))
IDSpec[(('his','NE2'),('rcys','CB'))] = cmd.select('his17', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+17.85,resSelectionSubs('cys','CB',subs)))
IDSpec[(('his','NE2'),('rcys','SG'))] = cmd.select('his18', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+16.47,resSelectionSubs('cys','SG',subs)))
IDSpec[(('his','CE1'),('rhis','CE1'))] = cmd.select('his19', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+19.64,resSelectionSubs('his','CE1',subs)))
IDSpec[(('his','CE1'),('rhis','ND1'))] = cmd.select('his20', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+20.96,resSelectionSubs('his','ND1',subs)))
IDSpec[(('his','CE1'),('rhis','NE2'))] = cmd.select('his21', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+19.26,resSelectionSubs('his','NE2',subs)))
IDSpec[(('his','ND1'),('rhis','CE1'))] = cmd.select('his22', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+18.77,resSelectionSubs('his','CE1',subs)))
IDSpec[(('his','ND1'),('rhis','ND1'))] = cmd.select('his23', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+20.09,resSelectionSubs('his','ND1',subs)))
IDSpec[(('his','ND1'),('rhis','NE2'))] = cmd.select('his24', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+18.35,resSelectionSubs('his','NE2',subs)))
IDSpec[(('his','NE2'),('rhis','CE1'))] = cmd.select('his25', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+19.20,resSelectionSubs('his','CE1',subs)))
IDSpec[(('his','NE2'),('rhis','ND1'))] = cmd.select('his26', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+20.52,resSelectionSubs('his','ND1',subs)))
IDSpec[(('his','NE2'),('rhis','NE2'))] = cmd.select('his27', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+18.83,resSelectionSubs('his','NE2',subs)))
IDSpec[(('his','CE1'),('rasn','CG'))] = cmd.select('his28', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+16.47,resSelectionSubs('asn','CG',subs)))
IDSpec[(('his','CE1'),('rasn','ND2'))] = cmd.select('his29', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+16.81,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('his','CE1'),('rasn','OD1'))] = cmd.select('his30', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+15.74,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('his','ND1'),('rasn','CG'))] = cmd.select('his31', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+15.35,resSelectionSubs('asn','CG',subs)))
IDSpec[(('his','ND1'),('rasn','ND2'))] = cmd.select('his32', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+15.76,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('his','ND1'),('rasn','OD1'))] = cmd.select('his33', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+14.60,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('his','NE2'),('rasn','CG'))] = cmd.select('his34', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+16.71,resSelectionSubs('asn','CG',subs)))
IDSpec[(('his','NE2'),('rasn','ND2'))] = cmd.select('his35', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+17.00,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('his','NE2'),('rasn','OD1'))] = cmd.select('his36', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+15.92,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('his','CE1'),('rasp','CG'))] = cmd.select('his37', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+19.27,resSelectionSubs('asp','CG',subs)))
IDSpec[(('his','CE1'),('rasp','OD1'))] = cmd.select('his38', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+20.21,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('his','CE1'),('rasp','OD2'))] = cmd.select('his39', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+19.23,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('his','ND1'),('rasp','CG'))] = cmd.select('his40', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+18.10,resSelectionSubs('asp','CG',subs)))
IDSpec[(('his','ND1'),('rasp','OD1'))] = cmd.select('his41', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+19.01,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('his','ND1'),('rasp','OD2'))] = cmd.select('his42', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+18.10,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('his','NE2'),('rasp','CG'))] = cmd.select('his43', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+19.22,resSelectionSubs('asp','CG',subs)))
IDSpec[(('his','NE2'),('rasp','OD1'))] = cmd.select('his44', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+20.18,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('his','NE2'),('rasp','OD2'))] = cmd.select('his45', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+19.08,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('his','CE1'),('rlys','CD'))] = cmd.select('his46', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+22.37,resSelectionSubs('lys','CD',subs)))
IDSpec[(('his','CE1'),('rlys','CE'))] = cmd.select('his47', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+20.96,resSelectionSubs('lys','CE',subs)))
IDSpec[(('his','CE1'),('rlys','NZ'))] = cmd.select('his48', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+20.95,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('his','ND1'),('rlys','CD'))] = cmd.select('his49', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+21.36,resSelectionSubs('lys','CD',subs)))
IDSpec[(('his','ND1'),('rlys','CE'))] = cmd.select('his50', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+19.94,resSelectionSubs('lys','CE',subs)))
cmd.select('his50',' br. his1&br. his2&br. his3&br. his4&br. his5&br. his6&br. his7&br. his8&br. his9&br. his10&br. his11&br. his12&br. his13&br. his14&br. his15&br. his16&br. his17&br. his18&br. his19&br. his20&br. his21&br. his22&br. his23&br. his24&br. his25&br. his26&br. his27&br. his28&br. his29&br. his30&br. his31&br. his32&br. his33&br. his34&br. his35&br. his36&br. his37&br. his38&br. his39&br. his40&br. his41&br. his42&br. his43&br. his44&br. his45&br. his46&br. his47&br. his48&br. his49&br. his50')
cmd.delete('his1')
cmd.delete('his2')
cmd.delete('his3')
cmd.delete('his4')
cmd.delete('his5')
cmd.delete('his6')
cmd.delete('his7')
cmd.delete('his8')
cmd.delete('his9')
cmd.delete('his10')
cmd.delete('his11')
cmd.delete('his12')
cmd.delete('his13')
cmd.delete('his14')
cmd.delete('his15')
cmd.delete('his16')
cmd.delete('his17')
cmd.delete('his18')
cmd.delete('his19')
cmd.delete('his20')
cmd.delete('his21')
cmd.delete('his22')
cmd.delete('his23')
cmd.delete('his24')
cmd.delete('his25')
cmd.delete('his26')
cmd.delete('his27')
cmd.delete('his28')
cmd.delete('his29')
cmd.delete('his30')
cmd.delete('his31')
cmd.delete('his32')
cmd.delete('his33')
cmd.delete('his34')
cmd.delete('his35')
cmd.delete('his36')
cmd.delete('his37')
cmd.delete('his38')
cmd.delete('his39')
cmd.delete('his40')
cmd.delete('his41')
cmd.delete('his42')
cmd.delete('his43')
cmd.delete('his44')
cmd.delete('his45')
cmd.delete('his46')
cmd.delete('his47')
cmd.delete('his48')
cmd.delete('his49')
IDSpec[(('his','ND1'),('rlys','NZ'))] = cmd.select('his51', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+19.88,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('his','NE2'),('rlys','CD'))] = cmd.select('his52', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+22.04,resSelectionSubs('lys','CD',subs)))
IDSpec[(('his','NE2'),('rlys','CE'))] = cmd.select('his53', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+20.63,resSelectionSubs('lys','CE',subs)))
IDSpec[(('his','NE2'),('rlys','NZ'))] = cmd.select('his54', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+20.65,resSelectionSubs('lys','NZ',subs)))
IDSpec['his'] = cmd.select('his',' his50&br. his51&br. his52&br. his53&br. his54')
IDSpec['r_his'] = cmd.count_atoms(resSelectionSubs('his', subs=subs, selection=True))
cmd.delete('his50')
cmd.delete('his51')
cmd.delete('his52')
cmd.delete('his53')
cmd.delete('his54')
IDSpec[(('asp','CG'),('shis','CE1'))] = cmd.select('asp1', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+19.06,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asp','CG'),('shis','ND1'))] = cmd.select('asp2', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+18.26,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asp','CG'),('shis','NE2'))] = cmd.select('asp3', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+18.40,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asp','OD1'),('shis','CE1'))] = cmd.select('asp4', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+18.02,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asp','OD1'),('shis','ND1'))] = cmd.select('asp5', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+17.24,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asp','OD1'),('shis','NE2'))] = cmd.select('asp6', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+17.34,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asp','OD2'),('shis','CE1'))] = cmd.select('asp7', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+19.30,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asp','OD2'),('shis','ND1'))] = cmd.select('asp8', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+18.44,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asp','OD2'),('shis','NE2'))] = cmd.select('asp9', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+18.71,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asp','CG'),('rcys','CA'))] = cmd.select('asp10', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+19.20,resSelectionSubs('cys','CA',subs)))
IDSpec[(('asp','CG'),('rcys','CB'))] = cmd.select('asp11', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+19.15,resSelectionSubs('cys','CB',subs)))
IDSpec[(('asp','CG'),('rcys','SG'))] = cmd.select('asp12', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+17.51,resSelectionSubs('cys','SG',subs)))
IDSpec[(('asp','OD1'),('rcys','CA'))] = cmd.select('asp13', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+18.78,resSelectionSubs('cys','CA',subs)))
IDSpec[(('asp','OD1'),('rcys','CB'))] = cmd.select('asp14', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+18.63,resSelectionSubs('cys','CB',subs)))
IDSpec[(('asp','OD1'),('rcys','SG'))] = cmd.select('asp15', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+16.95,resSelectionSubs('cys','SG',subs)))
IDSpec[(('asp','OD2'),('rcys','CA'))] = cmd.select('asp16', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+18.53,resSelectionSubs('cys','CA',subs)))
IDSpec[(('asp','OD2'),('rcys','CB'))] = cmd.select('asp17', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+18.58,resSelectionSubs('cys','CB',subs)))
IDSpec[(('asp','OD2'),('rcys','SG'))] = cmd.select('asp18', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+16.98,resSelectionSubs('cys','SG',subs)))
IDSpec[(('asp','CG'),('rhis','CE1'))] = cmd.select('asp19', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.92,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp','CG'),('rhis','ND1'))] = cmd.select('asp20', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+8.42,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp','CG'),('rhis','NE2'))] = cmd.select('asp21', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.96,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp','OD1'),('rhis','CE1'))] = cmd.select('asp22', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.61,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp','OD1'),('rhis','ND1'))] = cmd.select('asp23', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.28,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp','OD1'),('rhis','NE2'))] = cmd.select('asp24', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.62,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp','OD2'),('rhis','CE1'))] = cmd.select('asp25', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.00,resSelectionSubs('his','CE1',subs)))
IDSpec[(('asp','OD2'),('rhis','ND1'))] = cmd.select('asp26', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.45,resSelectionSubs('his','ND1',subs)))
IDSpec[(('asp','OD2'),('rhis','NE2'))] = cmd.select('asp27', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+5.93,resSelectionSubs('his','NE2',subs)))
IDSpec[(('asp','CG'),('rasn','CG'))] = cmd.select('asp28', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+16.44,resSelectionSubs('asn','CG',subs)))
IDSpec[(('asp','CG'),('rasn','ND2'))] = cmd.select('asp29', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+17.01,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('asp','CG'),('rasn','OD1'))] = cmd.select('asp30', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+15.31,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('asp','OD1'),('rasn','CG'))] = cmd.select('asp31', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+15.63,resSelectionSubs('asn','CG',subs)))
IDSpec[(('asp','OD1'),('rasn','ND2'))] = cmd.select('asp32', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+16.15,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('asp','OD1'),('rasn','OD1'))] = cmd.select('asp33', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+14.48,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('asp','OD2'),('rasn','CG'))] = cmd.select('asp34', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+16.35,resSelectionSubs('asn','CG',subs)))
IDSpec[(('asp','OD2'),('rasn','ND2'))] = cmd.select('asp35', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+17.00,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('asp','OD2'),('rasn','OD1'))] = cmd.select('asp36', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+15.21,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('asp','CG'),('rasp','CG'))] = cmd.select('asp37', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+12.12,resSelectionSubs('asp','CG',subs)))
IDSpec[(('asp','CG'),('rasp','OD1'))] = cmd.select('asp38', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+12.41,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('asp','CG'),('rasp','OD2'))] = cmd.select('asp39', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+11.39,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('asp','OD1'),('rasp','CG'))] = cmd.select('asp40', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+11.72,resSelectionSubs('asp','CG',subs)))
IDSpec[(('asp','OD1'),('rasp','OD1'))] = cmd.select('asp41', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+12.15,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('asp','OD1'),('rasp','OD2'))] = cmd.select('asp42', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+10.94,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('asp','OD2'),('rasp','CG'))] = cmd.select('asp43', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.77,resSelectionSubs('asp','CG',subs)))
IDSpec[(('asp','OD2'),('rasp','OD1'))] = cmd.select('asp44', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.93,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('asp','OD2'),('rasp','OD2'))] = cmd.select('asp45', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.16,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('asp','CG'),('rlys','CD'))] = cmd.select('asp46', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+11.73,resSelectionSubs('lys','CD',subs)))
IDSpec[(('asp','CG'),('rlys','CE'))] = cmd.select('asp47', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+10.64,resSelectionSubs('lys','CE',subs)))
IDSpec[(('asp','CG'),('rlys','NZ'))] = cmd.select('asp48', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+10.06,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('asp','OD1'),('rlys','CD'))] = cmd.select('asp49', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+11.49,resSelectionSubs('lys','CD',subs)))
IDSpec[(('asp','OD1'),('rlys','CE'))] = cmd.select('asp50', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+10.31,resSelectionSubs('lys','CE',subs)))
cmd.select('asp50',' br. asp1&br. asp2&br. asp3&br. asp4&br. asp5&br. asp6&br. asp7&br. asp8&br. asp9&br. asp10&br. asp11&br. asp12&br. asp13&br. asp14&br. asp15&br. asp16&br. asp17&br. asp18&br. asp19&br. asp20&br. asp21&br. asp22&br. asp23&br. asp24&br. asp25&br. asp26&br. asp27&br. asp28&br. asp29&br. asp30&br. asp31&br. asp32&br. asp33&br. asp34&br. asp35&br. asp36&br. asp37&br. asp38&br. asp39&br. asp40&br. asp41&br. asp42&br. asp43&br. asp44&br. asp45&br. asp46&br. asp47&br. asp48&br. asp49&br. asp50')
cmd.delete('asp1')
cmd.delete('asp2')
cmd.delete('asp3')
cmd.delete('asp4')
cmd.delete('asp5')
cmd.delete('asp6')
cmd.delete('asp7')
cmd.delete('asp8')
cmd.delete('asp9')
cmd.delete('asp10')
cmd.delete('asp11')
cmd.delete('asp12')
cmd.delete('asp13')
cmd.delete('asp14')
cmd.delete('asp15')
cmd.delete('asp16')
cmd.delete('asp17')
cmd.delete('asp18')
cmd.delete('asp19')
cmd.delete('asp20')
cmd.delete('asp21')
cmd.delete('asp22')
cmd.delete('asp23')
cmd.delete('asp24')
cmd.delete('asp25')
cmd.delete('asp26')
cmd.delete('asp27')
cmd.delete('asp28')
cmd.delete('asp29')
cmd.delete('asp30')
cmd.delete('asp31')
cmd.delete('asp32')
cmd.delete('asp33')
cmd.delete('asp34')
cmd.delete('asp35')
cmd.delete('asp36')
cmd.delete('asp37')
cmd.delete('asp38')
cmd.delete('asp39')
cmd.delete('asp40')
cmd.delete('asp41')
cmd.delete('asp42')
cmd.delete('asp43')
cmd.delete('asp44')
cmd.delete('asp45')
cmd.delete('asp46')
cmd.delete('asp47')
cmd.delete('asp48')
cmd.delete('asp49')
IDSpec[(('asp','OD1'),('rlys','NZ'))] = cmd.select('asp51', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.86,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('asp','OD2'),('rlys','CD'))] = cmd.select('asp52', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.75,resSelectionSubs('lys','CD',subs)))
IDSpec[(('asp','OD2'),('rlys','CE'))] = cmd.select('asp53', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+10.66,resSelectionSubs('lys','CE',subs)))
IDSpec[(('asp','OD2'),('rlys','NZ'))] = cmd.select('asp54', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+9.88,resSelectionSubs('lys','NZ',subs)))
IDSpec['asp'] = cmd.select('asp',' asp50&br. asp51&br. asp52&br. asp53&br. asp54')
IDSpec['r_asp'] = cmd.count_atoms(resSelectionSubs('asp', subs=subs, selection=True))
cmd.delete('asp50')
cmd.delete('asp51')
cmd.delete('asp52')
cmd.delete('asp53')
cmd.delete('asp54')
IDSpec[(('cys','CA'),('shis','CE1'))] = cmd.select('cys1', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+18.31,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('cys','CA'),('shis','ND1'))] = cmd.select('cys2', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+17.01,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('cys','CA'),('shis','NE2'))] = cmd.select('cys3', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+18.98,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('cys','CB'),('shis','CE1'))] = cmd.select('cys4', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+17.15,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('cys','CB'),('shis','ND1'))] = cmd.select('cys5', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+15.87,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('cys','CB'),('shis','NE2'))] = cmd.select('cys6', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+17.85,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('cys','SG'),('shis','CE1'))] = cmd.select('cys7', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+15.86,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('cys','SG'),('shis','ND1'))] = cmd.select('cys8', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+14.56,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('cys','SG'),('shis','NE2'))] = cmd.select('cys9', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+16.47,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('cys','CA'),('sasp','CG'))] = cmd.select('cys10', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+19.20,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('cys','CA'),('sasp','OD1'))] = cmd.select('cys11', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+18.78,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('cys','CA'),('sasp','OD2'))] = cmd.select('cys12', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+18.53,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('cys','CB'),('sasp','CG'))] = cmd.select('cys13', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+19.15,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('cys','CB'),('sasp','OD1'))] = cmd.select('cys14', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+18.63,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('cys','CB'),('sasp','OD2'))] = cmd.select('cys15', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+18.58,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('cys','SG'),('sasp','CG'))] = cmd.select('cys16', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+17.51,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('cys','SG'),('sasp','OD1'))] = cmd.select('cys17', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+16.95,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('cys','SG'),('sasp','OD2'))] = cmd.select('cys18', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+16.98,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('cys','CA'),('rhis','CE1'))] = cmd.select('cys19', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+18.67,resSelectionSubs('his','CE1',subs)))
IDSpec[(('cys','CA'),('rhis','ND1'))] = cmd.select('cys20', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+19.40,resSelectionSubs('his','ND1',subs)))
IDSpec[(('cys','CA'),('rhis','NE2'))] = cmd.select('cys21', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+17.84,resSelectionSubs('his','NE2',subs)))
IDSpec[(('cys','CB'),('rhis','CE1'))] = cmd.select('cys22', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+18.93,resSelectionSubs('his','CE1',subs)))
IDSpec[(('cys','CB'),('rhis','ND1'))] = cmd.select('cys23', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+19.75,resSelectionSubs('his','ND1',subs)))
IDSpec[(('cys','CB'),('rhis','NE2'))] = cmd.select('cys24', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+18.08,resSelectionSubs('his','NE2',subs)))
IDSpec[(('cys','SG'),('rhis','CE1'))] = cmd.select('cys25', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+17.45,resSelectionSubs('his','CE1',subs)))
IDSpec[(('cys','SG'),('rhis','ND1'))] = cmd.select('cys26', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+18.32,resSelectionSubs('his','ND1',subs)))
IDSpec[(('cys','SG'),('rhis','NE2'))] = cmd.select('cys27', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+16.58,resSelectionSubs('his','NE2',subs)))
IDSpec[(('cys','CA'),('rasn','CG'))] = cmd.select('cys28', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+10.53,resSelectionSubs('asn','CG',subs)))
IDSpec[(('cys','CA'),('rasn','ND2'))] = cmd.select('cys29', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+11.76,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('cys','CA'),('rasn','OD1'))] = cmd.select('cys30', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+10.45,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('cys','CB'),('rasn','CG'))] = cmd.select('cys31', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+9.62,resSelectionSubs('asn','CG',subs)))
IDSpec[(('cys','CB'),('rasn','ND2'))] = cmd.select('cys32', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+10.80,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('cys','CB'),('rasn','OD1'))] = cmd.select('cys33', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+9.57,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('cys','SG'),('rasn','CG'))] = cmd.select('cys34', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+8.73,resSelectionSubs('asn','CG',subs)))
IDSpec[(('cys','SG'),('rasn','ND2'))] = cmd.select('cys35', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+9.98,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('cys','SG'),('rasn','OD1'))] = cmd.select('cys36', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+8.42,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('cys','CA'),('rasp','CG'))] = cmd.select('cys37', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+11.90,resSelectionSubs('asp','CG',subs)))
IDSpec[(('cys','CA'),('rasp','OD1'))] = cmd.select('cys38', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+11.79,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('cys','CA'),('rasp','OD2'))] = cmd.select('cys39', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+13.03,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('cys','CB'),('rasp','CG'))] = cmd.select('cys40', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+11.86,resSelectionSubs('asp','CG',subs)))
IDSpec[(('cys','CB'),('rasp','OD1'))] = cmd.select('cys41', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+11.94,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('cys','CB'),('rasp','OD2'))] = cmd.select('cys42', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+12.91,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('cys','SG'),('rasp','CG'))] = cmd.select('cys43', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+10.72,resSelectionSubs('asp','CG',subs)))
IDSpec[(('cys','SG'),('rasp','OD1'))] = cmd.select('cys44', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+10.93,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('cys','SG'),('rasp','OD2'))] = cmd.select('cys45', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+11.69,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('cys','CA'),('rlys','CD'))] = cmd.select('cys46', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+16.99,resSelectionSubs('lys','CD',subs)))
IDSpec[(('cys','CA'),('rlys','CE'))] = cmd.select('cys47', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+16.12,resSelectionSubs('lys','CE',subs)))
IDSpec[(('cys','CA'),('rlys','NZ'))] = cmd.select('cys48', '%s w. %s of %s'%(resSelectionSubs('cys','CA',subs),d+15.44,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('cys','CB'),('rlys','CD'))] = cmd.select('cys49', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+16.94,resSelectionSubs('lys','CD',subs)))
IDSpec[(('cys','CB'),('rlys','CE'))] = cmd.select('cys50', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+16.01,resSelectionSubs('lys','CE',subs)))
cmd.select('cys50',' br. cys1&br. cys2&br. cys3&br. cys4&br. cys5&br. cys6&br. cys7&br. cys8&br. cys9&br. cys10&br. cys11&br. cys12&br. cys13&br. cys14&br. cys15&br. cys16&br. cys17&br. cys18&br. cys19&br. cys20&br. cys21&br. cys22&br. cys23&br. cys24&br. cys25&br. cys26&br. cys27&br. cys28&br. cys29&br. cys30&br. cys31&br. cys32&br. cys33&br. cys34&br. cys35&br. cys36&br. cys37&br. cys38&br. cys39&br. cys40&br. cys41&br. cys42&br. cys43&br. cys44&br. cys45&br. cys46&br. cys47&br. cys48&br. cys49&br. cys50')
cmd.delete('cys1')
cmd.delete('cys2')
cmd.delete('cys3')
cmd.delete('cys4')
cmd.delete('cys5')
cmd.delete('cys6')
cmd.delete('cys7')
cmd.delete('cys8')
cmd.delete('cys9')
cmd.delete('cys10')
cmd.delete('cys11')
cmd.delete('cys12')
cmd.delete('cys13')
cmd.delete('cys14')
cmd.delete('cys15')
cmd.delete('cys16')
cmd.delete('cys17')
cmd.delete('cys18')
cmd.delete('cys19')
cmd.delete('cys20')
cmd.delete('cys21')
cmd.delete('cys22')
cmd.delete('cys23')
cmd.delete('cys24')
cmd.delete('cys25')
cmd.delete('cys26')
cmd.delete('cys27')
cmd.delete('cys28')
cmd.delete('cys29')
cmd.delete('cys30')
cmd.delete('cys31')
cmd.delete('cys32')
cmd.delete('cys33')
cmd.delete('cys34')
cmd.delete('cys35')
cmd.delete('cys36')
cmd.delete('cys37')
cmd.delete('cys38')
cmd.delete('cys39')
cmd.delete('cys40')
cmd.delete('cys41')
cmd.delete('cys42')
cmd.delete('cys43')
cmd.delete('cys44')
cmd.delete('cys45')
cmd.delete('cys46')
cmd.delete('cys47')
cmd.delete('cys48')
cmd.delete('cys49')
IDSpec[(('cys','CB'),('rlys','NZ'))] = cmd.select('cys51', '%s w. %s of %s'%(resSelectionSubs('cys','CB',subs),d+15.46,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('cys','SG'),('rlys','CD'))] = cmd.select('cys52', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+15.82,resSelectionSubs('lys','CD',subs)))
IDSpec[(('cys','SG'),('rlys','CE'))] = cmd.select('cys53', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+14.78,resSelectionSubs('lys','CE',subs)))
IDSpec[(('cys','SG'),('rlys','NZ'))] = cmd.select('cys54', '%s w. %s of %s'%(resSelectionSubs('cys','SG',subs),d+14.23,resSelectionSubs('lys','NZ',subs)))
IDSpec['cys'] = cmd.select('cys',' cys50&br. cys51&br. cys52&br. cys53&br. cys54')
IDSpec['r_cys'] = cmd.count_atoms(resSelectionSubs('cys', subs=subs, selection=True))
cmd.delete('cys50')
cmd.delete('cys51')
cmd.delete('cys52')
cmd.delete('cys53')
cmd.delete('cys54')
IDSpec[(('his_i','CE1'),('shis','CE1'))] = cmd.select('his_i1', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+19.64,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('his_i','CE1'),('shis','ND1'))] = cmd.select('his_i2', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+18.77,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('his_i','CE1'),('shis','NE2'))] = cmd.select('his_i3', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+19.20,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('his_i','ND1'),('shis','CE1'))] = cmd.select('his_i4', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+20.96,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('his_i','ND1'),('shis','ND1'))] = cmd.select('his_i5', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+20.09,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('his_i','ND1'),('shis','NE2'))] = cmd.select('his_i6', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+20.52,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('his_i','NE2'),('shis','CE1'))] = cmd.select('his_i7', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+19.26,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('his_i','NE2'),('shis','ND1'))] = cmd.select('his_i8', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+18.35,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('his_i','NE2'),('shis','NE2'))] = cmd.select('his_i9', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+18.83,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sasp','CG'))] = cmd.select('his_i10', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.92,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sasp','OD1'))] = cmd.select('his_i11', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+8.61,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his_i','CE1'),('sasp','OD2'))] = cmd.select('his_i12', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+7.00,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sasp','CG'))] = cmd.select('his_i13', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+8.42,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sasp','OD1'))] = cmd.select('his_i14', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+9.28,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his_i','ND1'),('sasp','OD2'))] = cmd.select('his_i15', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+7.45,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sasp','CG'))] = cmd.select('his_i16', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+6.96,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sasp','OD1'))] = cmd.select('his_i17', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+7.62,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('his_i','NE2'),('sasp','OD2'))] = cmd.select('his_i18', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+5.93,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('his_i','CE1'),('scys','CA'))] = cmd.select('his_i19', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+18.67,resSelectionSubs('cys','CA',subs,selection=True)))
IDSpec[(('his_i','CE1'),('scys','CB'))] = cmd.select('his_i20', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+18.93,resSelectionSubs('cys','CB',subs,selection=True)))
IDSpec[(('his_i','CE1'),('scys','SG'))] = cmd.select('his_i21', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+17.45,resSelectionSubs('cys','SG',subs,selection=True)))
IDSpec[(('his_i','ND1'),('scys','CA'))] = cmd.select('his_i22', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+19.40,resSelectionSubs('cys','CA',subs,selection=True)))
IDSpec[(('his_i','ND1'),('scys','CB'))] = cmd.select('his_i23', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+19.75,resSelectionSubs('cys','CB',subs,selection=True)))
IDSpec[(('his_i','ND1'),('scys','SG'))] = cmd.select('his_i24', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+18.32,resSelectionSubs('cys','SG',subs,selection=True)))
IDSpec[(('his_i','NE2'),('scys','CA'))] = cmd.select('his_i25', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+17.84,resSelectionSubs('cys','CA',subs,selection=True)))
IDSpec[(('his_i','NE2'),('scys','CB'))] = cmd.select('his_i26', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+18.08,resSelectionSubs('cys','CB',subs,selection=True)))
IDSpec[(('his_i','NE2'),('scys','SG'))] = cmd.select('his_i27', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+16.58,resSelectionSubs('cys','SG',subs,selection=True)))
IDSpec[(('his_i','CE1'),('rasn','CG'))] = cmd.select('his_i28', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+18.88,resSelectionSubs('asn','CG',subs)))
IDSpec[(('his_i','CE1'),('rasn','ND2'))] = cmd.select('his_i29', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+19.81,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('his_i','CE1'),('rasn','OD1'))] = cmd.select('his_i30', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+17.70,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('his_i','ND1'),('rasn','CG'))] = cmd.select('his_i31', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+19.76,resSelectionSubs('asn','CG',subs)))
IDSpec[(('his_i','ND1'),('rasn','ND2'))] = cmd.select('his_i32', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+20.69,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('his_i','ND1'),('rasn','OD1'))] = cmd.select('his_i33', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+18.60,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('his_i','NE2'),('rasn','CG'))] = cmd.select('his_i34', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+17.71,resSelectionSubs('asn','CG',subs)))
IDSpec[(('his_i','NE2'),('rasn','ND2'))] = cmd.select('his_i35', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+18.61,resSelectionSubs('asn','ND2',subs)))
IDSpec[(('his_i','NE2'),('rasn','OD1'))] = cmd.select('his_i36', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+16.54,resSelectionSubs('asn','OD1',subs)))
IDSpec[(('his_i','CE1'),('rasp','CG'))] = cmd.select('his_i37', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+14.64,resSelectionSubs('asp','CG',subs)))
IDSpec[(('his_i','CE1'),('rasp','OD1'))] = cmd.select('his_i38', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+14.55,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('his_i','CE1'),('rasp','OD2'))] = cmd.select('his_i39', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+14.45,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('his_i','ND1'),('rasp','CG'))] = cmd.select('his_i40', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+15.20,resSelectionSubs('asp','CG',subs)))
IDSpec[(('his_i','ND1'),('rasp','OD1'))] = cmd.select('his_i41', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+15.01,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('his_i','ND1'),('rasp','OD2'))] = cmd.select('his_i42', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+15.01,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('his_i','NE2'),('rasp','CG'))] = cmd.select('his_i43', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+13.36,resSelectionSubs('asp','CG',subs)))
IDSpec[(('his_i','NE2'),('rasp','OD1'))] = cmd.select('his_i44', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+13.29,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('his_i','NE2'),('rasp','OD2'))] = cmd.select('his_i45', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+13.14,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('his_i','CE1'),('rlys','CD'))] = cmd.select('his_i46', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+15.95,resSelectionSubs('lys','CD',subs)))
IDSpec[(('his_i','CE1'),('rlys','CE'))] = cmd.select('his_i47', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+14.81,resSelectionSubs('lys','CE',subs)))
IDSpec[(('his_i','CE1'),('rlys','NZ'))] = cmd.select('his_i48', '%s w. %s of %s'%(resSelectionSubs('his','CE1',subs),d+13.72,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('his_i','ND1'),('rlys','CD'))] = cmd.select('his_i49', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+16.25,resSelectionSubs('lys','CD',subs)))
IDSpec[(('his_i','ND1'),('rlys','CE'))] = cmd.select('his_i50', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+15.21,resSelectionSubs('lys','CE',subs)))
cmd.select('his_i50',' br. his_i1&br. his_i2&br. his_i3&br. his_i4&br. his_i5&br. his_i6&br. his_i7&br. his_i8&br. his_i9&br. his_i10&br. his_i11&br. his_i12&br. his_i13&br. his_i14&br. his_i15&br. his_i16&br. his_i17&br. his_i18&br. his_i19&br. his_i20&br. his_i21&br. his_i22&br. his_i23&br. his_i24&br. his_i25&br. his_i26&br. his_i27&br. his_i28&br. his_i29&br. his_i30&br. his_i31&br. his_i32&br. his_i33&br. his_i34&br. his_i35&br. his_i36&br. his_i37&br. his_i38&br. his_i39&br. his_i40&br. his_i41&br. his_i42&br. his_i43&br. his_i44&br. his_i45&br. his_i46&br. his_i47&br. his_i48&br. his_i49&br. his_i50')
cmd.delete('his_i1')
cmd.delete('his_i2')
cmd.delete('his_i3')
cmd.delete('his_i4')
cmd.delete('his_i5')
cmd.delete('his_i6')
cmd.delete('his_i7')
cmd.delete('his_i8')
cmd.delete('his_i9')
cmd.delete('his_i10')
cmd.delete('his_i11')
cmd.delete('his_i12')
cmd.delete('his_i13')
cmd.delete('his_i14')
cmd.delete('his_i15')
cmd.delete('his_i16')
cmd.delete('his_i17')
cmd.delete('his_i18')
cmd.delete('his_i19')
cmd.delete('his_i20')
cmd.delete('his_i21')
cmd.delete('his_i22')
cmd.delete('his_i23')
cmd.delete('his_i24')
cmd.delete('his_i25')
cmd.delete('his_i26')
cmd.delete('his_i27')
cmd.delete('his_i28')
cmd.delete('his_i29')
cmd.delete('his_i30')
cmd.delete('his_i31')
cmd.delete('his_i32')
cmd.delete('his_i33')
cmd.delete('his_i34')
cmd.delete('his_i35')
cmd.delete('his_i36')
cmd.delete('his_i37')
cmd.delete('his_i38')
cmd.delete('his_i39')
cmd.delete('his_i40')
cmd.delete('his_i41')
cmd.delete('his_i42')
cmd.delete('his_i43')
cmd.delete('his_i44')
cmd.delete('his_i45')
cmd.delete('his_i46')
cmd.delete('his_i47')
cmd.delete('his_i48')
cmd.delete('his_i49')
IDSpec[(('his_i','ND1'),('rlys','NZ'))] = cmd.select('his_i51', '%s w. %s of %s'%(resSelectionSubs('his','ND1',subs),d+14.08,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('his_i','NE2'),('rlys','CD'))] = cmd.select('his_i52', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+14.64,resSelectionSubs('lys','CD',subs)))
IDSpec[(('his_i','NE2'),('rlys','CE'))] = cmd.select('his_i53', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+13.49,resSelectionSubs('lys','CE',subs)))
IDSpec[(('his_i','NE2'),('rlys','NZ'))] = cmd.select('his_i54', '%s w. %s of %s'%(resSelectionSubs('his','NE2',subs),d+12.41,resSelectionSubs('lys','NZ',subs)))
IDSpec['his_i'] = cmd.select('his_i',' his_i50&br. his_i51&br. his_i52&br. his_i53&br. his_i54')
IDSpec['r_his_i'] = cmd.count_atoms(resSelectionSubs('his_i', subs=subs, selection=True))
cmd.delete('his_i50')
cmd.delete('his_i51')
cmd.delete('his_i52')
cmd.delete('his_i53')
cmd.delete('his_i54')
IDSpec[(('asn','CG'),('shis','CE1'))] = cmd.select('asn1', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+16.47,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asn','CG'),('shis','ND1'))] = cmd.select('asn2', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+15.35,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asn','CG'),('shis','NE2'))] = cmd.select('asn3', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+16.71,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asn','ND2'),('shis','CE1'))] = cmd.select('asn4', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+16.81,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asn','ND2'),('shis','ND1'))] = cmd.select('asn5', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+15.76,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asn','ND2'),('shis','NE2'))] = cmd.select('asn6', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+17.00,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asn','OD1'),('shis','CE1'))] = cmd.select('asn7', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+15.74,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asn','OD1'),('shis','ND1'))] = cmd.select('asn8', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+14.60,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asn','OD1'),('shis','NE2'))] = cmd.select('asn9', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+15.92,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asn','CG'),('sasp','CG'))] = cmd.select('asn10', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+16.44,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asn','CG'),('sasp','OD1'))] = cmd.select('asn11', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+15.63,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asn','CG'),('sasp','OD2'))] = cmd.select('asn12', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+16.35,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asn','ND2'),('sasp','CG'))] = cmd.select('asn13', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+17.01,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asn','ND2'),('sasp','OD1'))] = cmd.select('asn14', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+16.15,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asn','ND2'),('sasp','OD2'))] = cmd.select('asn15', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+17.00,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asn','OD1'),('sasp','CG'))] = cmd.select('asn16', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+15.31,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asn','OD1'),('sasp','OD1'))] = cmd.select('asn17', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+14.48,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asn','OD1'),('sasp','OD2'))] = cmd.select('asn18', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+15.21,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asn','CG'),('scys','CA'))] = cmd.select('asn19', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+10.53,resSelectionSubs('cys','CA',subs,selection=True)))
IDSpec[(('asn','CG'),('scys','CB'))] = cmd.select('asn20', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+9.62,resSelectionSubs('cys','CB',subs,selection=True)))
IDSpec[(('asn','CG'),('scys','SG'))] = cmd.select('asn21', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+8.73,resSelectionSubs('cys','SG',subs,selection=True)))
IDSpec[(('asn','ND2'),('scys','CA'))] = cmd.select('asn22', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+11.76,resSelectionSubs('cys','CA',subs,selection=True)))
IDSpec[(('asn','ND2'),('scys','CB'))] = cmd.select('asn23', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+10.80,resSelectionSubs('cys','CB',subs,selection=True)))
IDSpec[(('asn','ND2'),('scys','SG'))] = cmd.select('asn24', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+9.98,resSelectionSubs('cys','SG',subs,selection=True)))
IDSpec[(('asn','OD1'),('scys','CA'))] = cmd.select('asn25', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+10.45,resSelectionSubs('cys','CA',subs,selection=True)))
IDSpec[(('asn','OD1'),('scys','CB'))] = cmd.select('asn26', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+9.57,resSelectionSubs('cys','CB',subs,selection=True)))
IDSpec[(('asn','OD1'),('scys','SG'))] = cmd.select('asn27', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+8.42,resSelectionSubs('cys','SG',subs,selection=True)))
IDSpec[(('asn','CG'),('shis_i','CE1'))] = cmd.select('asn28', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+18.88,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('asn','CG'),('shis_i','ND1'))] = cmd.select('asn29', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+19.76,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('asn','CG'),('shis_i','NE2'))] = cmd.select('asn30', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+17.71,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('asn','ND2'),('shis_i','CE1'))] = cmd.select('asn31', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+19.81,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('asn','ND2'),('shis_i','ND1'))] = cmd.select('asn32', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+20.69,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('asn','ND2'),('shis_i','NE2'))] = cmd.select('asn33', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+18.61,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('asn','OD1'),('shis_i','CE1'))] = cmd.select('asn34', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+17.70,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('asn','OD1'),('shis_i','ND1'))] = cmd.select('asn35', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+18.60,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('asn','OD1'),('shis_i','NE2'))] = cmd.select('asn36', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+16.54,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('asn','CG'),('rasp','CG'))] = cmd.select('asn37', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+8.23,resSelectionSubs('asp','CG',subs)))
IDSpec[(('asn','CG'),('rasp','OD1'))] = cmd.select('asn38', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+9.14,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('asn','CG'),('rasp','OD2'))] = cmd.select('asn39', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+8.64,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('asn','ND2'),('rasp','CG'))] = cmd.select('asn40', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+8.95,resSelectionSubs('asp','CG',subs)))
IDSpec[(('asn','ND2'),('rasp','OD1'))] = cmd.select('asn41', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+9.92,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('asn','ND2'),('rasp','OD2'))] = cmd.select('asn42', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+9.19,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('asn','OD1'),('rasp','CG'))] = cmd.select('asn43', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+7.60,resSelectionSubs('asp','CG',subs)))
IDSpec[(('asn','OD1'),('rasp','OD1'))] = cmd.select('asn44', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+8.58,resSelectionSubs('asp','OD1',subs)))
IDSpec[(('asn','OD1'),('rasp','OD2'))] = cmd.select('asn45', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+7.95,resSelectionSubs('asp','OD2',subs)))
IDSpec[(('asn','CG'),('rlys','CD'))] = cmd.select('asn46', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+11.88,resSelectionSubs('lys','CD',subs)))
IDSpec[(('asn','CG'),('rlys','CE'))] = cmd.select('asn47', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+11.08,resSelectionSubs('lys','CE',subs)))
IDSpec[(('asn','CG'),('rlys','NZ'))] = cmd.select('asn48', '%s w. %s of %s'%(resSelectionSubs('asn','CG',subs),d+11.33,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('asn','ND2'),('rlys','CD'))] = cmd.select('asn49', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+11.99,resSelectionSubs('lys','CD',subs)))
IDSpec[(('asn','ND2'),('rlys','CE'))] = cmd.select('asn50', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+11.30,resSelectionSubs('lys','CE',subs)))
cmd.select('asn50',' br. asn1&br. asn2&br. asn3&br. asn4&br. asn5&br. asn6&br. asn7&br. asn8&br. asn9&br. asn10&br. asn11&br. asn12&br. asn13&br. asn14&br. asn15&br. asn16&br. asn17&br. asn18&br. asn19&br. asn20&br. asn21&br. asn22&br. asn23&br. asn24&br. asn25&br. asn26&br. asn27&br. asn28&br. asn29&br. asn30&br. asn31&br. asn32&br. asn33&br. asn34&br. asn35&br. asn36&br. asn37&br. asn38&br. asn39&br. asn40&br. asn41&br. asn42&br. asn43&br. asn44&br. asn45&br. asn46&br. asn47&br. asn48&br. asn49&br. asn50')
cmd.delete('asn1')
cmd.delete('asn2')
cmd.delete('asn3')
cmd.delete('asn4')
cmd.delete('asn5')
cmd.delete('asn6')
cmd.delete('asn7')
cmd.delete('asn8')
cmd.delete('asn9')
cmd.delete('asn10')
cmd.delete('asn11')
cmd.delete('asn12')
cmd.delete('asn13')
cmd.delete('asn14')
cmd.delete('asn15')
cmd.delete('asn16')
cmd.delete('asn17')
cmd.delete('asn18')
cmd.delete('asn19')
cmd.delete('asn20')
cmd.delete('asn21')
cmd.delete('asn22')
cmd.delete('asn23')
cmd.delete('asn24')
cmd.delete('asn25')
cmd.delete('asn26')
cmd.delete('asn27')
cmd.delete('asn28')
cmd.delete('asn29')
cmd.delete('asn30')
cmd.delete('asn31')
cmd.delete('asn32')
cmd.delete('asn33')
cmd.delete('asn34')
cmd.delete('asn35')
cmd.delete('asn36')
cmd.delete('asn37')
cmd.delete('asn38')
cmd.delete('asn39')
cmd.delete('asn40')
cmd.delete('asn41')
cmd.delete('asn42')
cmd.delete('asn43')
cmd.delete('asn44')
cmd.delete('asn45')
cmd.delete('asn46')
cmd.delete('asn47')
cmd.delete('asn48')
cmd.delete('asn49')
IDSpec[(('asn','ND2'),('rlys','NZ'))] = cmd.select('asn51', '%s w. %s of %s'%(resSelectionSubs('asn','ND2',subs),d+11.74,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('asn','OD1'),('rlys','CD'))] = cmd.select('asn52', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+11.43,resSelectionSubs('lys','CD',subs)))
IDSpec[(('asn','OD1'),('rlys','CE'))] = cmd.select('asn53', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+10.48,resSelectionSubs('lys','CE',subs)))
IDSpec[(('asn','OD1'),('rlys','NZ'))] = cmd.select('asn54', '%s w. %s of %s'%(resSelectionSubs('asn','OD1',subs),d+10.64,resSelectionSubs('lys','NZ',subs)))
IDSpec['asn'] = cmd.select('asn',' asn50&br. asn51&br. asn52&br. asn53&br. asn54')
IDSpec['r_asn'] = cmd.count_atoms(resSelectionSubs('asn', subs=subs, selection=True))
cmd.delete('asn50')
cmd.delete('asn51')
cmd.delete('asn52')
cmd.delete('asn53')
cmd.delete('asn54')
IDSpec[(('asp_i','CG'),('shis','CE1'))] = cmd.select('asp_i1', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+19.27,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('shis','ND1'))] = cmd.select('asp_i2', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+18.10,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('shis','NE2'))] = cmd.select('asp_i3', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+19.22,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('shis','CE1'))] = cmd.select('asp_i4', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+20.21,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('shis','ND1'))] = cmd.select('asp_i5', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+19.01,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('shis','NE2'))] = cmd.select('asp_i6', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+20.18,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('shis','CE1'))] = cmd.select('asp_i7', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+19.23,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('shis','ND1'))] = cmd.select('asp_i8', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+18.10,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('shis','NE2'))] = cmd.select('asp_i9', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+19.08,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasp','CG'))] = cmd.select('asp_i10', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+12.12,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasp','OD1'))] = cmd.select('asp_i11', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+11.72,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasp','OD2'))] = cmd.select('asp_i12', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+11.77,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasp','CG'))] = cmd.select('asp_i13', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+12.41,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasp','OD1'))] = cmd.select('asp_i14', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+12.15,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasp','OD2'))] = cmd.select('asp_i15', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+11.93,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasp','CG'))] = cmd.select('asp_i16', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.39,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasp','OD1'))] = cmd.select('asp_i17', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+10.94,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasp','OD2'))] = cmd.select('asp_i18', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.16,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('asp_i','CG'),('scys','CA'))] = cmd.select('asp_i19', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+11.90,resSelectionSubs('cys','CA',subs,selection=True)))
IDSpec[(('asp_i','CG'),('scys','CB'))] = cmd.select('asp_i20', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+11.86,resSelectionSubs('cys','CB',subs,selection=True)))
IDSpec[(('asp_i','CG'),('scys','SG'))] = cmd.select('asp_i21', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+10.72,resSelectionSubs('cys','SG',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('scys','CA'))] = cmd.select('asp_i22', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+11.79,resSelectionSubs('cys','CA',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('scys','CB'))] = cmd.select('asp_i23', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+11.94,resSelectionSubs('cys','CB',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('scys','SG'))] = cmd.select('asp_i24', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+10.93,resSelectionSubs('cys','SG',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('scys','CA'))] = cmd.select('asp_i25', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+13.03,resSelectionSubs('cys','CA',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('scys','CB'))] = cmd.select('asp_i26', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+12.91,resSelectionSubs('cys','CB',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('scys','SG'))] = cmd.select('asp_i27', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+11.69,resSelectionSubs('cys','SG',subs,selection=True)))
IDSpec[(('asp_i','CG'),('shis_i','CE1'))] = cmd.select('asp_i28', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+14.64,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('shis_i','ND1'))] = cmd.select('asp_i29', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+15.20,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('shis_i','NE2'))] = cmd.select('asp_i30', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+13.36,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('shis_i','CE1'))] = cmd.select('asp_i31', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+14.55,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('shis_i','ND1'))] = cmd.select('asp_i32', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+15.01,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('shis_i','NE2'))] = cmd.select('asp_i33', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+13.29,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('shis_i','CE1'))] = cmd.select('asp_i34', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+14.45,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('shis_i','ND1'))] = cmd.select('asp_i35', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+15.01,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('shis_i','NE2'))] = cmd.select('asp_i36', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+13.14,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasn','CG'))] = cmd.select('asp_i37', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+8.23,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasn','ND2'))] = cmd.select('asp_i38', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+8.95,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('asp_i','CG'),('sasn','OD1'))] = cmd.select('asp_i39', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.60,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasn','CG'))] = cmd.select('asp_i40', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.14,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasn','ND2'))] = cmd.select('asp_i41', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+9.92,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('asp_i','OD1'),('sasn','OD1'))] = cmd.select('asp_i42', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+8.58,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasn','CG'))] = cmd.select('asp_i43', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+8.64,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasn','ND2'))] = cmd.select('asp_i44', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+9.19,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('asp_i','OD2'),('sasn','OD1'))] = cmd.select('asp_i45', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+7.95,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('asp_i','CG'),('rlys','CD'))] = cmd.select('asp_i46', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+7.15,resSelectionSubs('lys','CD',subs)))
IDSpec[(('asp_i','CG'),('rlys','CE'))] = cmd.select('asp_i47', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+6.23,resSelectionSubs('lys','CE',subs)))
IDSpec[(('asp_i','CG'),('rlys','NZ'))] = cmd.select('asp_i48', '%s w. %s of %s'%(resSelectionSubs('asp','CG',subs),d+5.71,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('asp_i','OD1'),('rlys','CD'))] = cmd.select('asp_i49', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+7.39,resSelectionSubs('lys','CD',subs)))
IDSpec[(('asp_i','OD1'),('rlys','CE'))] = cmd.select('asp_i50', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+6.67,resSelectionSubs('lys','CE',subs)))
cmd.select('asp_i50',' br. asp_i1&br. asp_i2&br. asp_i3&br. asp_i4&br. asp_i5&br. asp_i6&br. asp_i7&br. asp_i8&br. asp_i9&br. asp_i10&br. asp_i11&br. asp_i12&br. asp_i13&br. asp_i14&br. asp_i15&br. asp_i16&br. asp_i17&br. asp_i18&br. asp_i19&br. asp_i20&br. asp_i21&br. asp_i22&br. asp_i23&br. asp_i24&br. asp_i25&br. asp_i26&br. asp_i27&br. asp_i28&br. asp_i29&br. asp_i30&br. asp_i31&br. asp_i32&br. asp_i33&br. asp_i34&br. asp_i35&br. asp_i36&br. asp_i37&br. asp_i38&br. asp_i39&br. asp_i40&br. asp_i41&br. asp_i42&br. asp_i43&br. asp_i44&br. asp_i45&br. asp_i46&br. asp_i47&br. asp_i48&br. asp_i49&br. asp_i50')
cmd.delete('asp_i1')
cmd.delete('asp_i2')
cmd.delete('asp_i3')
cmd.delete('asp_i4')
cmd.delete('asp_i5')
cmd.delete('asp_i6')
cmd.delete('asp_i7')
cmd.delete('asp_i8')
cmd.delete('asp_i9')
cmd.delete('asp_i10')
cmd.delete('asp_i11')
cmd.delete('asp_i12')
cmd.delete('asp_i13')
cmd.delete('asp_i14')
cmd.delete('asp_i15')
cmd.delete('asp_i16')
cmd.delete('asp_i17')
cmd.delete('asp_i18')
cmd.delete('asp_i19')
cmd.delete('asp_i20')
cmd.delete('asp_i21')
cmd.delete('asp_i22')
cmd.delete('asp_i23')
cmd.delete('asp_i24')
cmd.delete('asp_i25')
cmd.delete('asp_i26')
cmd.delete('asp_i27')
cmd.delete('asp_i28')
cmd.delete('asp_i29')
cmd.delete('asp_i30')
cmd.delete('asp_i31')
cmd.delete('asp_i32')
cmd.delete('asp_i33')
cmd.delete('asp_i34')
cmd.delete('asp_i35')
cmd.delete('asp_i36')
cmd.delete('asp_i37')
cmd.delete('asp_i38')
cmd.delete('asp_i39')
cmd.delete('asp_i40')
cmd.delete('asp_i41')
cmd.delete('asp_i42')
cmd.delete('asp_i43')
cmd.delete('asp_i44')
cmd.delete('asp_i45')
cmd.delete('asp_i46')
cmd.delete('asp_i47')
cmd.delete('asp_i48')
cmd.delete('asp_i49')
IDSpec[(('asp_i','OD1'),('rlys','NZ'))] = cmd.select('asp_i51', '%s w. %s of %s'%(resSelectionSubs('asp','OD1',subs),d+5.86,resSelectionSubs('lys','NZ',subs)))
IDSpec[(('asp_i','OD2'),('rlys','CD'))] = cmd.select('asp_i52', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+6.18,resSelectionSubs('lys','CD',subs)))
IDSpec[(('asp_i','OD2'),('rlys','CE'))] = cmd.select('asp_i53', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+5.11,resSelectionSubs('lys','CE',subs)))
IDSpec[(('asp_i','OD2'),('rlys','NZ'))] = cmd.select('asp_i54', '%s w. %s of %s'%(resSelectionSubs('asp','OD2',subs),d+4.78,resSelectionSubs('lys','NZ',subs)))
IDSpec['asp_i'] = cmd.select('asp_i',' asp_i50&br. asp_i51&br. asp_i52&br. asp_i53&br. asp_i54')
IDSpec['r_asp_i'] = cmd.count_atoms(resSelectionSubs('asp_i', subs=subs, selection=True))
cmd.delete('asp_i50')
cmd.delete('asp_i51')
cmd.delete('asp_i52')
cmd.delete('asp_i53')
cmd.delete('asp_i54')
IDSpec[(('lys','CD'),('shis','CE1'))] = cmd.select('lys1', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+22.37,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('lys','CD'),('shis','ND1'))] = cmd.select('lys2', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+21.36,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('lys','CD'),('shis','NE2'))] = cmd.select('lys3', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+22.04,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('lys','CE'),('shis','CE1'))] = cmd.select('lys4', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+20.96,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('lys','CE'),('shis','ND1'))] = cmd.select('lys5', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+19.94,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('lys','CE'),('shis','NE2'))] = cmd.select('lys6', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+20.63,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('lys','NZ'),('shis','CE1'))] = cmd.select('lys7', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+20.95,resSelectionSubs('his','CE1',subs,selection=True)))
IDSpec[(('lys','NZ'),('shis','ND1'))] = cmd.select('lys8', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+19.88,resSelectionSubs('his','ND1',subs,selection=True)))
IDSpec[(('lys','NZ'),('shis','NE2'))] = cmd.select('lys9', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+20.65,resSelectionSubs('his','NE2',subs,selection=True)))
IDSpec[(('lys','CD'),('sasp','CG'))] = cmd.select('lys10', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+11.73,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('lys','CD'),('sasp','OD1'))] = cmd.select('lys11', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+11.49,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('lys','CD'),('sasp','OD2'))] = cmd.select('lys12', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+11.75,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('lys','CE'),('sasp','CG'))] = cmd.select('lys13', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+10.64,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('lys','CE'),('sasp','OD1'))] = cmd.select('lys14', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+10.31,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('lys','CE'),('sasp','OD2'))] = cmd.select('lys15', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+10.66,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('lys','NZ'),('sasp','CG'))] = cmd.select('lys16', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+10.06,resSelectionSubs('asp','CG',subs,selection=True)))
IDSpec[(('lys','NZ'),('sasp','OD1'))] = cmd.select('lys17', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+9.86,resSelectionSubs('asp','OD1',subs,selection=True)))
IDSpec[(('lys','NZ'),('sasp','OD2'))] = cmd.select('lys18', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+9.88,resSelectionSubs('asp','OD2',subs,selection=True)))
IDSpec[(('lys','CD'),('scys','CA'))] = cmd.select('lys19', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+16.99,resSelectionSubs('cys','CA',subs,selection=True)))
IDSpec[(('lys','CD'),('scys','CB'))] = cmd.select('lys20', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+16.94,resSelectionSubs('cys','CB',subs,selection=True)))
IDSpec[(('lys','CD'),('scys','SG'))] = cmd.select('lys21', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+15.82,resSelectionSubs('cys','SG',subs,selection=True)))
IDSpec[(('lys','CE'),('scys','CA'))] = cmd.select('lys22', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+16.12,resSelectionSubs('cys','CA',subs,selection=True)))
IDSpec[(('lys','CE'),('scys','CB'))] = cmd.select('lys23', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+16.01,resSelectionSubs('cys','CB',subs,selection=True)))
IDSpec[(('lys','CE'),('scys','SG'))] = cmd.select('lys24', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+14.78,resSelectionSubs('cys','SG',subs,selection=True)))
IDSpec[(('lys','NZ'),('scys','CA'))] = cmd.select('lys25', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+15.44,resSelectionSubs('cys','CA',subs,selection=True)))
IDSpec[(('lys','NZ'),('scys','CB'))] = cmd.select('lys26', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+15.46,resSelectionSubs('cys','CB',subs,selection=True)))
IDSpec[(('lys','NZ'),('scys','SG'))] = cmd.select('lys27', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+14.23,resSelectionSubs('cys','SG',subs,selection=True)))
IDSpec[(('lys','CD'),('shis_i','CE1'))] = cmd.select('lys28', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+15.95,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('lys','CD'),('shis_i','ND1'))] = cmd.select('lys29', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+16.25,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('lys','CD'),('shis_i','NE2'))] = cmd.select('lys30', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+14.64,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('lys','CE'),('shis_i','CE1'))] = cmd.select('lys31', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+14.81,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('lys','CE'),('shis_i','ND1'))] = cmd.select('lys32', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+15.21,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('lys','CE'),('shis_i','NE2'))] = cmd.select('lys33', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+13.49,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('lys','NZ'),('shis_i','CE1'))] = cmd.select('lys34', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+13.72,resSelectionSubs('his_i','CE1',subs,selection=True)))
IDSpec[(('lys','NZ'),('shis_i','ND1'))] = cmd.select('lys35', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+14.08,resSelectionSubs('his_i','ND1',subs,selection=True)))
IDSpec[(('lys','NZ'),('shis_i','NE2'))] = cmd.select('lys36', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+12.41,resSelectionSubs('his_i','NE2',subs,selection=True)))
IDSpec[(('lys','CD'),('sasn','CG'))] = cmd.select('lys37', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+11.88,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('lys','CD'),('sasn','ND2'))] = cmd.select('lys38', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+11.99,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('lys','CD'),('sasn','OD1'))] = cmd.select('lys39', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+11.43,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('lys','CE'),('sasn','CG'))] = cmd.select('lys40', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+11.08,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('lys','CE'),('sasn','ND2'))] = cmd.select('lys41', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+11.30,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('lys','CE'),('sasn','OD1'))] = cmd.select('lys42', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+10.48,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('lys','NZ'),('sasn','CG'))] = cmd.select('lys43', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+11.33,resSelectionSubs('asn','CG',subs,selection=True)))
IDSpec[(('lys','NZ'),('sasn','ND2'))] = cmd.select('lys44', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+11.74,resSelectionSubs('asn','ND2',subs,selection=True)))
IDSpec[(('lys','NZ'),('sasn','OD1'))] = cmd.select('lys45', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+10.64,resSelectionSubs('asn','OD1',subs,selection=True)))
IDSpec[(('lys','CD'),('sasp_i','CG'))] = cmd.select('lys46', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+7.15,resSelectionSubs('asp_i','CG',subs,selection=True)))
IDSpec[(('lys','CD'),('sasp_i','OD1'))] = cmd.select('lys47', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+7.39,resSelectionSubs('asp_i','OD1',subs,selection=True)))
IDSpec[(('lys','CD'),('sasp_i','OD2'))] = cmd.select('lys48', '%s w. %s of %s'%(resSelectionSubs('lys','CD',subs),d+6.18,resSelectionSubs('asp_i','OD2',subs,selection=True)))
IDSpec[(('lys','CE'),('sasp_i','CG'))] = cmd.select('lys49', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+6.23,resSelectionSubs('asp_i','CG',subs,selection=True)))
IDSpec[(('lys','CE'),('sasp_i','OD1'))] = cmd.select('lys50', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+6.67,resSelectionSubs('asp_i','OD1',subs,selection=True)))
cmd.select('lys50',' br. lys1&br. lys2&br. lys3&br. lys4&br. lys5&br. lys6&br. lys7&br. lys8&br. lys9&br. lys10&br. lys11&br. lys12&br. lys13&br. lys14&br. lys15&br. lys16&br. lys17&br. lys18&br. lys19&br. lys20&br. lys21&br. lys22&br. lys23&br. lys24&br. lys25&br. lys26&br. lys27&br. lys28&br. lys29&br. lys30&br. lys31&br. lys32&br. lys33&br. lys34&br. lys35&br. lys36&br. lys37&br. lys38&br. lys39&br. lys40&br. lys41&br. lys42&br. lys43&br. lys44&br. lys45&br. lys46&br. lys47&br. lys48&br. lys49&br. lys50')
cmd.delete('lys1')
cmd.delete('lys2')
cmd.delete('lys3')
cmd.delete('lys4')
cmd.delete('lys5')
cmd.delete('lys6')
cmd.delete('lys7')
cmd.delete('lys8')
cmd.delete('lys9')
cmd.delete('lys10')
cmd.delete('lys11')
cmd.delete('lys12')
cmd.delete('lys13')
cmd.delete('lys14')
cmd.delete('lys15')
cmd.delete('lys16')
cmd.delete('lys17')
cmd.delete('lys18')
cmd.delete('lys19')
cmd.delete('lys20')
cmd.delete('lys21')
cmd.delete('lys22')
cmd.delete('lys23')
cmd.delete('lys24')
cmd.delete('lys25')
cmd.delete('lys26')
cmd.delete('lys27')
cmd.delete('lys28')
cmd.delete('lys29')
cmd.delete('lys30')
cmd.delete('lys31')
cmd.delete('lys32')
cmd.delete('lys33')
cmd.delete('lys34')
cmd.delete('lys35')
cmd.delete('lys36')
cmd.delete('lys37')
cmd.delete('lys38')
cmd.delete('lys39')
cmd.delete('lys40')
cmd.delete('lys41')
cmd.delete('lys42')
cmd.delete('lys43')
cmd.delete('lys44')
cmd.delete('lys45')
cmd.delete('lys46')
cmd.delete('lys47')
cmd.delete('lys48')
cmd.delete('lys49')
IDSpec[(('lys','CE'),('sasp_i','OD2'))] = cmd.select('lys51', '%s w. %s of %s'%(resSelectionSubs('lys','CE',subs),d+5.11,resSelectionSubs('asp_i','OD2',subs,selection=True)))
IDSpec[(('lys','NZ'),('sasp_i','CG'))] = cmd.select('lys52', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+5.71,resSelectionSubs('asp_i','CG',subs,selection=True)))
IDSpec[(('lys','NZ'),('sasp_i','OD1'))] = cmd.select('lys53', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+5.86,resSelectionSubs('asp_i','OD1',subs,selection=True)))
IDSpec[(('lys','NZ'),('sasp_i','OD2'))] = cmd.select('lys54', '%s w. %s of %s'%(resSelectionSubs('lys','NZ',subs),d+4.78,resSelectionSubs('asp_i','OD2',subs,selection=True)))
IDSpec['lys'] = cmd.select('lys',' lys50&br. lys51&br. lys52&br. lys53&br. lys54')
IDSpec['r_lys'] = cmd.count_atoms(resSelectionSubs('lys', subs=subs, selection=True))
cmd.delete('lys50')
cmd.delete('lys51')
cmd.delete('lys52')
cmd.delete('lys53')
cmd.delete('lys54')
IDSpec['S_3gvp_3_3_1_1'] = cmd.select('S_3gvp_3_3_1_1', 'his|asp|cys|his_i|asn|asp_i|lys')
cmd.delete('his')
cmd.delete('asp')
cmd.delete('cys')
cmd.delete('his_i')
cmd.delete('asn')
cmd.delete('asp_i')
cmd.delete('lys')
